### ISSUE TITLE
gulp-sass doesn't seem to play nice with sass imports

### ISSUE THREAD

**Issue by webdesserts** [dlmanning/gulp-sass#1]
Right now if any of my sass files have an `@import` in them I get an error like this:

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
source string:1: error: file to import not found or unreadable: 'normalize'
```

Where normalize is a `normalize.scss` in the same directory.

This seems to be because you are using the data option without an [includePaths](https://github.com/andrew/node-sass#includepaths).

This could maybe be solved with an includePaths option?

```
gulp.src('./styles/main.scss')
  .pipe(sass({includePaths: ['./styles']}))
  .pipe(gulp.dest('./styles'))
```

**Comment by vdecree** [comment]
I'm getting this issue on windows 8.1 and the suggested fix doesn't seem to help. My task:
```
gulp.task('sass', function() {
    gulp.src('assets/scss/**/*.scss')
		.pipe(sass({style: 'expanded', includePaths: [ './assets/scss/partials', './assets/scss/modules', './assets/scss/helpers' ], errLogToConsole: true }))
		.pipe(autoprefixer('last 2 version'))
    	.pipe(rename(pkg.name + '.css'))
		.pipe(gulp.dest('assets/css'))
		.pipe(reload({stream: true}))
		.pipe(notify({message: 'SCSS processed!'}));
});
```

**Comment by quagliero** [comment]
@vdecree If you're including `./assets/scss/partials` as an includePath, then you probably don't need to `@import partials/header`, it just needs to be `@import header`. This is just a blind guess without context of course :smile:

**Comment by Keats** [comment]
Hello,

Try the next version of gulp-sass using
```sh
npm install dlmanning/gulp-sass#2.x
```

**Comment by vdecree** [comment]
@quagliero I thought you'd saved my day then! Turns I didn't know I could then remove the path prefix from the actual style.scss despite that being fairly obvious. It did make it happen less often but I've noticed it's still happening.

@Keats Will give that a go sir

**Comment by vdecree** [comment]
@Keats I found I had to roll back as lots of my plugins such as breakpoints and modular scale stopped working. I need to strip things back and see if I can find a setup that works or go back to grunt!

**Comment by Keats** [comment]
That's odd, the libsass version used in the 2.x branch should be much more feature-complete than the current one.
It might be worth making sure it's actually using libsass 3.2 and if it is and those plugins are not working open issues on them

**Comment by vdecree** [comment]
@Keats Will do - shall load it up in a moment and have another try. Would rather stay on gulp if I can - the speed is insanely good.

**Comment by Snugug** [comment]
Check out the libsass issue queue. They did a lot of refactoring and, while all of their tests passed, some things that worked but didn't have tests blew up. The modular scale issue, for instance, has a fix in place and is awaiting a new release (parsing `@elseif` as an at rule instead of as `@else if`)

**Comment by vdecree** [comment]
@Snugug Spot on buddie. I managed to change that myself and seems to be completing OK. I will see if this gets over the partials issue.

**Comment by vdecree** [comment]
I've found in the short time I've been running 2.x that the same issue occurs but the behavior is slightly different. Instead of simply being able to hit save again to trigger a successful process of the SCSS, it instead stops the task and comes out of watch, meaning I have to type `gulp` again to re-initiate the task. It's happening less often, but nonetheless still an issue and more of annoying one now

**Comment by guilima** [comment]
I am facing the same problem. I did extended tests with no results or significant glitch display. Tried to work with the gulp-ruby-sass but is 3 times slower to process the task.

@vdecree you are not alone buddy, gulp-sass#2.x didn't help.

**Comment by vdecree** [comment]
@guilima Glad I'm not alone! I'm still trying to figure out a fix. Moved back to Grunt in the meantime to avoid having to re-run the task constantly after it cuts out.

**Comment by theroyalstudent** [comment]
@vdecree @guilima Having this issue, know of any fix?

`
[15:26:18] Using gulpfile ~/Desktop/DigitalOcean/:var:www/staging/gulpfile.js
[15:26:18] Starting 'sass'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: resources/admin/style.sass
  4:9  file to import not found or unreadable: reset
Current dir: 
    at options.error (/Users/student/Desktop/DigitalOcean/:var:www/staging/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:276:32)
`

**Comment by Keats** [comment]
@theroyalstudent can you provide the smallest example where it fails?

**Comment by theroyalstudent** [comment]
It just fails when it runs into this:

`
@import 'reset'
@import 'base'
@import '../materialDesign/materialize'
@import '../bourbon/app/assets/stylesheets/bourbon'
@import '../miscDesign/animate'
`

reset and base are SASS, and everything else are SCSS.

**Comment by krishpraja** [comment]
Solved my problem. Thanks.

**Comment by arnolali** [comment]
I have the exact same issue, juste like @theroyalstudent, @vdecree and @guilima.
I'm going nuts!

**Comment by anttoon** [comment]
+1

**Comment by adamschoenemann** [comment]
I am also having this issue! (Windows 7)

**Comment by felipedefarias** [comment]
+1

**Comment by Snugug** [comment]
Please read and try out [Common Issues and Their Fixes](https://github.com/dlmanning/gulp-sass/wiki/Common-Issues-and-Their-Fixes#partials-sporadically-not-found). Everyone who has had this issue has had it resolved following those steps.

**Comment by adamschoenemann** [comment]
Right! Shame on me for not checking that out first. It does indeed appear to fix the problem (so far). Thank you!

**Comment by arnolali** [comment]
My problem was caused by a combination of Sublime Text **and** a slow hard drive.
We were able to solved it by changing the setting **atomic_save** to **true**.
`Preferences > Settings - User > "atomic_save": true`

**Comment by lachieh** [comment]
Changing the `atomic_save` option to `true` also solved this issue for me also. A more permanent fix for this would be to make gulp-sass wait for the file to be available and set the default timeout to a few hundred milliseconds.

**Comment by clintongreen** [comment]
@marcamos I ran into the same problem, I also had sass files and couldn't find gulp support for them. Luckily its only the import function that Gulp seems to have a problem with, so to solve it only change your sass file that imports the other files to scss. It can still import sass files into the scss file no problem. I hope this helps. Cheers

**Comment by TNT-Likely** [comment]
@Snugug thanks,

**Comment by Kaffesumpen** [comment]
@webdesserts thanks for this :+1:

**Comment by braintapper** [comment]
@arnolali thanks, that fixed my problem on Windows

**Comment by marcospgp** [comment]
@arnolali your solution fixed the issue here as well! <3

**Comment by FFirmenich** [comment]
@arnolali Thanks! Fixed my problem on Windows 10

**Comment by vitorspencer** [comment]
By the way, I'm not Mac (so, not Windows) and the only thing that fixed my problem here was to also set atomic_save to true on my SublimeText user settings.

**Comment by Chenzo** [comment]
I'd just like to also send my thanks to @arnolali too... I was suffering for a while, but that has fixed it for me (windows 10/sublime)

**Comment by chekit** [comment]
My thanks to you @arnolali I had the same issue with my gulp-sass task on saving, but your suggestion has solved the issue (windows 10/sublime text 3)

**Comment by valeco** [comment]
@arnolali Thanks!

**Comment by shreeshkatyayan** [comment]
Hey guys, in my base .scss file, I am importing the following modules in order of precedence to override the default behaviors.

```
@import "fonts.scss";
@import "reset.scss";
@import "_vendor.scss";
@import "master.scss";
@import "layout.scss";
@import "header.scss";
@import "input.scss";
@import "md-toast.scss";
@import '../login/_login.scss';
@import "../srp/_srp.scss";
@import '../directives/_directives.scss';
@import "utils.scss";
@import "_helper.scss";
```
But the css generated from my gulp process is not in the mentioned import order. Am I missing something?

Here is my gulp process - 
```javascript
'use strict';

var gulp = require('gulp');
var sass = require('gulp-sass');
var gutil = require('gulp-util');
var size = require('gulp-size');
var rename = require('gulp-rename');

module.exports = {
    doSass: function(){
        gulp.src('./src/sass/app.scss')
                .pipe(sass({outputStyle: 'compressed'}).on('error', gutil.log))
                .pipe(rename('app-rm-md.min.css'))
                .pipe(size({
                    title: "app-rm-md.min.css",
                }))
                .pipe(size({
                    title: "app-rm-md.min.css",
                    gzip: true
                }))
                .pipe(gulp.dest('./dist/css'));      
    },
    watchSass: function(){
        return gulp.watch('./src/**/*.scss', ['sass']);
    }
};
```

What could be the possible fix, other than adding another CSS class?

**Comment by xzyfer** [comment]
@shreeshkatyayan there were issues with ordering in old versions. Please update.

**Comment by shreeshkatyayan** [comment]
@xzyfer I am presently using v2.3.1..

**Comment by minhuang0** [comment]
I will still be a problem after I add the `includePaths `parameter .  Please help me to see the problem. Thanks !

`gulpfile.js`

```
gulp.task('styles', function() {
    return gulp.src('src/sass/main.scss')
        .pipe(sass({includePaths : ['src/sass']}))
        .pipe(gulp.dest('dist/css'));
});
gulp.task('watch', function() {
    gulp.watch('src/sass/**/*.scss', ['styles']);
});
```

`src/sass/main.scss`

```
@import "framework";
```

when i change `src/sass/framework.scss` file ，This error often occurs

error: 

```
      throw er; // Unhandled 'error' event
      ^
 Error: src\sass\main.scss
Error: File to import not found or unreadable: framework
       Parent style sheet: C:/workspace/xcj/translate_react/src/sass/main.scss
        on line 2 of src/sass/main.scss
>> @import "framework";
```

package.json

```
"devDependencies": {
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.1",
    "gulp-clean": "^0.3.2",
    "gulp-compass": "^2.1.0",
    "gulp-concat": "^2.6.0",
    "gulp-connect": "^5.0.0",
    "gulp-imagemin": "^3.0.3",
    "gulp-jshint": "^2.0.1",
    "gulp-minify-css": "^1.2.4",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.3.2",
    "gulp-uglify": "^2.0.0",
    "jshint": "^2.9.3"
  }
```
node-version : v5.10.1 
npm-version: 3.8.3
computer system: windows 7 64
shell: powershell

**Comment by felipedefarias** [comment]
@minhuang0 did you tried [this](https://github.com/dlmanning/gulp-sass/issues/1#issuecomment-123860611)?

**Comment by minhuang0** [comment]
@arnolali @felipedefarias thanks, that fixed my problem !

**Comment by Shaker-Hamdi** [comment]
O.K, this was driving me crazy, but I think I figured it out.
Although @arnolali fix did if for me, but it won't work for other editors, so for me the problem was in the Hard drive.

I'm using an SSD for the operating system, but all my files including my projects are in in a separate Mechanical Drive, and I suspected because Lib-Sass is so fast that it's (for some reason) it compiles the file faster than the save process is complete on files that's being imported, that's why it cant' see the @import "example" and throw this error. (or something like that, I'm just thinking out lout here)

Anyway, I moved my project to the desktop (on the SSD), and it worked like a charm (even without doing the "atomic_save" trick on sublime, and I tested it thoroughly.

I thought I would mention this solution in case someone was using another editor and has the same (SSD, HDD) situation.

**Comment by web2style** [comment]
I have a similar problem. My config doesn't throw any errors. All the sass code in my file is compiled, but import statements are just ignored. Here is my config:

```
var gulp = require('gulp');
var sass = require('gulp-sass');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('styles', function() {
  return gulp.src('./app/frontend/styles/all.scss')
    .pipe(sourcemaps.init())
    .pipe(sass({includePaths: ['./app/frontend/styles']}).on('error', sass.logError))
    .pipe(sourcemaps.write('./maps'))
    .pipe(gulp.dest('./app/assets/stylesheets/bundles'));
});

gulp.task('default', function() {
  gulp.watch('./app/frontend/styles/**/*.scss', ['styles']);
});
```

What can be the problem? Doesn't seem this is the same problem everybody has here.

**Comment by shobhitsharma** [comment]
When importing in SASS modules, make sure your files have `_` in front, i.e. when you have initialized`@import 'module/something'`, your directory must be having `module/_something.scss` not `module/something.scss`. If this is correct, then there must be issue the way you have declared styles.

**Comment by xiaofuyesnew** [comment]
@Shaker-Hamdi Great idea! Basicly the right cause.

So we can slow down the complie speed and code gulpfile like this:
```
gulp.task('sass:dev', () => {
    return setTimeout(() => {
        return gulp.src('./sassPath/*.scss')
        .pipe(sass())
        .pipe(gulp.dest('./distPath/css'))
        .pipe(reload({ stream: true }))   //if you use browser-sync
    }, 500)
})
```

It works fine for me!
Hope it could be helpful.

**Comment by mohdule** [comment]
@xiaofuyesnew Works for me 2, Thanks

**Comment by riptid3** [comment]
@xiaofuyesnew Thank you very much, i think same way but dont know how to put SetTimeout function in task right, had to write return ))) All works fine, you help me to overcome so big problem.

**Comment by mittalyashu** [comment]
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: _sass\style.sass
Error: File to import not found or unreadable: footer.sass.
       Parent style sheet: C:/Users/YASHU/Desktop/website/_sass/style.sass
        on line 9 of _sass/style.sass
>> @import "footer.sass";
   ^

    at options.error (C:\Users\YASHU\Desktop\website\node_modules\node-sass\lib\index.js:291:26)
```
Getting the same error. Tried everything.

**Comment by Shaker-Hamdi** [comment]
@mittalyashu Did you try this ...
https://github.com/dlmanning/gulp-sass/issues/1#issuecomment-247866836

**Comment by mittalyashu** [comment]
@Shaker-Hamdi You mean to say that it does take the time to fetch the files from the hard drive before compiling it.

**Comment by Shaker-Hamdi** [comment]
@mittalyashu something like that, I'm just guessing. The only thing that worked for me was moving all my projects to the SSD.

**Comment by tatwd** [comment]
The `sass task` only compiles the main sass file which imports other modules, and the `watch task` watches all sass files of your project.For example:

scss/main.scss
```  scss
@import "base";
...
```
scss/_base.scss
``` scss
// some styles
```
Then,you can modify your `gulpfile.js` like this:
``` javascript
...
gulp.task('sass', function() {
    return gulp.src('scss/main.scss')  // only compiles main.scss
        .pipe(sass())
        .pipe(gulp.dest('dist/css'));
});
...
gulp.task('watch:sass',function() {
    gulp.watch('scss/*.scss', ['sass']); // watching all .scss files
});
...
```
May you success！>_<

**Comment by starfish7** [comment]
how to solve this problem in vs code ?

**Comment by felipe-pita** [comment]
@starfish7 Did you tried this? https://github.com/dlmanning/gulp-sass/issues/1#issuecomment-278237590

**Comment by starfish7** [comment]
@felipe-pita , yes, but the same problem (
this is my sass part


gulp.task("styles", function() {
  return setTimeout(() => {
    return gulp
      .src("app/" + syntax + "/common." + syntax)
      .pipe(
        sass({ outputStyle: "expanded" }).on(
          "error",
          notify.onError({
            message: "<%= error.message %>",
            title: "Sass Error!",
            sound: "Pop"
          })
        )
      )
      .pipe(rename({ suffix: ".min", prefix: "" }))
      .pipe(autoprefixer(["last 15 versions", "> 0.1%"], { cascade: true }))
      .pipe(cleancss({ level: { 1: { specialComments: 0 } } }))
      .pipe(gulp.dest("app/css"))
      .pipe(browserSync.stream())
  }, 500);
});

**Comment by felipe-pita** [comment]
I think you should try to update node-sass or use https://www.npmjs.com/package/gulp-wait to insert a delay before run .pipe(sass..)

**Comment by xxx-nn** [comment]
`Error in plugin "gulp-sass"
Message:

gulp-sass 5 does not have a default Sass compiler; please set one yourself.
Both the `sass` and `node-sass` packages are permitted.
For example, in your gulpfile:

  var sass = require('gulp-sass')(require('sass'));

[16:22:12] The following tasks did not complete: sassHandler
[16:22:12] Did you forget to signal async completion?`

hi~  How to solve this problem？
