### ISSUE TITLE
pass errors to gulp stream

### ISSUE THREAD

**Issue by sandro-pasquali** [dlmanning/gulp-sass#101]
When sass() errors I'd like to catch the errors via [gulpstream].on('error', myHandler)

Currently, I can only log errors, or allow the whole task to throw.

**Comment by antwan1986** [comment]
+1

**Comment by Snugug** [comment]
This has been [resolved in 2.x](https://github.com/dlmanning/gulp-sass/blob/2.x). Please try it and report back. If we don't hear back, we'll assume it's been resolved and close this issue.

```
npm install dlmanning/gulp-sass#2.x
```

**Comment by Snugug** [comment]
As it's been a month, I'm closing this.
