### ISSUE TITLE
1.2.0 not pulling in imports

### ISSUE THREAD

**Issue by briandela** [dlmanning/gulp-sass#103]
Just noticed that when I upgrade to `1.2.0` from NPM (https://www.npmjs.org/package/gulp-sass) that the compile does not pull in my imports. `1.1.0` continues to pull in items correctly. This is the code I have:

``` js
var sassConfig = {
    includePaths: ['bower_components/foundation/scss'],
    outputStyle: 'expanded',
    errLogToConsole: true
};
return gulp.src(assets.styles.src)
    .pipe(sass(sassConfig))
    // ...
```

Any ideas? Was there a breaking change from `1.1.0` to `1.2.0`

**Comment by jonathan-reisdorf** [comment]
+1 - still doesn't work unfortunately

**Comment by CRKnight** [comment]
+1

**Comment by empirecoder** [comment]
+1

**Comment by dlmanning** [comment]
I'm not able to reproduce the issue. Could someone describe what's failing in more detail?

**Comment by empirecoder** [comment]
The node-sass version seems to be the problem. I'm converting a grunt file into a gulp file, for a Foundation build. My Foundation version is set to 5.3.3, so I can't upgrade that, and I didn't test with different versions of it. So I tested different versions of grunt-sass and gulp-sass, which have different dependency versions of node-sass.

Tested grunt-sass versions -> node-sass dependency version:
```
includePaths not included:
"grunt-sass" "~0.17.0" -> "node-sass": "1.2.3"
"grunt-sass" "~0.16.0" -> "node-sass": "^1.0.0"

includePaths included:
"grunt-sass" "~0.15.0" -> "node-sass": "^0.9.6"
"grunt-sass" "~0.13.1" -> "node-sass": "^0.9.0"
"grunt-sass" "~0.8.0" -> "node-sass": "~0.7.0"
```

Tested gulp-sass versions -> node-sass dependency version:
```
includePaths not included:
"gulp-sass": "~1.3.2" -> "node-sass": "2.0.0-beta"
"gulp-sass": "~1.2.3" -> "node-sass": "^1.0.0"
"gulp-sass": "~1.2.0" -> "node-sass": "^1.0.0"

includePaths included:
"gulp-sass": "~1.1.0" -> "node-sass": "^0.9.0"
```

gulpfile.js
```
var gulp         = require('gulp');
var sass         = require('gulp-sass');

gulp.task('sass', function() {
    return gulp.src([
            'scss/app.scss'
        ])
        .pipe(sass({
            includePaths: ['bower_components/foundation/scss'],
            outputStyle: 'nested',
            errLogToConsole: true
        }))
        .pipe(gulp.dest('dist/gulp'));
});

gulp.task('default', ['sass']);
```

gruntfile.js
```
module.exports = function(grunt) {
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),

        sass: {
            options: {
                includePaths: ['bower_components/foundation/scss']
            },
            dist: {
                options: {
                    outputStyle: 'nested'
                },
                files: {
                    'dist/grunt/app.css': 'scss/app.scss'
                }
            }
        }
    });

    grunt.loadNpmTasks('grunt-sass');
    grunt.registerTask('default', ['sass:dist']);
}
```

So, the successful configs for Foundation 5.3.3 are these:

bower.json
```
{
  "name": "defect",
  "dependencies": {
    "foundation": "~5.3.3"
  }
}
```

package.json
```
{
  "name": "defect",
  "version": "0.0.1",
  "devDependencies": {
    "bower": "~1.3.12",
    "gulp": "~3.8.10",
    "gulp-sass": "~1.1.0",
    "grunt": "~0.4.1",
    "grunt-sass": "~0.15.0"
  },
  "dependencies": {}
}
```

**Comment by moettinger** [comment]
+1

**Comment by loadedsith** [comment]
I was able to use an absolute path to work around this:

    var fs = require('fs'),
        path = require('path');

    var dirString = path.dirname(fs.realpathSync(__filename));

    gulp.task('styles', [],  function() {
      return gulp.src('src/{app, components}/**/*.scss')
        .pipe(sass({
          style: 'expanded',
          includePaths:[ dirString + '/../bower_components/foundation/scss' ]
        }))
        .on('error', handleError)
    });

Seemed to me that node-sass was getting passed the includePaths var, but that it wasnt resolving my relative directories correctly. Perhaps it is getting called from within node_modules/gulp-sass/node_modules/?

node@v0.10.35
npm@2.2.0

**Comment by Saturn2888** [comment]
Still having this issue w/ gulp-sass 2.0.4 where I put an array of paths in the includePaths option relative to the location of the Gulpfile, but not the file which was required in containing the pipe with gulp-sass in it.

**Comment by jacks0n** [comment]
I found prepending the relative path with `./` works for me. So `includePaths: [ './frameworks/foundation-5.5/scss' ]` instead of `includePaths: [ 'frameworks/foundation-5.5/scss' ]`.

**Comment by Saturn2888** [comment]
I believe this is working for me now without the './'. I don't know what changed.
