### ISSUE TITLE
malloc crash

### ISSUE THREAD

**Issue by aleemb** [dlmanning/gulp-sass#104]
I updated recently to 1.10 and ran into this issue

```
gulp(1166,0x7fff7db64310) malloc: *** error for object 0x1044a9d3d: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

Shortly there after, a day later 1.20 was released and I upgraded to that but still run into the same error. Is there something I can do to remedy this?

I am calling `sass()` without any options.

**Comment by DrummerHead** [comment]
For reference, I also had this error. My problem was that I missed some `;`s at the end of `@import` statements in `main.scss`. Adding these solved the issue. Cheers!

**Comment by xzyfer** [comment]
If you could supply a piece of Sass code that produced a malloc due to malformed `@import` that would be hugely useful.

**Comment by DrummerHead** [comment]
@xzyfer Of course! I created a repo with an isolated case that you can use for debugging at:

https://github.com/DrummerHead/sass-malloc-error

Cheers!

**Comment by xzyfer** [comment]
Thanks @DrummerHead this is perfect.

**Comment by xzyfer** [comment]
I've managed to get back around to this. This issue appears to have been fixed in successive node-sass releases.

**Comment by jakeNiemiec** [comment]
This happened for me recently after upgrade, fix: `rm -rf ./node_modules && npm cache clean --force && npm rebuild`
