### ISSUE TITLE
I can't install =/

### ISSUE THREAD

**Issue by romuloinnocencio** [dlmanning/gulp-sass#105]
What's wrong? I don't know...

![error](https://cloud.githubusercontent.com/assets/7289497/4691349/b1bdd362-5713-11e4-87bb-e666a520c8bd.jpg)

//GULPFILE//
var gulp    = require('gulp');
var sass    = require('gulp-sass')
var autop = require('gulp-autoprefixer');
var uglify  = require('uglify-js');
var watch = require('gulp-watch');

//sass
gulp.task('sass', function () {
    gulp.src('dev/styles/*.scss')
        .pipe(sass())
        .pipe(autop())
        .pipe(gulp.dest('css/geral.min.css'));
});

//uglify
gulp.task('uglify', function () {
    gulp.src('dev/js/*.js')
        .pipe(uglify())
        .pipe(gulp.dest('js/geral.min.js'));
});

//JSON//
  "devDependencies": {
    "gulp": "latest",
    "gulp-sass": "1.2.0",
    "gulp-autoprefixer": "latest",
    "gulp-watch": "latest",  
    "uglify-js": "latest"
  }

**Comment by SMERKY** [comment]
did anyone manage to fix this? still having the same issue?

**Comment by XmlmXmlmX** [comment]
This issue isn't solved

**Comment by xzyfer** [comment]
@XmlmXmlmX is long solved and affects ancient versions of gulp-sass and node-sass that are no long supported. There is no value in vaguely commenting on an issue that's over a year old. If you're experiencing issues please open a new issue with after reading the contributing documentation.
