### ISSUE TITLE
Source Maps not following imports

### ISSUE THREAD

**Issue by mattmischuk** [dlmanning/gulp-sass#109]
This might be a Safari 8 or Yosemite issue but since updating the source maps generated only go to the first import. 

In this case:

|-- screen.scss
|-- _base
|   |-- _base-config.scss
|   |-- _vars.scss
|   |-- _mixins.scss
|-- components
|   |-- _components-config.scss
|   |-- _header.scss
|   |-- _footer.scss

etc...

'screen.scss' imports all of the '*-config.scss' within each directory.
The contents of the '*-config.scss' are just imports for the sass files in each directory.

However the compiled source map is only showing the screen.scss file and doesn't follow the imports any further. Before the move away from ``` sourceComments: 'maps', ``` it worked fine.

**Comment by gonsfx** [comment]
+1

this is really needed. no point in using sass, gulp or this task if i can't use imports that work in sourcemaps.

**Comment by ralberts** [comment]
Confirmed - I see the same issue :-(

**Comment by mattmischuk** [comment]
Does anyone know of a good alternative to gulp-sass?


On Friday, Jan 16, 2015 at 11:40 AM, ralberts <notifications@github.com>, wrote:

Confirmed - I see the same issue :-(

**Comment by dlmanning** [comment]
Is this still a problem with gulp-sass 1.3.x?

**Comment by dlmanning** [comment]
@mattmischuk : gulp-ruby-sass is more stable if gulp-sass isn't working for you.

**Comment by dlmanning** [comment]
So a very cursory investigation shows source maps appear to be working just fine with imports on my machine. That's OS X 10.10.1, and gulp-sass 1.3.1. Will investigate more later.

**Comment by mattmischuk** [comment]
Yeah, after updating it appears to be working for me now. I will also test further. Thanks @dlmanning gulp-sass is exponentially faster than ruby. I'm glad it's working now. :)

**Comment by mattmischuk** [comment]
@gonsfx and @ralberts what version of gulp-sass were you/are you running?

**Comment by dlmanning** [comment]
@mattmischuk : Good to hear. FYI: gulp-sass is just a gulp plugin for node-sass, which itself is a set of node bindings to libsass. Both levels are ungoing rapid development, hence there's likely to continue to be some instability and breakage until things settle down.
