### ISSUE TITLE
Filename conflict

### ISSUE THREAD

**Issue by aleemb** [dlmanning/gulp-sass#111]
If I have a the following structure:

```
a/
  foo.scss
  all.scss
b/
  foo.scss
  all.scss
```

Both `foo.scss` files have different content. The `all.scss` files import their sibling `foo.scss` files:

```
// all.scss
@import 'foo';
```

The issue I am facing is that either b/all.css will include styles from `a/foo.scss` or vice-versa. The current work around is to rename the files so that one is call `afoo.scss` and the other is called `bfoo.scss`. This is kind of annoying since now all files have to be individually named across projects.

**Comment by Snugug** [comment]
This has been [resolved in 2.x](https://github.com/dlmanning/gulp-sass/tree/2.x). Please try it and report back. If we don't hear back, we'll assume it's been resolved and close this issue. If this issue persists with 2.x, please file this issue with `node-sass`

```
npm install dlmanning/gulp-sass#2.x
```

**Comment by Snugug** [comment]
As it's been a month, I'm closing this.

**Comment by msdark** [comment]
I'm having the same issue using v2.3.2

    return gulp.src([
       path.join(conf.paths.src, '/**/main.scss')
    ])
    .pipe($.debug({title: 'src'}))
    .pipe($.sourcemaps.init())
    .pipe($.sass(sassOptions)).on('error', conf.errorHandler('Sass'))
    .pipe($.inlineBase64({
      baseDir: 'src/',
      maxSize: 14 * 1024,
      debug: true
    }))
    .pipe($.autoprefixer()).on('error', conf.errorHandler('Autoprefixer'))
    .pipe($.sourcemaps.write())
    .pipe(gulp.dest(path.join(conf.paths.tmp, '/serve/')));

then the files under `folderA/main.css` and `folderB/main.css` contains the same css rules but the source files have different code (same names in the @import).
