### ISSUE TITLE
Incorrect mapping of sourcemaps using node-sass@1.1.4

### ISSUE THREAD

**Issue by dwayne-roberts** [dlmanning/gulp-sass#113]
@dlmanning I decided to update gulp-sass to 1.2.2. today and noticed that all my css classes mapped to incorrect scss sourcefiles and/or line numbers.  Figured it had to be something that changed. I'm no JS wizzkid but I checked your dependencies and noticed you're using the relaxt ^ instead of ~ for node-sass. dependency.They recently bumped from 1.0.3 to 1.1.4 and with ^1.0 it would require the new 1.1.4 version. If I use the 1.0.3 version the problem is resolved.

**Comment by Snugug** [comment]
As this is an upstream bug, I'm going to close this issue.
