### ISSUE TITLE
gulp-sourcemap-write: No source content for "style.css". Loading from file.

### ISSUE THREAD

**Issue by hilja** [dlmanning/gulp-sass#116]
I get that error if I try to use gulp-sourcemaps.

Here's my sass task:

```sass
gulp.task('styles', function() {
    gulp.src(paths.styles.masterFile)
        .pipe(sourcemaps.init())
            .pipe(sass({
                style: 'expanded',
                errLogToConsole: false,
                onError: function(err) {
                    return notify({
                        title: "Gulp Sass Error",
                        sound: "Pop"
                    }).write(err);
                }
            }))
        .pipe(sourcemaps.write(paths.root))
        .pipe(gulp.dest(paths.root))
});
```

Possibly related #109 #113 floridoo/gulp-sourcemaps#37 https://github.com/sindresorhus/gulp-autoprefixer/pull/3

**Comment by Snugug** [comment]
Can you provide some more information? What does your Sass file look like? Can you try to compile using [our 2.x branch](https://github.com/dlmanning/gulp-sass/tree/2.x)? Please try it and report back.

```
npm install dlmanning/gulp-sass#2.x
```

**Comment by Snugug** [comment]
As it's been a month, I'm closing this.

**Comment by urbanhop** [comment]
I also encountered this and tracked it somewhat down: It is related to sourcemaps and mixins.

base.less

	.mix() {	    
	    color: red;
	}

app.less

    @import "base.less";
	
	body {
		.mix;
	}

the gulp task warns:

    gulp-sourcemap-write: No source content for "base.less". Loading from file.
