### ISSUE TITLE
gulp-sass causes gulp to exit silently on empty .scss file

### ISSUE THREAD

**Issue by rogierschouten** [dlmanning/gulp-sass#118]
I had an empty scss file somewhere in my project, and this caused gulp to exit without telling me anything, gulp-plumber / log-to-console / on("error") etc notwithstanding. It might be nice to give a good error in this case, especially since the gulp task for sass is reported to have "Finished" so it took me a long time before I started looking at sass.

**Comment by Snugug** [comment]
This has been [resolved in 2.x](https://github.com/dlmanning/gulp-sass/tree/2.x). Please try it and report back. If we don't hear back, we'll assume it's been resolved and close this issue.

```
npm install dlmanning/gulp-sass#2.x
```

**Comment by jstoja** [comment]
I don't have the problem anymore with `1.3.3` :)
