### ISSUE TITLE
I never get any errors

### ISSUE THREAD

**Issue by kevinSuttle** [dlmanning/gulp-sass#138]
I can pass any gobbledygook nonsense to gulp-sass and it just compiles it into the CSS without warning or error.

**Task**
```
gulp.task('styles', function () {
  gulp.src(styleSrcDirectory + '/*.scss')
        .pipe($.sass({
          outputStyle: 'expanded',
          errLogToConsole: true
        }))
        .pipe(gulp.dest(styleOutputDirectory));
});
```

**SCSS** 
```
.example {
	nonsense: foo;
}
```
```
❯ gulp styles
[15:42:22] Using gulpfile ~/Code/EXAMPLE/gulpfile.js
[15:42:22] Starting 'styles'...
[15:42:22] Finished 'styles' after 80 ms
```
**CSS**
```
.example {
  nonsense: foo; }
```

**Comment by Snugug** [comment]
Sass very specifically does not have knowledge of individual valid `property: value`. This allows it to remain future friendly and not be tied to a specific version of the CSS spec, giving it flexibility.

**Comment by kevinSuttle** [comment]
But doesn't that go against the whole "scss is a superset of css" notion?

**Comment by Snugug** [comment]
No. `scss` being a superset of CSS means any valid CSS you write is valid `scss`. What you wrote is valid CSS syntax, just unrecognized properties. If you'd like to discuss the merits of Sass not throwing an error for writing unrecognized CSS properties, please open an issue in the [Sass issue queue](https://github.com/sass/sass/issues)

**Comment by quarterto** [comment]
```css
.example {
    nonsense: foo;
}
```

That's valid CSS syntax. Browsers just ignore unsupported properties, so it doesn't matter to SCSS that the property isn't a thing. Otherwise, you'd have to keep track of what properties every single browser actually implements, and update it every time something new gets implemented.

**Comment by kevinSuttle** [comment]
Makes sense.
