### ISSUE TITLE
suppress line number references in output

### ISSUE THREAD

**Issue by laurelnaiad** [dlmanning/gulp-sass#148]
I may not fully understand how sourcemaps are implemented, but I'm trying to solve an issue with output.

Due to the way my gulp streams work, by the time they get to gulp-sass a lot of the paths are absolute. If I allow the output to contain comments which refer to files/line numbers, then (because we have to commit our built app) each time someone builds the app on their machine, the paths in these comments change and look as if a real change has occurred, even though it's just someone's absolute path to their local repo.

I can work around his by changing the output to "compressed", and sourcemaps still work that way, but there are bugs in the version of libsass that I must use in order to get around installation issues on Linux... and when this version of libsass hits nested media queries, it doesn't produce the right output when in "compressed mode". In addition, I really don't want to be compressing the CSS, anyway.

All of this is to say that I would really like to find a way to **suppress the line number/file path** comments in nested output mode. Is there a way to do this? Am I overlooking the obvious? I've tried various combinations of flags but can't find something that works.

This is the relevant part of my code.
```
    sassParams = {
      includePaths: importDirs,
      onError: ctx.errorHandler,
      // compressed gets rid of the comments but exposes libsass bug with @media queries
      // outputStyle: 'compressed' 
    };

    sassPipe = lazypipe()
      // ....
      .pipe($.sourcemaps.init)
      .pipe($.sass, sassParams)
      .pipe(
        $.sourcemaps.write,
        '.',
        { includeContent: true, sourceRoot: '/' }
      )
```

**Comment by dlmanning** [comment]
Fixed by https://github.com/dlmanning/gulp-sass/pull/159
