### ISSUE TITLE
Stats object is not filled after compilation

### ISSUE THREAD

**Issue by laurensvanpoucke** [dlmanning/gulp-sass#149]
The stats object is not filled with stats after compilation. When using node-sass, you can get duration with stats.duration. This is not working with gulp-sass.

**Comment by Snugug** [comment]
This has been [resolved in 2.x](https://github.com/dlmanning/gulp-sass/tree/2.x). Please try it and report back. If we don't hear back, we'll assume it's been resolved and close this issue.

```
npm install dlmanning/gulp-sass#2.x
```

**Comment by Snugug** [comment]
As it's been a month, I'm closing this.
