### ISSUE TITLE
"File to read not found or unreadable" with concat + sourcemaps

### ISSUE THREAD

**Issue by parsnick** [dlmanning/gulp-sass#151]
I'm trying to use this plugin with gulp-concat and gulp-sourcemaps. Using one or the other in my gulp task works perfectly, but using both together causes "Error: File to read not found or unreadable: /path/to/filename/given/to/concat.css"

I've thrown together a quick minimal scenario to illustrate the problem: https://github.com/parsnick/gulp-sass-error-with-concat

gulpfile.js:

```javascript
var gulp       = require('gulp');
var concat     = require('gulp-concat');
var sourcemaps = require('gulp-sourcemaps');
var sass       = require('gulp-sass');

gulp.task('sass', function () {
  
  gulp.src('src/**/*.scss')
      .pipe(concat('all.css'))
      .pipe(sass())
      .pipe(gulp.dest('dist/'));
});

gulp.task('sassMap', function () {

  gulp.src('src/**/*.scss')
      .pipe(sourcemaps.init())
      .pipe(concat('allWithMap.css'))
      .pipe(sass())
      .pipe(sourcemaps.write())
      .pipe(gulp.dest('dist/'));
});

gulp.task('default', ['sass', 'sassMap']);
```

`sass` task runs fine, `sassMap` throws the error.

`sassMap` can work by simply piping to gulp-concat *after* gulp-sass, but that's not quite so easy in my actual gulpfile as there's a bit more going on!

**Comment by jmm** [comment]
This is due to a bug in gulp-sass. See #158.
