### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by pokoot** [dlmanning/gulp-sass#152]
Got this error

```bash
root@sandbox:/usr/share/nginx/html/Groovey(master) $ sudo npm install --no-bin-links
\
> node-sass@1.2.3 install /usr/share/nginx/html/Groovey/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/vagrant/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64/binding.node

> node-sass@1.2.3 postinstall /usr/share/nginx/html/Groovey/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

`linux-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vagrant/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-40-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"
npm ERR! cwd /usr/share/nginx/html/Groovey
npm ERR! node -v v0.13.0-pre
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by jonathanguevaraagudelo** [comment]
This worked for me: https://github.com/miguelcobain/ember-paper/issues/13

**Comment by dlmanning** [comment]
@pokoot : Whatever's going on here has to do with your configuration. It isn't gulp-sass specific.

**Comment by adregan** [comment]
Most likely this is due to node unstable. I had the same problem but a quick `n stable` fixed it for me.

If you aren't using n, give it a try `npm install -g n`

**Comment by ekortright** [comment]
Installing n and doing a 'n stable' worked perfectly for me.  Thanks @adregan

**Comment by costa** [comment]
@dlmanning You are perfectly right yet I don't think you must have closed the issue: rolling back to v0.10.36 — which helped me while v0.11 & v0.12 will not work — is not a solution, it's a workaround.
FYI, I have `gulp-haml-coffee` and `gulp-coffee` working in all the node versions.
Please check `gulp-sass` along with those under v0.12 (stable). Thank you.

**Comment by demisx** [comment]
+1 Running into this issue with node 0.12.0. Other plugins work fine. Please fix it as soon as time permits, since it's breaking all of our builds. Thank you!

**Comment by dlmanning** [comment]
See #189

**Comment by duellsy** [comment]
@demisx after you've installed `n`, you need to then use it to pick the version of npm you want, e.g.,

    n 0.10.32

Which will give you output like this: 

      install : v0.10.32
        mkdir : /usr/local/n/versions/0.10.32
        fetch : http://nodejs.org/dist/v0.10.32/node-v0.10.32-darwin-x64.tar.gz
    installed : v0.10.32

**Comment by demisx** [comment]
@duellsy Thank you. I haven't realized at first this was a node environment manager similar to `nvm`

**Comment by cameronjroe** [comment]
0.10.32 works, but 0.12.0 stable is still throwing an error `Error: Module did not self-register.`.

**Comment by mateeyow** [comment]
+1

**Comment by mieciu** [comment]
Fallen into same issue today
Was failing on Node v0.12.0:
```
./node_modules/.bin/gulp build
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
```
But runs successfully on v0.10.35.

**Comment by adregan** [comment]
This is apparently a problem with node sass https://github.com/sass/node-sass/issues/653 which is what gulp sass runs atop. And a fix is coming.

Unless you have some pressing need to run Node 0.12, I'd stick with 0.10.3x for the time being until everyone gets caught up (even though the release was two years coming ;) ). If you have someone in the office etc, who already upgraded (my boss, for example, just installed Node and as such had the new release), the above advice to use `n` or `nvm` to downgrade is pretty handy.

`npm install -g n`
`n 0.10`
`node --version`

**Comment by tcurdt** [comment]
node-sass 2.0.1 is out now
