### ISSUE TITLE
sourceComments "unavoidable" when generating sourceMaps

### ISSUE THREAD

**Issue by laurelnaiad** [dlmanning/gulp-sass#153]
I struggled for a while with trying to find the right combination of options to suppress the inline comments that were mapping to source line numbers.

It turns out this is due to this line ([index.js, line 25](https://github.com/dlmanning/gulp-sass/blob/0d1a5eb2b72ae3100b4c43463ff59c82c7ad90be/index.js#L25)):

```
    if (file.sourceMap) {
      opts.sourceComments = 'map';  // ******** here ***********
      opts.sourceMap = file.path;
    }
```

No matter what one sets for sourceComments, it's being overwritten to 'map' if  sourceMap is truthy.

Is there a reason for that line? Is it a relic of days when node-sass was crashing on various combinations of these parameters? I'm working on a gulp-sass branch that uses node-sass version 2 and its slightly modified API. Removing that line solves my issue and doesn't break anything for me, but I may not understand all of the implications.

EDIT: here is the branch I'm using which depends on node-sass v2 beta if anyone wants to play with it: https://github.com/laurelnaiad/gulp-sass/tree/node-sass-v2 (in npm terms, "laurelnaiad/gulp-sass#node-sass-v2").

**Comment by dlmanning** [comment]
Fixed in https://github.com/dlmanning/gulp-sass/pull/159
