### ISSUE TITLE
Sass options not working

### ISSUE THREAD

**Issue by satya164** [dlmanning/gulp-sass#156]
I'm trying to use it like this,

```
	return gulp.src(files.scss)
	.pipe(plumber())
	.pipe(sourcemaps.init())
	.pipe(sass({
		outputStyle: "nested",
		lineNumbers: !gutil.env.production,
		sourceMap: true
	}))
	.pipe(combinemq())
	.pipe(!debug ? autoprefixer() : gutil.noop())
	.pipe(!debug ? minify() : gutil.noop())
	.pipe(sourcemaps.write("."))
	.pipe(gulp.dest(dirs.css));
```

But I the options never work. The output style is always "compressed", and line numbers are always there, even if I disable them.

**Comment by Keats** [comment]
Hello,
can you try the 2.x branch to see if it's still an issue for you ?

**Comment by Snugug** [comment]
```
npm install dlmanning/gulp-sass#2.x
```

**Comment by satya164** [comment]
Doesn't seem to be working :(

**Comment by Snugug** [comment]
@satya164 Can you reduce your pipe to just the Sass bit and provided input and expected output? For instance, I can see `outputStyle` working (although we can write a test for it if you'd like), `lineNumbers` [isn't a `node-sass` option](https://github.com/sass/node-sass#options), and [this is the recommended way to handle sourcemaps](https://github.com/dlmanning/gulp-sass/tree/2.x#source-maps) as we handle setting up all of the required bits (in fact, your options for sourcemaps are actually invalid; if `sourceMap` is set to `true`, you need `outFile` set as well).

**Comment by satya164** [comment]
I'll try without line numbers and only sass. If I specify outFile for
sourcemaps, how can it be possible, considering there can be multiple sass
files? And then, there are inline sourcemaps, how can it be addressed then?

Isn't it better to have gulp-sass handle adding the source map using
gulp-sourcemaps? It'll address all those things as well as well work even
when I use multiple plugins.

**Comment by Snugug** [comment]
@satya164 that's my point. If you read the README (linked above) about how to handle sourcemaps, we do this for you.

Also, the default output style for `node-sass` is `nested`. Try changing it to `compressed` to see a difference

**Comment by Snugug** [comment]
As it's been a month, I'm closing this.

**Comment by Saturn2888** [comment]
I had the same issue, but found out it was because I minified after I generated the CSS without realizing it. User error might've been the case for @satya164 as well.
