### ISSUE TITLE
style.css compiles inside /sass folder no matter which path is set

### ISSUE THREAD

**Issue by vedranjaic** [dlmanning/gulp-sass#157]
Hello, sorry if this was asked before, but I'm not finding anything about it.
No matter what path I set in my gulpfile, style.css gets compiled inside sass folder.
Problem persists using either gulp-sass or gulp-ruby-sass

Ex,
`.pipe(gulp.dest('.'))`
compiles in `project/sass/style.css` instead of `project/style.css`

`.pipe(gulp.dest('/css'))`
compiles in `project/css/sass/style.css` instead of `project/css/style.css`

etc...
Does anyone know how to fix this?

**Comment by zebapy** [comment]
I'm not getting this issue upon trying to recreate. What's your full gulpfile.js look like?

**Comment by vedranjaic** [comment]
I think there was some character in gulpfile that was causing this error... When I re-typed manually the sass task, it worked fine, while copy/paste-ing the SAME code rendered an error

**Comment by zebapy** [comment]
It's interesting though, because when experimenting with gulp-watch, I ran into the problem you're getting now. Before, with a straight forward task, I didn't get this issue. Can you show your before / after code?

**Comment by vedranjaic** [comment]
It was __exactly__ the same, i c/p the code that had "an error" and pasted it over my manual type code, toggled with undo/redo and literally nothing changed... Except typed one worked, c/p one didn't...
<pre>
// Compile SASS
gulp.task('styles', function () {

	return sass(src.sass, {
			style: 'expanded',
			sourcemap: true
		})
		.on("error", notify.onError({
			title: "SASS Compile error",
			message: "<%= error.message %>"
		}))
		.pipe(autoprefixer({
			cascade: false
		}))
		.pipe(gulp.dest(dest.css))
		.pipe(reload({
			stream:true
		}))
		.pipe(notify({
			message: 'SASS approves this syntax!',
			onLast: true,
			sound: 'Hero'
		}));

});
</pre>

**Comment by Keats** [comment]
Seems like it was a gulp.dest oddity, not related to gulp-sass !
