### ISSUE TITLE
Dependancies on node-sass not up to date, 

### ISSUE THREAD

**Issue by cedriclombardot** [dlmanning/gulp-sass#162]
Hi,

When i try to install gulp sass i 've the following issue : https://github.com/sass/node-sass/issues/557

If i just install node-sass at last version 2.0.0 the bug is fixed. Have you got a patch method for me ?

Cédric

**Comment by brianium** [comment]
:+1:

**Comment by cedriclombardot** [comment]
I ve start a fork to fix that but not PR because not tested all the options : 

https://github.com/cedriclombardot/gulp-sass/compare/f3901174218d2bc58b12033f027c43c1655eefb2...HEAD

**Comment by ralberts** [comment]
@cedriclombardot Thanks!  Saved me today!  I am not sure the best option but for now I pulled in your fork: "npm install git+https://git@github.com/cedriclombardot/gulp-sass.git"

**Comment by laurelnaiad** [comment]
There's also a PR https://github.com/dlmanning/gulp-sass/pull/159 which does have working tests.

**Comment by dlmanning** [comment]
Updated with https://github.com/dlmanning/gulp-sass/pull/159
