### ISSUE TITLE
1.3.0 segmentation fault with neat

### ISSUE THREAD

**Issue by saadfarooq** [dlmanning/gulp-sass#165]
I keep getting segmentation faults when running `gulp-sass#1.3.0` with a project using [neat](neat.bourbon.io). If I comment out the `neat` import in my `scss` file, the fault doesn't occur.

Reverting to `1.2.4` fixes things.

**Comment by dlmanning** [comment]
@saadfarooq This is probable a libsass / node-sass thing. Have you made sure to completely reinstall gulp-sas?

**Comment by saadfarooq** [comment]
Yup... remove my npm cache, reinstalled all packages, even upgraded the system packages to make sure. Still crashes, even with `1.3.1`.

Maybe it's something in `neat` who don't claim compatibility with the latest `libsass` but there should still be an error. With so many wrappers it's hard to tell where in the chain it's going wrong for me.

**Comment by saadfarooq** [comment]
So this definitely seems like a `node-sass@2.0.0-beta` issues. Closing here.
