### ISSUE TITLE
Since node-sass v.2 error returns an object

### ISSUE THREAD

**Issue by joakimstrandell** [dlmanning/gulp-sass#170]
When setting `errLogToConsole` the output now is: [gulp-sass] [object Object]. That is because node-sass since v.2 now returns an object instead of an string. 

When using your own callback by setting `onError` an object is now returned instead of a string. That object looks like this:

```
{
    status: int,
    file: '',
    line: int,
    column: int,
    message: '',
    code: int
}
```

**Comment by pzatrick** [comment]
I'm seeing this in the output of gulp:

```
[15:34:09] Starting 'sass'...
[15:34:09] [gulp-sass] [object Object]
[15:34:09] [gulp-sass] [object Object]
[15:34:09] Finished 'sass' after 14 ms
```

Could this be related?

**Comment by joakimstrandell** [comment]
Yep. Because gulp-sass tries to write an object as an string. You can try handling the error with your own function until it's fixed. Do that by using the onError option, something like:

```
.pipe(sass({
    errLogToConsole: false,
    onError: function(err) {
        gutil.log('[gulp-sass] ' + err.message + ' on line ' + err.line + ' in ' + err.file);
    );
}
```

**Comment by dlmanning** [comment]
pr merged. thanks!
