### ISSUE TITLE
Top level file cannot be indented sass, must be scss file in gulp-sass 1.3.1

### ISSUE THREAD

**Issue by aaronjensen** [dlmanning/gulp-sass#173]
The top level file has to have the `.scss` extension. If you attempt to make it `.sass` and use the indented syntax it'll error out. See https://github.com/dlmanning/gulp-sass/issues/169 for an example. I believe that https://github.com/dlmanning/gulp-sass/issues/81 is no longer appropriate, because that doesn't seem to be a workaround anymore.

**Comment by greypants** [comment]
I believe this is the related commit and change: https://github.com/dlmanning/gulp-sass/commit/12f8db986359efe83dd7d0ca58c21b1c8b37e6de#diff-168726dbe96b3ce427e7fedce31bb0bcL25

**Comment by greypants** [comment]
JK! node-sass got updated to properly accept an indented syntax option!

https://github.com/sass/node-sass#indentedsyntax

Just pass `indentedSyntax: 'true'` in the options. No need for the hack anymore!

**Comment by aaronjensen** [comment]
Ah, this works, thanks!
