### ISSUE TITLE
Error message should indicate which file caused the error

### ISSUE THREAD

**Issue by cowwoc** [dlmanning/gulp-sass#177]
When `gulp-sass` runs across a broken `@import` it fails with:

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: file to import not found or unreadable: util/_Common.scss
Current dir: ~/foo/frontend/src/main/webapp/com/foo/frontend/page/
```

Expected behavior: The error message should indicate which file was referencing `util/_Common.scss`, otherwise I have no way of knowing which file to fix.

**Comment by Keats** [comment]
Did you have the errLogToConsole option set to true?
gulp-sass v2, which is due pretty soon (as soon as node-sass 3.0 is released I guess, in beta atm) will definitely have the file mentioned.
You can try the 2.x branch to use it, which also gives you a newer libsass
