### ISSUE TITLE
can not be compatible with io.js

### ISSUE THREAD

**Issue by VaJoy** [dlmanning/gulp-sass#178]
after installing io.js, gulp runs unsuccessfully, the `gulp-sass` module can not execute ( same result as I re-install this module )
Error info:

>E:\tomcat\webapps\dls>gulp
>
>module.js:341
>Module._extensions\[extension](this, filename);
>\ ^
>Error: The specified procedure could not be found.
>E:\tomcat\webapps\dls\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64\binding.node
>at Error (native)
>at Module.load (module.js:341:32)
>at Function.Module._load (module.js:296:12)
>at Module.require (module.js:351:17)
>at require (module.js:370:17)
>at Object. (E:\tomcat\webapps\dls\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:211:15)
>at Module._compile (module.js:446:26)
>at Object.Module._extensions..js (module.js:464:10)
>at Module.load (module.js:341:32)
>at Function.Module._load (module.js:296:12)

so plz update `gulp-sass` for io.js

**Comment by dlmanning** [comment]
See #175
