### ISSUE TITLE
indentedSyntax option should be set to true for all .sass files

### ISSUE THREAD

**Issue by mhamel06** [dlmanning/gulp-sass#180]

**Comment by bcherny** [comment]
+1 please merge this

**Comment by slavomirvojacek** [comment]
+1 this would solve a lot of problems, please merge

**Comment by telekosmos** [comment]
++1
... or if not default, at least documented (without diving the code), impossible to compile _sass_ files without this set to true. would solve many problems and save searching times :)

**Comment by Keats** [comment]
It seems like this is solved directly by node-sass/libsass in the next version, can you try the 2.x branch of gulp-sass and report on #222 of any bugs happening relating to that?

**Comment by Snugug** [comment]
As it's been a month, I'm closing this.
