### ISSUE TITLE
Error reporting broken in v1.3.2

### ISSUE THREAD

**Issue by valdelama** [dlmanning/gulp-sass#182]
Eg. remove the `;` from the end of a variable and get this error using 1.2.4:
```
/app/utility/variables:47: top-level variable binding must be terminated by ';'
```
but with 1.3.2 I get this: 
```
 [gulp-sass] [object Object]
```

**Comment by laurelnaiad** [comment]
Yes, that is what you get when you or some other code "`toString`s" the object. I think the issue may be that the error object doesn't have Error in its prototype chain, which I think would be a node-sass issue.

I hacked this into my error handler in gulp very quickly. There was no good reason to use a try/catch block, but I was being lazy:

```
    try {
      errString = JSON.stringify(err, false, ' ');
    }
    catch (myErr) {
      errString = err.toString().trim();
    }
```

I don't know what the "right" solution is, but I suspect it should be raised on node-sass, hopefully before 2.0 is frozen, if indeed the error objects coming out don't have a useful toString implementation in their chain.

**Comment by Snugug** [comment]
This has been [resolved in 2.x](https://github.com/dlmanning/gulp-sass/tree/2.x). Please try it and report back. If we don't hear back, we'll assume it's been resolved and close this issue.

```
npm install dlmanning/gulp-sass#2.x
```

**Comment by Ariix** [comment]
Just tried it. Worked great--Thank you!

**Comment by scerelli** [comment]
Can't figure out how to fix it, any idea?

**Comment by Snugug** [comment]
I'm… gonna close now. As you seem to confirm that we've indeed resolved this issue
