### ISSUE TITLE
Install fails - Windows 2008 - Error: `libsass` bindings not found. Try reinstalling `node-sass`?

### ISSUE THREAD

**Issue by mpiasta-ca** [dlmanning/gulp-sass#185]
Can someone give me a pointer here?

Trying to automate a build on a TeamCity server that's running on Windows 2008. For some reason, all the other npm packages install. But `gulp-sass` install seems to keep failing:

```
> Error: `libsass` bindings not found. Try reinstalling `node-sass`?
>      at getBinding (G:\[...]\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:21:11)
>      at Object.<anonymous> (G:\[...]\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:211:23)
>      at Module._compile (module.js:456:26)
>      at Object.Module._extensions..js (module.js:474:10)
>      at Module.load (module.js:356:32)
>      at Function.Module._load (module.js:312:12)
>      at Module.require (module.js:364:17)
>      at require (module.js:380:17)
>      at Object.<anonymous> (G:\[...]\node_modules\gulp-sass\index.js:3:17)
>      at Module._compile (module.js:456:26)
>      at Object.Module._extensions..js (module.js:474:10)
```

If I track the error to earlier in the log, this is what I find:

```
> fs: missing callback Error: EPERM, unlink 'G:\[...]\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-ia32\binding.node'
```

Happens every time. I tried installing `node-sass` directly too, which seems to pass without errors, but `gulp-sass` still throws the EPERM and libsass error anyway.

Thoughts?

**Comment by mpiasta-ca** [comment]
Found a temporary solution. When I first run `npm install node-sass@1.0.3` before installing `gulp-sass`, it seems to work after that.

https://github.com/sass/node-sass/issues/497#issuecomment-61116327

**Comment by dlmanning** [comment]
See #174

**Comment by benmirkhah** [comment]
Reinstalling gulp-sass fixed it for me, thanks @mpiasta-ca

**Comment by LunarDevelopment** [comment]
:+1: @benmirkhah

**Comment by jiro9611** [comment]
@mpiasta-ca Your solution works for me, thanks!

**Comment by sebhildebrandt** [comment]
For me the solution was like this:

It turned out, that I had a version of "node-sass" in my node-modules path. You can find it with this statement:

`node -e "console.log(require.resolve('node-sass'))"`

After removing this node-sass module completely, I was able to reinstall gulp-sass and then it worked perfectly.

**Comment by juukie** [comment]
:+1: @benmirkhah

**Comment by pmoelgaard** [comment]
This worked for me, I had to first install node-sass with sudo (I'm on Mac), and then subsequently install gulp-sass

**Comment by riapp** [comment]
`npm install node-sass` fixed the issue

**Comment by lchangdev** [comment]
thanks @benmirkhah :+1:!

**Comment by haydenhancock** [comment]
I am still having trouble with this. I've tried several things:

1. Uninstalled gulp-sass and node-sass
2. Installed node-sass and then gulp-sass in that order
3. Ran 'npm rebuild node-sass' as the error suggested but the "Binary is fine."
4. Uninstalled node.js x64 and installed node.js x86

When I require sass = ('gulp-sass'); in gulpfile.js Visual Studio throws the error. When I comment that line Visual Studio doesn't throw the error but obviously I can't run any tasks that use gulp-sass. I don't seem to be having the same issue when using Node.js CMD.

I am on Windows 10 x64 and using Visual Studio 2015 Professional. Node version 4.2.2, NPM version 2.14.7. After reading a lot of posts, it seems like this is a binding issue? Any help would be greatly appreciated.

**Comment by haydenhancock** [comment]
I resolved by issue with Visual Studio by moving the PATH variable higher in priority as found [here](http://blog.boro2g.co.uk/grunt-and-gulp-tasks-in-visual-studio-2015-libsass-error/).

**Comment by AgDude** [comment]
If you still get this issue upgrade to gulp-sass 2.1.

**Comment by 4score** [comment]
Same problem here and no combination or order of : npm rebuild node-sass, npm uninstall node-sass gulp-sass, or installing will fix it.

I am on a "forced" install of gulp4 and am running node version 5.6.0 if that matters.

Simply, the binding is located here:
/var/www/html/gulptest/node_modules/node-sass/vendor/linux-x64-**11**/binding.node

but gulp, node, is looking for it here:
/var/www/html/gulptest/node_modules/node-sass/vendor/linux-x64-**47**/binding.node

I beg for help.

**Comment by indahibrahim** [comment]
Try this fixes:

sudo npm install -g n
sudo n 0.12.7
sudo npm install node-sass@2
sudo npm -g install node-gyp@3
sudo npm rebuild node-sass

**Comment by Serjster** [comment]
@indahibrahim This doesn't work in VS, because VS still runs as 32 bit... n is 64 bit.

**Comment by Serjster** [comment]
@haydenhancock Make sure you're not using a beta version of gulp-sass

**Comment by alexandesigner** [comment]
> Uninstalled gulp-sass and node-sass
> Installed node-sass and then gulp-sass in that order
> Ran 'npm rebuild node-sass' as the error suggested but the "Binary is fine."
> Uninstalled node.js x64 and installed node.js x86

It's worked for me

**Comment by sumanbogati** [comment]
For me this `npm install -S gulp-sass@latest` fixed my problem.
I have centos6.5, `node v4.4.7` and `npm 3.10.4`

**Comment by indahibrahim** [comment]
Yeah installing latest gulp-sass works also, or remove your node-modules and npm i

**Comment by ykpoh** [comment]
@sumanbogati Thanks for the solution provided, it solved my problem too after trying the commands like `npm rebuild node-sass` and `npm remove node-sass and run npm install node-sass`

**Comment by umairhm** [comment]
I was facing this issue. In my case the parent package.json was referring to new version of node-sass but the version of gulp-sass was referring to old node-sass. As soon as I updated gulp-sass to latest version, and ran 'npm rebuild node-sass', issue was gone.

**Comment by kalyanchakravarthys** [comment]
My package.json had older version of gulp-sass, updated it to "gulp-sass": "^2.3.2" and did npm install. It worked !

**Comment by radosvet93** [comment]
I had a older version and running npm install -D gulp-sass@latest fix the problem
