### ISSUE TITLE
error reading values after  on line 32 in

### ISSUE THREAD

**Issue by rkmax** [dlmanning/gulp-sass#187]
I'm using gulp-sass and [gridle](http://gridle.org/) and using the following task

```js
gulp.task('styles', function() {

    var dir = config.dist + '/css';

    return gulp.src(config.scss) // src/styles/main.scss
        .pipe(sass({
            sourceComments: dist ? 'none' : 'map',
            sourceMap: 'sass',
            outputStyle: dist ? 'compressed' : 'nested',
            includePaths: ['node_modules/gridle/sass']
        }))
        //.pipe(autoprefixer("last 2 versions", "> 1%", "ie 8"))
        .on('error', handleErrors)
        .pipe(gulp.dest(dir))
        //.pipe(gulpif(browserSync.active, browserSync.reload({ stream: true })))
    ;
});
```

if the option `errLogToConsole: true` i the a ` error reading values after  on line 32 in node_modules/gridle/sass/gridle/_common-mixins.scss`

but i dont understand why running the command `sass src/styles/main.scss -Inode_modules/gridle/sass'` works fine

**Comment by callumacrae** [comment]
I'm also getting this. I'll send a pull request with a failing test case—I have no idea how to fix it, sorry.

Broken:

```js
'use strict';

var gulp = require('gulp');
var sass = require('gulp-sass');

gulp.task('default', function () {
  return gulp.src('./test/fixtures/sass/test.sass')
    .pipe(sass())
    .pipe(gulp.dest('output'));
});
```

Working:

```js
'use strict';

var gulp = require('gulp');
var sass = require('node-sass');

gulp.task('default', function (done) {
  sass.render({
    file: './test/fixtures/sass/test.sass',
    success: function () { done() }
  });
});
```

The problem is in gulp-sass.

**Comment by callumacrae** [comment]
And test.sass contains only this:

```sass
$color: blue

body .div
  color: $color
```

As far as I can see, that is perfectly valid Sass.

**Comment by dlmanning** [comment]
Thanks for putting in the effort to write a failing test. I'll take a look at this a little later.

**Comment by Keats** [comment]
Just ran that test into the 2.x branch and that seems fixed, I added that example as a test in https://github.com/dlmanning/gulp-sass/pull/222
