### ISSUE TITLE
invalid operands for multiplication error when using unquote()

### ISSUE THREAD

**Issue by pingyuanChen** [dlmanning/gulp-sass#188]
@mixin multi-ellipsis($font-size, $line-height, $lines, $is-adaptive: false){
  $font-size: unquote($font-size);   //only comment these two lines, gulp-sass can pass
  $line-height: unquote($line-height);
  @if $is-adaptive {
    max-height: $line-height * $lines;
  }
  @else{
    height: $line-height * $lines;
  }
  line-height: $line-height;
  font-size: $font-size;
  overflow: hidden;
  text-overflow: ellipsis;
  @include display-box();
  -webkit-line-clamp: $lines;
  @include box-orient(vertical);
}

**Comment by dlmanning** [comment]
This is an issue for https://github.com/sass/libsass
