### ISSUE TITLE
Module._extensions error with Node 0.12

### ISSUE THREAD

**Issue by rcollette** [dlmanning/gulp-sass#189]
I just updated to Node 0.12 on Windows 7 64 bit and am now receiving the following error.   I uninstalled and reinstalled gulp-sass with no luck.

```
Failed to load "C:\code\rcollette\RequestAngularTS\RequestAngularTS.Web\gulpfile.js"...
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: The specified procedure could not be found.

C:\code\rcollette\RequestAngularTS\RequestAngularTS.Web\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64\binding.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\code\rcollette\RequestAngularTS\RequestAngularTS.Web\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:211:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by chyld** [comment]
I'm on using 64-bit node v0.12 mac. Same error as above.

module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/chyld/Code/temp/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:211:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by DGStefan** [comment]
Same here after upgrading nodejs to 0.12

**Comment by RichardLitt** [comment]
Same here.

**Comment by dlmanning** [comment]
For the record the problem here is with node-sass. It's not something I can fix. Follow this thread: https://github.com/sass/node-sass/issues/653

**Comment by kylescousin** [comment]
Any estimate on when this will become compatible with 0.12?

**Comment by dlmanning** [comment]
@kylescousin : Please read my comment above

**Comment by sgade** [comment]
I used the current node-sass master and built the binaries myself. That worked fine.
However, now I'm getting this in my gulp.task:

```javascript
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: invalid top-level expression
```

I think this is an error of gulp-sass but I am happy to be corrected.

**Comment by oliversong** [comment]
@dlmanning fyi looks like they updated node-sass to the next version which resolves the issue.

**Comment by mcshaman** [comment]
Yeah... Apparently node-sass has been updated to work in Node 0.12. But still gulp-sass is still not working. I'm looking forward to using gulp-sass. I'm new to Node dev workflows... So new that Node 0.12 is the first version I installed. And the first thing I wanted to do was compile some SASS using Gulp. Took me ages to work out it wasn't my technical ability that was messing things up.

**Comment by dlmanning** [comment]
the newly released node-sass 2.0.0 still isn't building on iojs or node 0.12 for me. I've commented on the issue thread in the node-sass repo. I'll update the dependency when the build works (hopefully tomorrow). If anyone wants to try and see if they have more luck, just change the node-sass dependency to "^2.0.0" in package.json and `npm install .`

**Comment by mcshaman** [comment]
Didn't work for me

```
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@2.0.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@2.0.0 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/username/project/node_modules/gulp-sass/npm-debug.log
```

**Comment by mcshaman** [comment]
Well I just updated to node-sass 2.0.1. The self-register error has gone... but now I have the following error

```
[20:24:47] Using gulpfile ~/project/gulpfile.js
[20:24:47] Starting 'sass'...
[20:24:47] Finished 'sass' after 7 ms
/Users/username/project/node_modules/gulp-sass/index.js:50
        obj.map.sources = obj.map.sources.map(function(source) {
                                         ^
TypeError: Cannot read property 'map' of undefined
    at opts.success (/Users/username/project/node_modules/gulp-sass/index.js:50:42)
    at options.success (/Users/username/project/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:163:7)
```

Is this because of me or is it something else that needs fixing?

**Comment by mathiasbynens** [comment]
@mcshaman See https://github.com/dlmanning/gulp-sass/issues/190.

**Comment by dlmanning** [comment]
Fixed in 314ce5c1594e541a55e5c5009fb0733c45226567

**Comment by RichardLitt** [comment]
Thanks @dlmanning

**Comment by wdinau** [comment]
it works!! you're amazing @dlmanning 

My old error:
Module._extensions extension (this, filename);
^
Error: Module did not self-register.

after using 1.3.3 it all works.

**Comment by dlmanning** [comment]
@wdinau Thanks, but all the credit here goes to the node-sass team.
