### ISSUE TITLE
gulp.dest - specific .css file for output instead of directory

### ISSUE THREAD

**Issue by cmegown** [dlmanning/gulp-sass#19]
Just noticed this while trying to integrate Gulp into a WordPress theme I'm building. Can't output my `.scss` into the _required_ `style.css` file in the theme's root. Not sure if I'm missing something, but this kind of functionality seems necessary.

Ex:

```
gulp.task('sass', function() {
  gulp.src('./scss/*.scss')
      .pipe(sass())
      .pipe(gulp.dest('style.css'));
});
```

**Comment by kesha-antonov** [comment]
@cmegown thanks!

**Comment by ctrlaltdylan** [comment]
Exactly what I'm trying to accomplish @cmegown but I'm getting a `Error: EISDIR,` with the same gulpfile.
