### ISSUE TITLE
Can't use gulp-sass anymore because it keeps installing 2.0 beta

### ISSUE THREAD

**Issue by kylescousin** [dlmanning/gulp-sass#192]
npm install gulp-sass@1.3.2

Gives: node-sass@2.0.0-beta install
node-sass@2.0.0-beta postinstall

Then when running gulp it says:
Module._extensionsextension;
^
Error: no errorc:\Users...\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64\binding.node
at Error (native)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object. (c:\Users...\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:211:15)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)

Any idea how to fix this?

**Comment by canuzunoglu** [comment]
same

**Comment by dlmanning** [comment]
`npm install gulp-sass@1.2.4`

**Comment by kylescousin** [comment]
Then this happens:

npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "gulp-sass@1.2.4"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

**Comment by dlmanning** [comment]
Nothing you install is going to work with 0.12, node-sass doesn't support 0.12 yet. node-sass 2.0 will support io.js and 0.12 when it's released. You should follow https://github.com/sass/node-sass/issues/627 and go back to node 0.10 if node-sass is critical for your deployment.

**Comment by kylescousin** [comment]
Ok,  thanks.

**Comment by ChALkeR** [comment]
Can't this be closed now?

**Comment by dlmanning** [comment]
yep

**Comment by kylescousin** [comment]
Thanks Lord dlmanning, all works well with 0.12.
