### ISSUE TITLE
improve cli

### ISSUE THREAD

**Issue by meandavejustice** [dlmanning/gulp-sass#194]
need to be able to pull in `weekly-specials` from http://www.sheridanfruit.com/Weekly-Specials/.

I suggest you use the `request` & `cheerio` modules. Licensing of http://www.sheridanfruit.com/Weekly-Specials/ is unclear.

**Comment by dlmanning** [comment]
https://www.youtube.com/watch?v=pX_-Nd_kOKI&t=28
