### ISSUE TITLE
Sass 'Killed' after upgrading to 1.3.3

### ISSUE THREAD

**Issue by itonics-tbeauvais** [dlmanning/gulp-sass#195]
Upgraded to 1.3.3 to fixed some beta issues with node-sass but now.. 

````
[gulp] resources/modules/user/user.scss
[gulp] resources/modules/explorer/explorer.scss
[gulp] resources/pages/application/main/_layout.scss
[gulp] resources/pages/application/main/_navigation.scss
Killed
````

I have no way of knowing what the actual error is.

**Comment by dlmanning** [comment]
Unfortunately, neither do I. Could you investigate a little more?

**Comment by itonics-tbeauvais** [comment]
How?

**Comment by itonics-tbeauvais** [comment]
And in 1.2.4 I have a different problem:

````
`linux-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/lebowski/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Linux 3.13.0-39-generic
npm ERR! argv "node" "/usr/local/node/node-default/bin/npm" "install" "--no-bin-links"
npm ERR! node v0.12.0
npm ERR! npm  v2.1.11
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
````

**Comment by dlmanning** [comment]
Yes, the problem with 1.2.4 and node 0.12 is well documented elsewhere.

All I can tell is that something on your system is killing the gulp process for some reason. It's not a bug in gulp-sass, it's something going on in your environment.

Check out this thread for more info: http://stackoverflow.com/questions/726690/who-killed-my-process-and-why

**Comment by itonics-tbeauvais** [comment]
This is happening only upon upgrading to gulp 1.3+ and thus node-sass 2.0+ in all environments.  Every colleague, deployment situation (Jenkins), and Heroku instance was seeing this problem.  There are no underlying issues with the environment so I believe node-sass is doing something wrong here.

I will do some research if you have no further insight.  Thanks.

**Comment by dlmanning** [comment]
Yeah, it's completely opaque to me. Without being able to reproduce your issue locally I'm not going to be able to do much. If you think it might be a node-sass problem you could try running that CLI on by itself, or file an issue on their issue tracker. Sorry.
