### ISSUE TITLE
invalid unordered_map<K, T> key

### ISSUE THREAD

**Issue by Haemoglobin** [dlmanning/gulp-sass#200]
Hi - after upgrading to node 0.12 we seem to be getting the following error from the gulp-sass plugin.  

We have had to roll back to 0.10 until we resolve this:

ERROR [karma]: { [Error: invalid unordered_map<K, T> key]
  message: 'invalid unordered_map<K, T> key',
  fileName: undefined,
  lineNumber: undefined,
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass',
  __safety: { toString: [Function] } }
[10:26:17] Karma has exited with 1

Versions:
├─┬ gulp-sass@1.3.3
│ ├─┬ node-sass@2.0.1
│ │ ├─┬ sass-graph@1.0.3

Is this something that I should be raising on the node-sass project instead?

**Comment by laurent-le-graverend** [comment]
Also got this bug.

Could not find a clear reason for that, happening in Foundation for Apps sass source.

**Comment by Haemoglobin** [comment]
Linked to the following? 
http://discuss.prepros.io/t/libsass-error-invalid-unordered-map-k-t-key/287

**Comment by Haemoglobin** [comment]
I have found out what is causing this, by first guessing that maybe it was one of our scss files causing it and then individually going through them _one by one_ compiling each one before narrowing down the cause even within that file. 

So strangely here it is:
WORKS:
$map: (
  test: 1
);

ERROR:
$map: (
  notest: 1
);

If you have a sass map, where a key starts with 'no' - then you will see the following error: 
invalid unordered_map<K, T> key

I have raised a bug on libsass as I presume that's where the bug is (https://github.com/sass/libsass/issues/934), however is gulp-sass able to at least report the file that has the issue?

**Comment by joebell93** [comment]
Any luck on this @Haemoglobin?
I'm getting this issue on Foundation for Apps too

**Comment by Haemoglobin** [comment]
Yes - please follow the issue I linked to on libsass, it was an issue there that they have now fixed for the next release. The workaround was to quote the sass map keys for now.
