### ISSUE TITLE
Installation on Windows 8.1

### ISSUE THREAD

**Issue by sean-hill** [dlmanning/gulp-sass#201]
Hey there, I'm trying to install this on Windows 8.1, but I'm getting these errors.

I have installed ruby and sass successfully on my machine.

	C:\Users\Blitzcrank\Documents\Development\unbill-mobile>npm install gulp-sass
	npm WARN package.json unbill@1.0.0 No repository field.
	-
	> node-sass@0.9.6 install C:\Users\Blitzcrank\Documents\Development\unbill-mobile\node_modules\gulp-sass\node_modules\node-sass
	> node build.js

	child_process: customFds option is deprecated, use stdio instead.

	C:\Users\Blitzcrank\Documents\Development\unbill-mobile\node_modules\gulp-sass\node_modules\node-sass>node "C:\Program Files (x86)\nodejs\no
	de_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
	child_process: customFds option is deprecated, use stdio instead.
	Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
	cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\Blitzcrank\Documents\Development\unbill-mobile\node_modules\gulp-sa
	ss\node_modules\node-sass\build\binding.vcxproj]
	cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\Blitzcrank\Documents\Development\unbill-mobile\node_modules\gulp-sa
	ss\node_modules\node-sass\build\binding.vcxproj]
	cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\Blitzcrank\Documents\Development\unbill-mobile\node_modules\gulp-sa
	ss\node_modules\node-sass\build\binding.vcxproj]
	  binding.cpp
	cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\Blitzcrank\Documents\Development\unbill-mobile\node_modules\gulp-sa
	ss\node_modules\node-sass\build\binding.vcxproj]
	  sass_context_wrapper.cpp
	cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Users\Blitzcrank\Documents\Development\unbill-mobile\node_modules\gulp-sa
	ss\node_modules\node-sass\build\binding.vcxproj]
	  ast.cpp
	  base64vlq.cpp
	  bind.cpp
	C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error C1083: Cannot open include file: 'qos.h': No such file or d
	irectory (..\binding.cpp) [C:\Users\Blitzcrank\Documents\Development\unbill-mobile\node_modules\gulp-sass\node_modules\node-sass\build\bind
	ing.vcxproj]
	C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error C1083: Cannot open include file: 'qos.h': No such file or d
	irectory (..\sass_context_wrapper.cpp) [C:\Users\Blitzcrank\Documents\Development\unbill-mobile\node_modules\gulp-sass\node_modules\node-sa
	ss\build\binding.vcxproj]
	  constants.cpp
	  context.cpp
	  contextualize.cpp
	  copy_c_str.cpp
	  error_handling.cpp
	  eval.cpp
	  expand.cpp
	  extend.cpp
	  file.cpp
	  functions.cpp
	  inspect.cpp
	  output_compressed.cpp
	  output_nested.cpp
	  parser.cpp
	  prelexer.cpp
	  sass.cpp
	  sass_interface.cpp
	  source_map.cpp
	..\libsass\parser.cpp(997): warning C4101: 'err' : unreferenced local variable [C:\Users\Blitzcrank\Documents\Development\unbill-mobile\nod
	e_modules\gulp-sass\node_modules\node-sass\build\binding.vcxproj]
	  to_c.cpp
	  to_string.cpp
	  units.cpp
	  utf8_string.cpp
	  util.cpp
	  sass2scss.cpp
	gyp ERR! build error
	gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
	gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
	gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
	gyp ERR! System Windows_NT 6.3.9600
	gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
	gyp ERR! cwd C:\Users\Blitzcrank\Documents\Development\unbill-mobile\node_modules\gulp-sass\node_modules\node-sass
	gyp ERR! node -v v0.12.0
	gyp ERR! node-gyp -v v1.0.2
	gyp ERR! not ok
	Build failed
	npm ERR! Windows_NT 6.3.9600
	npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
	"gulp-sass"
	npm ERR! node v0.12.0
	npm ERR! npm  v2.5.1
	npm ERR! code ELIFECYCLE

	npm ERR! node-sass@0.9.6 install: `node build.js`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the node-sass@0.9.6 install script 'node build.js'.
	npm ERR! This is most likely a problem with the node-sass package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node build.js
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls node-sass
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     C:\Users\Blitzcrank\Documents\Development\unbill-mobile\npm-debug.log

	C:\Users\Blitzcrank\Documents\Development\unbill-mobile>

**Comment by dlmanning** [comment]
For some reason it appears to be trying to install a really old version of node-sass. The current version is 2.0.1. Do you have the dependency set at version 0.9.6 somewhere?

**Comment by sean-hill** [comment]
Hey @dlmanning, so in the package.json I have for gulp-sass it's pointing to 0.9.6, I'll have to fix that on my end. Thanks.
