### ISSUE TITLE
Why does errLogToConsole suppress error?

### ISSUE THREAD

**Issue by cappslock** [dlmanning/gulp-sass#203]
I'm trying to understand why passing `errLogToConsole: true` suppresses the error event from being emitted on the stream. I think it's useful for the stream to emit an error still so that the gulp process will fail and the process will have a non-zero exit code. If I want this to happen as it's built currently I have to do something like this:

```
        .pipe(sass({
            onError: function (error) {
                console.error('[gulp-sass] ' + error.message + ' on line ' + error.line + ' in ' + error.file);
                process.exit(1);
            }
        }))
```

Am I missing something?

**Comment by Keats** [comment]
That's the point of that option, if it's set to true gulp will not exit.
If you want gulp to stop, remove that option (it defaults to false)

**Comment by cappslock** [comment]
Why conflate useful error logging with useful process exit codes? They seem
like separate functions. Having to choose between them or write custom
logic to support both seems unnecessary. Is there a better way to achieve
that goal?

**Comment by cappslock** [comment]
Maybe a simpler way to state my issue: why doesn't the default behavior log
more error detail?

**Comment by Keats** [comment]
gulp-sass v2 will by default exit gulp on compilation error (quite standard for gulp plugins) but you can catch the errors that way:

```js
var gulp = require('gulp');
var sass = require('gulp-sass');

gulp.task('sass', function () {
    gulp.src('./scss/*.scss')
        .pipe(sass().on('error', sass.logError))
        .pipe(gulp.dest('./css'));
});
```

You can try that version by using the 2.x branch

**Comment by cappslock** [comment]
Perfect, thanks.
