### ISSUE TITLE
cannot download "binding.node" file

### ISSUE THREAD

**Issue by iTonyYo** [dlmanning/gulp-sass#205]
**CANNOT download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/win32-x64-node-1.5/binding.node** :point_down: :point_down: :point_down: :point_down: :point_down:

![gulp sass error](https://cloud.githubusercontent.com/assets/5499703/6636980/0a088b48-c9b0-11e4-81a7-b623ed4e9aad.png)

:point_down: :point_down: :point_down: :point_down: :point_down:

![gulp sass error extended](https://cloud.githubusercontent.com/assets/5499703/6637058/c720f788-c9b0-11e4-956c-c04b92785b8b.png)

**AND** there's no such file or dir like `v2.0.1/win32-x64-node-1.5/binding.node` in [node-sass-binaries](https://github.com/sass/node-sass-binaries) project :bangbang: :point_down: :point_down: :point_down: :point_down: :point_down:

![node sass binaries](https://cloud.githubusercontent.com/assets/5499703/6637231/ea7b2d50-c9b2-11e4-8fb1-d9828c1b3a9b.png)

**How can I solve this problem?**

**Comment by lmartins** [comment]
What's the use case here?
You should be installing `node-sass` via NPM with `npm install gulp-sass`.

Can you please explain what you're trying to achieve?

**Comment by Keats** [comment]
It downloads the binary when installing gulp-sass so it seems like a node-sass issue

**Comment by Snugug** [comment]
Please file this issue over on the [node-sass](https://github.com/sass/node-sass) issue queue.
