### ISSUE TITLE
@at-root BEM syntax error. 

### ISSUE THREAD

**Issue by flatsteve** [dlmanning/gulp-sass#21]
Hi there,

I'm using Sass 3.3.0.rc.1 with gulp-sass and everything is working great except for one little thing (which I can live without but just thought I'd bring up in case anyone can help). I've been using BEM style syntax on recent projects and use Scott Kelum's handy little mixin (below) which uses Sass 3.3's @at-root.

@mixin e($name) {@at-root   #{&}__#{$name} {@content;}}
@mixin m($name) {@at-root   #{&}--#{$name} {@content;}}

When I run this through gulp sass I get an "Unhandled stream error in pipe. Error reading values after "blank space" at ops.error". 

Bit of a noob to how gulp sass works so excuse my ignorance... when I run this using sass watch it compiles fine but when I use gulp watch I get the error above. Is this due to node-sass not supporting Sass 3.3 syntax yet?

Any help would be greatly appreciated. Cheers. 

Stephen.

**Comment by kgansberger** [comment]
hi there,
i like to use t @at-root in version 2.3.2, isn´t it possible?
cheers! Klaus

**Comment by xzyfer** [comment]
npm update node-sass
