### ISSUE TITLE
Changes for upcoming Node Sass 3.0

### ISSUE THREAD

**Issue by lmartins** [dlmanning/gulp-sass#210]
As highlighted in https://github.com/sass/node-sass/issues/767#issuecomment-81563394 there are a few changes coming in the way gulp-sass needs do interact with node-sass. 

Would be cool if gulp-sass could open a branch to test the new functionality prior to the official Libsass 3 release.

Thanks.

**Comment by dlmanning** [comment]
@lmartins Interested in #213?

**Comment by lmartins** [comment]
As a rule of principle if is something I depend on I try to help as I can, and gulp-sass is definitely one of those things. Looking at the issues open though, Im worried my skills won't allow me to be of great help. Perhaps something that can evolve, as im pretty invested both in Sass and Javascript alike.

**Comment by dlmanning** [comment]
@lmartins I've added you as a collaborators also because you've got a history of posting issues and keeping track of changes in node-sass. Feel free to do what you can.

**Comment by CaseyLeask** [comment]
If it helps, `grunt-sass` have done the upgrade https://github.com/sindresorhus/grunt-sass/commit/c14beebc304816fc9b5973f0bd0a47a19556f52d

**Comment by OnkelTem** [comment]
The title confuses — why "Libsass 3.0"? The latest *releasing* version of Libsass is 3.2, isn't it? If was meant 3.x branch, then this version tag should be used in the title.

On top of that, total mess in Libsass and node-sass.
Libsass is releasing 3.2, and claims to support things like @at-root which seems was introduced in Sass 3.3.
Current node-sass version is 3.0, but it's not clear which version of libsass is gonna be supported.
Only gulp-sass version is 1.3.3 which seems to mean just a version, w/o any references.

Can anybody clarify current status of things?

**Comment by dlmanning** [comment]
@OnkelTem : Pretty sure @lmartins meant node-sass 3.0

**Comment by OnkelTem** [comment]
@dlmanning Ah, your telepathy kung-fu is stronger than mine!

**Comment by Snugug** [comment]
We're working through this in the [2.x branch](https://github.com/dlmanning/gulp-sass/tree/2.x). Please try it and report back.

```
npm install dlmanning/gulp-sass#2.x
```

**Comment by lmartins** [comment]
Thanks @dlmanning for clarifying my mistake, and @Snugug for changing it, I was indeed referring to the node-sass version.

**Comment by OnkelTem** [comment]
Tried 2.0.0-alpha.1 today.

Unfortunately node-sass 3.0.0-beta.4 is not ready yet (one of showstoppers: https://github.com/sass/libsass/issues/1022), look forward when it is updated to libsass 3.2.0-beta.4

**Comment by xzyfer** [comment]
We've released node-sass@3.0.0-beta.7 which will likely become 3.0.0 shortly.

**Comment by xzyfer** [comment]
PR'd support for node-sass >= 3.0.0-beta.7 in https://github.com/dlmanning/gulp-sass/pull/245

**Comment by Keats** [comment]
Closed in favour of https://github.com/dlmanning/gulp-sass/issues/247
