### ISSUE TITLE
images in scss folder not copied over to destination

### ISSUE THREAD

**Issue by iamw00t** [dlmanning/gulp-sass#211]
EG.
/scss/foo/foo.scss (some class uses bar.png as a background image)
/scss/foo/bar.png

Results in
/css/foo/foo.css

Is this expected? If so did I miss a config somewhere? Do I have to a subsequent task to move it?

**Comment by Keats** [comment]
This is not part of sass, you want to copy something else (using gulp.src and gulp.dest directly) to move them
