### ISSUE TITLE
Error while using numbers in vars

### ISSUE THREAD

**Issue by artem-malko** [dlmanning/gulp-sass#214]
invalid top-level expression on line 451

scss string is $5pmtl_3d_c: 0px -128px 128px 128px 128px 2176px './test.svg' '5pmtl_3d_c';

Can i use numbers in scss vars?

**Comment by williamboman** [comment]
Can't have variables that start with a number :).

`lib-sass` has pretty bad error logs. http://sassmeister.com/

**Comment by artem-malko** [comment]
OOokkkayyy(
