### ISSUE TITLE
Not compiling (no output)

### ISSUE THREAD

**Issue by eteiks** [dlmanning/gulp-sass#216]
I am using example from https://github.com/dlmanning/gulp-sass#basic-usage and there is no output at my destination. Am I missing something ?

**Comment by eteiks** [comment]
Looks like this is caused due to package dependency configuration. node-sass has some breaking changes.

**Comment by awebdeveloper** [comment]
Following code gives me no error but no output 

 ```
var gulp            = require('gulp');
var scss            = require('gulp-sass');

gulp.src('scss/_bootstrap.scss')
    .pipe(debug())
    .pipe(scss().on('error', console.log))
    .pipe(gulp.dest(dest+'css/'));
```

**Comment by Keats** [comment]
That:s normal, you don't use a partial as a source in sass.
Rename it to bootstrap.scss or have a main.scss that imports _bootstrap
