### ISSUE TITLE
simply does not work?

### ISSUE THREAD

**Issue by mcorbridge** [dlmanning/gulp-sass#218]
I am running gulp-htmlmin in conjunction with gulp-sass to prove that gulp WILL create a new directory with the minimized html.  Gulp-sass does NOT create a directory of css, nor does it create the new directory as specified in the gulp task.  Any reason why??

**Comment by mcorbridge** [comment]
here is my gulpfile:
var gulp = require('gulp');

var htmlmin = require('gulp-htmlmin');
var sass = require('gulp-sass');

gulp.task('minify', function() {
	return gulp.src('src/*.html')
		.pipe(htmlmin({collapseWhitespace: true}))
		.pipe(gulp.dest('dist'))
});

gulp.task('sass', function () {
	return gulp.src('scss/*.scss')
		.pipe(sass())
		.pipe(gulp.dest('css'));
});

gulp.task('default', ['minify','sass']);

**Comment by lmartins** [comment]
Please provide a sample of your sass too.

**Comment by mcorbridge** [comment]
incoming:

nav {
	ul {
		margin: 0;
		padding: 0;
		list-style: none;
	}

	li { display: inline-block; }

	a {
		display: block;
		padding: 6px 12px;
		text-decoration: none;
	}
}

**Comment by mcorbridge** [comment]
here is the output in the terminal:

C:\development\test\qqq\chrome>gulp
[09:49:06] Using gulpfile C:\development\test\qqq\chrome\gulpfile.js
[09:49:06] Starting 'minify'...
[09:49:06] Starting 'sass'...
[09:49:06] Finished 'minify' after 55 ms

**Comment by lmartins** [comment]
That's really weird @mcorbridge 
I've replicated your environment on my local machine, except that im using OS X and not windows.
By copy/pasting your code and running `gulp-sass` I get the expected behaviour:

![screen shot 2015-03-23 at 13 59 56](https://cloud.githubusercontent.com/assets/151981/6781365/f359bff4-d164-11e4-8bcb-ec324e17a6a8.png)

![screen shot 2015-03-23 at 13 59 04](https://cloud.githubusercontent.com/assets/151981/6781329/d509cd96-d164-11e4-8d46-4dc6417dbe61.png)

The file open in the screenshot was generated by the sass task.

Im not really sure what might going on. Can you please also provide the contents of your package.json file please.

**Comment by mcorbridge** [comment]
this is the package.json from  node-sass

{
  "name": "node-sass",
  "version": "3.0.0-alpha.0",
  "libsass": "3.1.0",
  "description": "Wrapper around libsass",
  "license": "MIT",
  "homepage": "https://github.com/sass/node-sass",
  "repository": {
    "type": "git",
    "url": "https://github.com/sass/node-sass"
  },
  "author": {
    "name": "Andrew Nesbitt",
    "email": "andrewnez@gmail.com",
    "url": "http://andrew.github.com"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "main": "lib/index.js",
  "bin": {
    "node-sass": "bin/node-sass"
  },
  "gypfile": true,
  "scripts": {
    "coverage": "node scripts/coverage.js",
    "install": "node scripts/install.js",
    "postinstall": "node scripts/build.js",
    "pretest": "node_modules/.bin/jshint bin lib test",
    "test": "node_modules/.bin/mocha test"
  },
  "files": [
    "bin",
    "binding.gyp",
    "lib",
    "scripts",
    "src"
  ],
  "keywords": [
    "css",
    "libsass",
    "preprocessor",
    "sass",
    "scss",
    "style"
  ],
  "dependencies": {
    "chalk": "^1.0.0",
    "gaze": "^0.5.1",
    "get-stdin": "^4.0.1",
    "meow": "^3.1.0",
    "mkdirp": "^0.5.0",
    "nan": "^1.7.0",
    "npmconf": "^2.1.1",
    "pangyp": "^2.1.0",
    "request": "^2.53.0",
    "sass-graph": "^1.0.3"
  },
  "devDependencies": {
    "coveralls": "^2.11.2",
    "cross-spawn": "^0.2.6",
    "jscoverage": "^0.5.9",
    "jshint": "^2.6.3",
    "mocha": "^2.2.1",
    "mocha-lcov-reporter": "^0.0.2"
  },
  "readme": "# node-sass\n\n<table>\n  <tr>\n    <td>\n      <img width=\"100%\" alt=\"Sass logo\" src=\"https://rawgit.com/sass/node-sass/master/media/logo.svg\" />\n    </td>\n    <td valign=\"bottom\" align=\"right\">\n      <a href=\"https://nodei.co/npm/node-sass/\">\n        <img width=\"100%\" src=\"https://nodei.co/npm/node-sass.png?downloads=true&downloadRank=true&stars=true\">\n      </a>\n    </td>\n  </tr>\n</table>\n\n[![Build Status](https://travis-ci.org/sass/node-sass.svg?branch=master&style=flat)](https://travis-ci.org/sass/node-sass)\n[![Build status](https://ci.appveyor.com/api/projects/status/22mjbk59kvd55m9y/branch/master)](https://ci.appveyor.com/project/sass/node-sass/branch/master)\n[![npm version](https://badge.fury.io/js/node-sass.svg)](http://badge.fury.io/js/node-sass)\n[![Dependency Status](https://david-dm.org/sass/node-sass.svg?theme=shields.io)](https://david-dm.org/sass/node-sass)\n[![devDependency Status](https://david-dm.org/sass/node-sass/dev-status.svg?theme=shields.io)](https://david-dm.org/sass/node-sass#info=devDependencies)\n[![Coverage Status](https://coveralls.io/repos/sass/node-sass/badge.svg?branch=master)](https://coveralls.io/r/sass/node-sass?branch=master)\n[![Inline docs](http://inch-ci.org/github/sass/node-sass.svg?branch=master)](http://inch-ci.org/github/sass/node-sass)\n[![Gitter chat](http://img.shields.io/badge/gitter-sass/node--sass-brightgreen.svg)](https://gitter.im/sass/node-sass)\n\nNode-sass is a library that provides binding for Node.js to [libsass], the C version of the popular stylesheet preprocessor, Sass.\n\nIt allows you to natively compile .scss files to css at incredible speed and automatically via a connect middleware.\n\nFind it on npm: <https://npmjs.org/package/node-sass>\n\nFollow @nodesass on twitter for release updates: https://twitter.com/nodesass\n\n## Install\n\n```\nnpm install node-sass\n```\n\nSome users have reported issues installing on Ubuntu due to `node` being registered to another package. [Follow the official NodeJS docs](https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager) to install NodeJS so that `#!/usr/bin/env node` correctly resolved.\n\nCompiling versions 0.9.4 and above on Windows machines requires [Visual Studio 2013 WD](http://www.visualstudio.com/downloads/download-visual-studio-vs#d-express-windows-desktop). If you have multiple VS versions, use ```npm install``` with the ```--msvs_version=2013``` flag also use this flag when rebuilding the module with node-gyp or nw-gyp.\n\n## Usage\n\n```javascript\nvar sass = require('node-sass');\nsass.render({\n  file: scss_filename,\n  [, options..]\n}, function(err, result) { /*...*/ });\n// OR\nvar result = sass.renderSync({\n  data: scss_content\n  [, options..]\n});\n```\n\n## Options\n### file\nType: `String | null`\nDefault: `null`\n**Special**: `file` or `data` must be specified\n\nPath to a file for [libsass] to render.\n\n### data\nType: `String | null`\nDefault: `null`\n**Special**: `file` or `data` must be specified\n\nA string to pass to [libsass] to render. It is recommended that you use `includePaths` in conjunction with this so that [libsass] can find files when using the `@import` directive.\n\n### importer (>= v2.0.0)\nType: `Function` signature `function(url, prev, done)`\nDefault: `undefined`\n\nFunction Parameters and Information:\n* `url (String)` - the path in import **as-is**, which [libsass] encountered\n* `prev (String)` - the previously resolved path\n* `done (Function)` - a callback function to invoke on async completion, takes an object literal containing\n  * `file (String)` - an alternate path for [libsass] to use **OR**\n  * `contents (String)` - the imported contents (for example, read from memory or the file system)\n\nHandles when [libsass] encounters the `@import` directive. A custom importer allows extension of the [libsass] engine in both a synchronous and asynchronous manner. In both cases, the goal is to either `return` or call `done()` with an object literal. Depending on the value of the object literal, one of two things will happen.\n\nWhen returning or calling `done()` with `{ file: \"String\" }`, the new file path will be assumed for the `@import`. It's recommended to be mindful of the value of `prev` in instances where relative path resolution may be required.\n\nWhen returning or calling `done()` with `{ contents: \"String\" }`, the string value will be used as if the file was read in through an external source.\n\n`this` refers to a contextual scope for the immediate run of `sass.render` or `sass.renderSync`\n\n### includePaths\nType: `Array<String>`\nDefault: `[]`\n\nAn array of paths that [libsass] can look in to attempt to resolve your `@import` declarations. When using `data`, it is recommended that you use this.\n\n### indentedSyntax\nType: `Boolean`\nDefault: `false`\n\n`true` values enable [Sass Indented Syntax](http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html) for parsing the data string or file.\n\n### omitSourceMapUrl\nType: `Boolean`\nDefault: `false`\n**Special:** When using this, you should also specify `outFile` to avoid unexpected behavior.\n\n`true` values disable the inclusion of source map information in the output file.\n\n### outFile\nType: `String | null`\nDefault: `null`\n**Special:** Required when `sourceMap` is a truthy value\n\nSpecify the intended location of the output file. Strongly recommended when outputting source maps so that they can properly refer back to their intended files.\n\n### outputStyle\nType: `String`\nDefault: `nested`\nValues: `nested`, `compressed`\n\nDetermines the output format of the final CSS style. (`'expanded'` and `'compact'` are not currently supported by [libsass], but are planned in a future version.)\n\n### precision\nType: `Integer`\nDefault: `5`\n\nUsed to determine how many digits after the decimal will be allowed. For instance, if you had a decimal number of `1.23456789` and a precision of `5`, the result will be `1.23457` in the final CSS.\n\n### sourceComments\nType: `Boolean`\nDefault: `false`\n\n`true` enables additional debugging information in the output file as CSS comments\n\n### sourceMap\nType: `Boolean | String | undefined`\nDefault: `undefined`\n**Special:** Setting the `sourceMap` option requires also setting the `outFile` option\n\nEnables the outputting of a source map during `render` and `renderSync`. When `sourceMap === true`, the value of `outFile` is used as the target output location for the source map. When `typeof sourceMap === \"String\"`, the value of `sourceMap` will be used as the writing location for the file.\n\n### sourceMapEmbed\nType: `Boolean`\nDefault: `false`\n\n`true` embeds the source map as a data URI\n\n### sourceMapContents\nType: `Boolean`\nDefault: `false`\n\n`true` includes the `contents` in the source map information\n\n## `render` Callback (>= v3.0.0)\nnode-sass supports standard node style asynchronous callbacks with the signature of `function(err, result)`. In error conditions, the `error` argument is populated with the error object. In success conditions, the `result` object is populated with an object describing the result of the render call.\n\n### Error Object\n* `message` (String) - The error message.\n* `line` (Number) - The line number of error.\n* `column` (Number) - The column number of error.\n* `status` (Number) - The status code.\n* `file` (String) - The filename of error. In case `file` option was not set (in favour of `data`), this will reflect the value `stdin`.\n\n### Result Object\n* `css` (Buffer) - The compiled CSS. Write this to a file, or serve it out as needed.\n* `map` (Buffer) - The source map\n* `stats` (Object) - An object containing information about the compile. It contains the following keys:\n  * `entry` (String) - The path to the scss file, or `data` if the source was not a file\n  * `start` (Number) - Date.now() before the compilation\n  * `end` (Number) - Date.now() after the compilation\n  * `duration` (Number) - *end* - *start*\n  * `includedFiles` (Array) - Absolute paths to all related scss files in no particular order.\n\n### Examples\n\n```javascript\nvar sass = require('node-sass');\nsass.render({\n  file: '/path/to/myFile.scss',\n  data: 'body{background:blue; a{color:black;}}',\n  importer: function(url, prev, done) {\n    // url is the path in import as is, which libsass encountered.\n    // prev is the previously resolved path.\n    // done is an optional callback, either consume it or return value synchronously.\n    // this.options contains this options hash, this.callback contains the node-style callback\n    someAsyncFunction(url, prev, function(result){\n      done({\n        file: result.path, // only one of them is required, see section Sepcial Behaviours.\n        contents: result.data\n      });\n    });\n    // OR\n    var result = someSyncFunction(url, prev);\n    return {file: result.path, contents: result.data};\n  },\n  includePaths: [ 'lib/', 'mod/' ],\n  outputStyle: 'compressed'\n}, function(error, result) { // >= v3.0.0\n  if (error) {\n    console.log(error.status); // use \"code\" <= v3.0.0\n    console.log(error.column);\n    console.log(error.message);\n    console.log(error.line);\n  }\n  else {\n    console.log(result.css.toString());\n    console.log(result.stats);\n    console.log(result.map.toString()); // or console.log(JSON.stringify(result.map));\n  }\n});\n// OR\nvar result = sass.renderSync({\n  file: '/path/to/file.scss',\n  data: 'body{background:blue; a{color:black;}}',\n  outputStyle: 'compressed',\n  outFile: '/to/my/output.css',\n  sourceMap: true, // or an absolute or relative (to outFile) path\n  importer: function(url, prev, done) {\n    // url is the path in import as is, which libsass encountered.\n    // prev is the previously resolved path.\n    // done is an optional callback, either consume it or return value synchronously.\n    // this.options contains this options hash\n    someAsyncFunction(url, prev, function(result){\n      done({\n        file: result.path, // only one of them is required, see section Sepcial Behaviours.\n        contents: result.data\n      });\n    });\n    // OR\n    var result = someSyncFunction(url, prev);\n    return {file: result.path, contents: result.data};\n  },\n}));\n\nconsole.log(result.css);\nconsole.log(result.map);\nconsole.log(result.stats);\n```\n\n### Special behaviours\n\n* In the case that both `file` and `data` options are set, node-sass will give precedence to `data` and use `file` to calculate paths in sourcemaps.\n\n### Version information (>= v2.0.0)\n\nBoth `node-sass` and `libsass` version info is now present in `package.json` and is exposed via `info` method:\n\n```javascript\nvar sass = require('node-sass');\n\nconsole.log(sass.info);\n\n/*\n  it will output something like:\n\n  node-sass       2.0.1   (Wrapper)       [JavaScript]\n  libsass         3.1.0   (Sass Compiler) [C/C++]\n*/\n```\n\n## Integrations\n\nListing of community uses of node-sass in build tools and frameworks.\n\n### Brackets extension\n\n[@jasonsanjose](https://github.com/jasonsanjose) has created a [Brackets](http://brackets.io) extension based on node-sass: <https://github.com/jasonsanjose/brackets-sass>. When editing Sass files, the extension compiles changes on save. The extension also integrates with Live Preview to show Sass changes in the browser without saving or compiling.\n\n### Brunch plugin\n\n[Brunch](http://brunch.io)'s official sass plugin uses node-sass by default, and automatically falls back to ruby if use of Compass is detected: <https://github.com/brunch/sass-brunch>\n\n### Connect/Express middleware\n\nRecompile `.scss` files automatically for connect and express based http servers.\n\nThis functionality has been moved to [`node-sass-middleware`](https://github.com/sass/node-sass-middleware) in node-sass v1.0.0\n\n### DocPad Plugin\n\n[@jking90](https://github.com/jking90) wrote a [DocPad](http://docpad.org/) plugin that compiles `.scss` files using node-sass: <https://github.com/jking90/docpad-plugin-nodesass>\n\n### Duo.js extension\n\n[@stephenway](https://github.com/stephenway) has created an extension that transpiles Sass to CSS using node-sass with [duo.js](http://duojs.org/)\n<https://github.com/duojs/sass>\n\n### Grunt extension\n\n[@sindresorhus](https://github.com/sindresorhus/) has created a set of grunt tasks based on node-sass: <https://github.com/sindresorhus/grunt-sass>\n\n### Gulp extension\n\n[@dlmanning](https://github.com/dlmanning/) has created a gulp sass plugin based on node-sass: <https://github.com/dlmanning/gulp-sass>\n\n### Harp\n\n[@sintaxi](https://github.com/sintaxi)’s Harp web server implicitly compiles `.scss` files using node-sass: <https://github.com/sintaxi/harp>\n\n### Metalsmith plugin\n\n[@stevenschobert](https://github.com/stevenschobert/) has created a metalsmith plugin based on node-sass: <https://github.com/stevenschobert/metalsmith-sass>\n\n### Meteor plugin\n\n[@fourseven](https://github.com/fourseven) has created a meteor plugin based on node-sass: <https://github.com/fourseven/meteor-scss>\n\n### Mimosa module\n\n[@dbashford](https://github.com/dbashford) has created a Mimosa module for sass which includes node-sass: <https://github.com/dbashford/mimosa-sass>\n\n## Example App\n\nThere is also an example connect app here: <https://github.com/andrew/node-sass-example>\n\n## Rebuilding binaries\n\nNode-sass includes pre-compiled binaries for popular platforms, to add a binary for your platform follow these steps:\n\nCheck out the project:\n\n```bash\ngit clone --recursive https://github.com/sass/node-sass.git\ncd node-sass\ngit submodule update --init --recursive\nnpm install\nnode scripts/build -f  # use -d switch for debug release\n# if succeeded, it will generate and move\n# the binary in vendor directory.\n```\n\n## Command Line Interface\n\nThe interface for command-line usage is fairly simplistic at this stage, as seen in the following usage section.\n\nOutput will be saved with the same name as input SASS file into the current working directory if it's omitted.\n\n### Usage\n `node-sass [options] <input.scss> [<output.css>]`\n\n **Options:**\n\n```bash\n    -w, --watch                Watch a directory or file\n    -r, --recursive            Recursively watch directories or files\n    -o, --output               Output directory\n    -x, --omit-source-map-url  Omit source map URL comment from output\n    -i, --indented-syntax      Treat data from stdin as sass code (versus scss)\n    -v, --version              Prints version info\n    --output-style             CSS output style (nested|expanded|compact|compressed)\n    --source-comments          Include debug info in output\n    --source-map               Emit source map\n    --source-map-embed         Embed sourceMappingUrl as data URI\n    --source-map-contents      Embed include contents in map\n    --include-path             Path to look for imported files\n    --precision                The amount of precision allowed in decimal numbers\n    --importer                 Path to custom importer\n    --help                     Print usage info\n```\n\nNote `--importer` takes the (absolute or relative to pwd) path to a js file, which needs to have a default `module.exports` set to the importer function. See our test [fixtures](https://github.com/sass/node-sass/tree/974f93e76ddd08ea850e3e663cfe64bb6a059dd3/test/fixtures/extras) for example.\n\n## Post-install Build\n\nInstall runs only two Mocha tests to see if your machine can use the pre-built [libsass] which will save some time during install. If any tests fail it will build from source.\n\n## Maintainers\n\nThis module is brought to you and maintained by the following people:\n\n* Adeel Mujahid - Project Lead ([Github](https://github.com/am11) / [Twitter](https://twitter.com/adeelbm))\n* Andrew Nesbitt ([Github](https://github.com/andrew) / [Twitter](https://twitter.com/teabass))\n* Dean Mao ([Github](https://github.com/deanmao) / [Twitter](https://twitter.com/deanmao))\n* Brett Wilkins ([Github](https://github.com/bwilkins) / [Twitter](https://twitter.com/bjmaz))\n* Keith Cirkel ([Github](https://github.com/keithamus) / [Twitter](https://twitter.com/Keithamus))\n* Laurent Goderre ([Github](https://github.com/laurentgoderre) / [Twitter](https://twitter.com/laurentgoderre))\n* Nick Schonning ([Github](https://github.com/nschonni) / [Twitter](https://twitter.com/nschonni))\n* Adam Yeats ([Github](https://github.com/adamyeats) / [Twitter](https://twitter.com/adamyeats))\n\n## Contributors\n\nWe <3 our contributors! A special thanks to all those who have clocked in some dev time on this project, we really appreciate your hard work. You can find [a full list of those people here.](https://github.com/sass/node-sass/graphs/contributors)\n\n### Note on Patches/Pull Requests\n\n * Fork the project.\n * Make your feature addition or bug fix.\n * Add documentation if necessary.\n * Add tests for it. This is important so I don't break it in a future version unintentionally.\n * Send a pull request. Bonus points for topic branches.\n\n## Copyright\n\nCopyright (c) 2015 Andrew Nesbitt. See [LICENSE](https://github.com/sass/node-sass/blob/master/LICENSE) for details.\n\n[libsass]: https://github.com/hcatlin/libsass\n",
  "readmeFilename": "README.md",
  "bugs": {
    "url": "https://github.com/sass/node-sass/issues"
  },
  "_id": "node-sass@3.0.0-alpha.0",
  "_from": "node-sass@"
}

**Comment by lucho-yankov** [comment]
Hi,

I have the same issue. 
Running on Ubuntu with node v0.10.13. 
I have tried with node-sass version 3.0.0.alpha and 2.0.1. 

It seems like node-sass works just fine, but the gulp task does not finish.
The gulp file is this one - https://github.com/jakearchibald/svgomg/blob/master/gulpfile.js

I wanted to try out this sample project but I could not compile it correct and it took me a lot of time to figure out that there is an error, since there is no output to the terminal and the status code is 0. I think it will be good idea to keep `errLogToConsole: true` as default.

**Comment by Keats** [comment]
Agreed on defaulting errLogToConsole or changing the way it's done

**Comment by lucho-yankov** [comment]
Downgraded the version to 1.3.1 and it worked - the task finishes.

**Comment by lmartins** [comment]
Sorry @mcorbridge, I meant the package.json from your project. 
Can the others having issues confirm the following:

- Which gulp-sass version (current is 1.3.3)
- Which gulp version (current is 3.8.11)
- Which OS

Thank you.

**Comment by mcorbridge** [comment]
@lmartins 
my apologies for the delay ... here it is

{
  "name": "chrome",
  "version": "0.0.0",
  "description": "",
  "main": "gulpfile.js",
  "dependencies": {
    "gulp": "~3.8.11",
    "gulp-htmlmin": "~1.1.1",
    "gulp-sass": "~1.3.3",
    "gulp-scss-lint": "~0.1.10",
    "gulp-css-scss": "~0.0.2",
    "node-sass": "~3.0.0-alpha.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "mikecorbridge@gmail.com",
  "license": "BSD"
}

------------------------------------
OS: win7 pro

**Comment by mcorbridge** [comment]
@lmartins 
ok ... hold on
I created a new module an installed everything again
Now it is working!?

gulpfile.js
-------------------------------------------------------------
// include gulp
var gulp = require('gulp');

// include plug-ins
var jshint = require('gulp-jshint');
var minifyHTML = require('gulp-minify-html');
var autoprefix = require('gulp-autoprefixer');
var minifyCSS = require('gulp-minify-css');
var concat = require('gulp-concat');
var sass = require('gulp-sass');

// JS hint task
gulp.task('jshint', function() {
	gulp.src('./src/scripts/*.js')
		.pipe(jshint())
		.pipe(jshint.reporter('default'));
});


// CSS concat, auto-prefix and minify
gulp.task('styles', function() {
	gulp.src(['./src/styles/css/*.css'])
		.pipe(concat('styles.css'))
		.pipe(autoprefix('last 2 versions'))
		.pipe(minifyCSS())
		.pipe(gulp.dest('./build/styles/css'));
});

// minify new or changed HTML pages
gulp.task('htmlpage', function() {
	var htmlSrc = './src/html/*.html',
		htmlDst = './build/html';

	gulp.src(htmlSrc)
		.pipe(minifyHTML())
		.pipe(gulp.dest(htmlDst));
});

// Compile Our Sass
gulp.task('sass', function () {
	return gulp.src('./src/styles/scss/*.scss')
		.pipe(sass())
		.pipe(gulp.dest('./build/styles/css'));
});

// default gulp task
gulp.task('default', ['styles', 'htmlpage','sass'], function() {

	// watch for CSS changes
	gulp.watch('./src/styles/css/*.css', function() {
		gulp.run('styles');
	});

	// watch for HTML changes
	gulp.watch('./src/html/*.html', function() {
		gulp.run('htmlpage');
	});

	// watch for HTML changes
	gulp.watch('./src/styles/scss/*.scss', function() {
		gulp.run('sass');
	});

});

package.json
_______________________________________________
{
  "name": "senators",
  "version": "0.0.0",
  "description": "",
  "main": "gulpfile.js",
  "dependencies": {
    "gulp-changed": "~1.2.1",
    "gulp-imagemin": "~2.2.1",
    "gulp": "~3.8.11",
    "gulp-jshint": "~1.9.4"
  },
  "devDependencies": {
    "gulp-sass": "~1.3.3",
    "gulp-minify-html": "~1.0.1",
    "gulp-autoprefixer": "~2.1.0",
    "gulp-minify-css": "~1.0.0",
    "gulp-concat": "~2.5.2"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "BSD"
}

------------------------------------------------------------------------------------------------------

Please let me know if this helps anyone, or if I can shed any light on the problem for other people.

**Comment by lmartins** [comment]
My guess is something went wrong with the npm install at the first time.
Can the others having issues please try to remove `node_modules` and run `npm install` again to see if solves your issue.

Keep an eye on the log to see if any error pops up while installing the npm modules.

**Comment by elliottregan** [comment]
I had a very similar problem when I upgraded to 0.12 where the gulp task would finish, but there was no output CSS file. `gulp-debug` showed the parent Sass file going in, 1 file going out, but nothing got saved. Maybe another debug tool would have given more info, but I stopped there.

 After trying to find the right combination of package versions, I just upgraded every package, and it seems to have worked. Still not sure if it was `node-sass`, `gulp-sass`, or one of their dependencies that was causing the issues, though.

**Comment by Keats** [comment]
You can also try the 2.x branch of gulp-sass which should work better.
But yeah, probably an error during npm install, it's quite easy to miss sometimes

**Comment by cema93** [comment]
Hello. I have the same problem.
Then i start gulp in console i dont see errors, but css file and folder are not created.

package.json
`{
  "name": "efood-theme",
  "version": "1.0.0",
  "description": "Efood theme",
  "license": "MIT",
  "dependencies": {},
  "devDependencies": {
    "gulp": "^3.9.0",
    "gulp-imagemin": "^2.4.0",
    "gulp-rigger": "^0.5.8",
    "gulp-sass": "^2.1.1",
    "imagemin-pngquant": "^4.2.0",
    "rimraf": "^2.5.1"
  },
  "//": "lodash ^3.0.0"
}
`
gulpfile.js
`gulp.src('./src/style/**/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(gulp.dest('./css'));`

**Comment by DanielTate** [comment]
I am also getting this issue with the following:

I have tried uninstalling and reinstalling gulp-sass and this does not work.

{
  "name": "presentation",
  "version": "1.0.0",
  "description": "",
  "main": "x",
  "dependencies": {
    "bower": "^1.7.7",
    "gulp": "^3.9.1",
    "gulp-processhtml": "^1.1.0"
  },
  "devDependencies": {
    "bower": "^1.7.7",
    "browser-sync": "^2.11.2",
    "gulp": "^3.9.1",
    "gulp-clean-css": "^2.0.4",
    "gulp-concat": "^2.6.0",
    "gulp-jshint": "^2.0.0",
    "gulp-load-plugins": "^1.2.0",
    "gulp-processhtml": "^1.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.2.0",
    "gulp-uglify": "^1.5.3",
    "jshint": "^2.9.1",
    "jshint-stylish": "^2.1.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

**Comment by FlawaCLV** [comment]
Same problem for me. Doesn't prompt any error... After trying every possible combination of package versions, I seriously don't know where to look for!

**Comment by HydrateEfficiently** [comment]
Same here. Doesn't even output an error when I purposely screw up the syntax in the source scss files on purpose. Doing the most simple gulp-sass possible.

**Comment by Sri276286** [comment]
Can anyone please explain why gulp-sass is outputing .css files instead of .scss files after minification.
what fix needs to be done to get .scss files after minification?

**Comment by brizer** [comment]
remove node_modules ,then npm istall again. it works. but who know reasons?
