### ISSUE TITLE
Import configuration files everywhere

### ISSUE THREAD

**Issue by loick** [dlmanning/gulp-sass#221]
Hi everyone,

I tried to build all my SCSS files into CSS with gulp-sass bu I have some problems. I need to generate many CSS files and I actually don't import all of my dependencies at the top of my files. I had a PHP compiler which included my conf (variables, mixins etc.) in every files. This was really cool since I didn't have to import it in CSS everywhere.. 

Did you plan to add this kind of feature in gulp-sass ? 

Thank you very much

**Comment by Keats** [comment]
Probably not, gulp-sass ist just a gulp-frontend to node-sass so it shouldn't have any custom features like that

**Comment by Snugug** [comment]
Agreed with @Keats. This is outside the purview of this project. I'd recommend you filing a feature request with [node-sass](https://github.com/sass/node-sass)

**Comment by Snugug** [comment]
You may also consider filing a feature request with [eyeglass](https://github.com/sass-eyeglass/eyeglass), which will be a meta framework for **node-sass** in much the same way Compass is for Ruby Sass
