### ISSUE TITLE
symbol for IE hack was always ignored

### ISSUE THREAD

**Issue by VaJoy** [dlmanning/gulp-sass#226]
as I code `height:30px;*height:35px;` to hack IE6/7, gulp-sass will compile it to only `height:30px;` without error.
I have no idea about it, is it a bug?
most projects still DO need to fit IE8- in China :(

**Comment by Keats** [comment]
Hello

That would be a libsass issue, not a gulp-sass one.
Check https://github.com/sass/libsass

**Comment by VaJoy** [comment]
@keats oh I see, but I just figure it out with using `<!--[if IE 7 ]><html class="ie7"><! [endif]-->` ,and I think this may be a better way to hack lower version of IE.
anyway thx!! xD
