### ISSUE TITLE
feedback on a gulp-watch-sass

### ISSUE THREAD

**Issue by filtercake** [dlmanning/gulp-sass#227]
Hi.

We have recently switched from a ruby-sass bash script to a nice gulp-based workflow, so first of all thanks for all the work which went into this plugin!

What we really miss, though, is the built in import-graph of sass-watch – meaning when I change a partial, it triggers a re-compile of all files which use that partial (but do not recompile those which don't use the changed partial).

Now, if I understand it right, that is currently nobodies job in a gulp sass workflow:

- node-sass is using https://github.com/xzyfer/sass-graph in its `--watch` parameter – but the watching is not done by sass
- gulp-watch and gulp.watch are generic watchers and should not know about sass file dependencies
- gulp-sass is a wrapper for node-sass and passes files to a node-sass compile, not a watch, so if sass-compile doesn't consider the import-graph, that is not gulp-sass' concern.

So we came up with the idea of a gulp-watch-sass plugin which matches watch against the sass-graph and passes relevant files down the pipe to gulp-sass: `.pipe(watchSass())`

I've seen our problem come up in multiple issues and even leading to things like https://github.com/PGS-dev/gulp-recipe-sass/blob/eab3762e26c98b9d3f200dec7cd0be77a3142d32/recipe.js#L68

All feedback and input are appreciated...

Thx,
Fabian

**Comment by Snugug** [comment]
Do you envision this being a feature of `gulp-sass` or a stand-alone plugin?

**Comment by filtercake** [comment]
@Snugug not sure. as a stand-alone plugin it could work for gulp-ruby-sass too. a gulp-sass feature could then just depend on the stand-alone plugin. what would you recommend or want to see?

**Comment by Snugug** [comment]
I'm honestly not sure. I think having a tighter integration with `gulp-sass` would probably be good for us, but it may even be just generally a good `gulp-watch` replacement specifically for Sass files instead of part of a pipe. @dlmanning @Keats thoughts?

**Comment by dlmanning** [comment]
The tricky thing here is that it isn't just a generic watcher. It has to actually know enough about sass to figure out which files to change. It could use sass-graph for that. Then it's going to need to map out the entire dependency tree and keep that on hand. Then of course it's always possible that files have been updated to include a dependency where they hadn't before, or that new files have been added.

So I think this is definitely too much to be rolled onto gulp-sass. What sort of tighter integration would be necessary? It seems like you just need something that replaces or augments gulp-watch to expand the list of files for recompilation, no?

**Comment by filtercake** [comment]
ok, when I add

> I think this is definitely too much to be rolled onto gulp-sass.

and 

> as a stand-alone plugin it could work for gulp-ruby-sass too

a seperate plugin seems to make sense.

I'll set it all up, leave a link here and close this ticket.

Thanks for the feedback everybody, much appreciated!

**Comment by xzyfer** [comment]
FWIW there is a [gulp-sass-graph plugin](https://www.npmjs.com/package/gulp-sass-graph). The idea is you would do something like

```
gulp.task('watch-sass', function(cb) {
  return watch({glob:'/assets/css/**/*.scss', emitOnGlob: false, name: "Sass"})
    .pipe(sassGraph(sassLoadPaths))
    .pipe(sass({loadPath: sassLoadPaths}))
    .pipe(notify('Sass compiled <%= file.relative %>'))
    .pipe(gulp.dest('web/dist/css'))
    .pipe(livereload());
});
```

I've inherited the project from a colleague and it's very out of date. I would happily accept to be PR to restore it to it's former glory.

**Comment by niksy** [comment]
Any progress on this? Original Ruby Sass watcher is ideal in what it does, and node-sass could benefit from this.

**Comment by xzyfer** [comment]
Node sass has this. Gulp sass doesn't have a watcher because it's built
into gulp. There is nothing we can do here.

**Comment by xzyfer** [comment]
Use the above snippet in your gulp watch task

**Comment by sp00m** [comment]
Hey, I actually developer a gulp-watch-sass plugin, may this help: https://www.npmjs.com/package/gulp-watch-sass
