### ISSUE TITLE
"return gulp.src" breaks the stream?

### ISSUE THREAD

**Issue by didoo** [dlmanning/gulp-sass#229]
Hi everybody
I don't know if I am doing something wrong, is a bug or an expected behaviour.
I have switched from gulp-ruby-sass to gulp-sass. Nothing has changed in the task (apart from the options, of course), but what happens now is that if I do a `return gulp.src(...)` as I did before, the task gets executed, but the following tasks (I am using `run-sequence` because I need a specific execution order) are not executed at all.

The only workaround I could find was to have a callback like this:
```
gulp.task('sass', function(cb) {
    gulp.src(...)
        .pipe(sass({
            includePaths: [ ...],
            onSuccess: function(css) { gutil.log(gutil.colors.yellow('Processed Sass ' + css.stats.entry); },
            sync: true
        }))
    cb();
});
```
Which doesn't break the sequence, but breaks the order because the task is exited immediately:
```
[16:54:12] Starting 'sass:all'...
[16:54:13] Finished 'sass:all' after 7.24 ms
```
Any idea? Any suggestion? Any hint in what I am doing wrong?

**Comment by Keats** [comment]
Hello,

Can you try with the https://github.com/dlmanning/gulp-sass/tree/2.x branch ?

**Comment by didoo** [comment]
Hi Keats
using the `gulp-sass@2.0.0-alpha.1` the sequence and stream works as expected. :)

**Comment by Snugug** [comment]
Awesome. Closing.
