### ISSUE TITLE
Only variable declarations and control directives are allowed inside functions

### ISSUE THREAD

**Issue by lmartins** [dlmanning/gulp-sass#231]
After updating gulp-sass to the next release I started getting an error that didn't show before:

```
[11:32:04] Starting 'sass'...
[11:32:05] Finished 'sass' after 1.27 s

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bower_components/modular-scale/stylesheets/modular-scale/_sort-list.scss
  35:5  only variable declarations and control directives are allowed inside functions
```

Line 35 refers to the closing bracket of the following code:

```scss
    // Check if the A value is smaller
    // Uses or equal to avoid duplicate numbers
    @if nth($A, $A-counter) <= nth($B, $B-counter) {
      $Return: join($Return, nth($A, $A-counter));
      $A-counter: $A-counter + 1;
    }
```

Im not really sure if this is related to gulp-sass or an issue of the modular-scale library, so im posting in the hope you could help me figure that out.

**Comment by Snugug** [comment]
Compiling issues, especially where an error is thrown, are `Libsass` issues. Please [file this issue over there](https://github.com/sass/libsass/issues/new)

**Comment by lmartins** [comment]
Done, thanks.
