### ISSUE TITLE
Problem with ARM proc

### ISSUE THREAD

**Issue by JeanBanane** [dlmanning/gulp-sass#232]
I get this message when I try to install gulp-sass with npm :

> node-sass@2.1.1 install /home/dahmoz/chat/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js
> Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/linux-arm-node-0.10/binding.node

So it must compile from source, and it's veeeeerrryyyy sloooow.

**Comment by Snugug** [comment]
This is a `node-sass` issue and not a `gulp-sass` issue. Please try with `npm install gulp-sass@next` and if the issue persists, please file an issue over there.

http://GitHub.com/sass/node-sass
