### ISSUE TITLE
Gulp-sass does not respect original gulp.src order

### ISSUE THREAD

**Issue by austinpray** [dlmanning/gulp-sass#236]
Hey there guys. I have a reduced test case for ya'll:

https://gist.github.com/austinpray/15d4514e93217a66e6d3#gulp-sass

```
git clone https://gist.github.com/15d4514e93217a66e6d3.git gulp-sass-236
```

*note: ignore the whacky sass+less stuff in the above gist, I have isolated the issue to only sass+css files*

```js
var concat = require('gulp-concat');
var debug  = require('gulp-debug');
var gulp   = require('gulp');
var gulpif = require('gulp-if');
var sass   = require('gulp-sass');

gulp.task('sass', function() {
  return gulp.src([
    'external1.css',
    'sass.scss',
    'external2.css',
  ])
    .pipe(gulpif('*.scss', sass()))
    .pipe(debug({title: 'After'}))
    .pipe(concat('bundleSassOnly.css'))
    .pipe(gulp.dest('./'));
});
```

![screenshot 2015-04-11 12 23 58](https://cloud.githubusercontent.com/assets/2192970/7102432/938641b0-e046-11e4-8814-4d0e503df12d.png)

So as you can see:

My gulp.src is as such:

```js
gulp.src([
    'external1.css',
    'sass.scss',
    'external2.css',
  ])
```

but my output is this:

1. external1.css
2. external2.css
3. sass.scss

Note that if you, for instance, modified your gulp.src to this:

```js
gulp.src([
    'sass.scss',
    'external1.css',
    'external2.css',
  ])
```

You will get: 

1. external1.css
2. sass.scss
3. external2.css

This issue occurs on both node 0.10 and 0.12. All the package versions are in the gist package.json. This issue also occurs with `gulp-sass@2.0.0-alpha.1` as well.

[previous discussion](https://discourse.roots.io/t/ordering-stylesheets-before-gulp-concat/3489/7)

**update:** using the `sync: true` option fixes the ordering issue but then the task silently exits before completing.

**Comment by lamosty** [comment]
+1

I run the tests and the *sass* task doesn't respect the order of files in the `gulp.src([])` array. Using the `sync: true` option makes the task fail silently, as @austinpray mentioned.

I'm using node *v0.10.32* and gulp-sass *1.3.3*.

Thanks

**Comment by Snugug** [comment]
`gulp.src` globs arrays asynchronously, so order is not guaranteed when passed into the file stream. We work on individual streams that are passed in and have no knowledge of the files (or their order)  or be able to alter the order of the files being passed in.
