### ISSUE TITLE
Error running two gulp processes simultaneously

### ISSUE THREAD

**Issue by juanpasolano** [dlmanning/gulp-sass#240]
I have two websites using gulp and gulp-ruby-sass which i need to run at the same time. I run the first one perfectly but always the first time i run the second one I get many different errors and a bunch of folders (which seem like sass-cache from the first gulp task) populating my second project.

The other weird thing is that the **error(s) don't persist** when I run the second project again.

And to top things off: The errors it gives me always changes.

Sometimes is:

    events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
    TypeError: Uncaught, unspecified "error" event.
Sometimes is:  

    context.source = oldState.source;
    TypeError: Cannot read property 'source' of undefined
        at tokenize (/Users/juanpa/Documents/[...]/node_modules/gulp-minify-css/node_modules/clean-css/lib/selectors/tokenizer.js:191:34)

Sometimes this other (where "streamline" is actually a .scss from the first project I run):

    events.js:72
        throw er; // Unhandled 'error' event
              ^
    Error: Broken @import declaration of "streamline"

### This is the sass task of the first project

    gulp.task('sass', function () {
    gulp.src(paths.sass)
      .pipe(plumber({
        errorHandler: onError
      }))
      .pipe(rubySass({
        lineNumbers: true,
        bundleExec: false
      }))
      .pipe(header(banner, { pkg: pkg }))
      .pipe(size({title: 'main.css'}))
      .pipe(gulp.dest('../public/css/'))
      .pipe(rename('main.min.css'))
      .pipe(minifyCSS())
      .pipe(size({title: 'main.min.css'}))
      .pipe(gulp.dest('../public/css/'))
      .pipe(connect.reload())
    });

### And this is the gulp task of the second project

    gulp.task('sass', function () {
      return sass(paths.sass, {
        lineNumbers: true,
        bundleExec: false
      })
      .pipe(gulp.dest('css/'))
      .pipe(rename('main.min.css'))
      .pipe(minifyCSS())
      .pipe(gulp.dest('css/'))
      .pipe(connect.reload())
    });

I am not absolutely sure this is an specific gulp-ruby-sass issue but most of the errors point to that direction

**Comment by Keats** [comment]
Can you try the 2.x branch ?
It's a complete rewrite and should contain a libsass version that brings it to parity with ruby sass (afaik) which might make your use of ruby sass obsolete as well

**Comment by juanpasolano** [comment]
I actually downgraded to `~0.7.1`  and it seems to be responding. The `npm install` had this version set in the package.json `^1.0.0-alpha.3`
