### ISSUE TITLE
'libsass bindings not found. Try reinstalling 'node-sass'?

### ISSUE THREAD

**Issue by Milkbone** [dlmanning/gulp-sass#249]
I'm having a problem when running the command `gulp` I keep getting this error:
```
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/vagrant/Code/Auth/node_modules/gulp-sass/node_modules/n
ode-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/vagrant/Code/Auth/node_modules/gulp-sass/node_m
odules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vagrant/Code/Auth/node_modules/gulp-sass/index.
js:3:17)
    at Module._compile (module.js:456:26)
```
I have tried all of the solutions from this post #174 
and none of them have worked, I've been working through various npm/node/gulp problems for around 4 hours and I've seemed to have fixed mostly all of them except this error (and hopefully no errors past this one).

**Comment by Snugug** [comment]
What version of `gulp-sass` are you using?

**Comment by Milkbone** [comment]
this is my full package.json file
```
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.11",
    "gulp-autoprefixer": "^0.0.7",
    "gulp-ruby-sass": "^1.0.5",
    "gulp-sass": "^1.3.3",
    "gulp-util": "^3.0.4",
    "laravel-elixir": "*",
    "node-sass": "^2.1.1"
  }
}
```

**Comment by Snugug** [comment]
You appear to have two versions of Sass and Node Sass in your dependencies. Please remove your `node_modules` folder and remove the `gulp-ruby-sass` and `node-sass` lines from your `package.json`. Then run the following:

```
npm install gulp-sass@next --save-dev
```

If you continue to have issues, please look for a similar issue in the [Node Sass issue queue](https://github.com/sass/node-sass/issues) (opened and closed) specifically about `libsass bindings` as this is a Node Sass issue, not a Gulp Sass one.

**Comment by Milkbone** [comment]
I still have the same error, however I'll look over at the node sass. thanks for you help!
