### ISSUE TITLE
Import partials problem

### ISSUE THREAD

**Issue by Soularix** [dlmanning/gulp-sass#250]
Hey, please when I import a partial in my main scss 
@import "layout/header";
I made my changes into the _header.scss
then I run gulp-sass it said : [gulp-sass] file to import not found or unreadable:

**Comment by Keats** [comment]
Are you running the 2.x branch ?

**Comment by Soularix** [comment]
2.x branch of what ?

**Comment by Keats** [comment]
```
npm install dlmanning/gulp-sass#2.x
```

After removing gulp-sass from your node modules folder

**Comment by Soularix** [comment]
I got an error while trying to install it

**Comment by Snugug** [comment]
You should report installation issues to the node sass  issue queue

**Comment by Soularix** [comment]
I installed the last version by : npm install gulp-sass@next --save-dev but I still have the same problem

**Comment by Soularix** [comment]
I get this error : ←[90m  10:9←[39m  file to import not found or unreadable: layout/header

**Comment by Keats** [comment]
gulp-sass 2.0 has been published to npm, please update to that and try to reproduce the issue

**Comment by Soularix** [comment]
Now it's not even working lol

**Comment by Snugug** [comment]
Duplicate of #235. Moving conversation there

**Comment by Keats** [comment]
And closing this one
