### ISSUE TITLE
Gulp crashing with errLogToConsole

### ISSUE THREAD

**Issue by Jakobud** [dlmanning/gulp-sass#251]
I have the following gulp tasks:

```
gulp.task('sass', function(){

	return gulp.src(src.sass)
		.pipe(sass({
			errLogToConsole: true,
			onError: function(e){
				console.log(e);
			},
			outputStyle: 'nested',
			sourceComments: true
		}))
		.pipe(gulp.dest('css'));
});

gulp.task('default', ['sass'], function(){
	gulp.watch(src.sass, ['sass']);
});
```

When I get a SASS error due to a typo or whatever, gulp crashes at the command line. But according to your docs for `errLogToConsole`:

> Use this option with gulp.watch to keep gulp from stopping every time you mess up your sass.

So it seems like it shouldn't be completely crashing and I shouldn't have to restart gulp on each error.  I am expecting gulp to display the error on the console but not crash. What am I doing wrong here?

**Comment by Snugug** [comment]
Please [update to the latest version of `gulp-sass`](https://github.com/dlmanning/gulp-sass/wiki/Update-to-the-latest-Gulp-Sass)

**Comment by Jakobud** [comment]
1.3.3 or the latest 2.x?

**Comment by Snugug** [comment]
2.x

**Comment by Jakobud** [comment]
In package.json do I make the version "2.x"? I didn't know that was a valid version number for npm.

**Comment by Snugug** [comment]
Please follow the link, it has the instructions you need

**Comment by ifrac** [comment]
>Removing the `return` from the Gulp stream will fix the issue.

https://github.com/dlmanning/gulp-sass/wiki/Common-Issues-and-Their-Fixes#gulp-watch-stops-working-on-an-error
