### ISSUE TITLE
Speeds much slower > 2.0.0?

### ISSUE THREAD

**Issue by andrewmartin** [dlmanning/gulp-sass#258]
Sorry in advance if this is not the appropriate place for this––let me know where it should go and I'll gladly move this ticket there.

I was curious why the compilation speeds drop _significantly_ when upgrading to 2.0.0+?  I noticed my speeds (same file, same project) nearly doubled when I upgraded, so I experimented:

###### gulp-sass 2.0.0 
`[17:22:14] Finished 'styles' after 1.44 s`

###### gulp-sass 1.3.3
`[17:25:31] Finished 'styles' after 634 ms`

Just thought I'd ask and see if there might be something I did wrong when upgrading (`npm install gulp-sass@latest -S`). I love `gulp-sass` so much because of its lightning speeds. I'm sure it'd be worse with the Ruby version, and I know I can continue using 1.3.3...just figured I'd ask.

**Comment by dlmanning** [comment]
@andrewmartin : This is going to be an issue probably for the [libsass](https://github.com/sass/libsass) project most likely. There's nothing different about gulp-sass that would account for the difference in speed, what's mainly changed is the version of node-sass and libsass we wrap.

**Comment by andrewmartin** [comment]
@dlmanning understood. I'll move over there, thank you!
