### ISSUE TITLE
gulp sass instalation problem

### ISSUE THREAD

**Issue by Soularix** [dlmanning/gulp-sass#259]
I used to install sass normally but today when I tried to install it I got this error :
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-sass" "--save-dev"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\hey\npm-debug.log

**Comment by Keats** [comment]
it says you don't have git installed

**Comment by Soularix** [comment]
yeah, does the version 2.0 requires git ?

**Comment by Keats** [comment]
gulp-sass itself no but libsass/node-sass might

**Comment by Snugug** [comment]
Closing as @Soularix has followed up with Node Sass. https://github.com/sass/node-sass/issues/933
