### ISSUE TITLE
Error Handling In 2.0.0

### ISSUE THREAD

**Issue by MethodGrab** [dlmanning/gulp-sass#260]
Discussion for PR #257.

I like the new `.on('error', sass.logError)` technique for handling errors, it's more in line with how other plugins handle errors. However, I think all formatting should be handled by `logError` while `errorM` should return the raw error object, as before, to allow any customizations the user might require.

**Comment by Keats** [comment]
I agree with that

**Comment by Snugug** [comment]
I'm fin with that, as long as users are notified of the error message and the file the error comes from no matter how the error is thrown

**Comment by Snugug** [comment]
Related: #263

**Comment by Snugug** [comment]
Resolved by #273
