### ISSUE TITLE
Update Error Handling Tests to include File

### ISSUE THREAD

**Issue by Snugug** [dlmanning/gulp-sass#263]
Whenever an error gets thrown, it needs to include the file that the error comes from. We need to update our error tests to ensure file is included in error message

**Comment by xzyfer** [comment]
I was about to open this issue. I had mistake it for a node-sass bug https://github.com/sass/node-sass/issues/948. It seems like there is a lot of good stuff on master, please publish a new release?

**Comment by Snugug** [comment]
Our error messages always included this, we just needed tests for it. What was on Master were a couple of bug fixes. Just release 2.0.1

**Comment by xzyfer** [comment]
Sorry I believe there's been a miss understanding in my behalf. I guess this needs to be fixed on the Libsass side.
