### ISSUE TITLE
@at-root appear no implemented

### ISSUE THREAD

**Issue by SandHilt** [dlmanning/gulp-sass#264]
According to the SassMeister (http://sassmeister.com/), the libsass version 3.2 beta 6 is already implemented the directive ' @at-root '. Why gulp-sass not?

**Comment by Snugug** [comment]
Please make sure you are using [Gulp Sass 2.0](https://github.com/dlmanning/gulp-sass/wiki/Update-to-the-latest-Gulp-Sass). It uses the latest version of Libsass.
