### ISSUE TITLE
Source maps broken in 2.x?

### ISSUE THREAD

**Issue by callumacrae** [dlmanning/gulp-sass#269]
See this issue and comments: https://github.com/sass/node-sass/issues/947

Input is the same, but updating to gulp-sass 2.0.0 breaks the source maps. I've confirmed that it isn't an issue in node-sass.

**Comment by Keats** [comment]
There was a patch merged recently (no new version released yet). 
Can you try on current master and see if it works for you ?

**Comment by callumacrae** [comment]
Yep, that fixed it. When will you release the fix?

**Comment by Snugug** [comment]
Within the next few days.
