### ISSUE TITLE
Gulp falls on gulp-sass errors

### ISSUE THREAD

**Issue by hinews** [dlmanning/gulp-sass#272]
When scss file is empty, gulp-sass 2.0 throws errors and gulp falls.

```
Plumber found unhandled error:
 Error in plugin 'gulp-sass'
Message:
    .../file.scss
```

No errors in previous versions of gulp-sass.

**Comment by Snugug** [comment]
Please read the [Gulp Fils on Sass Errors](https://github.com/dlmanning/gulp-sass/wiki/Common-Issues-and-Their-Fixes#gulp-watch-stops-working-on-an-error) troubleshooting
