### ISSUE TITLE
write after end

### ISSUE THREAD

**Issue by besimhu** [dlmanning/gulp-sass#274]
I did a recent update to libsass and this is the error that I keep getting: `[gulp-sass] write after end`

After some reading around, it seems to be a common error in some other packages. My css is still being built just fine.

Here is a bit more detailed error:

```
[13:21:07] Starting 'sass'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write after end
    at writeAfterEnd (/Dev-Projects/Forty-Eta/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:144:12)
    at DestroyableTransform.Writable.write (/Dev-Projects/Forty-Eta/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:192:5)
    at write (/Dev-Projects/Forty-Eta/node_modules/gulp-css-globbing/node_modules/vinyl-map/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Dev-Projects/Forty-Eta/node_modules/gulp-css-globbing/node_modules/vinyl-map/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.<anonymous> (/Dev-Projects/Forty-Eta/node_modules/gulp-css-globbing/node_modules/vinyl-map/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:613:7)
    at DestroyableTransform.EventEmitter.emit (events.js:92:17)
    at onwriteDrain (/Dev-Projects/Forty-Eta/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:300:12)
    at afterWrite (/Dev-Projects/Forty-Eta/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:288:5)
    at onwrite (/Dev-Projects/Forty-Eta/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:281:7)
    at WritableState.onwrite (/Dev-Projects/Forty-Eta/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:106:5)
```

Here is my task:

```
var gulp         = require('gulp'),
    sass         = require('gulp-sass'),
    sourcemaps   = require('gulp-sourcemaps'),
    gulpFilter   = require('gulp-filter'),
    handleErrors = require('../util/handleErrors'),
    config       = require('../config'),
    autoprefixer = require('gulp-autoprefixer'),
    livereload   = require('gulp-livereload'),
    globbing     = require('gulp-css-globbing');

gulp.task('sass', function () {
  return gulp.src(config.sass.src)
    .pipe(sourcemaps.init())
    .pipe(globbing(config.sass.globbing))
    .pipe(sass(config.sass.settings))
    .on('error', sass.logError)
    .pipe(sourcemaps.write())
    .pipe(autoprefixer(config.autoprefixer))
    .pipe(gulp.dest(config.sass.dest))
    .pipe(livereload());
  return gulp.src(config.sass.src);
});
```

**Comment by Snugug** [comment]
Please provide the smallest possible reduced usecase where this is reproducable, not the whole task, and provide what version of Node and Gulp Sass you are using

**Comment by Snugug** [comment]
Will close if we haven't heard back in the next 2 weeks

**Comment by besimhu** [comment]
Apologies on the late reply. I've been testing some more around. 

Should give you some additional detail within a day or two hopefully.

**Comment by besimhu** [comment]
This error seems to be related to sass globbing.

**Comment by sp90** [comment]
@besimhu I think we have similar problem, this is sovled by running gulp sass in sync mode like this:

```javascript
gulp.task('sass', function () {
  return gulp.src(config.sass.src)
    .pipe(sourcemaps.init())
    .pipe(globbing(config.sass.globbing))
    .pipe(sass.sync(config.sass.settings))
    .on('error', sass.logError)
    .pipe(sourcemaps.write())
    .pipe(autoprefixer(config.autoprefixer))
    .pipe(gulp.dest(config.sass.dest))
    .pipe(livereload());
  return gulp.src(config.sass.src);
});
```

**Comment by mdfragala** [comment]
@besimhu, can you elaborate on the error being related to sass globbing, which I take to mean `gulp-css-globbing`? I'm also running into this issue, but `gulp-css-globbing` seems to be working fine.

For me, the `write after end` error pops up because of a mixin. Commenting the mixin out returns an error with its first reference obviously, but commenting out the references too yields the `write after end` error.

**Comment by macmladen** [comment]
@Snugug This happens with `gulp-css-globbing` and `gulp.src()` globbing with mixin.

It is introducing problem if some `.scss` file has `@import` of some partial (file starting with underscore like `_helpers.scss`) contains mixins.

If you move mixin to the main `.scss` file it will compile with everything else just the same.

Another solution (and probably the source to the problem) is the globing in `gulp.src()` argument with globbing so it could be that globbings are not playing together well.

This fails

```javascript
gulp.task('sass', function() {
  gulp.src('./sass/**/*.{sass,scss}')
    .pipe(cssGlobbing({
      extensions: ['.css', '.scss']
    }))
    ...
```

while this works

```javascript
gulp.task('sass', function() {
  gulp.src('./sass/main.scss')
```

with everything else exactly the same.

**Comment by xzyfer** [comment]
@macmladen thanks for your investigation. Your explanation is a quite difficult to follow. Could you please create a small github repo with a working example of this problem?

This will allow us to dig into the problem, as well communicate the issue clearly with the node-sass and LibSass teams.

**Comment by besimhu** [comment]
Yeah, we have since re-written our build script with the latest Sass & Node version.

However @macmladen that is in fact what I had thought it could be. Additionally, we've removed Sass globbing as that hasn't been updated to play nicely with the latest gulp-sass.

**Comment by macmladen** [comment]
@xzyfer I will, I actually conducted test on small sample while I didn't rule options out.

And while globbing may help to some extent it also may introduce a lot of problems because of order of globbing and including and also present some filename hacking like `_0init.scss` because I need that one first and so on.

So I am not too happy with globbing myself, but on the other hand it may come handy to include a bunch of components, to add them more easily and not requiring to always explicitly `@import` it and delete if not needed as that too introduce complexity.

I am still not wise on that issue, glob or not.

Also globbing presents a problem for `gulp` based thinking as it cannot import from imported as that is against `gulp` design.

**Comment by macmladen** [comment]
It did took some time to make this and to test so here is repository: https://github.com/macmladen/globbing-test

Explanations are in the root in `README.md` file.

There are four branches with different outcomes:

* `master` — fails, it has all of three things that breaks with **Error: write after end**
* `gulp-glob` — passes if only `gulp` globbing is turned off for directories
* `css-glob` — passes if we use `gulp` globbing but not `gulp-css-globbing`
* `mixin-in-scss` — both globbing there but no mixins in imported partials

If I can do anything to help, feel free to ask.

**Comment by craigcoles** [comment]
Is there any updates into this issue? It appears I am now experiencing this exact same issue.

**Comment by xzyfer** [comment]
Thanks for the reproduction @macmladen.

**Comment by xzyfer** [comment]
I am unable to reproduce this with v2.3.1. If the issue persists with latest gulp-sass please open an update issue.
