### ISSUE TITLE
undefined:undefined File context create without an input path

### ISSUE THREAD

**Issue by luqin** [dlmanning/gulp-sass#275]

**Comment by Snugug** [comment]
Please review our [Contributing Guidelines](https://github.com/dlmanning/gulp-sass/blob/master/CONTRIBUTING.md) when submitting an issue. This is not enough for us to help you. When ready, please open a new issue properly describing your problem and giving us the context needed to assist you.

**Comment by tonybaroneee** [comment]
This is because you are running it against a file with no contents. Simply add some text and watch it work :)

**Comment by rehmsen** [comment]
I also ran into this. It is indeed as @tonybaroneee points out: This happens whenever an input file is empty, which, depending on your editor and workflow, is not unusual right after creating a new file. Would it make sense to just  skip empty files instead of crashing gulp?

**Comment by nlundquist** [comment]
I also ran into this. I'd agree this should be reopened for an eventual change to ignore empty files.

**Comment by Keats** [comment]
I'm leaving for vacations right now so won't have time to work really, if someone is willing to do a PR with a test + fix i'll merge when I have internet
