### ISSUE TITLE
Error when using `@each`

### ISSUE THREAD

**Issue by camsong** [dlmanning/gulp-sass#277]
After updating to `v2.0.1`, got `error parsing interpolated value` error on line using `@each`.
![image](https://cloud.githubusercontent.com/assets/948896/7632778/a36ba592-fa82-11e4-9d6d-a84f650499c7.png)

the source code is like
```scss
@each $btn-color in $btn-colors {
// blabla
}
```
It works on `v1.3.*`

**Comment by Keats** [comment]
That's node-sass/libsass issue, not gulp-sass. Please open the issue on one of those repo (probably libsass)

**Comment by camsong** [comment]
Thanks, I've found the reason, it seems `#{}` has changed in latest version.
All I have to do is changing
```scss
$btn-size-namespace: '.oui-btn-' + #{$btn-size};
```
to

```scss
$btn-size-namespace: '.oui-btn-' + $btn-size;
```
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#interpolation_
