### ISSUE TITLE
Update to newer node-sass version

### ISSUE THREAD

**Issue by visualcookie** [dlmanning/gulp-sass#281]
Just discovered that u're using an old version of node-sass. [Current version is 3.1.2](https://github.com/sass/node-sass/releases).

Is it possible that you can update this or can we as users update this and it just works?

**Comment by Keats** [comment]
gulp-sass is using ^3.0.0 so it will fetch 3.1.2 on install.
If it doesn't on your project, delete node_modules and reinstall
