### ISSUE TITLE
Passing encoding through to sass

### ISSUE THREAD

**Issue by jonsamwell** [dlmanning/gulp-sass#283]
I'm having encoding issue with the latest release (2.01).  I've tracked this down to an encoding (http://blog.pixelastic.com/2014/09/06/compass-utf-8-encoding-on-windows/) issue and need to pass the correct encoding through to sass (-E utf-8).  Is there anyway I can do this?

**Comment by Keats** [comment]
Have you tried putting @charset "utf-8"; at the top of your main sass file?

**Comment by jonsamwell** [comment]
I have on my main one but I am using a third party file I have no control
over as an import into that main file which is causing the issue.  If I
drop the version back to 1.3.3 it works fine.  I assume this is because of
the file encoding determination stuff introduced in new sass versions.

**Comment by Keats** [comment]
Yep, nothing to do with gulp-sass, look if you can do that in node-sass otherwise raise an issue there
