### ISSUE TITLE
Issue with escaped values

### ISSUE THREAD

**Issue by Inrego** [dlmanning/gulp-sass#285]
I have a scss file with a lot of icons in it, like this;

    'action-3d-rotation': \e600,
    'action-accessibility': \e601,
    'action-account-balance': \e602,

This file is included by an `@import`
But in the resulting file, I get things like:

    .mdi-communication-call:before {
      content: ; }

    .mdi-communication-call-end:before {
      content: ; }

    .mdi-communication-call-made:before {
      content: ; }

I checked the unicode value of the invalid symbols, and it is the unescaped versions of the symbols. But that's causing the css to not work.

This seems to only be a problem with imports, not if the escaped value is in the main file itself.

Escaping the backslash with double backslash like this `\\e600` will provide the correct result, but that's not really suitable for imported libraries, and it does not seem to be the intented way (seems like a bug since it's only a problem for imports).

**Comment by alferov** [comment]
+1
I had to roll back to 1.x.x version. That solved the problem.

**Comment by Keats** [comment]
That would be a node-sass/libsass issue (most likely libsass), not gulp-sass itself.
Please report on that issue on one of those projects
