### ISSUE TITLE
node-sass dependency fails on some setups

### ISSUE THREAD

**Issue by charmeleon** [dlmanning/gulp-sass#287]
This is related to [this issue on node-sass](https://github.com/sass/node-sass/issues/550), which has been closed. The dependency `node-sass 2.0.1` fails on versions of node newer than 0.10.x in Ubuntu (my setup is Ubuntu 14.04, node 0.11.13). Their issue was closed by a contributor by suggesting upgrading to `node-sass >=3.0.0`.

**Comment by Keats** [comment]
gulp-sass is already using node-sass >= 3, you need to update your package.json to use the latest gulp-sass

**Comment by matteosaadat** [comment]
Updated on bluepill
