### ISSUE TITLE
Add example to the options section of the read me

### ISSUE THREAD

**Issue by robertpateii** [dlmanning/gulp-sass#288]
Took me half an hour to figure out how to add in options using gulp-sass. It's not exactly the same as node-sass since all the examples for node-sass show the options object in the render method.

    sass.render({
      file: scss_filename,
      [, options..]
    }, function(err, result) { /*...*/ });

gulp-sass doesn't use a render method. Evidently the option object needs to be passed in the sass() function. A quick example would help new users a lot. Like this:

     gulp.task('sass', function () {
     gulp.src('./sass/**/*.scss')
       .pipe(sass({sourceComments:true}))
       .pipe(gulp.dest('./css'));
    });

thanks, hope this helps others. happy to make a PR for this if you want, but it's just a readme change.

**Comment by Keats** [comment]
Added one, thanks!
