### ISSUE TITLE
Support for all CSS output styles

### ISSUE THREAD

**Issue by JamesMD** [dlmanning/gulp-sass#289]
Since libsass now supports all CSS outputs, would we see a future release for `gulp-sass` that supports it using `{ style: 'expanded' }`? 

See commit: https://github.com/sass/libsass/commit/7877cfa872b036d55344db5d12ea908bb70f3705

**Comment by Keats** [comment]
gulp-sass is a wrapper around node-sass which uses libsass.
As soon as node-sass updates the version of libsass it uses you will be able to use it by reinstalling gulp-sass

**Comment by JamesMD** [comment]
@Keats, thank you for the update. I'll reference this in node-sass.
