### ISSUE TITLE
How to use outputStyle options?

### ISSUE THREAD

**Issue by yisibl** [dlmanning/gulp-sass#291]
https://github.com/sass/node-sass#outputstyle

Like this?
```js
.pipe( sass({outputStyle: 'expanded'}) )
```

**Comment by Keats** [comment]
Yes, the dict you pass to gulp-sass will be passed to node-sass.
The only option gulp-sass gives is to compile synchronously with `sass.sync()`

**Comment by yisibl** [comment]
Thank you very much!

**Comment by Keats** [comment]
No worries, added an example to the readme as well

**Comment by yisibl** [comment]
Great! :ghost:
