### ISSUE TITLE
Sourcemaps without gulp-sourcemaps?

### ISSUE THREAD

**Issue by dpkonofa** [dlmanning/gulp-sass#295]
No matter what I've tried, I can't seem to get sourcemaps working with gulp-sass on its own.  It seems like I should be able to just pass the standard config options from node-sass to it, but I never get anything.  Here's the piece of the gulpfile I'm using:

    gulp.task('sass', function(){
	return gulp.src(['scss/styles.scss'])
		.pipe(sass(sassOptions))//.on('error', sass.logError))
		.pipe(gulp.dest(sassDest));
    });

My sassOptions variable is using this:

    {
		'errLogToConsole'	: true,
		'outputStyle' 		: 'expanded', // or 'compressed' doesn't matter
		'sourceComments'	: true,
		'sourceMap'			: true
    }

I've tried 'map' for 'sourceComments', I've tried specifying an 'outFile' and nothing seems to work.  Is there a way to get this to work or am I just supposed to be using gulp-sourcemaps for everything?

**Comment by dlmanning** [comment]
@dpkonofa : We don't support source maps without gulp-sourcemaps
