### ISSUE TITLE
g++ error while installing gulp-sass npm package

### ISSUE THREAD

**Issue by povilas0** [dlmanning/gulp-sass#298]
I am using Mac OS X 10.8, g++ 5.1, node 0.10.30, npm 2.0.0-beta.0. While trying to install gulp-sass npm package I get this error:

> node-sass@3.2.0 install /Users/myusera/workspace/frb/frontend/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

>Binary downloaded and installed at /Users/myuser/workspace/frb/frontend/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-11/binding.node

> node-sass@3.2.0 postinstall /Users/myuser/workspace/frb/frontend/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

> /Users/myuser/workspace/frb/frontend/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-11/binding.node ` exists.
 testing binary.
Problem with the binary.
Manual build incoming.
Building: /usr/local/Cellar/node/0.10.30/bin/node node_modules/pangyp/bin/node-gyp rebuild --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
  CXX(target) Release/obj.target/libsass/src/libsass/ast.o
g++: error: unrecognized command line option '-stdlib=libc++'
make: *** [Release/obj.target/libsass/src/libsass/ast.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/myuser/workspace/frb/frontend/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 12.6.0
gyp ERR! command "/usr/local/Cellar/node/0.10.30/bin/node" "/Users/myuser/workspace/frb/frontend/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/myuser/workspace/frb/frontend/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v0.10.30
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok
Build failed
npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.2.0 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

> npm ERR! System Darwin 12.6.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "--save-dev" "gulp-sass"
npm ERR! cwd /Users/myuser/workspace/frb/frontend
npm ERR! node -v v0.10.30
npm ERR! npm -v 2.0.0-beta.0
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/myuser/workspace/frb/frontend/npm-debug.log
npm ERR! not ok code 0

**Comment by Keats** [comment]
That's a node-sass error, report it on that repo

**Comment by lmartins** [comment]
You can also try cleaning your npm cache. It has helped me before with similar errors.
