### ISSUE TITLE
Compiling empty files fails

### ISSUE THREAD

**Issue by jmartsch** [dlmanning/gulp-sass#301]
When one ore more files of my glob folder are empty (have no content, but exist), the error ```undefined:undefined File context created without an input path``` occurs. I think this could be related to https://github.com/sass/node-sass/issues/924
What can i do?

**Comment by Snugug** [comment]
I just ran our tests with the latest version of Node Sass (3.2) and this no longer appears to be an issue. Please update [update to the latest version](https://github.com/dlmanning/gulp-sass/wiki/Update-to-the-latest-Gulp-Sass) and try again

**Comment by jmartsch** [comment]
I tried it with latest version of gulp-sass, following your instructions and it failed.
After that, i reinstalled latest node-sass (3.2) globally (not locally, and it´s not in my package.json) but still no success.
I am on a Windows 8.1 system

**Comment by xzyfer** [comment]
@Snugug this is a node-sass issue. If you somehow call `render` or `renderSync` without either `data` or `file` it will throw this non-sensical error. That is what appears to be happening here 

> one ore more files of my glob folder are empty

**Comment by Snugug** [comment]
Interesting, although we have [code in `2.0.3`](https://github.com/dlmanning/gulp-sass/blob/master/index.js#L31-L33) that should break out before `render` gets called.

@jmartsch Can you please 2.x check what version of Gulp Sass you're using?

**Comment by xzyfer** [comment]
IMHO this is poor UX on our side of things. I've left my feels in https://github.com/sass/node-sass/pull/956#discussion_r33430645

**Comment by Snugug** [comment]
:+1: @xzyfer

**Comment by jmartsch** [comment]
@Snugug My gulp-sass version was 2.0.1. Now with latest gulp-sass everything runs fine without errors.
