### ISSUE TITLE
compile always faild on win7

### ISSUE THREAD

**Issue by niluanxy** [dlmanning/gulp-sass#304]
my match was run win7 64bit,but always compile faild and tip:  gulp-ruby-sass: stderr: 'sass'                е.
the text after 'sass' can't display.

**Comment by ImBobby** [comment]
I think you are using gulp-ruby-sass instead of gulp-sass.

**Comment by niluanxy** [comment]
yes,and now i have replace gulp-ruby-sass by gulp-sass,this can closed;

**Comment by ImBobby** [comment]
@niluanxy 您可以通过点击关闭按钮发close issue

**Comment by niluanxy** [comment]
@ImBobby 恩，谢谢，已经关闭
