### ISSUE TITLE
v2.0.1 gone????

### ISSUE THREAD

**Issue by ctaepper** [dlmanning/gulp-sass#305]
npm ERR! version not found: gulp-sass@2.0.1

lot of builds are failing... version 2.0.2 is out, that is working. why would you remove 2.0.1 from npm registry?

**Comment by jonrimmer** [comment]
Same problem here. Please don't unpublish existing versions. Unless there is a very good reason.

**Comment by Snugug** [comment]
When I released 2.0.2 yesterday I accidentally unpublished 2.0.1 instead of deprecating it. I'm sorry, it sucks, it was my mistake, tried to cancel when I realized I typed the wrong thing and it didn't go through.

**Comment by atdrago** [comment]
I'm having strange issues with 2.0.2 generating extra scss files erroneously. I plan to submit a proper bug report for this when I get the time, but would like to go back to 2.0.1 in the mean time. 

@Snugug Will 2.0.1 be republished?

Thanks for all your hard work and for maintaining this project!

**Comment by Snugug** [comment]
Due to NPM's security policy we can't republish previous versions.
