### ISSUE TITLE
@at-root directive not compiling

### ISSUE THREAD

**Issue by fredkelly** [dlmanning/gulp-sass#308]
Using gulp-sass to compile the latest (v.3.3.5) bootstrap code I've noticed the '@at-root {}' directive seems to get incorrectly compiled (it's spat straight out into the rendered css) - is there a known compatibility issue?

gulp-sass @ 1.3.3
node @ v0.12.2
npm @ 2.7.5
OS X 10.10.4

**Comment by Snugug** [comment]
You're using a vastly out-of-date version of Gulp Sass. Please [update to the latest version of Gulp Sass](https://github.com/dlmanning/gulp-sass/wiki/Update-to-the-latest-Gulp-Sass)

**Comment by fredkelly** [comment]
Thank you - should've checked!
