### ISSUE TITLE
sass fill include "background-image:url(//www.google.com/as.gif)" error

### ISSUE THREAD

**Issue by tianzhiqing** [dlmanning/gulp-sass#309]
sass content will include "background-image:url(//www.google.com/as.gif)"  
error : unterminated argument to :url(...)

**Comment by JamesMD** [comment]
Because `//` isn't interpreted as a valid URL in CSS. Just use `http://` or `https://`.

**Comment by Keats** [comment]
That is not a gulp-sass issue, check the libsass repo
