### ISSUE TITLE
Incorrect rounding of numbers

### ISSUE THREAD

**Issue by opterion** [dlmanning/gulp-sass#311]
Example from bootstrap-sass:

$line-height-base: 1.428571429 !default; // 20/14
So, for buttons with 14px font-size, as example, line-height should be computed to 20px, but in fact, it computes to 19px (floors from 19.999979019165px), because sass compiler converts value 1.428571429 to 1.42857 but not to 1.42858 as expected!

SASS compiler: gulp-sass@1.3.2
Precision: default (5)

Details on screenshot:
![image](https://cloud.githubusercontent.com/assets/7903231/8573663/8b237610-259b-11e5-877e-6dca598fceab.png)

**Comment by verpixelt** [comment]
I'm trying to use precision `.pipe(plugins.sass({ outputStyle: 'expanded', precision: 3 }))` but is has simply no effect.

**Comment by Keats** [comment]
That would be a node-sass issue, not gulp-sass.
Try to use the latest version of gulp-sass @opterion 

@verpixelt all params are sent as is to node-sass so that would be a node-sass issue
