### ISSUE TITLE
Problem with @extand

### ISSUE THREAD

**Issue by Soularix** [dlmanning/gulp-sass#312]
when I try to compile my code this happens : 
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: build\scss\vendors\_grid.scss
  10:1  You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
From "@extend %clearfix" on line 38 of build/scss/vendors/_grid.scss

why I cant extand a selector from inside a @media
can I have some help pls ^^

**Comment by NicolasPoirierB** [comment]
You cannot extend a selector from an @media directive, as per SASS's rules. This is not an issue with gulp-sass but one with SASS itself. They decided to go that way for now, AFAIK.

**Comment by AndrewEastwood** [comment]
But it seems that it's fixed already: https://github.com/sass/libsass/issues/943

**Comment by AndrewEastwood** [comment]
And included into the https://github.com/sass/libsass/tree/3.2.0

**Comment by fosterinteractive** [comment]
You can have a media query in an @extended selector, but you cannot use a @extend within a media query unless you are extending an selector that's inside the same media query. 

The best explanation why this this the case is Hugo Giraudel's article on placeholders. But the short answer extending something in @media would create invalid css. 

See the last paragraph in the post http://hugogiraudel.com/2014/03/31/getting-the-most-out-of-sass-placeholders/

**Comment by xzyfer** [comment]
If this does not work in Ruby Sass it should not work in LibSass. We previously allowed `@extend` across media queries as a bug but it has been fixed.

If I have misunderstood please produce a copy-pastable working example of the issue you're experiencing.

**Comment by fosterinteractive** [comment]
@xzyfer - as you've pointed out red parity ruby sass with I think this issue should be closed. 

I was just including some notes as to why you can't @extend in a media query for others coming across this problem in the future.
