### ISSUE TITLE
error message details

### ISSUE THREAD

**Issue by rothbert** [dlmanning/gulp-sass#317]
Switched from gulp-ruby-sass to gulp-sass -
 `.pipe(sass.sync().on('error', sass.logError)) `

Working fine but missing the detailed error messages that gulp-ruby-sass produces. Only getting:     Message:
    scss/_layout.scss
  228:1  invalid top-level expression
[10:23:25] Finished 'styles' after 7.68 ms
[10:24:15] Starting 'styles'...
Error in plugin 'sass'

Is there an option for a more detailed message including at least line number?

Thanks

**Comment by Snugug** [comment]
288 is the line, 1 is the column.

**Comment by rothbert** [comment]
Ok, now I feel slightly stupid : /
Thanks Sam!
