### ISSUE TITLE
@imported files not given correct path or content in source map when a base is specified

### ISSUE THREAD

**Issue by martinoconnor** [dlmanning/gulp-sass#319]
Given a file *client/style/sass/aboutus.scss* : 
```
@import "base";

#aboutus-container {
	padding: 60px 15px 40px 15px;
	background-color: $gray;
    color: $charcoal;
    font-size: 16px;
}
```

and a file *client/style/sass/base.scss* : 
```
$teal: #0bbbd4;

$easternBlue: #ff9494;
$veryLightGray: #f6f6f6;
$lightGray: #F0F0F0;
$gray: #e9e9e9;
$mediumGray: #cccccc;
$charcoal: #5d5d5d;
$darkCharcoal: #393939; 
$neonGreen: #1fdd7c;
$warningOrange: #ff9900;
$pink: #ff9494;
$easternBlue: #008d9e;

$arrowSize: 7px;
...
```
The result of piping *client/style/sass/aboutus.scss* with a base: client, results in a source map that correctly references *client/style/sass/aboutus.scss*, but *client/style/sass/base.scss* is only referenced as *base.scss* without any content.

**Comment by martinoconnor** [comment]
This can be resolved by updating the imported files in the `sassMap.sources` relative to `file.base` instead of being relative to `file` as is the result from node-sass. Also setting `opts.sourceMapContents = true` will allow the contents to be passed to gulp-sourcemaps. I can prepare a PR demonstrating the solution.

**Comment by Snugug** [comment]
Have you tried with the latest version (`2.0.4`)?

**Comment by martinoconnor** [comment]
Yes, the latest version correctly references the files in the stream, but not the `@import`ed files.

**Comment by Snugug** [comment]
Yah, put together a PR and include tests demonstrating where it's failing now.
