### ISSUE TITLE
Lib cannot find libsass bindings

### ISSUE THREAD

**Issue by polishdeveloper** [dlmanning/gulp-sass#323]
When installing a gulp-sass library it fails to find node-sass lib and shows error `libsass bindings not found in /code/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node`.

Issue: node-sass is located in `/code/node-modules/node-sass/lib/index.js` but code still tries to find it under gulp-sass/node_modules directory.

Application is located under `/code` directory, all commands are executed as a root user (docker env)

node-sass is already installed :
```
root@5733d9c55f83:/code# node -e "console.log(require.resolve('node-sass'))"
/code/node_modules/node-sass/lib/index.js
```

Environment: Debian Jessie@Boot2Docker
Versions:
```
root@5733d9c55f83:/code# node --version
v0.12.7
root@5733d9c55f83:/code# npm --version
2.11.3
root@5733d9c55f83:/code# node -p "console.log(require('node-sass').info)"
node-sass	3.2.0	(Wrapper)	[JavaScript]
libsass  	3.2.5	(Sass Compiler)	[C/C++]
undefined
```

packages.json file:
```
{
  "name": "MyProject",
  "private": "true",
  "version": "0.0.1",
  "repository": {
    "type": "git",
    "url": "........."
  },
  "dependencies": {
    "angular": "1.4.3",
    "body-parser": "1.10.2",
    "boom": "2.8.0",
    "colors": "1.1.2",
    "debug": "~2.1.1",
    "del": "^1.2.0",
    "errorhandler": "1.3.2",
    "expect.js": "0.3.1",
    "express": "4.13.1",
    "hapi": "8.8.0",
    "method-override": "2.3.1",
    "node-statsd": "0.1.1",
    "q": "1.2.0",
    "request-promise": "0.4.3",
    "run-sequence": "1.0.2",
    "source-map-support": "0.3.1",
    "traverson": "2 .0.1",
    "winston": "1.0.0"
  },
  "devDependencies": {
    "tsd": "0.6.3",
    "gulp": "3.9.0",
    "bower": "^1.4.1",
    "gulp-filter": "2.0.2",
    "gulp-insert": "0.4.0",
    "gulp-livereload": "^3.8.0",
    "gulp-replace": "0.5.3",
    "gulp-sass": "^2.0.4",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-strip-comments": "^1.0.1",
    "gulp-tsc": "0.9.2",
    "gulp-tslint": "^3.1.2",
    "gulp-typedoc": "^1.1.0",
    "mocha": "2.2.5",
    "tslint": "^2.4.2",
    "typedoc": "^0.3.5"
  }
}
```

Sample output: 
```
root@5733d9c55f83:/code# gulp compile
/code/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:148
    throw new Error(['`libsass` bindings not found in ', binaryPath, '. Try re
          ^
Error: `libsass` bindings not found in /code/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath (/code/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:148:11)
    at Object.<anonymous> (/code/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/code/node_modules/gulp-sass/index.js:163:21)
    at Module._compile (module.js:460:26)
root@5733d9c55f83:/code# npm install node-sass
-
> node-sass@3.2.0 install /code/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /code/node_modules/node-sass/vendor/linux-x64-14/binding.node

> node-sass@3.2.0 postinstall /code/node_modules/node-sass
> node scripts/build.js

` /code/node_modules/node-sass/vendor/linux-x64-14/binding.node ` exists.
 testing binary.
Binary is fine; exiting.
node-sass@3.2.0 node_modules/node-sass
├── get-stdin@4.0.1
├── async-foreach@0.1.3
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── meow@3.3.0 (object-assign@3.0.0, camelcase-keys@1.0.0, minimist@1.1.3, indent-string@1.2.2)
├── npmconf@2.1.2 (uid-number@0.0.5, ini@1.3.4, inherits@2.0.1, once@1.3.2, osenv@0.1.3, config-chain@1.1.9, nopt@3.0.3, semver@4.3.6)
├── glob@5.0.14 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3.2, minimatch@2.0.10)
├── gaze@0.5.1 (globule@0.1.0)
├── nan@1.9.0
├── request@2.60.0 (aws-sign2@0.5.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.4, oauth-sign@0.8.0, tunnel-agent@0.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.3, qs@4.0.0, combined-stream@1.0.5, form-data@1.0.0-rc3, mime-types@2.1.4, http-signature@0.11.0, bl@1.0.0, tough-cookie@2.0.0, hawk@3.1.0, har-validator@1.8.0)
├── pangyp@2.2.1 (which@1.0.9, rimraf@2.2.8, graceful-fs@3.0.8, osenv@0.1.3, nopt@3.0.3, fstream@1.0.7, semver@4.3.6, glob@4.3.5, minimatch@2.0.10, tar@1.0.3, npmlog@1.0.0, request@2.51.0)
└── sass-graph@2.0.0 (yargs@3.18.0, lodash@3.10.1)
root@5733d9c55f83:/code# gulp compile
/code/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:148
    throw new Error(['`libsass` bindings not found in ', binaryPath, '. Try re
          ^
Error: `libsass` bindings not found in /code/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath (/code/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:148:11)
    at Object.<anonymous> (/code/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/code/node_modules/gulp-sass/index.js:163:21)
    at Module._compile (module.js:460:26)
```

I also tried to install `node-sass` package as a dependency in packages.json file but it also doesn't work

**Comment by polishdeveloper** [comment]
and one extra information, on nodejs 0.10.38~dfsg-1 (the default that comes from Debian:sid distro) it worked perfectly, but we switched Debian:jessie and started using nodejs. 0.12.x using nodesource installation guide and it stopped working.

**Comment by timomeh** [comment]
Same here, bindings not found.

`Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/darwin-x64-45_binding.node": HTTP error 404 Not Found`

**Comment by polishdeveloper** [comment]
@timomeh - your issue is different, you're trying to download file that doesn't exists, verify your paths/versions. My issue is that I already have file on file ssytem but somehow it didn't pick it up

**Comment by Keats** [comment]
@timomeh if you look at the page https://github.com/sass/node-sass/releases/ you can notice that there is indeed no binding for x64-44 so report the issue there.

@polishdeveloper gulp-sass doesn't do anything with the binary or its installation, it just passes args to node-sass so that's likely to be a node-sass issue.

**Comment by polishdeveloper** [comment]
@Keats yes, it doesn't do anything, even find it ;p. Why if I type in console it's able to find node-sass library. ah, ok, my bad... I just wanted to throw shit but error comes from `.../node_modules/node-sass/lib/extensions.js`. 
Sorry for bothering you guys

**Comment by timomeh** [comment]
@Keats Yeah, sorry. It happened just now while gulp was running. Suddenly it wanted an rebuild of node-sass, but it can't load the bindings, and it was just such a coincidence that in this moment there was this bugreport here.

**Comment by polishdeveloper** [comment]
@Keats one question if I can ask : why do I have to node-sass libs ??

one is located under ./node-modules/node-sass and second one is ./node-modules/gulp-sass/node-modules/node-sass. Both are at same version (3.2.0+libsass 3.2.5), bindings are only in the first one (./node-modules/node-sass) but gulp-sass uses the second-one

**Comment by Keats** [comment]
Must be related to how node loads packages (order etc).
gulp-sass should use the one in its own node_modules in theory

**Comment by xmakina** [comment]
@polishdeveloper how did you resolve the problem? I'm getting the same error on two separate machines and no idea how to fix it

**Comment by polishdeveloper** [comment]
My error was really stupid, it was related to docker container. I'm working on OSX+Boot2Docker and I was getting this error when I was trying to compile sass on wrong machine, for example:

a) when I did `npm install` in docker and tried to do `gulp compile-sass` in OSX it was complaining that darwin bindigs were missing
b) when I did `npm install` in osx and tried to do `gulp compile-sass` in docker it was complaining that linux bindings were missing

And each `npm install` was overriding previous binding. THere are two fixes for that @xmakina 

a) do `npm install` on one machine and download bindings manually
b) do everything only on one machine (we went this way), our whole development cycle is done only in docker
