### ISSUE TITLE
Interpolation causes parsing error when anchored to selector.

### ISSUE THREAD

**Issue by nathanjosiah** [dlmanning/gulp-sass#327]
I want to set a color on a class and a different color if it's applied to an `a`. 
Consider the following scss:

```scss
.item {
    color: red;

    a#{&} {
        color: blue;
    }
}
```

This renders `Parsing error: Please check validity of the block starting from line #4`

Obviously this example is very simple but let's assume my selector is more complex so please don't just say to just use two separate selectors because more complex situations makes this very difficult to maintain. Also, it looks like this is expected behavior based on [SASS documentation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#interpolation_) as well as certain [issues on sass/sass](https://github.com/sass/sass/issues/286).

**Comment by Snugug** [comment]
Gulp Sass is a thin wrapper around Node Sass, which in turn is a wrapper around Libsass. If you have output/parsing errors, please report them to [Libsass](https://github.com/sass/libsass)

**Comment by nathanjosiah** [comment]
Thank you. For reference, libsass has a [bigger bug](https://github.com/sass/libsass/issues/1210) that includes this one.

**Comment by Snugug** [comment]
Welcome! When that's released, Gulp Sass will support it
