### ISSUE TITLE
No body feel uncomfortable about css indentation after compiling with gulp-sass

### ISSUE THREAD

**Issue by titancat** [dlmanning/gulp-sass#329]
`test.scss`
```
body {
  font-size: 12px;
  p {
    font-size: 15px;
  }
}
```
after compiling

`test.css`
```
body {
  font-size: 12px; }
  body p {
    font-size: 15px; }
```

How can I get a better indentation ?

**Comment by xiadd** [comment]
try`sass({outputStyle: 'expanded'})`

**Comment by Okami92** [comment]
Same problem. Xiadd's solution not working for me.

**Comment by xzyfer** [comment]
This is not a bug.

**Comment by xzyfer** [comment]
You have `outputStyle` options
- nested (default)
- compact
- expanded
- compress
