### ISSUE TITLE
Update node-sass to the latest version

### ISSUE THREAD

**Issue by mhagemeister** [dlmanning/gulp-sass#330]
I've been using gulp-sass quite a lot lately and love it so far! Some libraries that I'm using require a newer libsass version. The node-sass dependency is still at 3.0.0. whereas the latest version is 3.3.1 as the time of this writing.

**Comment by MrSkippy** [comment]
:+1:

**Comment by deepakjois** [comment]
node-sass just released 3.3.0 which fixes an issue, enabling node-sass to run on io.js. Could you  pull that dependency in.

I am currently running gulp-sass from my own fork to work around this.

**Comment by dhritzkiv** [comment]
v3.3.2 is what fixes `SIGSEGV` errors on OS X

**Comment by deepakjois** [comment]
Yes, sorry. That was a typo. I meant to say _3.3.2_.

**Comment by Snugug** [comment]
Hopefully once and for all, Gulp Sass installs whatever the latest version of Node Sass is _at time of Gulp Sass's install_.

Added this to list of [common issues and their solutions](https://github.com/dlmanning/gulp-sass/wiki/Common-Issues-and-Their-Fixes#node-sass-version-not-up-to-date). Please follow the steps there to upgrade to the latest Node Sass

**Comment by Snugug** [comment]
For the record, the dependency is `^3.0.0`, The `^` means _any version that matches 3.x.x_

**Comment by dhritzkiv** [comment]
See, I believed that to be the behaviour. However, an odd thing is happening: running `npm remove gulp-sass` and then `npm install` again simply installs `node-sass` v3.3.1 (the version that fails on OS X), despite the latest on npm being 3.3.2. I even ran `npm cache clean`. It doesn't make sense.

`cd`'ing to `node_modules/gulp-sass` and then running `npm install node-sass@latest` there solves the node-sass version problem.
