### ISSUE TITLE
Doesn't compile when importing scss file with underscores

### ISSUE THREAD

**Issue by LoveAndHappiness** [dlmanning/gulp-sass#333]
This does not compile:

```
gulp.task('sass', function () {
    return gulp.src([
        'bower_components/bootstrap-sass/assets/stylesheets/_bootstrap.scss'
    ])
        .pipe(sass())
        .pipe(gulp.dest('css'));
});
```

I have to rename **_bootstrap.scss** to **bootstrap.scss** to be able to compile it, like this:

```
gulp.task('sass', function () {
    return gulp.src([
        'bower_components/bootstrap-sass/assets/stylesheets/bootstrap.scss'
    ])
        .pipe(sass())
        .pipe(gulp.dest('css'));
});
```

**Comment by Snugug** [comment]
Files starting with underscores are partials in Sass and, by the language definition, are not compiled.

**Comment by LoveAndHappiness** [comment]
Thanks for clarifying this, yet I wonder, why If I pull bootsrap-sass from bower **every file** in there is a partial.

**Comment by OEvgeny** [comment]
Wonder, because it works from console with ``node-sass``:
```
./node_modules/.bin/node-sass --include-path "node_modules/bootstrap-sass/assets/stylesheets" src/scss/_bootstrap.scss dist/css/bootstrap.css
```

Also main bootstrap files in SASS version are named with "_". And it works correctly.

**Comment by Keats** [comment]
bootstrap uses partials because they want you to mix and match, not use everything from the go, ie you pull whichever partial you want to use.

We ignore files starting with _ in gulp-sass since otherwise you would get one resulting css file for each partial, which is not what you want.

**Comment by OEvgeny** [comment]
In case described above you will end with 0 files. No warning or anything else will be shown. It finishes with positive result.

**Comment by LoveAndHappiness** [comment]
Yes, you (@Keats, @OEvgeny) are right. I misunderstood how to work properly with bootstrap. I'll close the ticket, because I understand it now.
