### ISSUE TITLE
Break after update: Variables are not imported

### ISSUE THREAD

**Issue by jbeja** [dlmanning/gulp-sass#337]
#### OS:
Windows 7

#### Versions:
Node@0.12.7
gulp@3.9.0
gulp-sass@2.0.4
node-sass@3.3.2

`gulpfile.js`:

```
var gulp = require('gulp'),
    sass = require('gulp-sass');

gulp.task('styles', function() {
    return gulp.src('web/assets/theme/new-theme/sass/*.scss')
        .pipe(sass().on('error', sass.logError))
        .pipe(gulp.dest('web/assets/theme/new-theme/css'));
 });
```

#### My case:

`web/assets/theme/new-theme/sass/framework/config.scss`:

```
$light-color: #fff;
```

`web/assets/theme/new-theme/sass/theme.scss`:

```
@import "framework/config";

body {
    background-color: $light-color;
}

```

After trigger `gulp styles` I get the following error:

```
Error in plugin 'sass'
Message:
    web\assets\theme\new-theme\sass\theme.scss
  7:14  Undefined variable: "$light-color".
```

Never have this problem before updating, Am I missing something?

**Comment by Keats** [comment]
your config.scss should be a partial, ie starting with _

**Comment by jbeja** [comment]
I am still having the same problem after rename it into a partial.
