### ISSUE TITLE
Broken on Node 4.0.0

### ISSUE THREAD

**Issue by Awk34** [dlmanning/gulp-sass#338]
Will have to wait for node-sass to support Node 4.0.0, and then update the dependency :/

**Comment by jarjan** [comment]
They already added support.

[Tweet](https://twitter.com/nodesass/status/641469706541604864):
>We've just landed @nodejs 4.x support for OS X and Linux.
>
>Windows and FreeBSD will land in the next 24hrs!
>
>Just `npm install`.

**Comment by cismous** [comment]
Gulp-sass not support Node v4.0.0 yet now.

**Comment by Awk34** [comment]
@jarjan I'm on Windows 10 : /

**Comment by Keats** [comment]
See https://github.com/sass/node-sass/issues/1122

You will need to wait for the next release of node-sass

**Comment by Awk34** [comment]
Yes, I'm waiting for that. I made this issue as a tracker against that.

**Comment by Awk34** [comment]
Hopefully others will see this issue and not post another 20 of them saying that it is broken on Node 4 XD

**Comment by xzyfer** [comment]
Node sass fully support Node.js 4.

**Comment by xzyfer** [comment]
For clarification only `node-sass@^3` supports iojs, and only the latest `node-sass@3.3.2` supports Node 4.

>Will have to wait for node-sass to support Node 4.0.0, and then update the dependency :/
>You will need to wait for the next release of node-sass

@Awk34 @Keats we are not releasing a new version for Node.js 4 support. We have backported the binaries to `node-sass@latest` (v3.3.2).

>Can not download file from ...

@cismous you're using `node-sass@2.1.1` which is ancient and unsupported. Please update.

**Comment by Awk34** [comment]
Thanks @xzyfer !

**Comment by Awk34** [comment]
Confirmed working wth new `node-sass` on my Windows 10 box.
