### ISSUE TITLE
libsass bindings not found when using Node v.4

### ISSUE THREAD

**Issue by lpommers** [dlmanning/gulp-sass#340]
After upgrading to the latest version of Node 4.0.0, running my gulp sass task fails. 

I do have node-sass installed, and re-installing does not fix the issue.

![screen shot 2015-09-10 at 8 49 35 am](https://cloud.githubusercontent.com/assets/5764316/9781885/11923ef0-5799-11e5-8d57-393039eb2264.png)

**Comment by mewben** [comment]
Having this problem too...

**Comment by SteveEdson** [comment]
Also having this issue, could it be because its not set to use the latest node-sass package?

**Comment by Keats** [comment]
> Also having this issue, could it be because its not set to use the latest node-sass package?

It is using the latest.

This error usually happens when node-sass install failed, could you uninstall and reinstall and check whether there was an error when installing gulp-sass?

**Comment by SteveEdson** [comment]
I was using Codeship, just reset the dependency cache and its working. 

False alarm, thanks!

**Comment by lpommers** [comment]
@Keats  yep, uninstalling and reinstall `gulp-sass` threw an error and the build failed.
![screen shot 2015-09-10 at 1 40 16 pm](https://cloud.githubusercontent.com/assets/5764316/9787276/aaaf53b6-57c1-11e5-8d9f-5f80c39e8f40.png)

**Comment by Keats** [comment]
You are installing gulp-sass 1.3.3 in that screenshot, that's a very old version.
Install the v2

**Comment by aasukisuki** [comment]
I'm having a similar issue, both within Visual Studio 2015 and the command line (windows 7 machine)

```
Failed to run "C:\{{App Dir}}\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
Error: `libsass` bindings not found in C:\{{App Dir}}\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-ia32-11\binding.node. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath (C:\{{App Dir}}\node_modules\gulp-sass\node_modules\node-sass\lib\extensions.js:150:11)
    at Object.<anonymous> (C:\{{App Dir}}\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:16:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\{{App Dir}}\node_modules\gulp-sass\index.js:163:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```
I've tried uninstalling & reinstalling and there are no errors.  What I did notice is that the win32-ia32-11 path location does not exist, but instead is a 64-bit location (C:\{{App Dir}}\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64-46) which does contain the binding.node file.

Any way to specify that the 64-bit version should be used during install?

**Comment by aasukisuki** [comment]
Deleting node_modules, and references to node-sass and gulp-sass, along with re-installing fixed my issue on the console, but VS is still having issues;  So my issue looks like it's more than likely not a gulp-sass issue.

**Comment by matthewrose** [comment]
Same problem here using gulp-sass with node v4 on Windows 10.

**Comment by Keats** [comment]
Install issues are a node-sass issue, not gulp-sass.
Report it on that repo if that still happens
