### ISSUE TITLE
Unable to use gulp-sass-binaries

### ISSUE THREAD

**Issue by jecuendet** [dlmanning/gulp-sass#351]
I have put the dep in package.json and npm got it -> OK
I have configured gulp like that:
At the beginning:
   var sass = require('gulp-sass-binaries');
In the task:
        .pipe(sass(sassOptions)).on('error', conf.errorHandler('Sass'))

I get:
module.js:522
  var nodePath = process.env['NODE_PATH'];
                        ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/git/pee/tools/kapla/client/node_modules/gulp-sass-binaries/node_modules/node-sass-binaries/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

An idea why?

**Comment by Keats** [comment]
Try `npm rebuild` or `rm -rf node_modules && npm install`

**Comment by xzyfer** [comment]
You have not provided enough information for address this issue. 

- Firstly please use gulp-sass instead of gulp-sass-binaries.
- Lastly please follow the [node-sass TROUBLESHOOTING guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#debugging-installation-issues) and place the entire output in a [gist](https://gist.github.com/).

**Comment by jecuendet** [comment]
In fact, I WANT to use  gulp-sass-binaries, that's the idea of this issue.
The policy around build servers in my company doesn't permit to compile libsass
Is it the right place to ask for help on  gulp-sass-binaries?
Else, where should I go?
Thanks.

**Comment by Keats** [comment]
gulp-sass will download binaries
Never heard of gulp-sass-binaries before today

**Comment by jecuendet** [comment]
gulp-sass-binaries is here: https://www.npmjs.com/package/gulp-sass-binaries
It points on https://github.com/dlmanning/gulp-sass though.

So if, when installing gulp-sass, it compiles libsass (with C++ which is my problem) instead of downloading binaries, there is a problem, right?
If so, I'll try to investigate, do you have an idea how?

**Comment by xzyfer** [comment]
@jecuendet 

>The policy around build servers in my company doesn't permit to compile libsass
binaries are only ever compiled if things go wrong during installation. 

>Is it the right place to ask for help on gulp-sass-binaries?
>Else, where should I go?

I don't know. We have no relation to gulp-sass-binaries and as such are not able to support it.

>do you have an idea how?

No. As requested please follow the [node-sass TROUBLESHOOTING guide](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#debugging-installation-issues) and place the entire output in a [gist](https://gist.github.com/).

**Comment by xzyfer** [comment]
@jecuendet for companies with firewalls or other restrictions node-sass (which gulp-sass uses) offers their [release binaries for download](https://github.com/sass/node-sass/releases/tag/v3.3.3) and [many binary configuration options](https://github.com/sass/node-sass#binary-configuration-parameters).

I cannot emphasis this more, please do not use gulp-sass-binaries.
