### ISSUE TITLE
Update node-sass dependency

### ISSUE THREAD

**Issue by corydorning** [dlmanning/gulp-sass#355]
Keep getting the lib bindings error using gulp-sass. If i update gulp-sass's bower.json to use node-sass 3.3.3 everything works properly.

**Comment by Keats** [comment]
Try to clear the npm cache or install the 2.1.0-beta for node-sass 3.4

**Comment by corydorning** [comment]
yeah i cleared cache, tried a rebase, etc. nothing worked. several team members were getting the error without an update to node or npm so not sure what happened. only thing that fixed was updating the node-sass dependency. will try 2.1.
