### ISSUE TITLE
cannot be installed when node version is 4.0

### ISSUE THREAD

**Issue by fedorjia** [dlmanning/gulp-sass#357]
The install command " npm install gulp-sass --save-dev "  error when node version is update to 4.0.
The error message: 
![qq20151004-1 2x](https://cloud.githubusercontent.com/assets/11704884/10266120/0a30ab92-6a81-11e5-85bc-8b6dedd2f5cd.jpg)

**Comment by xzyfer** [comment]
Only the latest version of gulp-sass is node 4 compatible.

**Comment by xzyfer** [comment]
I've taken a closer look. This appears to be a network timeout issue.

**Comment by fedorjia** [comment]
Maybe timeout issue, Delete node_module folder and run "npm install", it works. Thank you @xzyfer.
