### ISSUE TITLE
Underscore in source file name prevents task from executing

### ISSUE THREAD

**Issue by terales** [dlmanning/gulp-sass#36]
This code failing (file styles.css doesn't appear in target url.):

``` js
gulp.task('scss', function() {
    gulp.src('./sources/scss/_styles.scss')
        .pipe(sass({
            outputStyle: 'compressed'
        }))
        .pipe(gulp.dest('./dev-build'));
});
```

Content of the _styles.scss is valid.

**Comment by kuraga** [comment]
Well it's a problem because of some packages think different (i.e. https://github.com/twbs/bootstrap-sass).

An option maybe?

**Comment by dlmanning** [comment]
@kuraga bootstrap-sass works fine if you just import the path without including the leading underscore (e.g. "@import 'bootstrap/theme';" will import ./bootstrap/_theme.scss. This is actually a part of the sass spec: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#partials

**Comment by kuraga** [comment]
@dlmanning yes, but if *the main* file name starts with underscore?

**Comment by dlmanning** [comment]
@kuraga `@import 'bootstap';` will import ./_bootstrap.scss. If we're talking about *your* main file, don't do that.

**Comment by kuraga** [comment]
Yeah, nice idea! Thanks!

**Comment by kanbara** [comment]
Maybe there should be a warning or info flag on these files so when all your files begin with underscore because they are partials and you forget to import them, you'll know.
