### ISSUE TITLE
Problem with gulp-sass and multiple source

### ISSUE THREAD

**Issue by artem-malko** [dlmanning/gulp-sass#361]
Hi.
I've got multiple source to compile:
```javascript
gulp.src([
    'mixins/**/**.scss',
    'markup/modules/**.*.scss'
])
.pipe(sass())
.pipe(concat('main.css'))
.pipe(dest)
```
The problem is that  I can't use mixins from mixins/**/*.scss in modules. I think, that it is beacuse of order in stream, mixins are not  before modules in stream or something else wrong. Could you help?

**Comment by xzyfer** [comment]
This is on purpose. What you're telling gulp to do here is "resolve these two globs to a list of files, the pass each file to gulp-sass to compile". This means that none of the individual `.scss` files that your glob matches knows about any other file.

The **only** way for a Sass file to know about another Sass file is if it `@import` it. This cannot change.

**Comment by artem-malko** [comment]
This is really sad...

**Comment by xzyfer** [comment]
This is simply how both gulp and Sass work.

**Comment by artem-malko** [comment]
@xzyfer is there any possibilities to get error, that will point to a file with error, not to compiled main.css? I'm talking about the next variant:
```javascript
gulp.src([
    'mixins/**/**.scss',
    'markup/modules/**.*.scss'
])
.pipe(concat('main.css'))
.pipe(sass())
.pipe(dest)
```
If there is a error in modules, for example, I will never now, in what module it was occurred.

**Comment by xzyfer** [comment]
We do produce an error https://github.com/dlmanning/gulp-sass/blob/master/index.js#L123-L125

You'll need to make sure you're catching/handling the error. Gulp won't do this for you.

**Comment by artem-malko** [comment]
The question is not about error handling. It is about error content. In my case, there  will be a error with follow content:
Some error in main.css
Line 1933
Symbol 22

It's not clear, there problem is.

**Comment by xzyfer** [comment]
What is producing that error? The error we supply gulp has the specific error message receive from node-sass. 

Could you please create a small GitHub repo with a working example of this error message? This way we can work on ruling out extern factors and figuring out where own errors are getting swallowed.

**Comment by artem-malko** [comment]
@xzyfer Ok, i'll make it asap.
