### ISSUE TITLE
@each not working anymore as expected

### ISSUE THREAD

**Issue by scaljeri** [dlmanning/gulp-sass#369]
With gulp-sass version 1.3.2 I used to do the following:

    $list: abc def ghi jkl mno pqrs tuv wxyz dot #{or} money less-equal greater-equals brackets ;
    @each $char in $list {
        .my-keys-#{$char}::before {
            content: '#{$char}';
            font-size: 14px;
            letter-spacing: 1px;
            line-height: 17px;
        }
    }

It would generate the following:

    .my-keys-abc::before {
        content: 'abc';
        font-size: 14px;
        letter-spacing: 1px;
        line-height: 17px; }

    .my-keys-def::before {
        content: 'def';
        font-size: 14px;
        letter-spacing: 1px;
        line-height: 17px; }
      ...

However, with version 2.0.4 this code snippet gets compiled to:

    .my-keys-abc def ghi jkl mno pqrs tuv wxyz dot or money less-equal greater-equals brackets::before {
        content: "abc def ghi jkl mno pqrs tuv wxyz dot or money less-equal greater-equals brackets";
        font-size: 14px;
        letter-spacing: 1px;
        line-height: 17px; }

Is my scss incorrect or could this be a bug  ? 
CHeers

**Comment by xzyfer** [comment]
The code supplied does not compile with Ruby Sass. Please confirm it's correct.

```
$list: abc def ghi jkl mno pqrs tuv wxyz dot #{or} money less-equal greater-equals brackets;
@each $char in $list {
    .my-keys-#{$char}::before {
        content: '#{$char}';
        font-size: 14px;
        letter-spacing: 1px;
        line-height: 17px;
    }
}
```

**Comment by scaljeri** [comment]
Check, thats it. I changed #{or} to 'or' and it works. Thnx!
