### ISSUE TITLE
node-sass release folder missing

### ISSUE THREAD

**Issue by linxixuan** [dlmanning/gulp-sass#370]
When gulp-sass installing, console will show some code like below

```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.3.3/darwin-x64-46_binding.node": connect ETIMEDOUT 54.231.2.241:443
```

**Comment by Keats** [comment]
As indicated in that line, it's a timeout and if you paste that link in the browser it does work so just do another npm install

**Comment by linxixuan** [comment]
Thanks for your advise, install node-sass is very slow in China.

**Comment by xzyfer** [comment]
This is a known issue with installing node-sass in China. The current beta has a better error message which suggests using a proxy.

https://github.com/sass/node-sass/commit/8352799a4dc5da3c64f9d1e05975ad3e4efc80f2
