### ISSUE TITLE
How to make sure that the icons font will not be converted

### ISSUE THREAD

**Issue by Leonkao** [dlmanning/gulp-sass#371]
Sass file:
```
$var-font: "\f123";

.font-a{
	content: $var-font;
}
.font-b{
	content: "\f123";
}
```

Ootput:
```
.font-a{content: "";}
.font-b{content: "\f123";}
```

How to make sure that the icons font will not be converted. My gulp-sass version is 2.0.4 .
Thkns !

**Comment by xzyfer** [comment]
Try the latest beta

```
npm install node-sass@beta
```

This is a known issue. It doesn't actually affect font loading assuming you've set the character encoding type

```
<meta charset="UTF-8">
```

**Comment by Leonkao** [comment]
thanks!
