### ISSUE TITLE
Specify output file name

### ISSUE THREAD

**Issue by kurisubrooks** [dlmanning/gulp-sass#372]
I want to compile both an expanded and minified version of my sass project, but I can't figure out how to do so. Is there a way to specify the output filename, like `output.css` for expanded and `output.min.css` for compressed? Thanks!

**Comment by xzyfer** [comment]
You'll need to pipe the output through a rename plugin. We only do one thing which is turn Sass into CSS. You can pipe that CSS into any other plugins to achieve any output you desire.
