### ISSUE TITLE
importing mixins is not working as expected

### ISSUE THREAD

**Issue by xstortionist** [dlmanning/gulp-sass#380]
I'm importing mixins and trying to include them in other scss files but there is no output.

```@import "mixins/_grid";```

This is what I have in the imported file

```
%column-styles {
	position: relative;
	min-height: 1px;
	padding-left: 15px;
	padding-right: 15px;
}

@mixin col-list {
  @for $i from 1 through $columns {
  .col-xs-#{$i} { @extend %column-styles; }
  .col-sm-#{$i} { @extend %column-styles; }
  .col-md-#{$i} { @extend %column-styles; }
  .col-lg-#{$i} { @extend %column-styles; }
  }
}

%column-float {
  float: left;
}

@mixin col-float-xs {
  @for $i from 1 through $columns {
  .col-xs-#{$i} { @extend %column-float; }
  }
}

@mixin col-float-sm {
  @for $i from 1 through $columns {
  .col-sm-#{$i} { @extend %column-float; }
  }
}

@mixin col-float-md {
  @for $i from 1 through $columns {
  .col-md-#{$i} { @extend %column-float; }
  }
}

@mixin col-float-lg {
  @for $i from 1 through $columns {
  .col-lg-#{$i} { @extend %column-float; }
  }
}
```

I include the mixins in other files but there is no output. If I place the mixins within the file that I'm including them in, it works just fine. Gulp shows no errors when compiling.

**Comment by Keats** [comment]
None of those mixins would generate any css code until they are used so that's normal, unless i misunderstood the issue

**Comment by xstortionist** [comment]
I figured it out. You have to have to include variables within the mixin bubble or it doesn't work.

**Comment by Keats** [comment]
cool, closing then
