### ISSUE TITLE
extending nested %helper classes

### ISSUE THREAD

**Issue by willBMAS** [dlmanning/gulp-sass#382]
Recently moved to gulp sass from the Prepros program. I noticed that my nested helper classes don't work when I extend them, example:

%padding {
      padding: 20px;
      &-2 {
             padding: 40px;
      }
}

div {
      @extend %padding-2;
}

This used to work with Prepros, but doesn't work with gulp-sass. It works if I use the normal full-stop (period) instead of percentage, but then I lose the advantage of hiding the helper from the final output.

Any chance of this being added? Or do I need to do something extra for gulp-sass?

**Comment by Keats** [comment]
This is a libsass issue, not gulp-sass
I'm not sure if you can extend silent classes in Sass though
