### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by JohnAlbin** [dlmanning/gulp-sass#384]
The commit message for 4667e0bf8c5a8f818df0113bd33f1aeb2edbbcaa is `2.1.0`, but no tag and no actual release has been made.

gulp-sass 2.0.4 doesn't work with node-sass 3.4, but gulp-sass HEAD does.

**Comment by xzyfer** [comment]
Yes we're aware. The tag as delayed because of the holiday weekend here.

**Comment by xzyfer** [comment]
2.1.0 was released 5 days ago.

![screen shot 2015-11-02 at 10 10 54 am](https://cloud.githubusercontent.com/assets/579928/10871930/096d89de-814a-11e5-9476-8ed2dee53da5.png)

**Comment by JohnAlbin** [comment]
Thanks! :-D

https://www.npmjs.com/package/gulp-sass
