### ISSUE TITLE
Not working on Win10

### ISSUE THREAD

**Issue by artem-malko** [dlmanning/gulp-sass#386]
win10
node: 4.2.1
npm: 2.14.7
node-sass: 3.4.1
http://joxi.ru/n2Y5n0PtXGG426

**Comment by DabsDesign** [comment]
I'm having a similar issue, but when I try to install, the node-sass package isn't able to find the 
```
https://github.com/sass/node-sass/releases/download/v3.4.1/win32-x64-47_binding.node
```

Falling back to earlier versions doesn't seems to work, I tried until the v2.0.0.

**Comment by xzyfer** [comment]
@DabsDesign we don't support Node 5 on windows yet. Downgrade your Node.

**Comment by xzyfer** [comment]
@artem-malko I have no idea what this means, sorry. Maybe @saper or @am11 could be of more help.

**Comment by xzyfer** [comment]
Tracking in https://github.com/sass/node-sass/issues/1241

**Comment by artem-malko** [comment]
@xzyfer thank you.
