### ISSUE TITLE
can't installl gulp-sass ?

### ISSUE THREAD

**Issue by drioou** [dlmanning/gulp-sass#388]
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (E:\AppServ\www\周周测\node_modules\gulp-sass\node_modules\node-sass\node_modul
es\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at E:\AppServ\www\周周测\node_modules\gulp-sass\node_modules\node-sass\node_modules\node-gyp\li
b\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\AppServ\\www\\周周测\\node_modules\\gulp-sass\\node_mo
dules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\AppServ\www\周周测\node_modules\gulp-sass\node_modules\node-sass
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\duanyong\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\duanyong\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=C:\\Users\\duanyong\\.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=C:\\Users\\duanyong\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\pangyp\\bin\\node-gyp.js" "i" "gulp-sass" "--save-dev"
npm ERR! node v0.12.6
npm ERR! npm  v2.13.5
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.1 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

**Comment by xzyfer** [comment]
It appears that fetching the node-sass binaries failed. When this happens node tries to compile the extension for you. This requires python2 two which you don't have installed.

You have cut of the relevant part of the error log, but I'm guessing you're using a mirror to download the binaries. The mirror does not have the binary you require. Either choose a different mirror or install pythong2.

**Comment by drioou** [comment]
thx you
