### ISSUE TITLE
assertion failed  when use sourcempas

### ISSUE THREAD

**Issue by drioou** [dlmanning/gulp-sass#389]
my task

gulp.task('sass', function() {
  gulp.src('src/sass/*.scss')
    .pipe(sourcemaps.init())
    .pipe(sass.sync().on('error', sass.logError))
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('src/css'));
});

run with  a problem

Assertion failed
Program:  jscon.cpp
line:1129
Expression:uft98_validate(str)

**Comment by Keats** [comment]
That's a libsass issue, not a gulp-sass one. Open one there if the issue still happens
