### ISSUE TITLE
The `libsass` binding was not found in

### ISSUE THREAD

**Issue by haydenhancock** [dlmanning/gulp-sass#390]
I am running into this problem. What's interesting is that I don't have an issue running the gulp command in CMD, however, in Visual Studio, I receive the error. My environment is as follows:

OS: Windows 10 x64
IDE: Visual Studio 2015 Professional x64
npm: 2.14.7
node: 4.2.2
gulp: ^3.9.0
gulp-sass: ^2.1.0

I've tried the following things:

1. Updated gulp-sass using the method described [here](https://github.com/dlmanning/gulp-sass/wiki/Update-to-the-latest-Gulp-Sass)
2. Uninstalled gulp and gulp-sass using npm
3. The error suggests running 'npm rebuild node-sass.' When I ran that command it said the 'Binary is fine; exiting.'

Any other suggestions?

**Comment by xzyfer** [comment]
@haydenhancock it's impossible for the same node-sass folder to both say there is no binding, and say the binding is fine.

It sounds like you've mistaken installed node-sass twice, and one is broken. You can confirm this with 

```
npm ls node-sass
```

**Comment by Keats** [comment]
Still not working @haydenhancock ?

**Comment by haydenhancock** [comment]
Sorry for the late reply. I was able to resolve my error by moving the PATH variable higher in priority as found [here](http://blog.boro2g.co.uk/grunt-and-gulp-tasks-in-visual-studio-2015-libsass-error/).

**Comment by Keats** [comment]
cool closing it then, seems like an editor specific issue
