### ISSUE TITLE
Source map `sources` file name incorrect with node-sass 3.4.2

### ISSUE THREAD

**Issue by frio** [dlmanning/gulp-sass#394]
I have a pretty simple gulp task for CSS transpilation:

```javascript
gulp.task('transpile-sass', ['clean', 'lint'], function transpileSass() {
  return gulp.src(SOURCE.scss)
    .pipe(sourcemaps.init())
    .pipe(sass())
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(DEST.scss));
});
```

There's nothing particularly exotic in there.  However, after a recent `npm install` to grab newer versions of my deps, I've noticed that the produced source map has changed.

Instead of the following (prettified):

```json
{
  "version": 3,
  "sources": ["style.scss"],
  ...
}
```

I've been getting:

```json
{
  "version": 3,
  "sources": ["../../../../stdin"],
  ...
}
```

This appears to be related to a change in `node-sass` which I'm tracking down.  There is currently a line in `gulp-sass/index.js`:

```javascript
sassMapFile = sassMap.file.replace('stdout', 'stdin');
```

It appears that in 3.4.2, `node-sass` no longer sets `sassMap.file` to the path `"../../../../stdout"`, but now sets it to `"../../../../stdin.css"`.

I'm just digging through the commits now to find the change that did this, and then I hope to offer a fix (either here or to `node-sass`).

**Comment by frio** [comment]
I'm guessing this was introduced by https://github.com/sass/node-sass/commit/a474102df7cd072ae072ade19635b697346a9663, but `node-sass` 3.4.2 also incorporates `libsass 3.3.2`, so I'm having a quick peek through there.

I'm not sure why this logic exists in `gulp-sass` either -- if it's purely because the filenames are nonsense in our context, then I'll write a failing test and introduce a commit that renames both `stdout` and `stdin.css` to just `stdin` :).

**Comment by michaelfavia** [comment]
Confirming this issue. My gulp instance is running inside of a docker container but i dont think that should matter. Happy to test anything. -mf 

```
gulpfile.js

'use strict';
var gulp = require('gulp');
var sass = require('gulp-sass');
var sourcemaps = require('gulp-sourcemaps');
gulp.task('sass', function () {
  gulp.src('/var/www/sass/**/*.scss')
    .pipe(sourcemaps.init())
    .pipe(sass.sync().on('error', sass.logError))
    .pipe(sourcemaps.write('./maps'))
    .pipe(gulp.dest('./css'));
});
gulp.task('default', ['watch']);
```

```
.map

{"version":3,"sources":["../stdin"],"names":[],"mappings":"AAAA,IAAI
```

**Comment by gonsfx** [comment]
Same here. How can i help? :-/

**Comment by phazei** [comment]
![screenshot from 2015-11-20 03 26 59](https://cloud.githubusercontent.com/assets/431395/11298848/ce603d46-8f36-11e5-86d6-f36c48542754.png)

**Comment by phazei** [comment]
It seems it's trying to set the stream back from ../../../../stdin back to the source filename with new extension.  But it's looking for an indexOf ../../../../stdin.css in the sassMap.sources obj which returns -1 and never properly replaces the index.  This breaks other gulp items that use the stream afterwards because they look for the file in the sources but never finds it because it wasn't replace properly here.  Look at code and debug variables in previous post, it explains it better I think.

**Comment by phazei** [comment]
Also noticed, if you turn sourceComments on then it outputs:

```css
/* line 5, stdin */
html, body {
  height: 100%; }
```

Rather than the actual path to the file

**Comment by cheoAlejo** [comment]
Same here.

**Comment by CarterLi** [comment]
Same here.

**Comment by DJDavid98** [comment]
I'm getting the same issue, this is seriously annoying!

**Comment by callumflack** [comment]
Same here…

**Comment by JvanderHeide** [comment]
Same issue here

**Comment by joevbruno** [comment]
Hey guys, I temporary patched this by manually editing the `index.js` file in my gulp-sass dir in node_modules. It works for me; maybe you will find it useful too. Edit line 93 to this: 

`        // Replace the stdin with the original file name
        // sassMap.sources[sassMap.sources.indexOf(sassMapFile)] = sassFileSrc;

        /** EDITED HERE **/
        var allSources = sassMap.sources.filter(function(src) {
          //if (src.indexOf("stdin") === -1) {
            return src;
          //}
        });

        return Promise.resolve(allSources).then(function(srcs) {
          sassMap.sources = srcs;
          sassMap.sources.push(sassFileSrc);
          // Replace the map file with the original file name (but new extension)
          sassMap.file = gutil.replaceExtension(sassFileSrc, '.css');
          // Apply the map
          applySourceMap(file, sassMap);
        });
         /**END EDITS **/
      }`

**Comment by joevbruno** [comment]
I fixed this temporarily by manually editing the index.js file in my node_modules/gulp-sass dir. Edited line 93. 

        // Replace the stdin with the original file name
        // sassMap.sources[sassMap.sources.indexOf(sassMapFile)] = sassFileSrc;

        // Commented out line 93 and added lines 95 - 103
        // Remove 'stdin' from souces and replace with filenames!
        var srcs = sassMap.sources.filter(function(src) {
          if (src.indexOf("stdin") === -1) {
            return src;
         }
        });
        sassMap.sources = srcs;
        sassMap.sources.unshift(sassFileSrc);

**Comment by Psvensso** [comment]
@joevbruno Works like a charm, thnx for contrib

**Comment by Keats** [comment]
@joevbruno care to submit a PR ?

**Comment by joevbruno** [comment]
@Keats I did submit a PR.

**Comment by asdine** [comment]
Same here.

**Comment by Fuxy22** [comment]
+1 Having the same issue

**Comment by ericwooley** [comment]
@joevbruno are you opening a pull request for it?

**Comment by szupie** [comment]
@ericwooley The fix has already been merged, but it has not been updated on npm.

See https://github.com/dlmanning/gulp-sass/pull/407

**Comment by ericwooley** [comment]
@szupie Any idea when it will be published?

**Comment by xzyfer** [comment]
Sorry I missed this conversation. Released 2.1.1 with @joevbruno patch.

**Comment by Mellbourn** [comment]
After updating to 2.1.1, I get the correct file name. But inside that file, the source map seems to point to the beginning of the outermost block of SASS, not the line relevant to the a specific setting.

**Comment by michaelfavia** [comment]
@Mellbourn We noticed this as well. I think it deserves a follow up issue. Care ot make one and link to here?

**Comment by ericwooley** [comment]
I also noticed this behavior, but I don't have time to make an issue at the moment

**Comment by Mellbourn** [comment]
@michaelfavia  Ok, I have created https://github.com/dlmanning/gulp-sass/issues/415 for the follow up problem of where source maps point to inside the file.

**Comment by LPGhatguy** [comment]
I'm having this issue when it comes to error reporting through the plugin still, but not in the sourcemaps.

Is this a related issue, or perhaps the same issue but in a different part of the codebase?

```
 Error: src\main.scss
Error: Undefined variable: "$red".
        on line 15 of stdin
>>      world: $red;
   --------^
```
