### ISSUE TITLE
install gulp-sass errors with node 0.10

### ISSUE THREAD

**Issue by xinjingfen** [dlmanning/gulp-sass#397]
<pre><code>
gyp ERR! configure error
gyp ERR! stack Error: socket hang up
gyp ERR! stack     at SecurePair.error (tls.js:1010:23)
gyp ERR! stack     at EncryptedStream.CryptoStream._done (tls.js:702:22)
gyp ERR! stack     at CleartextStream.read [as _read] (tls.js:498:24)
gyp ERR! stack     at CleartextStream.Readable.read (_stream_readable.js:340:10)

gyp ERR! stack     at EncryptedStream.onCryptoStreamFinish (tls.js:303:47)
gyp ERR! stack     at EncryptedStream.g (events.js:180:16)
gyp ERR! stack     at EncryptedStream.emit (events.js:117:20)
gyp ERR! stack     at finishMaybe (_stream_writable.js:359:12)
gyp ERR! stack     at endWritable (_stream_writable.js:366:3)
gyp ERR! stack     at EncryptedStream.Writable.end (_stream_writable.js:344:5)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\nodeLearn\\simbajs2\
\simbajs\\node_modules\\simba-command-server\\node_modules\\gulp-sass\\node_modu
les\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose"
"--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\nodeLearn\simbajs2\simbajs\node_modules\simba-command-server\nod
e_modules\gulp-sass\node_modules\node-sass
gyp ERR! node -v v0.10.31
gyp ERR! node-gyp -v v3.1.0
gyp ERR! not ok
Build failed
npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
</code></pre>

**Comment by xzyfer** [comment]
>stack Error: socket hang up

This is a networking error on your machine. Maybe check that your proxy settings (if set) are correct.
