### ISSUE TITLE
Gulp crash due to malloc error

### ISSUE THREAD

**Issue by nastiatikk** [dlmanning/gulp-sass#398]
The source of my issue is that if there is a scss error in the files (missing semicolon, missing closing bracket, typo in the variable name, commented out variable, etc.) it aborts `gulp` that is run with `npm start`
```
gulp(5254,0x1038eb000) malloc: *** error for object 0x1020f4ecc: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

I see there are similar issues https://github.com/dlmanning/gulp-sass/issues/104 and https://github.com/sass/node-sass/issues/554 and https://github.com/dlmanning/gulp-sass/issues/155

I'm using
`"gulp-sass": "^2.1.0",`
`npm 3.3.6`
`node v5.0.0`

```
import gulp from 'gulp';
import sass from 'gulp-sass';
import sourceMaps from 'gulp-sourcemaps';
import postcss from 'gulp-postcss';
import autoprefixer from 'autoprefixer';
import gulpIf from 'gulp-if';
import csso from 'gulp-csso';
import handleErrors from '../lib/handle-errors';
import plumber from 'gulp-plumber';
import * as config from '../config';

export default function sassTask() {
    return gulp.src(config.sass.src)
        .pipe((plumber({ errorHandler: handleErrors })))
        .pipe(sourceMaps.init())
        .pipe(

            // Handle sass errors specifically
            sass(config.sass.sassConfig)
                .on('error', sass.logError)
        )
        .pipe(postcss([
            autoprefixer({
                browsers: ['last 3 versions']
            })
        ]))
        .pipe(gulpIf(!global.isWatching, csso()))
        .pipe(sourceMaps.write('./'))
        .pipe(gulp.dest(config.sass.dest));
}

gulp.task('sass', sassTask);
```

**Comment by nastiatikk** [comment]
@bassettsj

**Comment by xzyfer** [comment]
Malloc errors are an issue with LibSass. Without the Sass file that caused the issue there is nothing we can do.

**Comment by xzyfer** [comment]
If you still have a Sass file that reproduce this error please post it and we'll reopen the issue.

**Comment by nastiatikk** [comment]
Since this issue is duplicated in node-sass repo, here is a comment there with the files. And we could keep discussion in 1 place.
https://github.com/sass/node-sass/issues/1281#issuecomment-160247438
