### ISSUE TITLE
Output filename with error

### ISSUE THREAD

**Issue by scriby** [dlmanning/gulp-sass#40]
When I run gulp-sass, it does not include the file name of the file that failed compilation:

```
[gulp] Error in plugin 'gulp-sass': source string:1: error: invalid top-level expression
```

How can I tell which file that error occurred in?

Here is my gulp task:

```javascript
var sass = require('gulp-sass');
  gulp.src('./**/!(_)*.scss')
  .pipe(sass({ outputStyle: 'compressed' }))
  .pipe(gulp.dest('.'));
```

**Comment by Rowno** [comment]
:+1: `errLogToConsole: true` should output a filename for top level source file errors.

**Comment by unionx** [comment]
Same error here. It's the extension name that caused the problem.

So what if I want to write sass instead of scss?

**Comment by brettwise** [comment]
I received this error.

```
[gulp-sass] invalid top-level expression on line 1 in /src/sass/vendor/foundation/scss/foundation.scss
```

Seems to related to gulp-sass choking on this:

@charset "UTF-8";
 
Once I commented it out all was well.

**Comment by Snugug** [comment]
This has been [resolved in 2.x](https://github.com/dlmanning/gulp-sass/blob/2.x/index.js#L60-L71). Please try it and report back:

```
npm install dlmanning/gulp-sass#2.x
```

**Comment by Snugug** [comment]
As it's been a month, I'm closing this.

**Comment by num13ru** [comment]
The same problem under windows 8.1 x64

```
Error: ←[4msrc\style\main.scss←[24m
←[90m  129:2←[39m  invalid top-level expression
```

gulp-sass: 2.0.0-alpha.1
node-sass: 3.0.0-beta.7
libsass: 3.2.0-beta.6
Windows 8.1

main.scss
```
$small: 320px;
$large: 1024px;

@mixin respond-to($media) {
  @if $media == handhelds {
    @media only screen and (max-width: $small) { @content; }
  }
  @else if $media == medium-screens {
    @media only screen and (min-width: $small + 1) and (max-width: $large - 1) { @content; }
  }
  @else if $media == wide-screens {
    @media only screen and (min-width: $large) { @content; }
  }
}

header {
  @include respond-to(handhelds) {
    background-color: red;
  }
  @include respond-to(medium-screens) {
    background-color: blue;
  }
  @include respond-to(wide-screens) {
    background-color: green;
  }
}​
```
