### ISSUE TITLE
Bus error (core dumped)

### ISSUE THREAD

**Issue by eyakcn** [dlmanning/gulp-sass#401]
I was running a Jenkins in docker container, and when the job execute gulp-sass task, it fails.

The error message:
Bus error (core dumped)

The gulp file options:
  var sassOptions = {
    style: 'expanded'
  };

Dependencies:
gulp-sass: v2.0.4
guilp: v3.9.0
npm: v3.3.12
node: v5.1.0
Compass 1.0.3 (Polaris)

**Comment by xzyfer** [comment]
Please provide the **smallest** possible Sass file that still causes this issue. Do not include frameworks.

**Comment by eyakcn** [comment]
It has nothing to do with the sass file, because I can run the gulp task of sass only my local machine without any problem.

I think maybe it's due to "running gulp sass task inside a docker container"

**Comment by xzyfer** [comment]
Bus error is an issue with LibSass resulting from your Sass. It's like due to an invalid memory access which is why it doesn't happen on your host system.

>Please provide the **smallest** possible Sass file that still causes this issue. Do not include frameworks.

**Comment by eyakcn** [comment]
Thank you for your reply.

So how can I get more debug info about this problem? Any suggestions?

**Comment by xzyfer** [comment]
The only way to debug this kind of issue is to comment out sections of code until you the error no longer occurs. When the error stops the problematic code was in code commented out. Uncomment that and comment out other code. Keep doing this until you end up with the smallest amount of code required to make the bug happen.

**Comment by eyakcn** [comment]
Wow... 

So currently there are no other people report this problem?
Have you tried to run some gulp sass task inside a docker container? Maybe you can reproduce the same error, too.

My docker container was build on top of ubuntu:14.04

**Comment by xzyfer** [comment]
It'll be specific to the code you're running. I don't a docker environment
nor the time to set one up. I use docker with gulp-sass at work without any
issues.

**Comment by eyakcn** [comment]
OK, thank you anyway, I will see what I can do myself

**Comment by eyakcn** [comment]
@xzyfer I think maybe I found the problem, it seems that the 'node-sass' is not correctly installed. 
It's really confusing, because I can run 'npm install' without any problem, but can not pass 'npm install node-sass'

Here is the issue if you want to know.

https://github.com/sass/node-sass/issues/1290

**Comment by eyakcn** [comment]
Here is another link maybe related to my issue:
http://stackoverflow.com/questions/30384085/node-sass-error-try-reinstalling

It says at the bottom:

"
I ran into basically the same error on Debian Linux with gulp-sass(basically same thing as grunt-sass but for gulp... both are just wrappers for the respective tool around node-sass which is a nodejs port of the actual SASS compiler libsass).

The node-sass project mentions in their README.md that only binaries for "popular platforms"(apparently Windows/Mac) are included and you may need to build for other platforms.
"

But I don't understand why 'npm install gulp-sass' is not enough? Why should this guy need to install & build node-sass by himself?

**Comment by eyakcn** [comment]
Since this issue has been solved, I close it directly.

**Comment by roymj88** [comment]
@eyakcn  How did you solve this?

**Comment by eyakcn** [comment]
@roymj88 It's here: https://github.com/sass/node-sass/issues/1290

I run the command `npm install node-sass` for another try, and it works.

**Comment by ayalma** [comment]
Hello , I faced with same error , i already tried  @eyakcn  npm install node-sass . but problem steal are there

**Comment by knibals** [comment]
Resolved by installing Libsass `apt-get install libsass0 libsass-dev` (i'm on Ubuntu).

**Comment by eyakcn** [comment]
@ayalma I have no clear answer, [node-sass/issues/1290](https://github.com/sass/node-sass/issues/1290) remind me that I just succeed running `npm install node-sass` for the second time... lucky

Maybe you should try the way @knibals suggests.

**Comment by mpesterev** [comment]
try this - `gulp.task('watch', function(event) {
  gulp.watch(['/rd/rd/www/css/sass/*.scss', '/rd/rd/www/css/sass/assets/*.scss'], function() {
        setTimeout(function () {
            gulp.start('bamCss');
        }, 3000);
    });
});` for me timeout help.

**Comment by munsifmulla** [comment]
Try updating your Nodejs Version and rebuild node-sass. that helped me in my case.

**Comment by coderade** [comment]
The same error occurred with me when I tried to install the `gulp-sass` and the **ESOCKETTIMEDOUT** error with the download of the "https://github.com/sass/node-sass/releases/download/v4.5.2/linux-x64-48_binding.node" occurred on the `arch-linux`.

![screenshot_20170401_193955](https://cloud.githubusercontent.com/assets/9141708/24583002/8d609744-1713-11e7-8803-ea0953f0793d.png)

I think that is something related with a glitch on my internet connection at that time. 

After I tried to install again, everything worked properly.

**Comment by dumptyd** [comment]
ran into this issue. tried running `yarn install` again, everything went fine but I was still getting core dumped. Reinstalling gulp-sass from npm worked.
