### ISSUE TITLE
Bourbon _background mixin compile issue

### ISSUE THREAD

**Issue by ZonderKill** [dlmanning/gulp-sass#402]
Hello everyone,

I'm using Bourbon sass mixin libs in my project and stucked with an issue.
There is _background mixin in Bourbon which helps to create complex backgrounds with images, gradients etc. It takes a list of backgrounds as an argument and loop them with `@each` sass control directive. I noticed that if an item of this list have spaces for example `center no-repeat $bg-color-1 scroll`, and I compile scss with gulp-sass, there will be only the first word in item value in the `@each` loop, for given example it will be `center`. Also with gulp-ruby-sass plugin it works fine, there is no such issue.

Example from my code:
````
//Source Scss
@include background(url("https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/textures/inverted/#{nth($texture-list, $texture-number)}"), center no-repeat $bg-color-1 scroll);
````
````
//Compiled css with gulp-sass
background: url("https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/textures/inverted/texturetastic_gray.png"), center;
````
````
//Compiled css with gulp-ruby-sass (correct css)
background: url("https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/textures/inverted/texturetastic_gray.png"), center no-repeat rgba(230, 113, 236, 0.15) scroll;
````

**Comment by Keats** [comment]
Open an issue on libsass, that's not a gulp-sass issue

**Comment by xzyfer** [comment]
This is known issue https://github.com/sass/libsass/issues/1645
