### ISSUE TITLE
Use of consecutive brackets and commas causing issues in version 2.1.0 but not 2.0.4

### ISSUE THREAD

**Issue by ryandowd** [dlmanning/gulp-sass#406]
#After updating to 2.1.0 the following would not work:

```css
.class-name {
       &:nth-of-type(1),
       &:nth-of-type(3) {
        // styles
      }
}
```

By 'not work' I mean, it was outputting for the first line "nth-of-type(1)" but not the second.

#Also, the following variation would cancel out both:

```css
.class-name {
       &:nth-of-type(1), &:nth-of-type(3) {
        // styles
      }
}
```

#Only this worked:

```css
.class-name {
       &:nth-of-type(1) {
        // styles
       }

      &:nth-of-type(3) {
        // styles
      }
}
```

Oddly, no errors were thrown during any of these variations in the scss and the compiler did its thing without issue. Also there were other instances of a consecutive bracket and comma and they were outputting as expected.

**Comment by Keats** [comment]
That's not a gulp-sass issue, sounds like a libsass issue
