### ISSUE TITLE
Plugin only reports one error at a time

### ISSUE THREAD

**Issue by scriby** [dlmanning/gulp-sass#41]
It would be nice if the plugin would report errors found in all scss files instead of just the first. Some other plugins I use (gulp-tsc & gulp-tslint) work this way.

**Comment by Keats** [comment]
If you look at https://github.com/dlmanning/gulp-sass/blob/2.x/index.js#L112 you can see that it's actually node-sass (or maybe libsass, haven't checked) that only gives one error at a time.
gulp-sass (at least v2) display all the errors it gets

**Comment by Snugug** [comment]
@Keats is right, it's Libsass, and unfortunately there's nothing we can do about it. The way compiling works is that, if it runs into an error, it throws that error and stops trying to compile, therefore only one error can be thrown at a time.

If you're looking for static code analysis to catch mistakes, you can check out [scss-lint](https://github.com/brigade/scss-lint), but that requires Ruby. We're working on a [node only Sass Lint](https://github.com/sasstools/sass-lint), but it's still a few months off.
