### ISSUE TITLE
includePaths don't work, and on each task perfomance exit code is 0

### ISSUE THREAD

**Issue by asolopovas** [dlmanning/gulp-sass#411]
Hi, 

includePaths seems to be ignored, and even on simple task sass returns exit code 0. 

This is my task

var app        = {

```
fwrk: {
    app : "assets/src/framework",
    scss: "assets/src/framework/scss",
    js  : "assets/src/framework/js"
},
dest: {
    js : "assets/js",
    css: "assets/css"
},
src : {
    js  : "assets/src/js",
    scss: "assets/src/scss",
    ts  : "assets/src/ts"
}
```

};

gulp.task( 'sass:app', function () {

```
gulp.src( app.src.scss + '/app.scss' )
    .pipe( sourcemaps.init() )
    .pipe( sass( {
            includePaths: require('node-bourbon' ).includePaths,
            outputStyle : 'expanded',
        } ).on( 'error', handleError )
    )
    .pipe( sourcemaps.write() )
    .pipe( gulp.dest( app.dest.css ) );
```

} );

I am using Windows 7, node v5.1.1,      "gulp": "^3.9.0",       "gulp-sass": "^2.1.0",         "node-bourbon": "^4.2.3",

**Comment by artemsky** [comment]
Look documentation. `includePaths` is an array
you should use `includePaths: [require('node-bourbon' ).includePaths]` instead
