### ISSUE TITLE
Source maps point to the wrong line

### ISSUE THREAD

**Issue by Mellbourn** [dlmanning/gulp-sass#415]
We first had problems with source maps pointing to `stdin` instead of the correct file, outlined in https://github.com/dlmanning/gulp-sass/issues/394.

To fix this, we updated to 2.1.1 (as recommended). We then get the correct file name.

But inside that file, the source map seems to point to the beginning of the outermost block of SASS, not the line relevant to the a specific setting.

Example:
In Google Chrome Developer Tools Style tab, if I here click the file name `ag-theme-pp.scss`
![chromestylestab](https://cloud.githubusercontent.com/assets/1785727/11806380/e64b97f8-a312-11e5-9cd6-884fd8fe24b0.PNG)
It will take me to the correct file, but at the start of the `ag-pp` class, not the `border-right-width`
![chromesassview](https://cloud.githubusercontent.com/assets/1785727/11806397/045629fc-a313-11e5-8024-52d61ae1fa09.PNG)

**Comment by michaelfavia** [comment]
Just wanted to confirm the issue on the current version. Thanks for the great report.

**Comment by phazei** [comment]
I've seen this as well

**Comment by DJDavid98** [comment]
Can confirm, still an issue.

**Comment by thekip** [comment]
same issue

**Comment by ashleyconnor** [comment]
`@import` statements appear to resolve to the correct line but my entry `scss` file (`main.scss`) is reported as `stdin`.

**Comment by neojp** [comment]
This seems to have been fixed by https://github.com/sass/node-sass/issues/1206. But `gulp-sass` doesn't get the correct nested selectors source map.

**Comment by xzyfer** [comment]
Unfortunately this issue an issue with how browser naively handle source maps and is largely out of our control. We have made comprises in LibSass to help Chrome be better but there isn't much else we can do.

We're happy to look very specific isolated cases where you think sourcemaps could better. If the use case is justified but differs from the official Sass compiler we'll open an issue with them.

**Comment by cyphix333** [comment]
I've noticed this too and it's rather annoying. :( No work arounds for this?

**Comment by ashleyconnor** [comment]
@cyphix333 - See my comment above.

**Comment by cyphix333** [comment]
@ashleyconnor Hmmm..... I'll give it a try, thanks!

**Comment by cyphix333** [comment]
@ashleyconnor That didn't seem to work for me.

**Comment by ashleyconnor** [comment]
Works for me - I've create a sample repo to demo it here

[https://github.com/ashleyconnor/sourcemaps-example](https://github.com/ashleyconnor/sourcemaps-example)
