### ISSUE TITLE
Unable to import partial

### ISSUE THREAD

**Issue by andrewjmead** [dlmanning/gulp-sass#419]
I didn't want to create this, but the related issues/solutions did not work for me. I've worked through the common docs, deleted the gulp-sass folder, and also used the auto_save property though I'm not on windows.

No matter what I do, I can't import a partial. I've uploaded a completed zip so you can test with the same source code [(Download Zip)](http://files.mead.io/0c1z0k3X3H3e). I pulled out all other plugins to isolate the issue. If you run `gulp sass`, you'll see the error (I hope!).

The error is as follows:

```
Andrew:~/Desktop/gulp-sass-example$ gulp sass
[22:02:36] Using gulpfile ~/Desktop/gulp-sass-example/gulpfile.js
[22:02:36] Starting 'sass'...
[22:02:36] Finished 'sass' after 14 ms

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: public/scss/styles.scss
Error: File to import not found or unreadable: pages/home
       Parent style sheet: stdin
        on line 1 of stdin
>> @import "pages/home";
   ^

    at options.error (/Users/Andrew/Desktop/gulp-sass-example/node_modules/node-sass/lib/index.js:277:32)
```

Any help would be amazing.

\- Andrew

**Comment by Keats** [comment]
You are importing `@import "pages/home";` however the filename of your partial is `_home.css.scss` so you have 2 options:

- rename the file to `_home.scss` 
- change the import to `@import "pages/home.css";`

First solution is preferred, no need for a css suffix in the filename imo

**Comment by andrewjmead** [comment]
Haha, I knew it was something I missed. I usually left off the css suffix, but started using it after working with Rails. 

Thanks @Keats!
