### ISSUE TITLE
Invalid css output after running gulp sass for variables with escaped unicode

### ISSUE THREAD

**Issue by marekstabla** [dlmanning/gulp-sass#421]
So I'm using scss files from ionic lib to compile them using gulp-sass task with my project files.
The result is that compiled output for ionicons is invalid.

```
.ion-android-bulb:before {
  content: ""; }

.ion-android-bus:before {
  content: ""; }

.ion-android-calendar:before {
  content: ""; }

.ion-android-call:before {
  content: ""; }
```

I've also pulled newest ionic source files from github and running npm install, installing global gulp and then running gulp sass tasks ends up the same (creating invalid css file in dist folder).

Looking at ionic files, variables are defined like this:
```
$ionicon-var-alert: "\f101";
$ionicon-var-alert-circled: "\f100";
$ionicon-var-android-add: "\f2c7";
$ionicon-var-android-add-circle: "\f359";
$ionicon-var-android-alarm-clock: "\f35a";
$ionicon-var-android-alert: "\f35b";
```

Node 5.3
Gulp-sass 2.1.1

Tried on several machines, osx/windows

It was fine on gulp-sass 1.3.3. After upgrading to 2.1.1 (libsass error) task is working but the output is incorrect.

edit
It's still valid output. Unicode is replaced with symbol invisible for current font.

**Comment by cliffmullis** [comment]
So how did you resolve this? I am having this same problem in the build script for ionicons.

**Comment by marekstabla** [comment]
It's still valid output. Unicode is replaced with symbol invisible for current font (in IDE) but it's still valid.
