### ISSUE TITLE
Include all Sub-directories

### ISSUE THREAD

**Issue by Knight-Yoshi** [dlmanning/gulp-sass#423]
How would I include all sub-directories of a directory in the includePaths property without explicitly listing each one, if that's possible? I have `assets/vendor/zurb/f6/scss` and I can impourt the foundation file fine from that directory, but I can't include the settings file `assets/vendor/zurb/f6/scss/settings/settings.scss`. I have tried  `assets/vendor/zurb/f6/scss/*` and `assets/vendor/zurb/f6/scss/**`, but no luck.

**Comment by Keats** [comment]
There's no globbing in sass because the order of the import matters: https://github.com/sass/libsass/issues/156

**Comment by Knight-Yoshi** [comment]
I was afraid of that. Eh.
