### ISSUE TITLE
Race Condition

### ISSUE THREAD

**Issue by strawlion** [dlmanning/gulp-sass#425]
Hey all, I'm encountering a race condition when compiling my sass.

As you can see, the first run works correctly, but the second fails to find a mixin (which should be available)
![image](https://cloud.githubusercontent.com/assets/3640788/12134134/32c39200-b3e1-11e5-8f46-20b8aa6df1c7.png)

The gulp code itself is straightforward
![image](https://cloud.githubusercontent.com/assets/3640788/12134158/6e6b33da-b3e1-11e5-9d4c-18e2348378a4.png)

Node: v5.2.0
Gulp: v4.0.0-alpha2
gulp-sass: v2.1.1
node-sass: v3.4.2

It's failing about 50% of the time. Any ideas?

**Comment by strawlion** [comment]
This error doesn't occur in grunt-sass

**Comment by strawlion** [comment]
Hello?

**Comment by tuelsch** [comment]
#426 may be related to this issue.

**Comment by crdelapazz** [comment]
+1

**Comment by xzyfer** [comment]
Unfortunately this issue an issue with `gulp.watch` and is out of our control. In my experience the issue get's better if you watch less files i.e. exclude `bower_components` and `node_modules`.
