### ISSUE TITLE
Unhandled error when saving .sass

### ISSUE THREAD

**Issue by kev200** [dlmanning/gulp-sass#426]
Hey i would really need help here because i'm new to this stuff. 

Problem : I start gulp and start editing my sass that is included in the main.sass , whenever i save for like 2 times the site crashes and i get error , while saving the main.sass doesn't give off error.
Tried copying all the content of the problematic .sass file to the main.sass and it works , but that means i can never include any other .sass files?

Error looks like this : 

events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: assets\css\main.sass
Error: File to import not found or unreadable: 3-layouts/home
       Parent style sheet: stdin
        on line 5 of stdin
>> @import "3-layouts/home";
   ^

    at options.error (C:\wamp\www\****\****\node_modules\node-sass\lib\index.js:277:32)

Thank you very much!

**Comment by name-k** [comment]
I have the same problem for a long time. As a temporary workaround you can wrap watcher with setTimeout function.

In addition I can say that when you change included file - there is a bug, but when you save main.scss which includes all other stuff - it works fine. Error is thrown not all the time, but quite often, 50/50 I would save.

**Comment by tuelsch** [comment]
I had the same issue and found it could be a race condition when  a glob of multiple entry files with references to the same file (e.g. variables.scss) is passed to `gulp.src("src/sass/*.scss")`. It seems that both bundles get compiled at the same time, therefore node-sass is trying to read `src/sass/shared/variables.scss` at the same time, making it inaccessible for the second hit.

To reproducec the issue, try creating 3 or more entry files with `@import` statements referencing a shared file.

**Comment by dariakuznetsova** [comment]
> To reproducec the issue, try creating 3 or more entry files with @import statements referencing a shared file.

tuelsch, did this help you?

**Comment by tuelsch** [comment]
Did what help me? Has there been an update regarding this issue?

**Comment by xzyfer** [comment]
Unfortunately this issue an issue with `gulp.watch` and is out of our control. In my experience the issue get's better if you watch less files i.e. exclude `bower_components` and `node_modules`.
