### ISSUE TITLE
Error when escaping liquid

### ISSUE THREAD

**Issue by goldsteinr** [dlmanning/gulp-sass#429]
I'm trying to escape liquid syntax with interpolate (#{' '}) but i'm getting this error:
```javascript
[22:07:05] Starting 'scss'...
[22:07:05] Finished 'scss' after 9.77 ms
[22:07:05] [gulp-sass] stylesheets/main.css
  527:10  Invalid CSS after "  color: {": expected "}", was "ttings.color-te..."
```
When i remove all the liquid syntax from the code, the task runs perfectly.  This is the scss task:
```javascript
var gulp = require('gulp');
var watch = require('gulp-watch');
var sass = require('gulp-sass');
var cssnano = require('gulp-cssnano');
var rename = require("gulp-rename");
var autoprefixer = require('gulp-autoprefixer');
var sourcemaps = require('gulp-sourcemaps');
gulp.task('scss', function() {
    gulp.src('stylesheets/*.scss')
    	.pipe(sass({ includePaths : ['./stylesheets/**/*.scss'] }))
        .pipe(sass().on('error', sass.logError))
        .pipe(sourcemaps.init())
        .pipe(autoprefixer({
          browsers: ['last 2 versions'],
          cascade: false
        }))
        .pipe(cssnano())
        .pipe(rename({ suffix: '.min.css', extname: '.liquid' }))
        .pipe(gulp.dest('./assets'));
});
gulp.task('watch', function() {
    gulp.watch('stylesheets/**/*.scss', ['scss']);
});
```

If i remove this part >

```javascript

  .pipe(sass().on('error', sass.logError))
        .pipe(sourcemaps.init())
        .pipe(autoprefixer({
          browsers: ['last 2 versions'],
          cascade: false
        }))
        .pipe(cssnano())

```

the task runs fine, but with problems to upload to shopify... I`m using shopify-upload in another task too.

**Comment by xzyfer** [comment]
Please provide a sample snippet of scss code that produces error.

**Comment by goldsteinr** [comment]
Every part with liquid and interpolation. Example:

```
body {
    color: #{' {{settings.color-text}}  '} ;
} 
```

**Comment by illarionvk** [comment]
This is an issue with Autoprefixer, not Sass. Autoprefixer parses CSS code Sass outputs and expects legitimate CSS values in order to do its magic.

I'd recommend to move all CSS declarations with Liquid variables to a separate file, use [gulp-filter](https://github.com/sindresorhus/gulp-filter) to run Autoprefixer only on a subset of files that do not contain Liquid and then [concat the files into one](https://github.com/contra/gulp-concat).

As an alternative, you could [disable Autoprefixer for individual CSS rules](https://github.com/postcss/autoprefixer#disabling) by adding `/* autoprefixer off */` inside the rule.

**Comment by goldsteinr** [comment]
I removed the autoprefixer pipe, concat all files into one and the error still continues...

```javascript
[10:20:47] Starting 'scss'...
Container#eachInside is deprecated. Use Container#walk instead.

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: all.css:1414:28: Unknown word
.divider {
  border-top: 1px solid {{ settings.color-border }}; }
                                           ^
```

It seems the error is in the CSS, dont know why. Maybe cssnano.

**Comment by illarionvk** [comment]
Yes, cssnano is built on top of PostCSS like Autoprefixer so it may throw the same error.

**Comment by xzyfer** [comment]
>Every part with liquid and interpolation.

In future it's worth not assuming everyone is using or familiar with the tools you're using. Provide as much context as possible to help people help you :)

**Comment by xzyfer** [comment]
I can confirm the following compiles with recent version of gulp-sass
```sass
body {
    color: #{' {{settings.color-text}}  '} ;
}
```
```css
body {
  color:  {{settings.color-text}}  ; }
```

**Comment by goldsteinr** [comment]
the error is in cssnano and autoprefixer. They can't compile with liquid statements inside the css. Thanks, guys.
