### ISSUE TITLE
Output filename

### ISSUE THREAD

**Issue by BenRacicot** [dlmanning/gulp-sass#430]
Sorry if this is super basic but renaming the output path does not change the output filename:

```javascript
gulp.task('ums-sass', function () {
  gulp.src('wp-content/themes/util/library/demo/scss/style.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(gulp.dest('wp-content/themes/util/library/demo/css/demo.css'))
});
```
Can I get an example to see how to change output filenames? maybe the solution could make the readme in the future? Thanks.

**Comment by mattidupre** [comment]
To answer your question, you want [gulp-rename](https://www.npmjs.com/package/gulp-rename)
```javascript
      var gulpRename = require('gulp-rename');
      
      gulp.task('ums-sass', function () {
        gulp.src('wp-content/themes/util/library/demo/scss/style.scss')
          .pipe(sass().on('error', sass.logError))
          .pipe(gulpRename({ basename: 'demo' }))
          .pipe(gulp.dest('wp-content/themes/util/library/demo/css'))
      });
```

No sense in adding this to the gulp-sass docs since it's a general gulp issue. Lots of documentation out there. :)

**Comment by Keats** [comment]
What @mattidupre said.

**Comment by ramswaroop** [comment]
@BenRacicot just to add, `gulp.dest()` works with folder and not files. So whatever argument you pass to it, will become a folder.
