### ISSUE TITLE
Bug on source comments relative paths

### ISSUE THREAD

**Issue by kiokotzu** [dlmanning/gulp-sass#433]
I`m using gulp-sass v2.1.1, and the paths of the source .sass file show a absolute path, this is the gulp task

`gulp.task('sass', function () {

  gulp.src(app.sass)
    .pipe(sass({
      indentedSyntax: true,
      outputStyle: 'expanded',
      sourceComments: true
    })
    .pipe(gulp.dest(dist.css))
});`
this is the type of commet that shows

`/* line 113, /Users/estebanvera/Documents/Sites/project/profiles/themes/custom/project_theme/sass/pages/_home.sass */`

and I want a path relative to the css output file
`../sass/pages/_home.sass`

How can i achive this.

Thanks.

**Comment by xzyfer** [comment]
This is a bug in LibSass. I've created https://github.com/sass/libsass/issues/1898 to track it there.
There's not gulp-sass can do. You can work around this by running a string replace over the file after compilation.
