### ISSUE TITLE
node-sass 3.5.0 beta

### ISSUE THREAD

**Issue by btwolfe79** [dlmanning/gulp-sass#435]
Any chance we could consider a pre-release version/tag that uses the big node-sass/libsass upgrade:
https://github.com/sass/node-sass/releases/tag/v3.5.0-beta.1   ?

It would be great if the gulp-sass community could start testing the big changes in the beta.  Not sure how much work it would be to update the dependencies and flag a pre-release.

Thanks so much.

**Comment by xzyfer** [comment]
We already have this.

npm install node-sass@beta

**Comment by xzyfer** [comment]
Apologies I misread the which repository this was. We'll release a beta soon.

**Comment by xzyfer** [comment]
v2.3.1 has been release with node-sass@v3.7.0.
