### ISSUE TITLE
Cannot compile imports - Error in plugin 'sass'

### ISSUE THREAD

**Issue by lindeberg** [dlmanning/gulp-sass#438]
**Software:**

- Node: v4.2.6 (x64)
- npm: latest, I think, I downloaded it today ^^
- Gulp: 3.9.0
- gulp-sass: 2.2.0
- OS: Windows 7
- IDE: Visual Studio 2015 (Web Essentials 2015)

It compiles properly when I have basic sass like this:
https://i.gyazo.com/e5f30a66e6cfe23466d3416fab7805a9.png

But when I try to compile with the partials imported I get an error:
https://i.gyazo.com/d5fdc3e2ffc0df588ecd7586c479463e.png

```
Starting 'sass-compile'...
Error in plugin 'sass'
Message: 
    Content/Styles/application.scss
undefined
Finished 'sass-compile' 
Process terminated with code 0.
```

I've tried importing just one of the partials, with very clean, basic sass inside, and everything, but I still get the error.

I'm very new to node and task managers. I probably haven't given you enough of information, please tell me what you need to know! I hope you do not hate me because I'm just providing you with images - but I am not at the office right now and I can't get this problem out of my mind. Sorry!

**Comment by Radau** [comment]
Issue is not present for me with the following settings (slightly outdated compared to yours).

Node: 4.0.0
npm: 2.14.2
Gulp: 3.9.0
gulp-sass: 2.1.1
OS: Mac OS X 10.11
Running gulp from Terminal

I'll try a pass running the same setup as you (only on linux) via docker shortly here and report back.

**Comment by Radau** [comment]
Running pretty similar to you [here](http://i.imgur.com/iBpf5gW.png) on a different platform and my demo (using your gulpfile, slightly different directory structure).

If you want to link to a repo with a setup that is failing on your end I can give it a try, may need someone running windows to give it a try too though.

**Comment by LetSevI** [comment]
I faced similar problem ([image](http://s018.radikal.ru/i524/1602/c3/9163f50a72f9.png)) when the project folder was located:
`C:\Users\Евгений\Desktop\template`
I solved the problem by moving the folder `template` to the **root of drive C**.

**Software:**
- Windows 10 (x64)
- Node: 5.5.0 Stable (x64)
- Gulp: 3.9.0
- gulp-sass: 2.2.0

**Comment by xzyfer** [comment]
There is a known issue with LibSass and directories with Cyrillic characters. This may also apply to other non-ascii characters. Please try the gulp-sass beta for the patch.

```
npm install gulp-sass@beta
```

**Comment by agustin107** [comment]
Try to replace on package.json of gulp-sass, instead of
`"node-sass": "^3.4.2"`
with
`"node-sass": "^3.5.0-beta.1"`

This worked for me :+1:

**Comment by LetSevI** [comment]
@xzyfer, yes, it solved the problem for me.

**Comment by dhust** [comment]
Followed the instructions on this page and it solved my issue.
https://github.com/dlmanning/gulp-sass/wiki/Update-to-the-latest-Gulp-Sass

**Comment by KrunalDatascience** [comment]
Hey, I am getting same error when i am trying to customize an online open source [template](https://github.com/creativetimofficial/argon-design-system). After extracting the .zip file from above location I am running following sets of command in command prompt. Note - node.js is already installed in my system.

```
npm install -g gulp //installing gulp globally
npm init //initialization 
npm install --save-dev gulp //installing gulp locally - dev utility

npm install -g npm-install-all 
npm-install-all gulpfile.js //Installing all required modules from gulpfile.js 
```
After preparing my env. when i run the gulp task defined in the gulpfile.js using following code, it throws the mentioned error:

```
C:\Users\my_user\Documents\my_project>gulp build
[18:42:36] Using gulpfile ~\Documents\my_project\gulpfile.js
[18:42:36] Starting 'build'...
[18:42:36] Starting 'clean:dist'...
[18:42:36] Finished 'clean:dist' after 4.27 ms
[18:42:36] Starting 'scss'...
Error in plugin 'sass'
Message:
    assets\scss\custom\_mixins.scss
Error: File to import not found or unreadable: custom/mixins/alert.scss.
        on line 1 of assets/scss/custom/_mixins.scss
        from line 28 of assets/scss/argon.scss
>> @import "custom/mixins/alert.scss";

   ^

[18:42:37] Finished 'scss' after 805 ms
[18:42:37] Starting 'copy:css'...
[18:42:37] Finished 'copy:css' after 33 ms
[18:42:37] Starting 'copy:js'...
[18:42:37] Finished 'copy:js' after 11 ms
[18:42:37] Starting 'minify:js'...
[18:42:37] Finished 'minify:js' after 128 ms
[18:42:37] Starting 'minify:css'...
[18:42:38] Finished 'minify:css' after 992 ms
[18:42:38] Finished 'build' after 2 s
```
The content of all the file is unchanged and is the same as the git repo. So, incase if one wants to refer, one can check the link attached earlier.

I am using a windows-10 machine with:

```
>npm -v
6.4.1

>node -v
v8.12.0

>gulp -v
[19:04:01] CLI version 3.9.1
[19:04:01] Local version 3.9.1
```
