### ISSUE TITLE
Permit usage of data option

### ISSUE THREAD

**Issue by D34THWINGS** [dlmanning/gulp-sass#439]
`gulp-sass` completely overrides the `data` option of `node-sass` whereas you can concatenate it with the file content. This is frustrating since I want to set different variables for different builds, eg changing color palette by setting an env variable. With `node-sass` i would do:
```js
import sass from 'node-sass';

sass.render({
  file: 'entry.scss',
  data: `$some-color: ${process.env.BRAND === 'a-brand' ? '#fff' : '#000'}`
});
```
Can you please add the support for data option ?

**Comment by xzyfer** [comment]
We have discussed at length why we don't allow this in https://github.com/dlmanning/gulp-sass/issues/302. We're yet to be convinced there's a real world use case for this that can't better be solved with existing, portable, solutions.

**Comment by D34THWINGS** [comment]
Thank you for your reactivity and I apologize for the duplication. Is it possible nonetheless to add a warning or a field in the documentation that says the `data` field isn't supported, because I struggled 30min searching why my option wasn't took in account, everything vanishing for no reason and i had to go into your code to see what's happening. Also you mension in the docs that we can you use the options as in `node-sass` but that's not true at all since your code has much side-effects on the configuration and many fields are overridden without taking any account of what was previously given. I think you should explicitly tell which options we can use or produce code with less side effect on configuration.

Best regards
