### ISSUE TITLE
gulp-sass not using globally install node modules

### ISSUE THREAD

**Issue by jaredmorrow** [dlmanning/gulp-sass#442]
First off, I've searched through similar problems in the issues list, and I really hesitated to create a new issue, but every solution I tried did not work.  I am trying to install gulp-sass on a SmartOS machine, and the way in which it is trying to install node-sass is not working (since there is no node-sass package for sunos).  

I have looked at https://github.com/dlmanning/gulp-sass/wiki/Update-to-the-latest-Gulp-Sass and all related docs.  Usually the issue is node-sass or libsass not getting installed properly, but I've already fought that issue https://github.com/sass/libsass/pull/1782

With that said, here's my info

```
# npm -v
3.6.0
# node -v
v5.6.0
# npm config get prefix
/opt/local
# npm list -g --depth=0
/opt/local/lib
├── bower@1.7.7
├── gulp@3.9.1
├── jshint@2.9.1
├── marked@0.3.5
├── node-gyp@3.3.0
├── node-sass@3.4.2
└── npm@3.6.0
```

As you can see, node-sass is indeed installed globally.

Here is gulp-sass still trying to install it the usual way

```

# npm install gulp-sass
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash.padleft@3.1.1: This package has been renamed. Use lodash.padstart@^4.0.0.
npm WARN deprecated lodash.padright@3.1.1: This package has been renamed. Use lodash.padend@^4.0.0.
npm WARN prefer global node-gyp@3.3.0 should be installed with -g

> node-sass@3.4.2 install <redacted>/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/sunos-x64-47_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> spawn-sync@1.0.15 postinstall <redacted>/spawn-sync
> node postinstall


> node-sass@3.4.2 postinstall <redacted>/node-sass
> node scripts/build.js

... lots of resulting failure
```

So, how can I convince gulp-sass to use the globally installed version of things so it doesn't try to fetch a tarball that doesn't exist?

Thanks for the help.

**Comment by xzyfer** [comment]
I don't believe npm allows global packages to be used a dependencies. This
is an npm issue/feature and not related or fixable by gulp-sass.

**Comment by jaredmorrow** [comment]
@xzyfer well that is an unfortunate feature of npm then :).  I'll keep thinking of a way to work around this I guess.  Thanks.

**Comment by Snugug** [comment]
This functionality already exists in `gulp-sass`, although it appears very under documented.

You should be able to do something like the following:

```javascript
var gulp = require('gulp');
var sass = require('gulp-sass');
var mySass = require('node-sass'); // Your globally installed Sass compiler

// The Magic!
// From https://github.com/dlmanning/gulp-sass/blob/master/index.js#L186
sass.compiler = mySass;

gulp.task('sass', function () {
  return gulp.src('./sass/**/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(gulp.dest('./css'));
});
```

**Comment by Snugug** [comment]
Give that a try

**Comment by xzyfer** [comment]
@snugug the bigger issue is that npm will simply fail because node-sass
won't install on sunos.

You could try installing the gulp-sass beta, which uses the node-sass beta
with the sunos patches. The node-sass installer should fallback to local
compliation once the download fails.

**Comment by jaredmorrow** [comment]
@xzyfer okay, I'll try that method.  It is very curious that the `-g` option even exists if dependencies can't even use them, but that is certainly a loaded question for a different day.

I'll let you know if beta does the right thing and falls back to building from source (which did work on the global install).

**Comment by xzyfer** [comment]
@jaredmorrow global dependencies are resolved by `require` as @snugug noted. However they are not used in the resolution processing during installs.

Global dependencies exist mostly as a way to use node packages and system tools, like `bower`, `david` and `npm` itself.

**Comment by jaredmorrow** [comment]
@xzyfer and @Snugug thanks for the help.  The beta of gulp-sass did indeed fallback and build node-sass from source, which did work.  So going with the beta solved my issues.  Sorry I wasn't aware about the local v. global in regards to dependencies.  Of all the docs I read trying to figure out this issue, that was never stated.  Thanks for the help.
