### ISSUE TITLE
Issue with partials

### ISSUE THREAD

**Issue by tlkiong** [dlmanning/gulp-sass#443]
I am sorry if this has been raised before but I can't seem to find a solution here.
I am trying to include partials. However, I think it might be because of the way my files are structured. I would love to keep the way my files are structured while also able to import my partials.

```
/www
    |- core
    |     |- partials
    |     |       |- _colours.scss
    |- module1
    |     |- module1.scss
```

In module1.scss, I have tried the following to no result (or error)
```
@import 'colours';
@import "colours";
@import "../core/partials/colours"
```

Oh. And in my gulpfile.js

```
gulp.src('./www/**/*.scss')
        .pipe(sass({includePaths: ['./www/core/partials']})
        .on('error', sass.logError))
        .pipe(gulp.dest('./www/'));
```

Would love to have some enlightenment on this.
Thanks!

**Comment by xzyfer** [comment]
You have not described what your issue is. All these cases should work.
