### ISSUE TITLE
Font Awesome incorrect compiled

### ISSUE THREAD

**Issue by ayoubabid** [dlmanning/gulp-sass#445]
I use gulp-sass to compile vaadin sass file. The problem is the compiler doesn't understand font awesome characters. For example a "Toggle Bold" "\f032" in sass file will be interpreted after compilation as other symbols. 
How can i avoid that problem and have the correct symbol ?

**Comment by xzyfer** [comment]
This isn't a problem. The weird character output is valid. It looks strange but works fine.
