### ISSUE TITLE
Errors reported in the wrong location

### ISSUE THREAD

**Issue by LPGhatguy** [dlmanning/gulp-sass#447]
First of all, here's a reproduction case: https://github.com/LPGhatguy/gulp-sass-sourcemaps-bug

I'm having strange issues with a combination of variable interpolation and multi-line selectors causing gulp-sass to report errors in the wrong spots. In the above example, the error is off by one line, but in one of my test projects that started my hunt for the bug, I have errors that are off by over 100 lines!

In addition, the file is reported as being stdin, which although fixed in sourcemap generation, does not work in error output in this case.

**Comment by LPGhatguy** [comment]
This issue appears to be still relevant with the latest versions of each dependency. Has anyone reviewed this issue yet?

**Comment by xzyfer** [comment]
Remove all other gulp plugins. If the issue persists please open an issue with libsass (used by gulp-sass).
