### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by MrHidalgo** [dlmanning/gulp-sass#451]
Hi. 
After updating the plugin ("gulp-sass") and also breaching recommendations... the task displays the following error, after add to style file:

`@import "mixin/mixin";`

```
[16:04:16] Starting 'sass'...
[16:04:16] Finished 'sass' after 9.55 ms
**Segmentation fault (core dumped)**
```

Example tasks:

```
gulp.task('sass', function() { 
    gulp.src({path_to_src})
        .pipe(sass().on('error', sass.logError))
        .pipe(gulp.dest({path_to_dist}));
});
```

package.json:

`"gulp-sass": "^2.2.0",`

File structure:

```
style
   |__function
      |__function.scss
   |__mixin
      |__mixin.scss
   |__variable
      |__variable.scss
   |__...
style.scss (uses @import '{path/to/file{mixin||function||variable}}')
```

Ta!

**Comment by lenarich** [comment]
I have a similar issue when running gulp-sass with materialize.scss

@MrHidalgo have you figured out what the problem was?

**Comment by tarpey** [comment]
I'm getting this with with materialize.scss, too.

**Comment by jrm2k6** [comment]
Same thing here. Starting breaking randomly. Using gulp-sass through laravel-elixir

**Comment by MrHidalgo** [comment]
I had a problem due to the fact that the scss/sass files were called and formed recursion.

**Comment by xzyfer** [comment]
node-sass@3.6.0 was released today which fixes the segfault with normalize-css
