### ISSUE TITLE
Problem installing gulp-sass with node v4.2.2 ?

### ISSUE THREAD

**Issue by kamalpatel125** [dlmanning/gulp-sass#452]
I am trying to install gulp-sass using node v4.2.2 and npm 2.1.9 but having some issue related to node-sass and node-gyp. Has anyone got any idea about this issue ? 
Thanks

**Comment by kamalpatel125** [comment]
Why it's trying to download https://nodejs.org/download/release/v4.2.2/node-v4.2.2-headers.tar.gz ? It's creating problem for private npm repo.

**Comment by xzyfer** [comment]
Sounds like an issue with node-gyp. They may have a work around for private
repos.
