### ISSUE TITLE
includePaths are getting larger after every compilation

### ISSUE THREAD

**Issue by maciej-pawlisz** [dlmanning/gulp-sass#453]
before each compilation opts.includePaths are extended with dirname of file.path
`opts.includePaths.unshift(path.dirname(file.path));`

since `opts.includePaths` are copied from `options.includePaths` and are always the same, it will grow after every compilation, resulting in a very long list if there are many files, or when we are watching for changes.

This line should be changed to: `opts.file=file.path`, or this dir should be removed from `includePaths` or we should make a new array before each compilation

**Comment by xzyfer** [comment]
Fixed in v2.3.2
