### ISSUE TITLE
Error running gulp

### ISSUE THREAD

**Issue by edionmelarosa** [dlmanning/gulp-sass#456]
First, im getting 'Error: `libsass` bindings not found. Try reinstalling `node-sass`?' issue when running gulp. I found solution which seems solved the issue. 

Solution:
        npm uninstall --save-dev gulp-sass
        npm install --save-dev gulp-sass@2

That somehow solved the issue but new issue is showing which stuck me. This is the issue:

       Error: You may not @extend an outer selector from within @media.
       You may only @extend selectors within the same directive

http://screencloud.net/v/43ea

**Comment by miton18** [comment]
Not working with me, same error with v2 of gulp-sass

    Error: The `libsass` binding was not found in D:\projets\projet-m1-front\node_modules\node-sass\vendor\win32-x64-46\binding.node
    This usually happens because your node version has changed.
    Run `npm rebuild node-sass` to build the binding for your current node version.

And I try npm rebuild ....same thing
