### ISSUE TITLE
Question: Is Incremental Compilation enabled by default?

### ISSUE THREAD

**Issue by ghpabs** [dlmanning/gulp-sass#461]
Is Incremental Compilation enabled by default or should I use plugins like [gulp-memory-cache](https://www.npmjs.com/package/gulp-memory-cache) or [gulp-remember](https://www.npmjs.com/package/gulp-remember) if I need this feature?

**Comment by xzyfer** [comment]
gulp does not have incremental watching built in. We don't offer any kind of watching. I doubt these projects will work correctly with Sass code since they do not parse dependency graphs.
