### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by M1ke** [dlmanning/gulp-sass#462]
Unfortunately I can't provide examples as doing so would require upload of all our SCSS files, but we have a very highly nested SASS structure, lots of imports, lots of `@extend` usage. overall we can expect a full run of gulp sass to take 4-5 minutes.

However the problem is that during the first minute we tend to get a complete system lock-up as the process runs. This might be a problem with node-sass or even libsass. What I wonder is if it is possible through the gulp process to limit how much CPU the process can use?

Running on Ubuntu 14.04, gulp-sass 2.2.0.

**Comment by moebiusmania** [comment]
+1 :(

**Comment by xzyfer** [comment]
I am unable to reproduce this. I use gulp-sass everyday on many large projects. This is likely due to something else if your pipeline.

gulp-sass is a very thin gulp interface.
