### ISSUE TITLE
No error on .sass file

### ISSUE THREAD

**Issue by THE-Beck** [dlmanning/gulp-sass#465]
I'm using [generator-webapp](https://github.com/yeoman/generator-webapp) (with [this](https://github.com/yeoman/generator-webapp/blob/master/docs/recipes/jade.md) modification) and changed .scss to .sass. Which is working fine. I've noticed that if i mistype something gulp-sass doesn't gave me a error. Just compiling with error. e.g `color: qwerty` compiles to `color: qwerty`. I've tried all kinds ways but still doesn't gave me a error. Just compiles with mistype.

- windows with Cmder
- Node [ 0.12.7 ]
- Npm [ 2.11.3 ]
- gulp-sass [ 2.2.0 ]

**Comment by xzyfer** [comment]
Doesn't look like your listening to errors in your config. Please read either our or gulp-plumber's documentation of displaying errors.
