### ISSUE TITLE
 Encoding::CompatibilityError: incompatible character encodings: GBK and UTF-8

### ISSUE THREAD

**Issue by kanlidy** [dlmanning/gulp-sass#466]
Encoding::CompatibilityError: incompatible character encodings: GBK and UTF-8

(1) first try
I've already add "Encoding.default_external = Encoding.find('utf-8')" to C:\Ruby23-x64\lib\ruby\gems\2.3.0\gems\sass-3.4.22\lib\sass\engine.rb

(2) second try
or use {style: 'expanded'}

gulp.task('scss',function(){
    return sass("sass/mui.scss",{sourcemap: true,style: 'expanded'})
    	.on('error', sass.logError)
        .pipe(autoprefixer({
            browsers: ['last 2 versions']
        }))
        .pipe(concat('mui.css'))
   		.pipe(sourcemaps.write())
        .pipe(gulp.dest("dist/css"))
        .pipe(browserSync.stream({match: 'dist/**/*.css'}))
});

(3)last try:
add     "  @charset "utf-8"  "
to each *.scss

not work.

Tks, guys.

**Comment by xzyfer** [comment]
gulp-sass does not use Ruby. This is probably a bug with `gulp-ruby-sass`.
