### ISSUE TITLE
update to 2.3.0 no longer finds @import file

### ISSUE THREAD

**Issue by jimmymain** [dlmanning/gulp-sass#469]
Hi,

I have been building a custom bootstrap for some time using gulp-sass version 2.2.0.
The 2.3.0 version is failing to find variables.scss where before it used to.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: Content\build\skins\_greentur.scss
Error: File to import not found or unreadable: variables
       Parent style sheet: Aureus.Web/Content/build/skins/_greentur.scss
        on line 4 of Content/build/skins/_greentur.scss
>> @import "variables";
```

The directory structure looks like this:
```
   build\all.scss
   build\_variables.scss
   build\skins\_greentur.scss
```
`_greentur.scss` contains `@import "variables"`
`all.scss` contains `@import "skins\greentur"`

I have successfully built this using the original native sass version, so I don't think my paths are wrong?

**Comment by xzyfer** [comment]
Can you please create a small github repo with the files required produce this error so we can see it locally?

**Comment by Traksewt** [comment]
I get the same error. Degraded back to 2.2.0 and the @import works.

**Comment by xzyfer** [comment]
I am unable to reproduce this on two large applications. There is something else interfering with gulp-sass.

**Comment by JimmyVV** [comment]
yeah. it doesn't work. and i also try 2.2.0. 
tell me why:
```
"gulp-sass": "^2.2.0",
 "node-sass": "^3.5.1"
```
and my gulpfile is
```
 gulp.src("dev/sass/**/*.scss")
        .pipe(sass({outputStyle: 'compressed',includePaths: ['dev/sass/dist/']}).on('error', sass.logError))
        .pipe(postcss(processors))
        .pipe(gulp.dest('dev/styles'));
```
i need help.

**Comment by xzyfer** [comment]
There is simply not enough information here for us to help you. Someone needs to create a github repo where we can run `gulp` and see this problem for ourselves.

**Comment by JimmyVV** [comment]
finally, success. I find this work with 
```
"gulp-sass": "^2.2.0",
 "node-sass": "^3.5.1"
```
and i dont add any tricks. just use 
```
gulp.src("dev/sass/**/*.scss")
        .pipe(sass({outputStyle: 'compressed',includePaths: ['dev/sass/dist/']}).on('error', sass.logError))
        .pipe(postcss(processors))
        .pipe(gulp.dest('dev/styles'));
```

**Comment by jimmymain** [comment]
I have tried to create a trivial example, and alas, the trivial case seems to work just fine.

**Comment by xzyfer** [comment]
I suspect this is an issue with another plugin that's not playing by the
gulp rules. We generally have trouble with sourcemap plugins or postcss. If
you're using either of those try disabling it and seeing if the error
continues.

**Comment by jimmymain** [comment]
I have figured it out.
It happens precisely when the root of the sass build is not the current directory.
Rolling back to version 2.2.0 solves the problem.

Here is a zip file with a gulp that works on 2.2.0, and not on 2.3.0
[sass.zip](https://github.com/dlmanning/gulp-sass/files/229496/sass.zip)

**Comment by jubi** [comment]
Same problem here - reverted to 2.2.0

**Comment by xzyfer** [comment]
@jimmymain your error is because you have not defined the appropriate `includePaths`. Change the following line and it works as expected.

```
.pipe(sass({ includePaths: ['./build'] }))
```

This is because `@imports` are always relative to where `node-sass` (or gulp-sass or even ruby sass) is being run. In your case it's being run at your project root but your files are in `build`. By adding this include path you're tell Sass to also try to resolve relative those extra directories.

As configured, this will fail to compile in both node-sass and Ruby Sass. It also fails in node-sass@v3.4.2.

**Comment by xzyfer** [comment]
@JimmyVV it looks like your `includePaths` are also incorrect. If your source is

```js
gulp.src("dev/sass/**/*.scss")
```
Your `includePaths` should be
```js
sass({ includePaths: ['dev/sass/'] })
```

**Comment by jimmymain** [comment]
@xzyfer thanks very much, that did the trick.
cheers
j

**Comment by xzyfer** [comment]
This appears to have been cause by some code that may have been mistakenly removed. I have restored it in https://github.com/dlmanning/gulp-sass/pull/474 and currently waiting on confirmation from the author.
