### ISSUE TITLE
Error on node-sass 3.5.1

### ISSUE THREAD

**Issue by basvandenheuvel** [dlmanning/gulp-sass#471]
Since yesterday the node-sass package has proxy issues with the new 3.5.1 version.

The thing is, we use gulp-sass which has a dependency on node-sass. I haven't changed my gulp-sass version (still 2.1.1) but i do get this error. Do you guys have a dependency on node-sass with the "^" in front of it or did you change the dependency in 2.1.1 without creating a new version for this?

**Comment by xzyfer** [comment]
We depend on node-sass@^3

**Comment by basvandenheuvel** [comment]
@xzyfer  what do you mean?

**Comment by xzyfer** [comment]
We pull in the latest version of node-sass

**Comment by basvandenheuvel** [comment]
@xzyfer  yes thats the problem. You should stop doing that. The LATEST version of node-sass is broken. Because you use the "^" you now automatically use the broken version.....

**Comment by basvandenheuvel** [comment]
What version of gulp-sass can i use that DOESN'T the "latest version of node-sass" A.K.A. 3.5.1 (broken!)?

**Comment by xzyfer** [comment]
I understand you're frustrated but this won't change. Bugs unfortunately
happen. There's no way to know if there is a bug until some like you finds
it.

**Comment by basvandenheuvel** [comment]
I do understand that. But by refering to a static version (so, without the "^") can be sure that this gulp-sass package doesn't stop working when the dependency does.
