### ISSUE TITLE
segmentation fault gulp-sass

### ISSUE THREAD

**Issue by jaider2523** [dlmanning/gulp-sass#475]
Please......one solution for this.....

**Comment by mitchhentges** [comment]
I'm having the same issue.
This might be related to me updating NodeJS.
```
Node: v5.11.0
Gulp: 3.9.1
gulp-sass: 2.3.1
```

Here's how I'm using `gulp-sass`:
```
return gulp.src('style/main.scss')
    .pipe(sass({outputStyle: 'compressed'}).on('error', sass.logError))
    .pipe(gulp.dest('build'));

**Comment by mitchhentges** [comment]
I'm going to investigate the base projects, as described [here](https://github.com/dlmanning/gulp-sass#issues)

**Comment by mitchhentges** [comment]
This issue should be closed, the guys at node-sass and libsass have this issue covered: https://github.com/sass/node-sass/issues/1464

**Comment by jaider2523** [comment]
Hi, @mitchhentges  i have the same issue on linux y mac :(. I need urgent solution for this.  Hey you now use node-sass and libsass...?

**Comment by mitchhentges** [comment]
Yes, check out that `node-sass` issue I linked. It looks like putting `node-sass: "3.4.2"` in your `package.json` should work.

See https://github.com/sass/node-sass/issues/1464#issuecomment-212976697 and https://github.com/sass/node-sass/issues/1464#issuecomment-212987632.

It worked for my local development machine, but not for my Travis build machine, so your mileage may vary.

**Comment by jaider2523** [comment]
Excellent notice for this morning.  I will  try this solution now.....
