### ISSUE TITLE
Import directives may not be used within control directives or mixins

### ISSUE THREAD

**Issue by ACastans** [dlmanning/gulp-sass#476]
Hi, this is an issus that I have since today.

I try to get a previous version of gulp-sass but since the node-sass dependency is not fixed I can't get over this issue.

I also post here : https://github.com/sass/node-sass/issues/1471

Do you have any idea how I can get my build working again ?

Regards.

Adrien.

**Comment by xzyfer** [comment]
Please don't post in two places. This has been answered in the linked issue.
