### ISSUE TITLE
node-sass version is still latest

### ISSUE THREAD

**Issue by manthanhd** [dlmanning/gulp-sass#479]
Hello,

Referring to https://github.com/dlmanning/gulp-sass/commit/cfee7560774d8f3c5cde46b42569b8d1d2a15f82

What benefit does this change provide?
Whenever I do `npm install`, it installs latest node-sass anyway which defeats the purpose of this change? Unless I'm missing something..?

Thanks,
M

**Comment by gvilarino** [comment]
The problem is that dependencies aren't pinned. As a good practice, all entries under `dependencies` should alwasy be pinned.

**Comment by xzyfer** [comment]
This was becuase people were relying in bugs in 3.4.2 which caused the code
to break in 3.5.0. This gave them an escape hatch until they fixed their
code.

**Comment by gvilarino** [comment]
Thanks for the explanation @xzyfer, we double-checked our stylesheets and fixed them; the error went away.
