### ISSUE TITLE
`node-sass` dependency breaks previously working sass

### ISSUE THREAD

**Issue by gvilarino** [dlmanning/gulp-sass#480]
Hi, after a recent dependency clean and re-install I ran into this:

```
Error in plugin 'sass'
Message:
    path/to/some/style.sass
Error: You may not @extend an outer selector from within @media.
       You may only @extend selectors within the same directive.
```

This started happening, I noticed, because of `gulp-sass` now pulling `node-sass@3.6.0`, and that breaks the parsing.

I also noticed #479 and saw a common pattern here.

I think this is due to the fact that `dependencies` aren't pinned; which usually at some point cause stuff like this. If I manually install `node-sass@3.4.2` it does work, but it will still break any automated build mechanism.

May I suggest you pinned your dependencies? 

If you want to keep patches coming in without manually updating your deps, you may always use [tilde ranges](https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1) or [X ranges](https://docs.npmjs.com/misc/semver#x-ranges-12x-1x-12-) instead of [caret ranges](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004).

**Comment by xzyfer** [comment]
Have you confirmed your Sass code is valid and compiles with the official
Sass compiler?

This error is likely due to your Sass being in invalid. More information in
https://medium.com/@xzyfer/why-node-sass-broke-your-code-and-semver-1b3e409c57b9

We will not pin our dependencies.

**Comment by xzyfer** [comment]
Will reopen this issue when you confirm the error is not caused by invalid code.

**Comment by gvilarino** [comment]
I can confirm that downgrading to `node-sass@3.4.2` makes it work, but I hadn't read that article before (thanks).

I'll double-check and confirm (or take back) my initial bug report.

**Comment by gvilarino** [comment]
@xzyfer, we double-checked our code and fixed them; the error went away.
