### ISSUE TITLE
node-sass dependency is breaking build

### ISSUE THREAD

**Issue by ziyadparekh** [dlmanning/gulp-sass#483]
a node-sass release is missing which is causing the build to fail

https://www.dropbox.com/s/cwepy5l8huy47ve/Screenshot%202016-04-26%2015.03.50.png?dl=0

Not sure if you know a quick workaround...

**Comment by xzyfer** [comment]
Node Sass does not Coreen support node 6. Down grade to node 5.

**Comment by xzyfer** [comment]
Subscribe to https://github.com/sass/node-sass/issues/1484 for updates.
