### ISSUE TITLE
node 6 broke node-sass

### ISSUE THREAD

**Issue by bertez** [dlmanning/gulp-sass#485]
Further info:
https://github.com/sass/node-sass/issues/1484

Seems like they are working on the issue and the will release a new version supporting node 6 soon. The dependency should be updated when the new version is released.

**Comment by talyuk** [comment]
Same problem 😔

**Comment by bertez** [comment]
the new version of node-sass should be working in a week or so,

for the time being I installed nvm and I'm using node 5.11 to build my projects

**Comment by amcdnl** [comment]
Tracking in https://github.com/sass/node-sass/pull/1498

**Comment by Sankluj** [comment]
node-sass v3.7.0 should resolve the issue :)

**Comment by amcdnl** [comment]
We need to update this depedency and should be good.

**Comment by xzyfer** [comment]
3.7.0 has not been released yet, we're still generating the binaries.

**Comment by bertez** [comment]
Thanks @xzyfer

**Comment by nyilmaz** [comment]
3.7.0 released. https://github.com/sass/node-sass/issues/1484
