### ISSUE TITLE
gulp-sass never moving to next pipe

### ISSUE THREAD

**Issue by thehindenburg** [dlmanning/gulp-sass#486]
this has been working fine for me till recently, but whenever I run 

```
gulp.task('styles', function() {
  return gulp.src(gulpConfig.styles)
    .pipe(gulpConcat({path: 'style-bundle.css', cwd: ''}))
    .pipe(gulpSass({
      style: 'expanded'
    }))
    .pipe(gulp.dest('client/src/bundle'))
    .pipe($.size());
});
```
is just hangs on gulp-sass. I'm using Node 0.12.9 and gulp-sass version 2.3.1

**Comment by thehindenburg** [comment]
Okay, a little more debugging and I got it. It wasn't liking one of my `@import` statements anymore and failing silently.

**Comment by xzyfer** [comment]
Please read the documentation before filing an issue. Errors will not be printed by default.

```
.pipe(sass().on('error', sass.logError))
```
