### ISSUE TITLE
fixed dependencies

### ISSUE THREAD

**Issue by cancerberoSgx** [dlmanning/gulp-sass#487]
Could you please point to fixed dependencies in your package.json. What's happening is that lib-sass is enforcing new policies in the same minor version so my users are getting errors from one day to the other without changing the gulp-sass version. :(

Basically this is solved by changing: "node-sass": "^3.4.2", to "node-sass": "3.4.2", in your package.json

Thanks!

**Comment by xzyfer** [comment]
We will not be doing this. More information in 

https://medium.com/@xzyfer/why-node-sass-broke-your-code-and-semver-1b3e409c57b9

**Comment by cancerberoSgx** [comment]
Aja, OK I , kind-of, understand. Nevertheless is an error from lib-sass not to respect the semver, the document is not a justification for that :( too bad.   Thanks for the explanation :) very appreciated
