### ISSUE TITLE
gulp-sass 2.x and Foundation 5, broken after gulp-sass update

### ISSUE THREAD

**Issue by schikulski** [dlmanning/gulp-sass#488]
Hi! A year ago I developed a site using gulp-sass 1.1.0 and Foundation 5. Everything was working fine. Today I needed to do some updates to the site, so I cloned the site back down on my computer, ran `npm install` and got the following error:

```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/binding/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/simen/Desktop/ferdigsnakka.no/content/themes/ferdigsnakka/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
Build failed
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.9.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.9.6 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
```

I figured gulp-sass was running old, so I tried updating the gulp-sass package in my package.json to 2.3.1. `npm install` ran successfully, but now my site seems to be broken in term of including the Foundation 5 files that's needed for the CSS framework. To me it looks like the files are found(tested this with a simple code I searched for in the concatinated stylesheet through the various .scss-files), but some of the classes and styles are being left out of the concatinated stylesheet. Specifically classes like all the .column and .pull classes are left out.

Here's my gulp sass job:

```
	gulp.task('sass', function (){
		gulp.src([
			'bower_components/foundation/scss/normalize.scss',         // Gets normalize
			'assets/scss/app.scss'])                                   // Gets the apps scss
			.pipe(sass({style: 'compressed', errLogToConsole: true}))  // Compile sass
			.pipe(concat('main.css'))                                  // Concat all css
			.pipe(rename({suffix: '.min'}))                            // Rename it
			.pipe(minifycss())                                         // Minify the CSS
			.pipe(gulp.dest('assets/css/'))                            // Set the destination to assets/css
			.pipe(livereload())                                        // Reloads server
			util.log('Sass compiled & minified');                 // Output to notification
	});
```

I'm no gulp or sass expert, but I was wondering if anyone had any suggestion for what my choices are? Could Foundation 5 and gulp-sass 2.x not be working well together?

**Comment by xzyfer** [comment]
Looks you're trying to install `node-sass@0.9.6`. That version is ancient and unsupported. Update your node-sass to a newer version.

**Comment by xzyfer** [comment]
My guess is you don't have your `includePath` configured correctly.

**Comment by schikulski** [comment]
I appreciate your help, @xzyfer! 

Yes, the first version(1.x) of the `gulp-sass` install's an ancient version of `node-sass`. But if I update to the latest `gulp-sass`(and thus `node-sass`) the site breaks. That's the problem.

Okay, So I'm now running `gulp-sass 2.3.1`, and gulp does not give me any errors when running, but some of the styles are still not imported. I found the #103 issue, and tried using absolute paths for `IncludePaths` as well as `./` with the same results. My `gulp-sass` task is now:

```
var sassPaths = [
	'assets/scss',
	'bower_components/foundation/scss/foundation'
];


	gulp.task('sass', function (){
		gulp.src([
			'bower_components/foundation/scss/normalize.scss',         // Gets normalize
			'assets/scss/app.scss'])                                   // Gets the apps scss
			.pipe(sass({style: 'compressed', includePaths: sassPaths, errLogToConsole: true}))  // Compile sass
			.pipe(concat('main.css'))                                  // Concat all css
			.pipe(rename({suffix: '.min'}))                            // Rename it
			.pipe(minifycss())                                         // Minify the CSS
			.pipe(gulp.dest('assets/css/'))                            // Set the destination to assets/css
			.pipe(livereload())                                        // Reloads server
			util.log('Sass compiled & minified');                 // Output to notification
	});

```

I still can't figure out why the Foundation 5 files are left out.

**Comment by xzyfer** [comment]
You're likely getting an error but not printing it. The `errLogToConsole` options has been removed. Please read the documentation before opening an issue.

```
.pipe(sass({style: 'compressed', includePaths: sassPaths}).on('error', sass.logError)))
```

**Comment by schikulski** [comment]
Ah, yes, I should definitely check that first. Still not getting any errors, though. Anyway, thanks for helping out, I'll ask if someone has any clue in the Foundation forums.
