### ISSUE TITLE
Update dependencies (including node-sass v3.7.0)

### ISSUE THREAD

**Issue by mandrean** [dlmanning/gulp-sass#489]
A number of dependencies can be updated, eslint and node-sass being a few.

**Comment by xzyfer** [comment]
We use the latest node-sass

**Comment by mandrean** [comment]
No? node-sass v3.7.0 released a day ago https://github.com/sass/node-sass/releases

**Comment by xzyfer** [comment]
I am aware as I released it. We're locked to `node-sass@^3.4.2` which means you'll get the latest `node-sass@3.x` release on a new `npm install`.

I suggest familiarising yourself with [SemVer](http://semver.org/).

**Comment by mandrean** [comment]
Yes of course I know about semver. Sorry, overlooked the carret operator.

**Comment by mandrean** [comment]
@xzyfer How about all the other dependencies that can be updated? Especially eslint (v1 -> v2), but also globule (v0.2 -> v1, which in turn updates an old lodash subdependency), should (v7 -> v8) and autoprefixer-core (v5 -> v6).

**Comment by xzyfer** [comment]
They're dev dependencies so I'm not too fussed. I've bumped the trivial ones in #490.
The postcss ones are trickier because postcss 6 broke node 0.10 support.
