### ISSUE TITLE
Linter reports wrong line numbers

### ISSUE THREAD

**Issue by kimblim** [dlmanning/gulp-sass#492]
Here's an example of a file:

```
/* Utilities */
@import '../Global/animate';
@import '../Global/grid';
@import '../Global/utils';

/* Helpers */
@import 'helpers/colors';
@import 'helpers/helper-classes';
@import 'helpers/z-index';

/* Iconfont*/
@import 'generated/iconfont';

/* Base */
@import 'base/animation';
@import 'base/default';
@import 'base/typography';
@import 'base/utils';
@import 'base/rich-text';

/* Settings */
@import 'base/settings';
```

Which outputs  the following errors:

> 1:1  warning  Multiline style comments should not be used  no-css-comments
> 11:1  warning  Multiline style comments should not be used  no-css-comments
> 21:1  warning  Multiline style comments should not be used  no-css-comments
> 27:1  warning  Multiline style comments should not be used  no-css-comments
> 41:1  warning  Multiline style comments should not be used  no-css-comments

Expected output should be:

> 1:1  warning  Multiline style comments should not be used  no-css-comments
> 6:1  warning  Multiline style comments should not be used  no-css-comments
> 11:1  warning  Multiline style comments should not be used  no-css-comments
> 14:1  warning  Multiline style comments should not be used  no-css-comments
> 21:1  warning  Multiline style comments should not be used  no-css-comments

Has anyone else experienced this issue and does anyone have a fix for it?

**Comment by LPGhatguy** [comment]
I may be having a similar issue that occurs with some specific, edge-case CSS with #447.

**Comment by xzyfer** [comment]
gulp-sass has no linter. I don't understand your issue.

**Comment by kimblim** [comment]
@xzyfer 
Sorry if I'm phrasing it wrong — when I run gulp-sass it outputs the wrong line numbers in the results. I'm not sure I can express it much more clear than that?

**Comment by xzyfer** [comment]
Sorry, I'm still not following. What config are you using in order to produce line numbers?

**Comment by xzyfer** [comment]
gulp-sass turns Sass code into CSS. It sounds like whatever is reading your CSS after we create it has an issue.

**Comment by kimblim** [comment]
@xzyfer Now I get why you don't get it — I reported the issue on the wrong repo. Sorry! What a n00b-mistake.

**Comment by xzyfer** [comment]
Thanks for the clarification
