### ISSUE TITLE
Incompatibility with Node 6 via node-sass

### ISSUE THREAD

**Issue by mdsharpe** [dlmanning/gulp-sass#495]
When restoring packages, with node 6 installed, I am experiencing the following error:

`Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/win32-x64-48_binding.node"`

This appears to be due to the fact that gulp-sass depends on node-sass 3.4.2, but there is no node 6 version of 3.4.2. At a glance it looks like the first node 6 compatible build of node-sass is 3.6.0, and they announced node 6 compatibility in the release notes of 3.7.0.

Is there an easy way for me to work around this, i.e. cause my build to grab 3.7.0 instead of 3.4.2? Or does gulp-sass need to increment its dependency?

**Comment by xzyfer** [comment]
`npm update` will do it assuming no packages are specifically locked to an
older version.

**Comment by mdsharpe** [comment]
Thanks, but the scenario in which this is a problem is in a CI build where packages are restored afresh. There is no opportunity to `npm update` because it is erroring during `npm install`.

**Comment by xzyfer** [comment]
npm install should grab the latest node-sass unless a package is specifically preventing it. Try installing the latest gulp-sass.

**Comment by vijaykuma** [comment]
@xyzfer -- updating gulp-sass works  for me. thanks
