### ISSUE TITLE
“Node Sass does not yet support your current environment: Linux 64-bit with false"

### ISSUE THREAD

**Issue by jitendravyas** [dlmanning/gulp-sass#496]
Getting this error on Arch Linux.

```
$ gulp -v
[19:43:15] CLI version 3.9.1
[19:43:15] Local version 3.9.1

$ npm -v
3.9.0
```

**Comment by xzyfer** [comment]
Arch and Alpine Linux distributions are currently not compatible with the precompiled node-sass Linux binaries. You can compile them locally with

```
npm rebuild node-sass
```

**Comment by jitendravyas** [comment]
@xzyfer I have already tried `npm rebuild node-sass` before posting here. Getting same error even after running that.

**Comment by rochdev** [comment]
@xzyfer Is there any plan to support Alpine Linux and if so is there a timeline for when it will be? I'd rather use the precompiled binaries to keep my docker image lightweight.

**Comment by xzyfer** [comment]
@rochdev this is something we would like to do but we need help from the community - see https://github.com/sass/node-sass/issues/1589

**Comment by birdspider** [comment]
@jitendravyas - ran into the same problem today - oddly enough `npm remove node-sass` and `npm install node-sass` fixed it for me (for now)
