### ISSUE TITLE
Node 6 Compatibility (upgrade to node-sass 3.7.0)

### ISSUE THREAD

**Issue by SmaugTheGreat** [dlmanning/gulp-sass#497]
Unfortunately this project doesn't have full Node.js v6 support yet as it is using an outdated version of node-sass (https://github.com/sass/node-sass/releases). Upgrading it would be great!

**Comment by xzyfer** [comment]
This project uses the latest version of node-sass, you just need to update your local dependencies.
```
npm update
````

I suggest taking a moment to read about semver and npm. It's a critical aspect of the node ecosystem.

https://docs.npmjs.com/getting-started/semantic-versioning

**Comment by SmaugTheGreat** [comment]
What you said should be true, however I used npm update and it won't update to 3.7.0 (only to 3.6.0)...

**Comment by xzyfer** [comment]
This means you have a package that is locked to v3.6.0.

```
npm ls node-sass
```

The above will list all the node-sass dependencies in your app. One of their parents is likely hardcoded to 3.6.0.

**Comment by SmaugTheGreat** [comment]
deleting node_modules and using npm install again solved the issue. `npm ls node-sass` only lists gulp-sass as the only module that uses it. No idea why this issue happened. Anyway, sorry for wasting your time.
