### ISSUE TITLE
Compatibility with Node 6

### ISSUE THREAD

**Issue by tex0l** [dlmanning/gulp-sass#499]
Hi, we need to bump the node-sass version to 3.7.0 to have Node 6 compatibility.

I wanted to make a PR, then I saw that you wanted an issue to be filed before, here it is anyway:
https://github.com/tex0l/gulp-sass

**Comment by xzyfer** [comment]
We lock to ^3.4.2 which means when you install gulp-sass you'll get the
latest 3.x of node-sass. You can update your dependencies with `npm update`
or deleting your node_modules folder and running `npm install `.
