### ISSUE TITLE
File to import not found or unreadble

### ISSUE THREAD

**Issue by marijarahman** [dlmanning/gulp-sass#500]
I've been having a huge issue with gulp sass. I am getting "Error: File to import not found or unreadable: _reset" error when I try to import .scss files. I have to use gulp and I have to be able to have import options for including files. Has anyone had this problem and have a solution? 

Thanks

**Comment by xzyfer** [comment]
Sounds like your includePaths are not configured.

**Comment by marijarahman** [comment]
I solved it using this library https://github.com/mathisonian/gulp-sass-bulk-import
