### ISSUE TITLE
Dependency issue still occuring for node-sass

### ISSUE THREAD

**Issue by puranjayjain** [dlmanning/gulp-sass#501]
@xzyfer Although there were a number of issues and PRs opened, yet this issue somehow slipped by. Can you please look into the version of node-sass it still occurs as 3.6.0 and not 3.7.0 due node's flattening and the version in package.json being ^3.4.2. Can you suggest me what I can do for it or update the dependencies in package.json to ^3.7.0 or enable greenkeeper for this repo if possible. Thank you

**Comment by xzyfer** [comment]
There are many duplicates of this issue. You can check the recent closed
issues for the information you're after.
