### ISSUE TITLE
I have a folder of theme files, I want them separately to be comipled

### ISSUE THREAD

**Issue by ebrahim-tadbir** [dlmanning/gulp-sass#502]
I have a folder in sass project 
-sass
    -- global.scss
    -theme
            -- _blue-color.scss
            -- _base-color.scss
 
i run this files:

```
gulp.task('sass', function () {
  	return gulp.src('./sass/**/*.scss')
		  		// Sass - Compile Sass files into CSS
		  		.pipe(sass({
		  			outputStyle: 'expanded',
		  			includePaths: ['./sass/']
		  		}))
          .on('error', errorLog)
			    .pipe(gulp.dest('./css'))
});
```
It generates files in the path /css/globall.css

but I want to have  css color files separately

**Comment by xzyfer** [comment]
Sass won't compile files that begin with an underscore. Create files that
import the underscored files or remove the underscores.

**Comment by ebrahim-tadbir** [comment]
Thanks, I see,
I removed the underscore again it is not generating separate files again.

should I change gulpfile.js that this includePaths or destination ?

**Comment by xzyfer** [comment]
You may be silently running into errors. Make sure you've followed the
documentation on how output errors.

**Comment by ebrahim-tadbir** [comment]
I see this error:
(node:1388) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

**Comment by xzyfer** [comment]
I have never seen that error. There is something wrong with your
environment that I cannot help with.

**Comment by ebrahim-tadbir** [comment]
you are hopeless!

**Comment by ebrahim-tadbir** [comment]
the problem of the error resolved, but it can not make theme files
please help me
