### ISSUE TITLE
Node 6 and node-sass causes gulp-sass to print a lot of errors

### ISSUE THREAD

**Issue by bleadof** [dlmanning/gulp-sass#503]
This has been reported in the upstream: https://github.com/sass/node-sass/issues/1484

**Comment by xzyfer** [comment]
Run npm update. We lock to ^3.4.2 which mean you get the latest 3.x node-sass. There are many identical closed issues. Please search before opening an issue.

**Comment by bleadof** [comment]
Ah, indeed! I did search upstream, but not here! You might want to put it in the README if it comes up all the time. :-)
