### ISSUE TITLE
Empty output file on `watch`

### ISSUE THREAD

**Issue by stilllife00** [dlmanning/gulp-sass#506]
I run `sass:watch` task, I edit my main `.scss` file, `gulp-sass` runs but the output file is empty.
If I instead `touch` the same file, the compilation goes fine.
If I just run `sass` task the compilation goes fine.
## code

```
 gulp.task('sass', function() {
     return gulp.src('./source/sass/*.scss')
         .pipe(sass())
         .pipe(gulp.dest('./dist/css'));
 });
 gulp.task('sass:watch', function() {
      gulp.watch('./source/sass/*.scss', ['sass']);
 });
```
## info

```
gulp 3.9.1
gulp-sass@2.3.1
  └── node-sass@3.7.0 
Linux 3.13.0-43-generic #72-Ubuntu
Sublime text 3
working on remote files mounted with sshfs
```

How can I collect more debugging info ?

**Comment by evseevnn** [comment]
+1

**Comment by loehnertz** [comment]
+1

**Comment by kfyuecn** [comment]
gulp.task('sass:watch', function() {
      gulp.watch('./source/sass/*.scss', ['sass']);
 }); 
попробуй убери sass: перед watch должно быть
 gulp.task('watch', function() {
      gulp.watch('./source/sass/*.scss', ['sass']);
 });

**Comment by xzyfer** [comment]
Make sure you have atomic saves turned on in sublime text. By default when you save a file in Sublime it first empties the file then writes the current content of the editor to the file.

This cases watchers like gulp to be triggered when the file is initially cleared out, which means gulp only sees the empty file.
