### ISSUE TITLE
Sass on error does not show errors

### ISSUE THREAD

**Issue by Lisaj** [dlmanning/gulp-sass#507]
Hello,
sass().on('error', sass.logError) does not appear in the output error.
If you only use sass() errors are displayed.

Using
node: 6.2.1
gulp: 3.9.1
node-sass: 3.7.0
gulp-sass: 2.3.1
windows 10 x64

**Comment by Elephant-Vessel** [comment]
http://stackoverflow.com/questions/37703914/gulp-sass-logerror-not-working-in-visual-studio-task-runner/
