### ISSUE TITLE
Please upgrade dependencies

### ISSUE THREAD

**Issue by niftylettuce** [dlmanning/gulp-sass#508]
You are using an outdated deprecated version of `node-sass` which has weird installation errors.

https://github.com/dlmanning/gulp-sass/blob/master/package.json#L25

See "Improved installation errors" starting in v3.5.1 at https://github.com/sass/node-sass/releases

**Comment by mrking** [comment]
So am I but I'm not sure is related. I filed an issue under node-sass either way. 

https://github.com/sass/node-sass/issues/1579

**Comment by xzyfer** [comment]
Please search before opening a new issue. Duplicate #504 #501 #499 #497 #493 #491 #489.
