### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by ghost** [dlmanning/gulp-sass#514]
VCBuild.exe not Windows 10

**Comment by Delliant** [comment]
Installed `gulp-ruby-sass` and it works.

**Comment by MrOhyang** [comment]
What's the difference between gulp-sass and gulp-ruby-sass......
gulp-ruby-sass can work.

**Comment by xzyfer** [comment]
gulp-ruby-sass uses Ruby Sass, gulp-sass use Node Sass. Node Sass is much faster.
