### ISSUE TITLE
node-sass sourcemaps build faster than gulp-sourcemaps

### ISSUE THREAD

**Issue by icai** [dlmanning/gulp-sass#516]
node-sass sourcemaps build faster than gulp-sourcemaps, can you support node-sass sourcemaps instead of gulp-sourcemaps?

https://github.com/sass/node-sass#sourcemap

**Comment by xzyfer** [comment]
We use node-sass sourcemaps. The slowness is with gulp itself unfortunately.

**Comment by icai** [comment]
may machine problem, faster now.
