### ISSUE TITLE
Node Sass could not find a binding for your current environment

### ISSUE THREAD

**Issue by fatefan** [dlmanning/gulp-sass#517]
I run gulp-sass,but screen display:
'Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x'

**Comment by xzyfer** [comment]
Looks like you have not npm installed correctly. Run npm install again or
npm rebuild node-sass.

**Comment by aendrew** [comment]
@xzyfer Nope, node-sass has been updated substantially so it works in 6.x+. See: sass/node-sass#1484.

**Comment by fatefan** [comment]
I reinstall node-sass. I am in china,network unstable.
