### ISSUE TITLE
linefeed bug with sourcemaps

### ISSUE THREAD

**Issue by icai** [dlmanning/gulp-sass#518]
I found a bug in windows platform.
`linefeed: process.platform === 'win32' ? 'crlf': 'lf',`

![2016-07-06_161848](https://cloud.githubusercontent.com/assets/1061012/16611679/618ae9dc-4395-11e6-9448-6526161b2098.png)

@floridoo

**Comment by xzyfer** [comment]
What's the output of

```
npm ls node-sass
```

**Comment by icai** [comment]
@xzyfer 

-- gulp-sass@2.3.2
  `-- node-sass@3.8.0

**Comment by icai** [comment]
I read the code using @sindresorhus plugin  `detect-newline` to do this. @floridoo gulp-sourcemaps

**Comment by xzyfer** [comment]
Please supply the gulp config you're using. It's not clear to me if you're using node-sass sourcemaps (which would be a bug in LibSass) or gulp-sourcemaps (which would be a bug in that plugin).

**Comment by xzyfer** [comment]
Having read through https://github.com/floridoo/gulp-sourcemaps/issues/209, this appears to be a bug in another library.
