### ISSUE TITLE
Allow altering the current working directory (cwd)

### ISSUE THREAD

**Issue by roydukkey** [dlmanning/gulp-sass#519]
How could an alteration to the `cwd` be provided to gulp-sass? Consider that `gulp.src()` and `gulp.dest()` have are supplied with a `cwd` option. `includePaths` will not inherit the `cwd` of the source glob.

``` javascript

var projectPath = './Site/Web';

var cfg = {
    src: './wwwroot/theme/**/*.sass',
    options: {
        precision: 6,
        includePaths: [
            './wwwroot/css',
            './wwwroot/lib'
        ]
    }
};

gulp.task('build:sass', function () {
    return gulp.src(cfg.src, { cwd: projectPath, base: projectPath })
        .pipe(sass().on('error', sass.logError))
        .pipe(gulp.dest('./', { cwd: projectPath}));
});

```

If `cfg` was an external configuration file, I would be intuitive that `includePaths` would have the same root as the source glob.

**Comment by xzyfer** [comment]
This is simply not how gulp works. If you want to change the cwd you'll need to use a plugin to do so before calling `src`. The cwd config in src doesn't not change the cwd, it just does the glob relative to that directory.
