### ISSUE TITLE
@import file compiler faild !

### ISSUE THREAD

**Issue by tamamadesu** [dlmanning/gulp-sass#520]
I have a question ,when I use gulp-sass with gulp, here is my file code :

style.sass
```
@import "normalize.sass"
@import "variables.sass"
```
gulpfile.js
```
gulp.task('style', function () {
        gulp.src('./style.sass')
            .pipe(sass({ includePaths : ['./'] }))
            .pipe(gulp.dest(build_css))
    });
gulp.watch('./style.sass',['style']);
```

but, if I change variables.sass , my style task not run, am I config something wrong or  gulp-sass is  not support like this situation，how can I do ?

**Comment by xzyfer** [comment]
You need to use `gulp.watch` for automatic compilations on save.

**Comment by tamamadesu** [comment]
watch  "variables.sass"  and run style task ?
