### ISSUE TITLE
gulp-sass 执行gulp 任务时候出现

### ISSUE THREAD

**Issue by qiangran** [dlmanning/gulp-sass#523]
Error: dlopen(/XXX/XXXX/XXXX/XXXX/study/node_modules/node-sass/vendor/darwin-x64-47/binding.node, 1): no suitable image found.  Did find:
        /Users/XXX/XXX/XXX/study/node_modules/node-sass/vendor/darwin-x64-47/binding.node: truncated mach-o error: seXXXgment __TEXT extends to 1212416 which is past end of file 225840
    at Error (native)
gulp version 
![image](https://cloud.githubusercontent.com/assets/16221496/17170538/1b981734-541f-11e6-9905-bcc1459d911c.png)

**Comment by xzyfer** [comment]
npm rebuild node-sass
