### ISSUE TITLE
New line issues in CSS @media directive

### ISSUE THREAD

**Issue by billyhalim** [dlmanning/gulp-sass#525]
Hello,

I am currently using gulp-sass to compile my Sass code into CSS. When compiling, the CSS selector will make a new line before writing the next CSS selector. Here's the example : 

```
.left {
    margin-right: auto; }

.right {
    margin-left: auto; } 
```

As you can see above, it makes a new line before the `.right` selector.

However, I have met a problem when CSS selectors are inside a @media query directive. Here's the example : 

```
@media (min-width: 80px) {
    .small-offset {
        margin-left: 50%; }
    .small {
        width: 50% }
}
```

As you can see above, it doesn't make a new line before the `.small` selector.

Are there any bugs or should I configure something to achieve a new line in @media directive ? Thanks in advance !

**Comment by xzyfer** [comment]
There is no way to change this. We don't exactly match the Sass output and likely never will. We try to get close enough. If you want very specific out for some reason, you should use a post processor.
