### ISSUE TITLE
How to use division for number

### ISSUE THREAD

**Issue by wanghao0557** [dlmanning/gulp-sass#526]
When I use division for my scss file. for example, 20/2px convert to css file also is 20/2px. Is this a bug or use other symbol for division?
![qq 20160813131801](https://cloud.githubusercontent.com/assets/1477919/17641580/8ee04018-6158-11e6-841d-9d96c180a758.png)

**Comment by xzyfer** [comment]
What result would you expect here? Numbers in Sass are the same as math.
The unit is significant. You can divide 20px by 2px, but dividing 20 by 2px
doesn't make sense.

**Comment by wanghao0557** [comment]
@xzyfer 
Sorry, I didn't express clearly.
When I use the math operators like "+, -, *, /, and %", only "/" can't compile the correct results.
![20160815102515](https://cloud.githubusercontent.com/assets/1477919/17654169/afc203ea-62d2-11e6-8690-7b27ab817356.png)

**Comment by majabee** [comment]
try (20/ 2) I had division problems too.

**Comment by xzyfer** [comment]
@wanghao0557 `/` is treated special in Sass. You can use http://www.sassmeister.com/ to compare LibSass (gulp-sass) and Ruby Sass. If you find difference please file a bug with at https://github.com/sass/node-sass/issues.
