### ISSUE TITLE
 messageOriginal: Undefined variable: "$btn-line-height".     relativePath: node_modules\bootstrap\scss\_buttons.scss

### ISSUE THREAD

**Issue by qq645381995** [dlmanning/gulp-sass#527]
use  bootstrap@4.0.0-alpha.3   
button error

`Message:
    node_modules\bootstrap\scss\_buttons.scss
Error: Undefined variable: "$btn-line-height".
        on line 10 of node_modules/bootstrap/scss/_buttons.scss
>>   line-height: $btn-line-height;
   ---------------^

Details:
    formatted: Error: Undefined variable: "$btn-line-height".
        on line 10 of node_modules/bootstrap/scss/_buttons.scss
>>   line-height: $btn-line-height;
   ---------------^

    column: 16
    line: 10
    file: node_modules/bootstrap/scss/_buttons.scss
    status: 1
    messageFormatted: node_modules\bootstrap\scss\_buttons.scss
Error: Undefined variable: "$btn-line-height".
        on line 10 of node_modules/bootstrap/scss/_buttons.scss
>>   line-height: $btn-line-height;
   ---------------^

    messageOriginal: Undefined variable: "$btn-line-height".
    relativePath: node_modules\bootstrap\scss\_buttons.scss`

**Comment by xzyfer** [comment]
What is your gulp-sass config?

**Comment by qq645381995** [comment]
'use strict';

var path = require('path');
var gulp = require('gulp');
var conf = require('./conf');
var browserSync = require('browser-sync');
var $ = require('gulp-load-plugins')();

var wiredep = require('wiredep').stream;
var _ = require('lodash');

gulp.task('styles-reload', ['styles'], function () {
  return buildStyles()
    .pipe(browserSync.stream());
});

gulp.task('styles', function () {
  return buildStyles();
});

// 构建 css 样式表
var buildStyles = function () {
  var sassOptions = {
    includePaths: conf.includePaths,
    style: 'expanded'
  };
  // 使用 inject 的方式 处理注入的 scss 模块
  // `!` 排除在外的文件
  var injectFiles = gulp.src([
    path.join(conf.paths.src, '/sass/**/_*.scss')
    //'!' + path.join(conf.paths.src, '/sass/main.scss')
  ], {read: false});

  var injectOptions = {
    transform: function (filePath) {
      filePath = filePath.replace(conf.paths.src + '/sass/', '');
      //$.util.log('@import "' + filePath + '";');
      return '@import "' + filePath + '";';
    },
    starttag: '// injector',
    endtag: '// endinjector',
    addRootSlash: false
  };

  return gulp.src([
    path.join(conf.paths.src, '/sass/main.scss')
  ])
    // 注入文件
    .pipe($.inject(injectFiles, injectOptions))
    // 处理 bower 引用
    .pipe(wiredep(_.extend({}, conf.wiredep)))
    // 初始化 sourcemaps
    .pipe($.sourcemaps.init())
    // sass convert css
    .pipe($.sass(sassOptions)).on('error', conf.errorHandler('Sass'))
    // 自动处理前缀
    .pipe($.autoprefixer()).on('error', conf.errorHandler('Autoprefixer'))
    // source map 处理结束
    .pipe($.sourcemaps.write('maps'))
    // 写入 tmp 目录
    .pipe(gulp.dest(path.join(conf.paths.tmp, '/serve/app/')));
};

**Comment by qq645381995** [comment]
'use strict';

var path = require('path');
var gulp = require('gulp');
var conf = require('./conf');
var browserSync = require('browser-sync');
var $ = require('gulp-load-plugins')();

var wiredep = require('wiredep').stream;
var _ = require('lodash');

gulp.task('styles-reload', ['styles'], function () {
  return buildStyles()
    .pipe(browserSync.stream());
});

gulp.task('styles', function () {
  return buildStyles();
});


var buildStyles = function () {
  var sassOptions = {
    includePaths: conf.includePaths,
    style: 'expanded'
  };

  var injectFiles = gulp.src([
    path.join(conf.paths.src, '/sass/**/_*.scss')
    //'!' + path.join(conf.paths.src, '/sass/main.scss')
  ], {read: false});

  var injectOptions = {
    transform: function (filePath) {
      filePath = filePath.replace(conf.paths.src + '/sass/', '');
      //$.util.log('@import "' + filePath + '";');
      return '@import "' + filePath + '";';
    },
    starttag: '// injector',
    endtag: '// endinjector',
    addRootSlash: false
  };

  return gulp.src([
    path.join(conf.paths.src, '/sass/main.scss')
  ])

    .pipe($.inject(injectFiles, injectOptions))

    .pipe(wiredep(_.extend({}, conf.wiredep)))

    .pipe($.sourcemaps.init())
    // sass convert css
    .pipe($.sass(sassOptions)).on('error', conf.errorHandler('Sass'))
    
    .pipe($.autoprefixer()).on('error', conf.errorHandler('Autoprefixer'))

    .pipe($.sourcemaps.write('maps'))

    .pipe(gulp.dest(path.join(conf.paths.tmp, '/serve/app/')));
};

**Comment by xzyfer** [comment]
Please provide the *gulp-sass* config. The rest of your gulp file does not concern gulp-sass.

**Comment by xzyfer** [comment]
In this case we need the of `sassOptions`.

**Comment by qq645381995** [comment]
var sassOptions = {
    includePaths: conf.includePaths,
    style: 'expanded'
  };

conf.includePaths=  exports.includePaths = [
  'node_modules/bootstrap/scss' 
];

**Comment by xzyfer** [comment]
It looks like your glob is incorrect. You appear to be compiling an file whose name begins with an underscore (`_`). You should never directly compile a `.scss` or `.sass` file that starts with an `_`.

**Comment by qq645381995** [comment]
includePaths: [
    'node_modules/bootstrap/scss' ,
  ]  
includePaths is  catalogue  
Where are you saying you want to change?

**Comment by xzyfer** [comment]
I don't understand what you mean. You have a bad glob in your gulp config. Probably something here. I don't understand what this is doing but it looks wrong.

```
var injectFiles = gulp.src([
path.join(conf.paths.src, '/sass/*/_.scss')
//'!' + path.join(conf.paths.src, '/sass/main.scss')
], {read: false});
```

**Comment by qq645381995** [comment]
The question seems to be here, but how do you write?

**Comment by xzyfer** [comment]
I don't understand what this code is trying to do. You need to make sure that your glob's do not match files that begin with an `_`.


```
path.join(conf.paths.src, '/sass/*/_.scss')
```

This looks like you're **only** matching files that begin with an `_` which will not work.

My guess is what you want is maybe

```
var injectFiles = gulp.src([
  path.join(conf.paths.src, '/sass/main.scss')
], {read: false});
```

Unfortunately we cannot help you with gulp. You'll need to read their documentation or ask a question on stackoverflow.
