### ISSUE TITLE
Illegal instruction Error. When '#' and '*' appear in the scss file. Use the windows7 .

### ISSUE THREAD

**Issue by AtomicRose** [dlmanning/gulp-sass#528]
# scene 1

```
*{
    font-size: 14px;
}
```
# scene 2

a.scss

```
$bgColor: #f00;
```

b.scss

```
@import "a.scss"
.box{
    background: $bgColor;
}
```

when I use the gulp-sass to compile the scss file. It will throw a error `/c/Users/Administrator/AppData/Romaing/npm/gulp: line 14: 9896 Illegal instruction     node "$basedir/node_modules/gulp/bin/gulp.js" "$@"`

But the same code and the same node_modules version in Mac or Linux. It will success.

Who can help me?

**Comment by xzyfer** [comment]
What version of node-sass are you using?

```
npm ls node-sass
```

I am unable to reproduce this locally. Please update your gulp-sass.

**Comment by AtomicRose** [comment]
gulp-sass@2.3.2
node-sass@3.8.0

**Comment by xzyfer** [comment]
I can't cause this error. I suggest selectively removing parts of your gulp file until you find what is causing the error. I don't believe it is gulp-sass.

**Comment by xzyfer** [comment]
I am testing on OSX. I am unable to test on Windows however our window tests pass.

**Comment by AtomicRose** [comment]
yeah, I know it tests pass on OSX. And try your ways, I remove the other parts of the gulp file. 
It only like this, but still throw the same error.
```
var gulp = require('gulp');
var sourcemaps = require('gulp-sourcemaps');
var sass = require('gulp-sass');

gulp.task('framework-sass', function () {
    return gulp.src('framework/framework.scss')
        //.pipe(sourcemaps.init())
        .pipe(sass().on('error', sass.logError))
        //.pipe(sourcemaps.write())
        .pipe(gulp.dest('dist/framework/'));
});
```

**Comment by popoAOAOgroan** [comment]
same error :(

**Comment by simskij** [comment]
is scene 1 a separate scss file? it doesnt really tell from your issue. Also, what happens if you put a semicolon after the import in b.scss? If you dont include the semicolon, things will break for sure.

**Comment by simskij** [comment]
You forgot the semicolon after the import in b.scss.
Also, is scene 1 a separate scss file?

**Comment by AtomicRose** [comment]
Because the windows version. You must better than win7 sp1. sp1. sp1😔
