### ISSUE TITLE
Import directives may not be used within control directives or mixins.

### ISSUE THREAD

**Issue by wideckop** [dlmanning/gulp-sass#531]
CSS file:
```
@include breakpoint() {
  @import "header";
}
```
Mixin file:
```
@mixin breakpoint() {
   @media (min-width: 480px) {@content;}
}
```
Sass fails with:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: src\main.scss
Error: Import directives may not be used within control directives or mixins.
        on line 59 of src/main.scss
>>    @import "header";
   -----------^
```

**Comment by wideckop** [comment]
This issue was fixed in Sass Ruby: https://github.com/sass/libsass/issues/1724

**Comment by xzyfer** [comment]
The issue you've linked to is the same error message but different circumstances. As the error states you cannot use `@import` inside of a mixin. This is part of the Sass language. Issues regards the Sass language need to opened with https://github.com/sass/sass
