### ISSUE TITLE
gulp.watch doesn't notice new files

### ISSUE THREAD

**Issue by sanbor** [dlmanning/gulp-sass#532]
I found a bug which I'm not sure if it's an issue of gulp or gulp-sass.

The styles of my app has the following structure:

```
  /styles
    /moduleA
      moduleA.scss
      moduleA.css
    /moduleB
      moduleB.scss
      moduleB.css
```

And I have the following tasks in gulp:

```
gulp.task('sass', function () {
    return gulp.src(['styles/**/*.scss'],{base: "./"})
        .pipe(sourcemaps.init())
        .pipe(sass().on('error', sass.logError))
        .pipe(sourcemaps.write())
        .pipe(gulp.dest("./"));
});

gulp.task('sass:watch', function () {
    gulp.watch(cfg.rootPath + '**/*.scss', ['sass']);
});
```

The goal is to place the generated `.css` next to the `.scss`. This works well for existing `.scss` files but for some reason it doesn't work for new files.

Surprisingly, if I manually call the `sass` task it works as expected.

```
gulp.task('sass:watch', function () {
    gulp.watch(cfg.rootPath + '**/*.scss', function() {
        gulp.start('sass');
    });
});
```

Any clue why is this happening? Thanks!

**Comment by xzyfer** [comment]
This is a feature/bug with gulp. It's only watching files that match your glob (`cfg.rootPath + '**/*.scss'`) at the time you ran the command.

**Comment by sanbor** [comment]
Thank you for your promptly reply.
