### ISSUE TITLE
File to import not found or unreadable on save in Sublime Text 3.

### ISSUE THREAD

**Issue by makedonec88** [dlmanning/gulp-sass#534]
So, I've started to have this error when i change Atom to Sublime text 3.
And now, when i'm working on file and hit "save", gulp give me this error:

`Error: app\sass\style.scss`
`Error: File to import not found or unreadable: templates/card`
`Parent style sheet: D:/git/happiness/app/sass/style.scss
on line 26 of app/sass/style.scss`
`@import 'templates/card';`

All my files imports in one "style.scss". If i save another, not modified file - everything saves ok.

Windows 10, Sublime Text 3, gulp - 3.9.1, gulp-sass 2.3.2, sass - 3.4.22.

**Comment by xzyfer** [comment]
You need to turn on atomic saves in Sublime Text. You can google how to do this.
