### ISSUE TITLE
how to actually include the contents of a @include?

### ISSUE THREAD

**Issue by gerardolima** [dlmanning/gulp-sass#535]
Hi, all, I'm new to sass pre-processor and I'm really not sure if this is a trivial issue

I'm moving from Grunt to Gulp and noticed that [gulp-sass](https://www.npmjs.com/package/gulp-sass) does not include the contents of files referenced by `@import "reset.css"` statements. Instead, it normalizes the url reference, as `@import url(reset.css)`. My intention is to have a single CSS reference on my `index.html`, that would be the concatenation of my CSS dependencies.

It's a simple _read-file-and-output-contents_ operation, but I bet this is already implemented and I just don't know where to find it -- I'm still new on this ecosystem and would not like to spend time reinventing the wheel.

This question has also been published on [stackoverflow](http://stackoverflow.com/questions/39486891/scss-how-to-actually-include-the-contents-of-a-include)

**Comment by xzyfer** [comment]
Sass won't inline imports for `.css` files. Check out the Sass documentation for [@import](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import)
