### ISSUE TITLE
amazon .node file blocked by corporate firewall

### ISSUE THREAD

**Issue by sitrobotsit** [dlmanning/gulp-sass#536]
It seems that the .node file is hosted on amazonaws and I get a ECONNRESET error when trying "npm install -g gulp-sass". This is because I'm behind a corporate firewall at the moment. I have access (via proxy) to github and npm registry but aws isn't allowed . I appreciate that this is a "me" problem. However, other npm packages install fine. I'm wondering if there's an alternate hosting option?

**Comment by xzyfer** [comment]
The binaries are downloaded from the [GitHub release](https://github.com/sass/node-sass/releases/tag/v3.10.0) and are hosted on `https://github.com`.

For people with restrictive firewalls you can configure a proxy via the standard `HTTP_PROXY` and `HTTPS_PROXY` environment variables, or via the `npm config` CLI.

Alternative the node-sass installer has a [couple of configuration options](https://github.com/sass/node-sass#binary-configuration-parameters) for self-hosting the binaries.

**Comment by sitrobotsit** [comment]
Great, thanks. I'll give the self-hosting a go. Just FYI, GitHub uses AWS as the end point store for the binaries. So that's why even though I have Github whitelisted, because AWS isn't, the install fails.
