### ISSUE TITLE
Issue on OS X 64-bit

### ISSUE THREAD

**Issue by kchetan92** [dlmanning/gulp-sass#539]
I am unable to run gulp-sass due to some issue in node-sass here's the error:

Error: Node Sass does not yet support your current environment: OS X 64-bit wi  th Unsupported runtime (50)
  For more information on which environments are supported please see:
  https://github.com/sass/node-sass/releases/tag/v3.10.0
  
  - index.js:13 Object.<anonymous>
    [styleguide]/[node-sass]/lib/index.js:13:11
  
  - module.js:20 require
    internal/module.js:20:19
  
  - index.js:187 Object.<anonymous>
    [styleguide]/[gulp-sass]/index.js:187:21

**Comment by xzyfer** [comment]
This is a bug with electron. You'll need to rebuild your native extensions.
Either npm rebuild or electron rebuild should help.

**Comment by kchetan92** [comment]
Thanks for the prompt response @xzyfer , appreciate the help

**Comment by nmccready** [comment]
@kchetan92 close the issue please
