### ISSUE TITLE
Enable "data" parameter

### ISSUE THREAD

**Issue by Takeno** [dlmanning/gulp-sass#540]
It should be useful to inject custom data in building time.

My scenario is a _$theme_ variable. All my code depends from _THEME_ environment var, but right now I had to change manually the _$theme_ variable inside my scss. Passing data to node-sass allows me to inject vars.

**Comment by xzyfer** [comment]
This has been discussed many time. We will not be adding this. You can read more in https://github.com/dlmanning/gulp-sass/issues/302
