### ISSUE TITLE
Issue with includePath, it works randomly!

### ISSUE THREAD

**Issue by manuel-di-iorio** [dlmanning/gulp-sass#543]
``` js
Error in plugin 'sass'
Message:
    ..\css\style.scss
Error: File to import not found or unreadable: includes/feed.scss
       Parent style sheet: D:/my_folder/app/raw_assets/css/style.scss
        on line 24 of ../css/style.scss
>> @import "includes/profile.scss";
[BS] 2 files changed (fonts.css, navbar.css)
//should be 10 files changed, not 2
```

When I hit the Ctrl+S key of my text editor, I get this error most of the times, but not always. Read again, when saving, **not** always the error is thrown :\ 
Also, it happens only when modifying the includes, not with the main scss file.

My gulp task:

``` js
scssOptions = 
    errLogToConsole: true
    outputStyle: 'compressed'
    includePaths: [ 'raw_assets/css/includes', 'css/includes', 'includes' ] # I tried different paths, none of them is apparently correct..

gulp.task 'scss', ->
    gulp.src( srcPath )
      .pipe scss.sync(scssOptions).on('error', scss.logError) # Same error even if not using .sync()
      .pipe autoprefixer() 
      .pipe gulp.dest(scssOutput)
      .pipe browserSync.reload({stream: true})

gulp.task 'scss-watch', ->
    gulp.watch srcPath, [ 'scss' ]

->  
    gulp.start 'scss', 'scss-watch'
```

Folder structure:

```
| /raw_assets
     |___ /gulpfile
         |___ gulpfile.coffee
         |___ /folder of gulp tasks

    |___ /scss
        |___ /includes
            |___ various .scss includes files
        |___ style.scss

| / app
    |___ css
        |___ style.css
```

PS: I'm on win10 x64
gulp v. 3.9.1
gulp-sass v.2.3.2

**Comment by KolayKovalchuk** [comment]
+1 having the same issue

**Comment by nomood89** [comment]
+1 having the same issue too, anyone with the way to solve this? 

To explain further on my issue, the error will occurs roughly 50% of the time with a empty line break between styles (or at last row) in the scss file. The first time I **CTRL + S** to save, it will hit the error. However, on the 2nd save (without any changes), it can compile properly.

**Comment by technbuzz** [comment]
I am also experiencing same issue. When I went through the [common issues](https://github.com/dlmanning/gulp-sass/wiki/Common-Issues-and-Their-Fixes) where basically `autosave:true` solves it for **Sublime Text**. But, in my case it's **Visual Studio Code on Windows**.

Every time I had to make change or simple line break to **main file** *(which imports all the partials)* in order to get away with that. Next time when I make change to partial file, again I get the same error.

**Comment by amit-coditas** [comment]
@technbuzz : I use VSCode too, have you found any solution?

**Comment by technbuzz** [comment]
@amit-coditas I moved from **gulp-sass** to **gulp-ruby-sass**. For windows I had to install Ruby and then `gem install ruby`. That worked for me.

**Comment by xzyfer** [comment]
You need to configure your editor to do atomic saves.

**Comment by manuel-di-iorio** [comment]
Thank you @xzyfer 
Even if I'm not using gulp anymore, this could be useful in future or for other people 👍

**Comment by Harvzor** [comment]
I can't figure out how to fix this properly so I've just stuck a wait into my pipeline (which is pretty horrible).

https://www.npmjs.com/package/gulp-wait

```
.pipe(wait(500))
```

**Comment by Harvzor** [comment]
Switching to Gulp@4.0.0 seems to have helped - I no longer need the hacky `wait` solution.
