### ISSUE TITLE
Missing documentation for how to use with Compass

### ISSUE THREAD

**Issue by leosuncin** [dlmanning/gulp-sass#545]
There are [various issues](https://github.com/dlmanning/gulp-sass/issues?utf8=%E2%9C%93&q=is%3Aissue%20compass) related to how to properly import compass with this gulp plugin, in order to prevent more people open a new issue I think is necesary a example of [how to use compass](https://github.com/dlmanning/gulp-sass/issues/38#issuecomment-253614085) and don't die in the process.  
That why I will send a pull request of `README.md` with the steps and an example of configuration.

**Comment by xzyfer** [comment]
IMO this does not belong in this project. It's a Sass community issue to educate Sass developers that

- compass is a dead project
- compass will never work with node-sass/gulp-sass
- bourbon is the only true compass mixin polyfill library

These things should be address is community blog posts and newsletters. It's certainly out of scope for this project.
