### ISSUE TITLE
Is it possible to combine multiple SCSS files in to a single file?

### ISSUE THREAD

**Issue by ajithr** [dlmanning/gulp-sass#548]
I need to combine multiple scss file into a single file like reported in this [stackoverflow](http://stackoverflow.com/questions/37133297/combine-all-sass-files-into-a-single-file) question. Is this possible or not in gulp-sass?

**Comment by konekoya** [comment]
I think you need [gulp-concat](https://www.npmjs.com/package/gulp-concat) or [cssnano](https://github.com/ben-eb/cssnano)

**Comment by xzyfer** [comment]
gulp-sass just turns a sass file into a css file. Anything other than that needs to be done by other plugins.
