### ISSUE TITLE
Update to use Libsass 2.0

### ISSUE THREAD

**Issue by bigandy** [dlmanning/gulp-sass#55]
Libsass has just [updated to 2.0](https://github.com/hcatlin/libsass/releases/tag/v2.0) and it would be awesome if the gulp-sass could be updated to use this.

**Comment by jmm** [comment]
@idflood @chrisdl @cspiegl @jsheffers Just FYI, doing that will result in any changes to the file content from earlier in the gulp pipeline (e.g. earlier plugins) being discarded. See #158.
