### ISSUE TITLE
why gulp-sass is outputing .css files instead of .scss files after minification

### ISSUE THREAD

**Issue by Sri276286** [dlmanning/gulp-sass#551]
Can anyone please explain why gulp-sass is outputing .css files instead of .scss files after minification.
what fix needs to be done to get .scss files after minification?

**Comment by xzyfer** [comment]
Turning scss into css is what gulp-sass does. It's the entire point of the project.

**Comment by Sri276286** [comment]
Any Idea what needs to be done to minify .scss without converting to .css

**Comment by xzyfer** [comment]
Why would you ever want to minify scss? Browsers cannot understand scss.

**Comment by Sri276286** [comment]
but in my project I am including .scss files and if .scss get minified to .css .

I am getting an error like "file not found". How can I overcome that

**Comment by xzyfer** [comment]
I don't know. This is a situation I have never seen. You'll need some kind of gulp rename plugin.

**Comment by Sri276286** [comment]
Did you get my point. I am minifying all html and .scss files in my project. In html files, I am including .scss files and after minification "Getting an error like file not found".

Thanks for help

**Comment by xzyfer** [comment]
I'm sorry I don't understand, gulp-sass turns scss into css. If you want to change the filename after gulp-sass has run you need to do that if you gulp file.
