### ISSUE TITLE
Inline base 64 on properties using url()

### ISSUE THREAD

**Issue by daminufe** [dlmanning/gulp-sass#555]
I am using [angular-toastr](https://github.com/Foxandxss/angular-toastr) on my project, and I have a gulp task that looks like this:

`.pipe(sass({includePaths: ['./node_modules']})`

And during the process, is adding the `node_modules` prefix to the base64 images.

![whatsapp image 2016-11-09 at 16 11 11](https://cloud.githubusercontent.com/assets/4832774/20143323/e53a0e1e-a698-11e6-966d-73d4f668948a.jpeg)

Is that a bug on the gulp-sass, or am I doing something wrong?

**Comment by daminufe** [comment]
@xzyfer any thoughts on that?

**Comment by xzyfer** [comment]
Sorry no idea. Seems like an issue with angular-toastr. Please open an issue there.
