### ISSUE TITLE
Error when using 'width: 256px' 

### ISSUE THREAD

**Issue by sorcamarian** [dlmanning/gulp-sass#556]
A error appears when I use the rule:  `width: 256px`.
When I change the value to `255px`, no error is thrown.
![256error](https://cloud.githubusercontent.com/assets/12509753/20248626/af8178f6-a9f0-11e6-8393-5ab9f55e504f.png)

Code:
```
@mixin underline-icon(){
  position       : relative;

  &:after{
    background   : url($images-path + "/general/underline-icon.png");
    height       : 33px;
    width        : 255px;
    position     : absolute;
    right        : 40px;
    bottom       : -33px;
    content      :  "";
  }
}

.underline-icon{
  @include underline-icon();
}
```

Versions: 
"gulp": "^3.9.1",
 "gulp-sass": "^2.3.2"

**Comment by artemsky** [comment]
Tested it with gulp 4. All is okay.

```
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-sass": "^2.3.2"
