### ISSUE TITLE
gulp task not working (can not find node-sass/vendor)

### ISSUE THREAD

**Issue by seeliang** [dlmanning/gulp-sass#562]
not sure what went wrong

version:
"gulp-sass": "2.3.2"

in terminal 
if i run gulp 

```terminal
Listening on port 1337
[1] fs.js:951
[1]   return binding.readdir(pathModule._makeLong(path), options.encoding);
[1]                  ^
[1]
[1] Error: ENOENT: no such file or directory, scandir '/Users/someone/Documents/somefolder/node_modules/gulp-sass/node_modules/node-sass/vendor'
```

my current fix 
install node-sass as dev dependency

**Comment by xzyfer** [comment]
Run npm rebuild node-sass

**Comment by bf** [comment]
I have the same issue and `npm rebuild` did not work.

**Comment by xzyfer** [comment]
Error: EACCES: permission denied, mkdir
'/home/yupnano/gitHub/metaMask/metamask-extension/node_modules/gulp-sass/node_modules/node-sass/vendor'


Make sure you have the correct permissions. If you need to run as sudo
make sure you use the --unsafe-perms flag with npm install
