### ISSUE TITLE
Grunt skips the scss file that triggers compiling

### ISSUE THREAD

**Issue by jackfaulkner** [dlmanning/gulp-sass#564]
Hi, I'm having trouble compiling a sass file with several partials. 

I have a Gulp task watching for changes (all .scss files are in the same folder). When I save a partial the main.scss file compiles, however it appears to skip the partial I just saved. And when I save main.scss, it doesn't compile anything. I have to save a partial to get main.scss to compile at all.

I'm working on the sass files in Coda which pushes them to a server when I save. Could the issue be the speed of the server?

package.json
```json
{
  "name": "Default",
  "version": "1.0.0",
  "description": "Basic npm package file for compiling SASS via Gulp.",
  "main": "gulpfile.js",
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-sass": "^2.3.2",
    "gulp-sourcemaps": "^1.6.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Red Tiki",
  "license": "ISC"
}
```
Gulpfile.js
```javascript
var gulp = require('gulp');
var sass = require('gulp-sass');
var autoprefixer = require('gulp-autoprefixer');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('styles', function() {
	// Output styles.css
  gulp.src('./sass/main.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(sourcemaps.init())
    .pipe(autoprefixer({
        browsers: ['last 3 versions'],
        cascade: false
    }))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('./css'));
});

// Watch task
gulp.task('default',function() {
  gulp.watch('sass/*.scss',['styles']);
});
```
main.scss
```scss
...

@import 'home.scss';

...
```

The same thing happens if I remove the autoprefixer and sourcemap plugins. 

Any help is appreciated. I'm fairly new to Gulp; sorry if this has been asked before or I missed something in the docs. Thanks!

**Comment by xzyfer** [comment]
This is likely due to your editor not doing atomic saves. If you're using Sublime Text make sure atomic saving is enabled. If you're using another editor google for how to enable atomic saves.
