### ISSUE TITLE
node-sass dependency looks for non-existent version

### ISSUE THREAD

**Issue by karlgroves** [dlmanning/gulp-sass#566]
gulp sass looks for a version of node-sass that does not exist
https://github.com/dlmanning/gulp-sass/blob/master/package.json#L26 lists `"node-sass": "^3.4.2",`

This results in broken builds for people who depend on your plugin:
```
> node-sass@3.4.2 install /home/travis/[REDACTED]/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js
Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/linux-x64-48_binding.node": 
```

Latest version of node-sass, published 2 weeks ago, is 3.13.0

**Comment by xzyfer** [comment]
node-sass@v3.4.2 does exists, however it does not support Node 6. Node 6 support was added much later in v3.8.0. Do a fresh npm install to get the latest node-sass.
