### ISSUE TITLE
Unable to pass options

### ISSUE THREAD

**Issue by venelinpetrov** [dlmanning/gulp-sass#569]
Is there something wrong with this code:

```javascript
.pipe($.sass({
    outFile: 'styles.css'
})
```

I can't see gulp-sass to do anything when passing options. In the documentation you say 

> Pass in options just like you would for node-sass; they will be passed along just as if you were using node-sass.

**Comment by xzyfer** [comment]
This is not how gulp works. The input will be `pipe`d into `sass` and the output needs to be piped some where. If you want to write to disk you need to `pipe` to `dest`.

**Comment by venelinpetrov** [comment]
I know that you should pipe to somewhere... I didn't paste all my code, it's unnecessary. Is it true that you can't pass `data` parameter? This is the reason I went for esoteric ways to achieve my goal 
> ...Except for the data option which is used by gulp-sass internally.

**Comment by xzyfer** [comment]
Correct you cannot pass the data option. That breaks the semantics of gulp.
You can search closed issue for a detailed discussion on why we do not
support the data option and some alternative approaches.
