### ISSUE TITLE
Media query expression must begin with '('

### ISSUE THREAD

**Issue by matometaru** [dlmanning/gulp-sass#570]
$breakpoints: (
  'tb': 'screen and (min-width: 768px)',
  'pc': 'screen and (min-width: 1025px)',
  'pclg': 'screen and (min-width: 1200px)',
);
// media query
@mixin mq($breakpoint: md) {
  @media #{map-get($breakpoints, $breakpoint)} {
    @content;
  }
}

**Comment by xzyfer** [comment]
I cannot reproduce this with the latest 3.x or 4.x release.

```sass
$breakpoints: (
    'tb': 'screen and (min-width: 768px)',
    'pc': 'screen and (min-width: 1025px)',
    'pclg': 'screen and (min-width: 1200px)',
);

@mixin mq($breakpoint: md) {
    @media #{map-get($breakpoints, $breakpoint)} {
        @content;
    }
}

@include mq(tb) {
    foo { a: b; }
}
```
```css
@media screen and (min-width: 768px) {
  foo {
    a: b; } }
```

**Comment by xzyfer** [comment]
Try updating your node-sass version. Running `npm outdated` should give you an indication of how out of date your install is.
