### ISSUE TITLE
Slow Compilation

### ISSUE THREAD

**Issue by ritchieanesco** [dlmanning/gulp-sass#571]
We have 53 files that follow similar code below.

@charset "UTF-8";

/*------------------------------------*\
    #MAIN
\*------------------------------------*/

$mqs: true !default;
$critical-css-only: false !default;
$critical-css-override: false !default;

@import "../bower_components/bourbon/dist/bourbon",
"../bower_components/neat/app/assets/stylesheets/neat",
"../bower_components/neat/app/assets/stylesheets/neat-helpers"; // or "neat-helpers" when in Rails

//Global setting with local overrides
@import "base/settings/global",
"en-hk/settings/global";

// base module settings
@import "base/settings/components",
"base/settings/modules";

//override module settings
@import "en-hk/settings/modules",
"en-hk/settings/components";

//base objects
@import "../../../node_modules/normalize.scss/normalize",
"base/objects/components",
"base/objects/modules";

Each file branches off to their set of imports and uses a lot of sass mappings to pass in values to the styling declarations.

We have this setup in grunt and we are now porting it over to gulp however I was surprised that it took **grunt 8.8 seconds** for the sass compilation to complete while it took **gulp 22 seconds** to complete.

I thought it was the imports so i put them in the includePaths options but there was no difference. Thoughts?

Here are the specs for my setup:

- NPM version (`npm -v`): 4.0.3
- Node version (`node -v`): 6.9.1
- Node Process (`node -p process.versions`):
{ http_parser: '2.7.0',
  node: '6.9.1',
  v8: '5.1.281.84',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' }
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):
├─┬ gulp-sass@3.0.0
│ └── node-sass@3.13.1 
└── node-sass@4.0.0

**Comment by xzyfer** [comment]
This is common. Gulp tends to be slower for things like Sass because of how it uses streams. This is unavoidable simply due to how gulp works.
