### ISSUE TITLE
Bus error (exit code 135 / signal 7: SIGEMT) on Linux Mint

### ISSUE THREAD

**Issue by bra1n** [dlmanning/gulp-sass#572]
Hi,

it seems that gulp-sass still doesn't support Linux Mint out of the box. 
I tried 3.13.1 as well as 4.0.0, in both cases I get a "Bus error" wenn running an empty Gulpfile that only has the line `var sass = require('gulp-sass');` in it.

Node: v6.9.2
NPM: 3.10.9
OS: Linux mint 4.4.0-53-generic #74-Ubuntu SMP x86_64 GNU/Linux

Gulpfile:
```
var gulp = require('gulp');
var sass = require('gulp-sass');

gulp.task('default', function() {
  // do nothing
});
```

If I remove the line `var sass = require('gulp-sass');`, Gulp runs fine. I also tried everything from #401 but didn't get any further.

**Comment by xzyfer** [comment]
Please try the latest node-sass.
