### ISSUE TITLE
npm install gulp-sass not working(Exit status -4058 )

### ISSUE THREAD

**Issue by neu10** [dlmanning/gulp-sass#579]
Getting below error while installing package:- 

Tried with latest node and npm versions still the same.

$ npm install -g node-sass
C:\Program Files\nodejs\node-sass -> C:\Program Files\nodejs\node_modules\node-sass\bin\node-sass

> node-sass@4.1.1 install C:\Program Files\nodejs\node_modules\node-sass
> node scripts/install.js

C:\Program Files\nodejs
└── (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-sass"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! file C:\Windows\system32\cmd.exe;
npm ERR! path C:\Windows\system32\cmd.exe;
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Windows\system32\cmd.exe;

npm ERR! node-sass@4.1.1 install: `node scripts/install.js`
npm ERR! spawn C:\Windows\system32\cmd.exe; ENOENT
npm ERR!
npm ERR! Failed at the node-sass@4.1.1 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
C:\Program Files\nodejs
└── (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-sass"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.1.1 install: `node scripts/install.js`
npm ERR! Exit status -4058
npm ERR!
npm ERR! Failed at the node-sass@4.1.1 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Resolve\Trunk\DEL_Resolve\WebProjects\npm-debug.log
npm ERR! code 1

**Comment by xzyfer** [comment]
Looks like npm wasn't able to download the files into that directory. 

```
C:\Program Files\nodejs
└── (empty)
```

It's likely a permissions issues. You should never install gulp-sass, or node-sass globally.
