### ISSUE TITLE
Error when using `:host()` syntax

### ISSUE THREAD

**Issue by PascalPrecht** [dlmanning/gulp-sass#58]
When using `:host()` syntax in scss (which is a syntax you need to style web components, because they have encapsulated style) I get the following error from `gulp-sass`:

```sh
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
[gulp] Error in plugin 'gulp-sass': source string:24: error: invalid argument to :host(...)

    at opts.error (/Users/pp/projects/polyonic/polyonic-button/node_modules/gulp-sass/index.js:67:17)
    at onError (/Users/pp/projects/polyonic/polyonic-button/node_modules/gulp-sass/node_modules/node-sass/sass.js:72:16)
```

However, when compiling the same file with `sass` from the command line, it works.

Installed `sass` version is `Sass 3.2.13 (Media Mark)`. So this has either something to do with this plugin, or with the sass implementation that is used by this plugin (AFAIK it uses `node-sass`, so maybe this issue has to be filed there).

Lemme know, if I can do anything to help out!

**Comment by Keats** [comment]
That was a node-sass issue (probably fixed since then)
