### ISSUE TITLE
Error message when there is no error

### ISSUE THREAD

**Issue by majabee** [dlmanning/gulp-sass#580]
gulp: 3.9.1
gulp-sass: 3.0.0

After I tried to run my gulp-sass task with a .scss file that a already used in other projects without problems, I got a strange error message that didn´t make any sense.
the original code in my .scss file is this:
```
.notice {
	visibility: hidden;
	position: fixed;
	z-index: 9999;
	right: 0;
	left: 0;
	bottom: 0;
	background-color: #000000;
	color: #fff;
}
```
the error message i got was this:
```
Invalid CSS after "...tice {":
expected "}", was "{"
    relativePath:
src/core/scss/components/notice.scss
```
I first thought something might be wrong with my file since there was no code error in it. So i decided to delete that file and created a testfile. In this completely new testfile that I placed in the same directory the other file was in before I wrote in the following:
`body { background-color:#f00; }` and I started the sass task again.
This error message is what I got:

```
Invalid CSS after "...nd-color:#f00;}":
expected 1 selector or at-rule, was "{}"
        on line 1 of src/core/scss/components/temp.scss
>> body{background-color:#f00;} {}
   -----------------------------^

```
this file is completely new, I didn´t copy and paste something in it so there are no hidden characters
or something like that in it . What can it be? And what can I do? 

The strange thing about it is that I changed the src  path in the sass task to another scss directory and ran the task and everything was good as expected.

**Comment by majabee** [comment]
I found out after a lot of testing what the problem was. Somehow the option indentedSyntax:true caused this error. When I removed it everything worked ok again

**Comment by xzyfer** [comment]
Indented syntax is Sass' old syntax

```sass
body
  background-color: #f00
```

It uses an entirely different parser so the SCSS syntax isn't valid.
