### ISSUE TITLE
Importing multiple files / partials in one @import statement fails to execute

### ISSUE THREAD

**Issue by selrond** [dlmanning/gulp-sass#581]
This is what Gulp throws
```
Error in plugin 'sass'
Message:
    src\sass\main.scss
Error: File to import not found or unreadable: abstracts/variables.
       Parent style sheet: C:/Users/Selrond/Desktop/Code/100DaysOfCode/003/src/sass/main.scss
        on line 4 of src/sass/main.scss
>> @import
   ^
```
a part of my `main.scss` file:
```sass
@import
  'abstracts/variables',
  'abstracts/functions',
  'abstracts/mixins';
```
As documented [in the official SASS docs](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import), it should work.

**Comment by gretzky** [comment]
I'm having the same exact issue, but with imports from node_modules and bower_components

**Comment by xzyfer** [comment]
Looks like you have not configured you're includePaths

Regards,
Michael
