### ISSUE TITLE
Watch SASS and all imports?

### ISSUE THREAD

**Issue by pizza2code** [dlmanning/gulp-sass#584]
Is there any way to watch a SASS file and all of its imports dynamically?  In my setup, the @imports can be from multiple directories.  Would like to handle addition/deletion of @import statements by starting/stopping watches on those files.

I've also looked at node-sass, but a solution did not appear obvious for that module either.

**Comment by xzyfer** [comment]
Please search the dozen other identical closed issues. This is not how gulp
works unfortunately.
