### ISSUE TITLE
Problems with running task 'sass'

### ISSUE THREAD

**Issue by markmans** [dlmanning/gulp-sass#587]
after installing gulp-sass and filling gulpfile.js, I can not run my task 'sass' in powershell on my Windows 10. It worked yesterday, but today something goes wrong...
---------------------------------------
// gulpfile.js
var gulp = require ( 'gulp'),
sass = require ( 'gulp-sass');

gulp.task ( 'sass', function () {
return gulp.src ( 'app / sass / *. sass')
.pipe (sass ())
.pipe (gulp.dest ( 'app / css /'));
});

// and run it in powershell... gulp sass
--------------------------------------------
And that notifies following

Using gulpfile.js .../.../
Starting 'sass'...

... and thats all is happening

 I've tried to update graceful-fs, and minimatch (as it was written after re-installation of npm, gulp and gulp-sass), but nothing happened

Please help

**Comment by xzyfer** [comment]
This doesn't seem related to gulp-sass.
