### ISSUE TITLE
Is it possible to emulate a conditional @import?

### ISSUE THREAD

**Issue by joelstransky** [dlmanning/gulp-sass#590]
I have a `main.scss` which I would like to have a conditional `@import '_variables.scss';` as it's first line.
Since sass doesn't support conditional imports, is there a way I might conditionally pipe that in during my gulp-sass task?
Thanks!

**Comment by xzyfer** [comment]
Technically no, but for environment specific variables you can fake it like this

https://github.com/sass/node-sass/issues/965#issuecomment-103384773

**Comment by joelstransky** [comment]
Thanks for the reply. I found a way to do it with gulp-header.
