### ISSUE TITLE
@import .scss file

### ISSUE THREAD

**Issue by soulcreate** [dlmanning/gulp-sass#592]
New version 3.1.0 not correct import .scss file in construction:
```
.nestly{
    @import "main.scss";
}
```
But version 2.3.2 do it perfect!

**Comment by jethrinfox** [comment]
Have the same problem with 3.1.0v. It 's looks like a bug. I have to downgrade to 2.3.2 to make it work for now.

**Comment by xzyfer** [comment]
Try latest node-sass.
