### ISSUE TITLE
Errors with CSS grid properties

### ISSUE THREAD

**Issue by freshyill** [dlmanning/gulp-sass#597]
The older version of libsass reports errors with CSS grid properties 

> Message: 
>     source/css/scss/modules/_layout.scss 
> Error: Invalid CSS after "...   \\[row1-start": expected expression (e.g. 1px, bold), was '] "fourth fourth fo' 
>         on line 47 of source/css/scss/modules/_layout.scss 
> &#62;&#62;     \[row1-start] "fourth fourth fourth"       [row1-end] 
>    ----^

Node-sass has already been updated to newer version of libsass, which now support grid. I confirmed locally that bumping node-sass to ^4.5.0 in gulp-sass fixes this issue.

**Comment by xzyfer** [comment]
Remove node_modules and npm install to get the latest node-sass.
