### ISSUE TITLE
Gulp Watcher throws undefined variable error but works when run directly

### ISSUE THREAD

**Issue by userdude** [dlmanning/gulp-sass#598]
**gulp-sass**: 3.1.0
**Gulp**: 3.9.1
**Node**: v6.9.4
**Yarn**: 0.21.3 
**OS**: CentOS Linux release 7.3.1611 (Core) 

-----

I have a very simple gulp script that attempts to build a site.scss file:

```
var gulp = require('gulp'),
    sass = require('gulp-sass');

var tasks = [],
    config = {
        publicDir: process.cwd()+'/public_html/assets',
        bootstrapPublicDir: process.cwd()+'/public_html/assets/sources/bootstrap-sass',
    };

gulp.task('test', function(){
    return gulp
        .src(config.publicDir+'/stylesheets/scss/site.scss')
        .pipe(sass().on('error', sass.logError))
        .pipe(gulp.dest(config.publicDir+'/stylesheets/compiled'))
    ;
});

gulp.task('watch', function(){
    gulp.watch(config.publicDir+'/stylesheets/scss/*.scss', ['test']);
});
```

As you can see, I'm watching any of the partials and site.css file in that directory, but the actual task only runs `site.css` directly. In other words, I don't know how this error is happening?

When I run `gulp test` directly, it builds perfectly; no issues. However, using `gulp.watch()`, it (more often than not) throws an error (there are several files it errors on, this is just one, but it's only ever one, so yes, they kind've round robin at times):

```
[16:11:20] Working directory /home/iwca7418
[16:11:20] argv: ["/usr/bin/node","/home/iwca7418/gulp","watch"]
[16:11:20] Using gulpfile ~/Gulpfile.js
[16:11:20] Starting 'watch'...
[16:11:20] Finished 'watch' after 14 ms
[16:11:24] Starting 'test'...
[16:11:24] Finished 'test' after 46 ms
[16:11:26] Starting 'test'...
[16:11:26] Finished 'test' after 23 ms
[16:11:28] Starting 'test'...
Error in plugin 'sass'
Message:
    public_html/assets/sources/bootstrap-sass/assets/stylesheets/bootstrap/_glyphicons.scss
Error: Undefined variable: "$bootstrap-sass-asset-helper".
        on line 14 of public_html/assets/sources/bootstrap-sass/assets/stylesheets/bootstrap/_glyphicons.scss
>>     src: url(if($bootstrap-sass-asset-helper, twbs-font-path('#{$icon-font-pat
   ----------------^

[16:11:28] Finished 'test' after 17 ms
```

Notice how the watcher actually did (seemingly?) run without error, then it errors. 

Some other notes:

* It isn't consistent; sometimes it's the local _variables.scss file, or it's Bootstrap's source _scaffolding.scss, or _glyphicons.scss. 
* I've debugged the paths (cwd, base) and I don't see anything different between `gulp test` and `gulp watch` with a file change event, meaning I don't think the path from the watcher is changing? 
* I've tried absolute paths all over the place, to no avail.
* I also tried running the task with `gulp.start('test')` from the watcher callback, didn't work.
* I see several other seemingly-similar issues, except those always seem to have an actual bad variable, mistake, or some other issue.
* I've read the docs (even vinyl-fs), I've looked at source code (which now I see why the stack trace is useless).

Here is what's in `./public_html/assets/stylesheets/scss/site.css`, what's in the Glyphicons file is the standard Bootstrap source:

```
/*!
 * Bootstrap v3.3.7 (http://getbootstrap.com)
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */

// Core variables and mixins
@import "./public_html/assets/stylesheets/scss/variables";
@import "./public_html/assets/sources/bootstrap-sass/assets/stylesheets/bootstrap/mixins";
@import "./public_html/assets/stylesheets/scss/mixins";
// @import "./public_html/assets/stylesheets/scss/mixins/fonts";
// @import "./public_html/assets/stylesheets/scss/mixins/grid-framework";
// @import "./public_html/assets/stylesheets/scss/mixins/grid";

// Reset and dependencies
@import "./public_html/assets/sources/bootstrap-sass/assets/stylesheets/bootstrap/normalize";
@import "./public_html/assets/sources/bootstrap-sass/assets/stylesheets/bootstrap/print";
@import "./public_html/assets/sources/bootstrap-sass/assets/stylesheets/bootstrap/glyphicons";
```

`./public_html/assets/sources/bootstrap-sass` is a symlink to `./node_modules/bootstrap-sass`.

I hope someone can shed some light on this. I feel like I've missed something basic and crucial.

**Comment by webmasterpf** [comment]
I get same issue, in addition of disappearing compiled files...hope someone find a fix

**Comment by userdude** [comment]
Looks like the resolution is to use a `change` event to call the task:

```
gulp.task('watch', ['dev'], function(){
    tasks.push('dev');
    
    ctlog("Now watching 'dev' task ...");
    
    gulp.watch(config.publicDir+'/stylesheets/scss/*.scss').on('change', function(){
        gulp.start('dev');
    });
});
```

This appears to work, although I won't know for sure until I get to test with a coworker.

**Comment by xzyfer** [comment]
You should never compile partials. They will always fail in this way. Add a `filter` to the `src()` to ignore partials.

**Comment by userdude** [comment]
That doesn't help. I'm watching a `site.scss` file that includes partials; how is "compiling partials"? If you would, show me what I've done wrong?

**Comment by xzyfer** [comment]
```
gulp.task('watch', function(){
    gulp.watch(config.publicDir+'/stylesheets/scss/*.scss', ['test']);
});
```
This tells the `test` task to use the changed file as a `src`. If you change `_foo.scss` then it will try to compile that file which will produce an error if it depends on variables imported somewhere else by `site.scss`. This is why your work around works because it's ignoring the changed file and jsut executing the task which uses the default src `site.scss`.
