### ISSUE TITLE
node-sass data

### ISSUE THREAD

**Issue by mabar** [dlmanning/gulp-sass#599]
Better than current behavior would be throwing error if options.data is set. But it would be best if internal file.contents is merged with options.data
I want to pass variables from my system (eg. baseUrl). Without it is required to write it twice.

**Comment by mabar** [comment]
Problem with silent error is too [here](https://github.com/dlmanning/gulp-sass/blob/master/index.js#L50-L52). If opts.includePaths is not string, error would be throwed

**Comment by montrealist** [comment]
@mabar can you share how you "write it twice"? I need a way to pass something to node-sass via the `options.data` parameter, and the current code simply wipes it out with `opts.data = file.contents.toString();`

**Comment by mabar** [comment]
With write it twice I mean, that I have base config in yaml for my php part of app. But I need parts of config in sass too. In current state must be this config duplicated to sass file.

I tried to merge user config with `file.contents.toString` in #600. Don't know if it's good solution, but it works. Now I would like only wait for stable version of dart-sass to give major release a reason.

**Comment by xzyfer** [comment]
Regarding `includePaths`, I don't see a bug in the link code. `includePaths` accepts a string or array of strings. The link code makes sure we always pass an array to node-sass as it expects.

**Comment by xzyfer** [comment]
Regarding injecting data, this has come up before #302. 

I'm not convinced there are concrete use cases for passing data to node-sass that aren't better address by `importers` or `functions`. Additionally this would wreck havoc on sourcemaps.

I'm happy to re-consider this if there is a use-case that fits within the semantics of gulp streams, and cannot be addressed by `importers` and/or `functions`.

**Comment by mabar** [comment]
It was very weird for me why gulp-sass limits api of node-sass. But explanation is good enough. Thank you
