### ISSUE TITLE
outputStyle 'expanded' getting ignored?

### ISSUE THREAD

**Issue by jonkemp** [dlmanning/gulp-sass#6]
Maybe this is an issue with node-sass but using the `outputStyle: 'expanded'` the output looks the same as nested. Using 'compressed' seems to work though.

**Comment by yisibl** [comment]
Done, https://github.com/sass/libsass/commit/7877cfa872b036d55344db5d12ea908bb70f3705
 
But how to used it?

**Comment by cinic** [comment]
@yisibl use [gulp-ruby-sass](https://www.npmjs.com/package/gulp-ruby-sass)

**Comment by Snugug** [comment]
Make sure your [node sass version is up to day](https://github.com/dlmanning/gulp-sass/wiki/Common-Issues-and-Their-Fixes#node-sass-version-not-up-to-date) and you should be able to use as described in Node Sass
