### ISSUE TITLE
Error while running gulp release. --> stream.js^ throw er; // Unhandled stream error in pipe.

### ISSUE THREAD

**Issue by vinodnarayankar** [dlmanning/gulp-sass#601]
Error while running gulp release. All was fine before 12 hours.  Kinldy find below error and do the needful.

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./~/react-datepicker/~/react-onclickoutside/index.js
Module not found: Error: Cannot resolve module 'create-react-class' in D:\dev\web\node_modules\react-datepicker\node_modules\react-onclickoutside
resolve module create-react-class in D:\dev\web\node_modules\react-datepicker\node_modules\react-onclickoutside
  looking for modules in D:\dev\web\resources\assets
    D:\dev\web\resources\assets\create-react-class doesn't exist (module as directory)
    resolve 'file' create-react-class in D:\dev\web\resources\assets
      resolve file
        D:\dev\web\resources\assets\create-react-class doesn't exist
        D:\dev\web\resources\assets\create-react-class.webpack.js doesn't exist
        D:\dev\web\resources\assets\create-react-class.web.js doesn't exist
        D:\dev\web\resources\assets\create-react-class.js doesn't exist
        D:\dev\web\resources\assets\create-react-class.json doesn't exist
  looking for modules in D:\dev\web\node_modules\react-datepicker\node_modules
    D:\dev\web\node_modules\react-datepicker\node_modules\create-react-class doesn't exist (module as directory)
    resolve 'file' create-react-class in D:\dev\web\node_modules\react-datepicker\node_modules
      resolve file
        D:\dev\web\node_modules\react-datepicker\node_modules\create-react-class doesn't exist
        D:\dev\web\node_modules\react-datepicker\node_modules\create-react-class.webpack.js doesn't exist
        D:\dev\web\node_modules\react-datepicker\node_modules\create-react-class.web.js doesn't exist
        D:\dev\web\node_modules\react-datepicker\node_modules\create-react-class.js doesn't exist
        D:\dev\web\node_modules\react-datepicker\node_modules\create-react-class.json doesn't exist
  looking for modules in D:\dev\web\node_modules
    D:\dev\web\node_modules\create-react-class doesn't exist (module as directory)
    resolve 'file' create-react-class in D:\dev\web\node_modules
      resolve file
        D:\dev\web\node_modules\create-react-class doesn't exist
        D:\dev\web\node_modules\create-react-class.webpack.js doesn't exist
        D:\dev\web\node_modules\create-react-class.web.js doesn't exist
        D:\dev\web\node_modules\create-react-class.js doesn't exist
        D:\dev\web\node_modules\create-react-class.json doesn't exist

**Comment by vinodnarayankar** [comment]
code was working fine. It started breaking from last two days.   Looks like one of the core dependency might have changed.

however, after adding  "object-assign": "^4.1.1" in package.json.  I am able to build the code.

I am not sure, its the right way to fix this. If any body come across this issue. kindly help.

**Comment by xzyfer** [comment]
```
Error: .//react-datepicker//react-onclickoutside/index.js
Module not found: Error: Cannot resolve module 'create-react-class' in 
```

This is not relate to gulp-sass. This is an npm issue. Remove your node_modules and run npm install.
