### ISSUE TITLE
can't install on window 7 x64 (can't build by msbuild)

### ISSUE THREAD

**Issue by huoxudong125** [dlmanning/gulp-sass#602]
> node-sass@4.5.2 install E:\TestProjects\gulp-demo\node_modules\node-sass

> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.2/win32-x64-48_binding.node

> node-sass@4.5.2 postinstall E:\TestProjects\gulp-demo\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe E:\TestProjects\gulp-demo\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
生成启动时间为 2017/4/10 17:06:18。
节点 1 上的项目“E:\TestProjects\gulp-demo\node_modules\node-sass\build\binding.sln”(默认目标)。
ValidateSolutionConfiguration:
  正在生成解决方案配置“Release|x64”。
项目“E:\TestProjects\gulp-demo\node_modules\node-sass\build\binding.sln”(1)正在节点 1 上生成“E:\TestProjects\gulp-demo\node_modules\node-sass\build\binding.vcxproj.metaproj”(2) (默认目标)。
项目“E:\TestProjects\gulp-demo\node_modules\node-sass\build\binding.vcxproj.metaproj”(2)正在节点 1 上生成“E:\TestProjects\gulp-demo\node_modules\node-sass\build\src\libsass.vcxproj”(3) (默认目标)。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets(44,5): error MSB8020: The builds tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, either click the Project menu or right-click the solution, and then select "Update VC++ Projects...". Install v140 to build using the v140 build tools. [E:\TestProjects\gulp-demo\node_modules\node-sass\build\src\libsass.vcxproj]
已完成生成项目“E:\TestProjects\gulp-demo\node_modules\node-sass\build\src\libsass.vcxproj”(默认目标)的操作 - 失败。
已完成生成项目“E:\TestProjects\gulp-demo\node_modules\node-sass\build\binding.vcxproj.metaproj”(默认目标)的操作 - 失败。
已完成生成项目“E:\TestProjects\gulp-demo\node_modules\node-sass\build\binding.sln”(默认目标)的操作 - 失败。

生成失败。

“E:\TestProjects\gulp-demo\node_modules\node-sass\build\binding.sln”(默认目标) (1) ->
“E:\TestProjects\gulp-demo\node_modules\node-sass\build\binding.vcxproj.metaproj”(默认目标) (2) ->
“E:\TestProjects\gulp-demo\node_modules\node-sass\build\src\libsass.vcxproj”(默认目标) (3) ->
(PlatformPrepareForBuild 目标) -> 
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets(44,5): error MSB8020: The builds tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, either click the Project menu or right-click the solution, and then select "Update VC++ Projects...". Install v140 to build using the v140 build tools. [E:\TestProjects\gulp-demo\node_modules\node-sass\build\src\libsass.vcxproj]

    0 个警告
    1 个错误

已用时间 00:00:00.10

**Comment by stevelacy** [comment]
The error and the solution is in the error log if you read closely.
```
成“E:\TestProjects\gulp-demo\node_modules\node-sass\build\src\libsass.vcxproj”(3) (默认目标)。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets(44,5): error MSB8020: The builds tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, either click the Project menu or right-click the solution, and then select "Update VC++ Projects...". Install v140 to build using the v140 build tools. [E:\TestProjects\gulp-demo\node_modules\node-sass\build\src\libsass.vcxproj]
```
http://stackoverflow.com/questions/31792663/visual-studio-2013-error-ms8020-build-tools-v140-cannot-be-found

**Comment by huoxudong125** [comment]
@stevelacy is there a possible that we don't need to build after we got the node-sass module. When I install the VisualStudio 2017 the solution can't be built.

**Comment by stevelacy** [comment]
I am not sure what you are saying, but, one you install the VS17 libraries then reinstall the gulp-sass module

**Comment by xzyfer** [comment]
>sass/node-sass@v4.5.2 win32-x64-48_binding.node (download)

This should be a full url. There's is something weird with your npm. There were some issues with lock files and the npm cache not being compatible with npm@5.

- remove your node_modules
- remove your shrinkwrap.json and package-lock.json files
- run `npm cache clean`
- run `npm install`
