### ISSUE TITLE
Encoding issues (with FontAwesome)

### ISSUE THREAD

**Issue by timo002** [dlmanning/gulp-sass#603]
Hello,

I'm using gulp-sass to compile a custom set of icons from FontAwesome. In the FontAwesome `_variables.scss`, there is a variable `$fa-var-home`
```
$fa-var-home: "\f015";
```
After running gulp-sass, this is compiled into a weird character:
```
.fa-home:before {
  content: "";
}
```
Why doesn't it say `\f015`?

I added `@charset "UTF-8";` at the top of my main.scss file.

Version:
gulp-sass: 3.1.0
node: 5.3.0
npm: 3.3.12

**Comment by mabar** [comment]
@timo002 Write it on node-sass issues tracker. gulp-sass is only a wrapper

**Comment by xzyfer** [comment]
It's a different representation of the same character. It's on purpose and part of the CSS spec.
