### ISSUE TITLE
[Question] Include comment for each sass file before compiling

### ISSUE THREAD

**Issue by kamlekar** [dlmanning/gulp-sass#604]
Hi there,

Suppose that I have the following sass directory structure:

     _dashboard.scss
     _projects.scss
     _items.scss
     styles.scss

Before compiling the above sass files to css, I want the gulp to add comments as follows (considering `_dashboard.scss` as example):

     /* Start of Dashboard styles */

     ## _dashboard.scss styles here

     /* End of Dashboard styles */

The above comment wrapping should happen only to the scss files which starts with `_` prefix. 

I tried using `gulp-wrap` but it just add comment only once because all files are being compiled to one in the gulp-sass plugin. I am hoping there is some way in this plugin itself.

Please help.

**Comment by Surfing-Chef** [comment]
I might be off base, but I just add an exclamation mark after the first asterix and sass leaves them alone when compiling the css.  
```css
/*! Start of Dashboard styles */

 ## _dashboard.scss styles here

 /*! End of Dashboard styles */
```

**Comment by kamlekar** [comment]
@Surfing-Chef I didn't ask for that. I want gulp sass to add comments automatically to each underscore prefixed sass files while compiling.

**Comment by xzyfer** [comment]
You'd need to write a custom node-sass [importer][0]. I stronger recommend against doing this. The solution offered above is the best bet.

[0]: https://github.com/sass/node-sass#importer--v200---experimental
