### ISSUE TITLE
node.js 8.0 node-sass

### ISSUE THREAD

**Issue by 5an1ty** [dlmanning/gulp-sass#606]
Please update the node-sass dependency to support node.js 8.0

**Comment by xzyfer** [comment]
rm -rf node_modules
npm install

**Comment by 5an1ty** [comment]
Oops, thanks!

**Comment by meduzen** [comment]
Hi! I’d like to re-open this to-do.

Most former projects I worked on use [laravel-elixir](https://github.com/laravel/elixir) as a Gulp wrapper. laravel-elixir currently [uses gulp-sass 3.2.2](https://github.com/laravel/elixir/blob/master/package.json).

As gulp-sass makes use of node-sass 4.2.0, it makes laravel-elixir unusable on configurations updated to the recently released Node 8. node-sass only works on Node 8 starting the [node-sass 4.5.3](https://github.com/sass/node-sass/releases/tag/v4.5.3).

So, deleting the `node_modules` folder and running `npm install` is only working for Node before version 8.

I think it would be a good thing to bump node-sass dependency to 4.5.3.

**Comment by xzyfer** [comment]
Gulp sass uses node-sass@^4 which means it uses the newest node-sass
available at the time you ran npm install. To get a newer version of
node-sass delete your node_modules folder and run npm install again.

**Comment by meduzen** [comment]
I did it, it didn’t work, but you’re right: node-sass 4.5.3 was installed (checked with `npm ls --depth=1`). node-sass 3.1.3 also wants to be there along 4.5.3, so I guess the problem is somewhere else.

It’s out of my expertise field for now, so I will roll back to node 7.7.4 (thanks to nvm).

Thanks again for your answer.

**Comment by xzyfer** [comment]
You'll need node-sass@4.5.3 for Node 8.

Run `npm ls node-sass`. This will show you all the node-sass installations and the package that is pulling it in. Then you can either update those dependencies to a version that depends on node-sass@^4 or open an issue asking for them to update their node-sass dependency.
