### ISSUE TITLE
node_modules/steamcommunity/node_modules/steam-totp/node_modules/

### ISSUE THREAD

**Issue by bikashbaruah19** [dlmanning/gulp-sass#607]
Hello everyone, previously i made few steam bots without having any issue but this time whenever i try to run the bot with node then i get this error : 

/home/bot/node_modules/steamcommunity/node_modules/steam-totp/node_modules/@doctormckay/stats-reporter/index.js:9
let g_StartupTimestamp = Math.floor(Date.now() / 1000);

can anyone please help me ? thank you

**Comment by xzyfer** [comment]
This is not related to this modules. Remove your node_modules and run npm install again.
