### ISSUE TITLE
Node Sass does not yet support your current environment (win 10)

### ISSUE THREAD

**Issue by nicothin** [dlmanning/gulp-sass#608]
![image](https://cloud.githubusercontent.com/assets/3499680/26775448/b44acd8c-49dd-11e7-8133-2a103920a735.png)
Node 8
With Node 6.9 everything works fine :)

Windows 10
gulp-sass 3.1.0

**Comment by xzyfer** [comment]
Please search the many many similar issues.

**Comment by xzyfer** [comment]
You need node-sass@4.5.3. Remove your node_modules and npm install again.
