### ISSUE TITLE
Option for disabling generation of sourcemaps

### ISSUE THREAD

**Issue by mian3010** [dlmanning/gulp-sass#609]
There is currently a bug in libsass: https://github.com/sass/libsass/issues/2312

This means that sourcemap generation fails for scss-files that contain an `&` in selector, such as `&.mod-enabled` or `&:after`

Until that bug is fixed it would be great to have the option of disabling sourcemap generation through options to `gulp-sass`, instead of it assuming you want them generated whenever the sourcemap plugin is present:
```
    if (file.sourceMap) {
      opts.sourceMap = file.path;
      opts.omitSourceMapUrl = true;
      opts.sourceMapContents = true;
    }
```

Am i reading the code correctly? I am still a gulp/nodejs novice.

Even after the bug in libsass is fixed, it would be nice to have the option to disable sourcemap generation through options.

My suggestion is this: https://github.com/reload/gulp-sass/commit/1724bee8781699e3b4d6908dd5a729d1ae3bd97b

Then setting `sourceMap: false` in `gulpfile.js` will disable sourcemap generation.

Additional information:
```
# node --version
v6.7.0
```
```
# npm --version
5.0.3
```
```
# cat package.json
...
    "gulp-sass": "^3.1.0",
...
```

OS: Alpine Linux

**Comment by xzyfer** [comment]
You should be able to set the [sourceMap][0] config directly.

[0]: https://github.com/sass/node-sass#sourcemap

**Comment by mian3010** [comment]
Yes, however, that makes no difference, when i set it. Also, looking at the condition, i do not believe that it is even used, that option.

The documentation clearly states that the default value is `undefined`, and that sourcemaps will be generated when the value is `=== true`, or the type of the value is `string`, so if i do not set that option at all, sourcemaps should not be generated. They are anyway, and failing.

**Comment by mian3010** [comment]
Why can't i reopen this?
