### ISSUE TITLE
Support for Node 8.x

### ISSUE THREAD

**Issue by darrenahunter** [dlmanning/gulp-sass#610]
Hi
I have recently upgraded to Node 8.1 and have found gulp-sass not supporting the latest node 8.

Are you able to push a change to update the node-sass dependency to at least v.4.5.3 as you will see it supports latest node 8
https://github.com/sass/node-sass/releases/tag/v4.5.3

thanks
Darren

**Comment by xzyfer** [comment]
Gulp sass 3 will install the latest available node-sass. Delete your
node_modules and run npm install
