### ISSUE TITLE
Error: Undefined operation: "1.5 times .875rem"

### ISSUE THREAD

**Issue by sstikkel** [dlmanning/gulp-sass#611]
I had to downgrade to gulp-sass 3.0.0. It's bug in libsass https://github.com/sass/libsass/issues/2309. So it should solve this by upgrading libsass and node sass to the latest version.

**Comment by xzyfer** [comment]
Close by #666

**Comment by sovanyio** [comment]
Still getting this on 3.2.0

```
Error in plugin 'sass'
Message:
    file.scss
Error: Undefined operation: "3 times 0.375em".
        on line 18 of file.scss
        from line 15 of other-file.scss
>>   padding-left: 3 * $s-units--base-spacing;

   ----------------^
```
Works on 2.3.2

**Comment by JanikWeb** [comment]
Same here:

`Error: Undefined operation: "2 times 1sqrt(5)/2".Error: Undefined operation: "2 times 1sqrt(5)/2".`

**Comment by xzyfer** [comment]
Please provide actual sass code that produces this error so we that we can
reproduce it locally

**Comment by sovanyio** [comment]
@JanikWeb are you using interpolation? Found out that arithmetic doesn't work against interpolated strings, which libsass team doesn't think is worth fixing or expected behavior.

**Comment by ryyy20** [comment]
@sovanyio does that mean you can't do something like this:

`$font-size-base: rems(18) !default; // Assumes the browser default, typically `16px`
$font-size-lg:   $font-size-base * 1.25 !default;`

**Comment by nachtfunke** [comment]
> From what I've discovered, it depends on what `rems()` does, and how it does it.
> If it returns: `#{calculated-rem}rem;`, (which I've seen in some solutions), then further calculations are not possible, because the returned value is seen by the compiler as being a string (which you can't do math on).
> If it returns: `($size-px / 16px) * 1rem;`, then further calculations are possible because the returned value is a calculable number.

Thank you very much, this was the solution that I needed! @cartbeforehorse
