### ISSUE TITLE
Return file name

### ISSUE THREAD

**Issue by KePitt2** [dlmanning/gulp-sass#613]
Hello to everyone.
I'm trying to log the file name when my task compile my source sass folder (including more than one scss file):

This is the simplified code

```javascript
gulp.task('mergeCss', function() {
    gulp.src(styles_dir + '*.scss')
        .pipe(sass(sass_options).on('error', sass.logError))
        .pipe(autoprefixer(autoprefixer_options))
        .pipe(gulp.dest(css_dir))
        .pipe(notify("scss compiled"))
    ;
}); // Compile/Unify/Minify CSS
```

¿Is thera a way to notify the finished output file name in the log? By now, I'm only able to print "scss compiled".

Thank you very much!

**Comment by xzyfer** [comment]
This isn't possible. Gulp internally doesn't operate on files, it works on streams of data. These streams do not have filenames.
