### ISSUE TITLE
Outdated node-sass, issues with Node 8.x

### ISSUE THREAD

**Issue by bladeSk** [dlmanning/gulp-sass#614]
`gulp-sass` fails to install on Node 8.x without a C++ compiler, because the outdated version of `node-sass` doesn't have a binary for the new version of Node. The latest version of `node-sass` provides the required binaries and doesn't seem to break anything, so it's just a matter of bumping the version number to `^4.5.3`.

Are there any plans for updating?

**Comment by xzyfer** [comment]
Please search the dozen of other closed issues about this for the solution.

**Comment by bladeSk** [comment]
The solution was to `npm install` the latest version, but that didn't work for me.

The latest version of gulp-sass on npm (`3.1.0`) has this dependency defined in package.json: `"node-sass": "^4.2.0",`. It needs to be at least `4.5.3` to be able to download the binary for node 8.

**Comment by xzyfer** [comment]
`^4.2.0` is the [semver caret range][1] which means it will install the latest 4.x version available, in this case 4.5.3. Deleting your node_modules and running `npm install` will install the latest 4.x node-sass. If you have a lock file (`package-lock.json` or `shrink-wrap.json`) it will interfere and always download the version specified in the lock file. You'll need to delete the lock file or update the node-sass version inside it.

Running `npm update node-sass` might do this for you automatically.

[1]: https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

**Comment by bladeSk** [comment]
Sorry, my bad, it's working when installed on a clean project. It was clearly a problem with upgrading. A warning in the readme could be useful, though, a lot of people are having similar issues.
