### ISSUE TITLE
Not importing the SASS files properly

### ISSUE THREAD

**Issue by mittalyashu** [dlmanning/gulp-sass#615]
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: sass\main.sass
Error: File to import not found or unreadable: _base.sass.
       Parent style sheet: C:/Users/YASHU/Desktop/gulp/sass/main.sass
        on line 1 of sass/main.sass
>> @import "_base.sass";
   ^

    at options.error (C:\Users\YASHU\Desktop\gulp\node_modules\node-sass\lib\index.js:291:26)
```

Generally, I use `@import` to import all the files into one sass file and then convert it into CSS.
But when I make a single change in any of the SASS files. The above error shows up.

**Comment by n1kt0** [comment]
I have also problems with importing frameworks like susy and using their mixins.
`Error in plugin 'sass'
Message:
    sass/screen.scss
Error: no mixin named border-box-sizing

       Backtrace:
       	sass/screen.scss:21
        on line 21 of sass/screen.scss
    @include border-box-sizing;

**Comment by xzyfer** [comment]
@mittalyashu this looks like an issue with your [includePaths][0] config.

[0]: https://github.com/sass/node-sass#includepaths
