### ISSUE TITLE
Outdated node-sass version

### ISSUE THREAD

**Issue by dhniels** [dlmanning/gulp-sass#616]
Latest node-sass release is 4.5.3 (may 16)

gulp-sass hasn't been updated for over 7 months, appears to be using node-sass 4.2.0 currently. There are some fairly significant new features and fixes that have been released since January including greater CSS Grid selector support.

Would be nice to have gulp-sass brought up to speed with node-sass.

**Comment by joaoribeirost** [comment]
For what I've been reading on this repo issues it uses the 4.x  newest version. I've seen explained on other issues like #614 .

Deleting `node_modules` and running `npm install` again should solve the version issue.

**Comment by phawxby** [comment]
@dhniels it's not just feature sets. gulp-sass does not work on node 8 because node-sass@4.2.0 [does not support it](https://github.com/sass/node-sass/releases/tag/v4.2.0). 

I've managed to hack it together for now by using the yarn.lock to forcibly set the node version in use to 4.5.3. FYI 4.5.2 is broken on Windows 10 x64.

**Comment by xzyfer** [comment]
This is as intended. You don't need to hack anything. Check anyone of the last dozen identical closed issues.

**Comment by phawxby** [comment]
Hmmm, I wonder if there is a problem elsewhere. `yarn upgrade-interactive` consistently upgraded node-sass to 4.5.2 and I just couldn't explain it. Looking through the many other PR's as you suggested it seems the only way I could get it to reliably upgrade to 4.5.3 was to completely delete my yarn.lock and `yarn` again. It makes no sense to me but hopefully someone will stumble across this comment and it will help them.
