### ISSUE TITLE
Update README.md documentation to utilize ECMA6 features

### ISSUE THREAD

**Issue by kevjames3** [dlmanning/gulp-sass#624]
README needs to not use `vars` and instead use `const` and/or `let`, since `var` is bad practice

**Comment by kevjames3** [comment]
Note: as long as `"use strict"` is enabled, this should work all the way back to node 4

**Comment by xzyfer** [comment]
We disagree this is bad practice. We have chosen to use ES5 syntax because it's accessible to everyone. Not everyone is able to use new ES6 features.

**Comment by Announcement** [comment]
@xzyfer Isn't that why we use vcs? If people want the old code they can look at the history or relevant branch in which we could kindly link them to once updated.

**Comment by xzyfer** [comment]
Es5 is the lowest common denominator and as such is the accessible to the most people. We see no value is changing this.
