### ISSUE TITLE
Is it possible to add extensions?

### ISSUE THREAD

**Issue by JacobDB** [dlmanning/gulp-sass#627]
I'm trying to set up something that checks if a file exists before including it; I've found this `file_exists` extension, which I'm instructed to place in config.rb, which doesn't seem to exist for gulp-sass. 

Is it possible to add this type of extension to gulp-sass?

```
module Sass::Script::Functions
  def file_exists(image_file)
    path = image_file.value
    Sass::Script::Bool.new(File.exists?(path))
  end
end
```

**Comment by xzyfer** [comment]
That is for ruby-sass. Gulp uses node-sass.

**Comment by xzyfer** [comment]
You can look into node-sass custom importers
