### ISSUE TITLE
Using /deep/ throws error and does not compile

### ISSUE THREAD

**Issue by jeshuamaxey** [dlmanning/gulp-sass#63]
```
body /deep/ {
    font-family: 'Lato', 'Helvetica', sans-serif;
}
```

throws the following error:

```
[gulp-sass] /Users/jeshuamaxey/app/public/css/src/base/typography:1: error: invalid top-level expression
```

I'm using gulp-sass v0.7.1

This is a syntax used for styling elements in the Shadow DOM. Compiling with sass (Sass 3.3.0.rc.5 (Maptastic Maple)) on the command line throws no error. This bug is similar in vein to [#58](https://github.com/dlmanning/gulp-sass/issues/58).

**Comment by SamHH** [comment]
Surely this issue should remain open and be fixed? I'd rather use this so as to remove Ruby as a development dependency but can't.
