### ISSUE TITLE
After compilation, styles are same

### ISSUE THREAD

**Issue by SilencerWeb** [dlmanning/gulp-sass#634]
I have a problem with styles' compilation. Example:

```
.link
    text-decoration: none
    color: #fff
```

Output:
```
.link {
  text-decoration: none;
  color: #fff;
}
```

If I change the name of the property or add new styles, it will compile and everything will be okay:

```
.link
    font-size: 14px
    text-decoration: none
    background-color: #fff
```

Output:
```
.link {
    font-size: 14px;
    text-decoration: none;
    background-color: #fff;
}
```

BUT! If I change VALUE of the property, it will compile, but styles will be same! For example:

```
.link
    font-size: 14px
    text-decoration: none
    background-color: red
```

Output:
```
.link {
    font-size: 14px;
    text-decoration: none;
    background-color: #fff;
}
```

How is it? I don't know what can be the reason for it. System? Console? Gulp? Now I'm working on the MacBook, but before I worked on the computer with Windows and hadn't ever had such problems. If you need more information - just ask.

gulp-sass: 3.1.0
node: 9.1.0
System: macOS Sierra 10.12.6
Project: https://github.com/SilencerWeb/spark17

**Comment by xzyfer** [comment]
This isn't a bug with gulp-sass. Double check your gulp config. Make sure you don't have any optimizations like gulp-newer that would be hiding file changes.
