### ISSUE TITLE
Node 9 Support

### ISSUE THREAD

**Issue by mikemccaffrey** [dlmanning/gulp-sass#636]
The current release of gulp-sass require node-sass version 4.2.0, which isn't able to run on version 9 of node. It would be great if we could update this project to use node-sass 4.6.0 or higher which has support node 9 support. 

https://github.com/sass/node-sass/releases/tag/v4.6.0

The rolling release for the Arch Linux nodejs package has just reached version 9.2.0, so I currently need to use nvm to select an earlier version of node whenever I need to use gulp. Luckily it is not a huge deal, but I'd love one less thing to do every day! Thanks a bunch!

**Comment by xzyfer** [comment]
It's `^4.2.0` not `4.2.0`. Please search before opening issues.

**Comment by Iambecomeroot** [comment]
Even though @xzyfer doesn't approve, this helped me. Thanks.
