### ISSUE TITLE
Source map generation issue

### ISSUE THREAD

**Issue by aifrim** [dlmanning/gulp-sass#639]
In `index.js:105` the `applySourceMap(file, sassMap);` is called that calls `mozilla/source-maps` and throws this https://github.com/mozilla/source-map/issues/301.

Does not matter if I want to generate the sourcemaps or not. Whilst trying to find a patch I saw that commenting that line fixes the problem. The sourcemaps are still being generated and the error vanishes.

```js
        ...
        // Replace the map file with the original file name (but new extension)
        sassMap.file = gutil.replaceExtension(sassFileSrc, '.css');
        // Not applying the map (Apply the map)
        // applySourceMap(file, sassMap);
      }
      ...
```

`"gulp-sass": "^3.1.0"`

Better leave the sourcemap generation to `node-sass`.

**Comment by xzyfer** [comment]
Sorry this bug need to be fixed in the upstream issue you linked to.

That code isn't generating sourcemaps it's combining the sourcemaps from previous plugins. It cannot be commented out.

**Comment by fkleuver** [comment]
@xzyfer This seems to be related to an issue in libsass which was [fixed](https://github.com/sass/libsass/pull/2540) a couple days ago.
I [informed](https://github.com/sass/node-sass/issues/2188#issuecomment-359454319) the node-sass team. Once they picked it up, updating the node-sass dependency in this project ought to fix it, correct?

**Comment by xzyfer** [comment]
Yes
