### ISSUE TITLE
How to write error build to css file ?

### ISSUE THREAD

**Issue by kytosai** [dlmanning/gulp-sass#644]
Before, i used gulp-ruby-sass , it default setting can write error build scss to css file.

Example: http://prntscr.com/hocdps

But gulp-sass i don't know setting to write error to css build file

How to use gulp-sass write error to css build file ? Because i use sass-watch so i have to use gulp-sass :( !!!

**Comment by xzyfer** [comment]
Check the read me

**Comment by KytoSai** [comment]
Sorry, But uou can share me link to that setting ?
Please, i'm not good english !

Thanks you !

**Comment by xzyfer** [comment]
https://github.com/dlmanning/gulp-sass#basic-usage

**Comment by xzyfer** [comment]
I don't believe this is supported.
