### ISSUE TITLE
Drop dependency on deprecated `gulp-util`

### ISSUE THREAD

**Issue by demurgos** [dlmanning/gulp-sass#646]
Hi,
[`gulp-util`](https://github.com/gulpjs/gulp-util) is deprecated. It should be replaced by dependencies on the individual components used by `gulp-eslint`. The README lists alternatives for the different components.

See https://github.com/gulpjs/gulp/issues/2065

**Comment by ladom** [comment]
gulpjs [recommend](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5) using `ansi-colors` instead of `chalk`. I tried it on, it works good and passes all test.

**Comment by decksterr** [comment]
`chalk` could still be used w/o any much problem i guess, it's `gutil.colors` from `gulp-util` that's deprecated

**Comment by stefan-lehmann** [comment]
Can someone please merge this, thanks!

**Comment by markushausammann** [comment]
Please release!!

**Comment by xzyfer** [comment]
Fixed in #667

**Comment by demurgos** [comment]
- Closed by https://github.com/dlmanning/gulp-sass/pull/667
