### ISSUE TITLE
Transpiling sass files to their same directory

### ISSUE THREAD

**Issue by ORESoftware** [dlmanning/gulp-sass#650]
I have this issue on StackOverflow, not sure if it will receive an answer:
https://stackoverflow.com/questions/48123786/gulp-src-is-not-writing-destination-files-out

```js
 gulp.src(path.resolve(root + '/src/**/**/*.scss'))
    .pipe(gdebug())
    .pipe(sass())
    .pipe(gulp.dest('.'))                 // transpile sass to same directory as original .scss file?
    .once('finish', function () {
      console.log('notify clients of css change');
      notifyClients();
    });
```

as you can see, I am trying to transpile sass to same directory as original .scss file...any idea why that wouldn't work? Using gulp-debug, I can determine that it is reading the right files, but it doesn't seem to be outputting the results anywhere..

**Comment by xzyfer** [comment]
Define not working. What exactly is happening?

**Comment by ORESoftware** [comment]
the .css files don't actually get written out

however, it looks like my Angular app can work with .scss directly so, not sure if this issue matters to me anymore

**Comment by xzyfer** [comment]
Everything looks fine. Remember gulp-sass will not compile files that start
with an underscore (_).
