### ISSUE TITLE
Error: undefined variable, but styles work anyway

### ISSUE THREAD

**Issue by carlotrimarchi** [dlmanning/gulp-sass#654]
Hello,
I have these files in my project:

```
settings/
  _fonts.scss
_typography.scss
styles.scss
```
Inside the files:

```
// fonts.scss
$bodyFont: 'Montserrat';
```

```
// typography.scss
body {
  font-family: $bodyFont;
}
```

```
// style.scss
@import 'settings/fonts/;
@import 'typography;
```

When I compile style.scss with gulp-sass I get this error:

Error: Undefined variable: "$headingsFont".
        on line 4 of _typography.scss
>> font-family: $headingsFont;

But the css file gets compiled anyway correctly and the font works as expected. Why is it throwing the error?

**Comment by xzyfer** [comment]
`$headingsFont` isn't shown in the code sample. it's working because `$bodyFont` is defined.

**Comment by Junior2Ran** [comment]
I got the exact same problem above！
```
// index.scss
@import "./themes/huiyan";
@import "./core/index";
```

```
// huiyan.scss
$font-family: "PingFangSC-Regular", "PingFang SC", "Microsoft YaHei" !default;
```

```
//  core/index.scss
@import "./base";
@import "mixins";
```

```
//  core/base.scss
body {
    padding: 0;
    margin: 0;
    font-family: $font-family;
}
```

When I compile style.scss with gulp-sass I get this error:
> Error in plugin "sass"
> Message:
>     src/components/style/core/base.scss
> Error: Undefined variable: "$font-size-base".
>         on line 11 of src/components/style/core/base.scss
> >>     font-size: $font-size-base;
>
>    ---------------^

and it works on browser!
What should i do??

ps. my gulpfile.js
```
function compile(modules) {
    const scssStream = gulp.src(['src/components/**/*.scss'])
        .pipe(sass().on('error', sass.logError))
        .pipe(gulp.dest(modules === false ? esDir : libDir));
}
gulp.task('style', () => {
    compile();
});
```
