### ISSUE TITLE
Cannot install node-sass in Visual Studio Code

### ISSUE THREAD

**Issue by alisonludick** [dlmanning/gulp-sass#656]
I'm unable to install sass in Visual Studio Code, using the command 

npm install -g node-sass less

I ran into a permissions issue and ran this command instead 

sudo npm install -g node-sass less

and this is what took place:
![screen shot 2018-02-06 at 1 01 10 pm](https://user-images.githubusercontent.com/34286802/35856637-4a923c94-0b3f-11e8-9ed7-3ccac998cd3f.png)

(hope you can see the picture I attached - it shows on preview, not but here)

I'm using a Macbook, 10.10.5 Yosemite
Would appreciate any help/advice

**Comment by xzyfer** [comment]
If you install as sudo you need it use the --unsafe-perms flag

**Comment by alisonludick** [comment]
Thank you!
