### ISSUE TITLE
Node Security warning - hoek

### ISSUE THREAD

**Issue by kumavis** [dlmanning/gulp-sass#662]
we see this warning in our project
https://nodesecurity.io/orgs/metamask/projects/6680bc33-6e65-4db7-a943-2aef82f2a881/3458

blocked by `node-sass` https://github.com/sass/node-sass/pull/2170

**Comment by xzyfer** [comment]
Close this because it's an issue with node-sass. 
They've explained why it cannot be resolved at this time.
There is nothing we can do.

**Comment by dsandstrom** [comment]
Can the dependency be updated now? https://github.com/sass/node-sass/issues/2355#issuecomment-402674792
