### ISSUE TITLE
IncludePath  not working in current version

### ISSUE THREAD

**Issue by jayaprakashkamaraj** [dlmanning/gulp-sass#668]
Hi Team,
Reason : It's works with old node-sass 4.7.2, but it doesn't work in node-sass 4.8.1 latest version. Can you please provide the solution for this issue. It throws error.

Error: File to import not found or unreadable: '..'

Note: It's works with node-sass 4.7.2 version

 `  
var sass = require('gulp-sass');
pipe(sass({
            outputStyle: 'expanded',
            **includePaths: path**
        })`

Thanks,
Jayaprakash K.

**Comment by xzyfer** [comment]
Please provide the actually `includePaths` you're using. 
We have tests for `includePaths` so this shouldn't have broken.

**Comment by jayaprakashkamaraj** [comment]
my actual path is ,

`pipe(sass({ outputStyle: 'expanded', 
includePaths: ["./node_modules/@syncfusion/"]
})
`

**Comment by xzyfer** [comment]
Do you know the `@import` producing the error?

**Comment by jayaprakashkamaraj** [comment]
all the styles available in that path.. but it throws error.. can you tell me the reason why it's not working in latest version..

**Comment by xzyfer** [comment]
That's what I'm trying to figure out. Trying to get more information
because the error is confusing

**Comment by jayaprakashkamaraj** [comment]
styles\XX\bootstrap.scss
Error: File to import not found or unreadable: base/styles/bootstrap.scss.

this is the error.. and the mentioned styles are available in that path..

**Comment by ashclarke** [comment]
I had the same issue.

* Sass Config: `includePaths: ["app/css/**/*.scss", "./app/third-party"]`    

* Failing Import example: `@import "./pioneer/src/1.settings/settings"`

* The file to import is located in `<projectroot>/app/third-party/pioneer/src/1.settings/`

* The file importing from these directories is one SCSS file in: `<projectroot>/app/css/`

However, I have fixed the issue. I removed `./` from the start of my second include:

`includePaths: ["app/css/**/*.scss", "app/third-party"]`

@jayaprakashkamaraj - Have a try.

**Comment by xzyfer** [comment]
We have identified the issue in LibSass https://github.com/sass/libsass/issues/2588.

The work around for now is to not use `./` or `../` in include paths.

**Comment by ashclarke** [comment]
@xzyfer - Thanks for the update 👍🏻

**Comment by xzyfer** [comment]
Out of curiosity are you working on, or load files from a UNC or network path?

**Comment by ashclarke** [comment]
No, my directory looks like this:

The main app SCSS file imports all the others, in the sub-directories, and is located in `./app/css`.

```
app
├───css
│   ├───1.settings
│   ├───4.base
│   ├───5.components
│   ├───6.trumps
│   └───7.third-party
...
├───third-party
│   ├───pioneer
│   │   └───src
│   │       ├───1.settings
│   │       ├───2.tools
│   │       ├───3.generic
│   │       ├───4.base
│   │       ├───5.components
│   │       ├───6.trumps
│   │       └───7.third-party
...
```

**Comment by ErraticFox** [comment]
@xzyfer I've tried using the `path` module get around using `./` or `../` but still no success. I've tried multiple different ways, a couple of which being this:
``js
includePaths: [
    path.join(__dirname, 'node_modules')
]
```
and
``js
includePaths: [
    'node_modules'
]
```

in my SCSS file I'm compiling, I have `@import '@material/toolbar';` though I keep getting the error `Error: File to import not found or unreadable: @material/toolbar.`

**Comment by landsman** [comment]
Yeah, I want it too please :)

**Comment by aosmichenko** [comment]
Is there a working example on how to use includePath ?

**Comment by aosmichenko** [comment]
I am using: 
gulp -v
[01:51:02] CLI version 2.0.1
[01:51:02] Local version 4.0.0
"gulp-sass": "^4.0.2",
"gulp": "^4.0.0",
Here is my gulpfile: https://gist.github.com/aosmichenko/7db099af4c80664a4686d83aff09379e

and everything works fine doing import like that:
`@import "bootstrap/scss/bootstrap-grid";`

**Comment by kwhat** [comment]
`@import "~bootstrap/scss/functions";` should be `@import "bootstrap/scss/functions";` as the ~ does not appear to resolve to node_modules using gulp.

**Comment by xzyfer** [comment]
~ imports are a webpack feature and are not part of the Sass language.
