### ISSUE TITLE
throw er; // Unhandled stream error in pipe.

### ISSUE THREAD

**Issue by s-d-p** [dlmanning/gulp-sass#67]
I'm getting the following error consistently:

    ESL@eslmbp /Applications/MAMP/htdocs/craigpomranz[master*]$ gulp sass
    [17:54:53] Using gulpfile /Applications/MAMP/htdocs/craigpomranz/gulpfile.js
    [17:54:53] Starting 'sass'...

    stream.js:94
          throw er; // Unhandled stream error in pipe.
                ^
    Error in plugin 'gulp-sass'
    /Applications/MAMP/htdocs/craigpomranz/wp-content/themes/craig/scss/partials/base:13: error: error reading values after 'xsmall'

        at opts.error (/Applications/MAMP/htdocs/craigpomranz/node_modules/gulp-sass/index.js:67:17)
        at onError (/Applications/MAMP/htdocs/craigpomranz/node_modules/gulp-sass/node_modules/node-sass/sass.js:73:16)

I've provided even more in depth details here: http://stackoverflow.com/questions/24620629/gulp-sass-error-unhandled-stream-error-in-pipe

**Comment by Keats** [comment]
From the stackoverflow post it was a libsass error

**Comment by vinodnarayankar** [comment]
I am getting below error when I run gulp release command. 
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./~/react-datepicker/~/react-onclickoutside/index.js
Module not found: Error: Cannot resolve module 'create-react-class' in D:\dev\web\node_modules\react-datepicker\node_modules\react-onclickoutside
resolve module create-react-class in D:\dev\web\node_modules\react-datepicker\node_modules\react-onclickoutside
  looking for modules in D:\dev\web\resources\assets
    D:\dev\web\resources\assets\create-react-class doesn't exist (module as directory)
    resolve 'file' create-react-class in D:\dev\web\resources\assets
      resolve file
        D:\dev\web\resources\assets\create-react-class doesn't exist
        D:\dev\web\resources\assets\create-react-class.webpack.js doesn't exist
        D:\dev\web\resources\assets\create-react-class.web.js doesn't exist
        D:\dev\web\resources\assets\create-react-class.js doesn't exist
        D:\dev\web\resources\assets\create-react-class.json doesn't exist
  looking for modules in D:\dev\web\node_modules\react-datepicker\node_modules
    D:\dev\web\node_modules\react-datepicker\node_modules\create-react-class doesn't exist (module as directory)
    resolve 'file' create-react-class in D:\dev\web\node_modules\react-datepicker\node_modules
      resolve file
        D:\dev\web\node_modules\react-datepicker\node_modules\create-react-class doesn't exist
        D:\dev\web\node_modules\react-datepicker\node_modules\create-react-class.webpack.js doesn't exist
        D:\dev\web\node_modules\react-datepicker\node_modules\create-react-class.web.js doesn't exist
        D:\dev\web\node_modules\react-datepicker\node_modules\create-react-class.js doesn't exist
        D:\dev\web\node_modules\react-datepicker\node_modules\create-react-class.json doesn't exist
  looking for modules in D:\dev\web\node_modules
    D:\dev\web\node_modules\create-react-class doesn't exist (module as directory)
    resolve 'file' create-react-class in D:\dev\web\node_modules
      resolve file
        D:\dev\web\node_modules\create-react-class doesn't exist
        D:\dev\web\node_modules\create-react-class.webpack.js doesn't exist
        D:\dev\web\node_modules\create-react-class.web.js doesn't exist
        D:\dev\web\node_modules\create-react-class.js doesn't exist
        D:\dev\web\node_modules\create-react-class.json doesn't exist
