### ISSUE TITLE
Update node-sass to 4.8.2

### ISSUE THREAD

**Issue by rohmann** [dlmanning/gulp-sass#671]
`gulp-sass` can't be used under some circumstances because `node-sass` version 4.8.1 is crashing. 

https://github.com/sass/node-sass/issues/2280

The issue was fixed in 4.8.2

**Comment by NeoGenet1c** [comment]
Should not be necessary, because the rule in package.json is

> "node-sass": "^4.8.1",

Which automatically updates to highest minor + patch version available (~ v4.*.*)

Have you tried to delete the node_modules/ folder and reinstall?

**Comment by xzyfer** [comment]
Fixed in 3.2.1
