### ISSUE TITLE
Are @support {} queries supported?

### ISSUE THREAD

**Issue by jesseyuen** [dlmanning/gulp-sass#673]
I'm on the latest build of gulp-sass (3.2.1) and trying to use:

`@supports (display: grid) { 
	// do something  
}`

The @support queries are being skipped on the css compile. Anyone else dealt with a similar issue?

Here is my package.json:

{
  "name": "static template",
  "version": "1.2.0",
  "private": true,
  "devDependencies": {
    "del": "^2.0.2",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.1",
    "gulp-cache": "^0.4.1",
    "gulp-clean-css": "^3.7.0",
    "gulp-concat": "^2.6.1",
    "gulp-csso": "^3.0.0",
    "gulp-iconfont": "^8.0.1",
    "gulp-iconfont-css": "2.1.0",
    "gulp-imagemin": "^3.2.0",
    "gulp-jshint": "^1.12.0",
    "gulp-merge-media-queries": "^0.2.1",
    "gulp-notify": "^2.2.0",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^3.2.1",
    "gulp-uglify": "^2.1.2"
  }
}

**Comment by xzyfer** [comment]
Define skipped? Please provide working SCSS code that produces the problem you're describing.

**Comment by jesseyuen** [comment]
So this is an excerpt of a scss file in my project I'm using as a test...

_body {
	@include font-size(18);
	font-family: $fontStack;
	line-height: 1.4;

	@include breakpoint(0, 900px) {
		@include font-size(16);
	}
}

@supports (display: grid) {
	body {
		display: none;
	}
}
...
_

Outputted css:

_body {
	font-size: 18px;
	font-size: 1.8rem;
	font-family: "Averta", "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
	line-height: 1.4;
}

// expected @support query here but nothing shows in the compiled css

..._

**Comment by xzyfer** [comment]
I am unable to reproduce this locally using your snippet minus the
breakpoint mixin (because I don't have it).

Try commenting out your other gulp plugins to see if one of them is the
cause.

**Comment by jesseyuen** [comment]
Yeah, I just realised that, sorry!  I updated the example to remove all mixins, and the outputted result. 

I'll work through the other gulp plugins - good idea.

**Comment by jesseyuen** [comment]
It turns out gulp-merge-media-queries was causing the issue. Cheers @xzyfer
