### ISSUE TITLE
node-sass as peerDependency

### ISSUE THREAD

**Issue by MhMadHamster** [dlmanning/gulp-sass#676]
Please consider adding node-sass as a peerDependency instead of dependency, while i am understanding that the current approach more user-friendly, gulp-sass is not really dependent on a node-sass strict version, more of a having node-sass in the project. Moving it to the peerDependency also allows migrating to the latest versions of node-sass more gracefully, since new versions can introduce breaking changes or a lot of warning when compiling, if user will be able to specify version by himself he can update his source code step by step and updating node-sass after.  
Unfortunately specifying dependency explicitly in package.json not always will override version requested by your other dependency.

**Comment by xzyfer** [comment]
Gulp sass has an explicit dependency on node-sass
