### ISSUE TITLE
@media #{$desktop-media} { any-styles }

### ISSUE THREAD

**Issue by archimed3s** [dlmanning/gulp-sass#677]
@media #{$desktop-media} { any-styles } 
This isn't working anymore in latest version of gulp-sass: 3.2.1

To reproduce go thru steps below:
1. define variable - **$desktop-width: XXXpx;**
2. define variable and use previous var - **$desktop-media: 'screen and (min-width: $desktop-width)';**
3. Use variable in the code - **@media #{$desktop-media} { any-styles }**
**Resolution**: after sass compile you can see string in css like example below:
 **@media screen and (min-width: $desktop-width) { any styles }** That not working in any browsers
because **$desktop-width** not defined. And can't be wrote like in the example above.

From package.json:
`"gulp": "git+https://github.com/gulpjs/gulp.git#4.0",

"gulp-autoprefixer": "^5.0.0",

"gulp-if": "^2.0.2",

"gulp-load-plugins": "^1.5.0",

"gulp-sass": "^3.2.1",

"gulp-sourcemaps": "^2.6.4",

"yargs": "^11.1.0"`

From gulpfile.babel.js:
import gulpConfig from './gulp.config';
import gulp from 'gulp';
import plugins from 'gulp-load-plugins';
import yargs from 'yargs';
const $ = plugins(), PRODUCTION = !!(yargs.argv.production);

`function scss() {

return gulp.src(gulpConfig.src.scss)

.pipe($.if(!PRODUCTION, $.sourcemaps.init()))

.pipe($.sass().on(`error`, $.sass.logError))

.pipe($.autoprefixer(gulpConfig.autoPrefixer))

.pipe($.if(!PRODUCTION, $.sourcemaps.write(gulpConfig.mapsDest)))

.pipe(gulp.dest($.if(PRODUCTION, gulpConfig.destProd.scss, gulpConfig.dest.scss)));

}`

**Comment by mmintel** [comment]
same here but not related to media queries:

```SCSS
.theme--light {
  --transparency-1: $black-0125;
}
```

will produce 

```SCSS
.theme--light {
  --transparency-1: $black-0125;
}
```

instead of

```CSS
.theme--light {
  --transparency-1: rgba(0,0,0,0.125);
}
```

**Comment by xzyfer** [comment]
You need to use interpolation when using variables in custom properties

--transparency-1: #{$black-0125};
