### ISSUE TITLE
gulp-sass "command not found"

### ISSUE THREAD

**Issue by amandam2017** [dlmanning/gulp-sass#679]
I have included gulp-sass on gulpfile.js and when I run gulp-sass on the terminal its brings the above error. When I run sass -v it brings back Sass 3.4.24 (Selective Steve)

**Comment by rakeshshriwas** [comment]
**Share your code for better solution**

**Comment by amandam2017** [comment]
C:\mywork\maarman_amanda>
C:\mywork\maarman_amanda>C:\mywork\maarman_amanda>ls
'C:\mywork\maarman_amanda' is not recognized as an internal or external command,
operable program or batch file.

C:\mywork\maarman_amanda>'ls' is not recognized as an internal or external command,
''ls'' is not recognized as an internal or external command,
operable program or batch file.

C:\mywork\maarman_amanda>operable program or batch file.
'operable' is not recognized as an internal or external command,
operable program or batch file.

C:\mywork\maarman_amanda>
C:\mywork\maarman_amanda>C:\mywork\maarman_amanda>sass -v
'C:\mywork\maarman_amanda' is not recognized as an internal or external command,
operable program or batch file.

C:\mywork\maarman_amanda>Sass 3.4.24 (Selective Steve)
Errno::ENOENT: No such file or directory @ rb_sysopen - 3.4.24
  Use --trace for backtrace.

C:\mywork\maarman_amanda>
C:\mywork\maarman_amanda>C:\mywork\maarman_amanda>
The syntax of the command is incorrect.
C:\mywork\maarman_amanda>
C:\mywork\maarman_amanda>
C:\mywork\maarman_amanda>
C:\mywork\maarman_amanda>
