### ISSUE TITLE
Undefined operation: 'rems(18) times 1.25'

### ISSUE THREAD

**Issue by ryyy20** [dlmanning/gulp-sass#682]
I am getting the error: Undefined operation: 'rems(18) times 1.25'. I saw similar posts about this being resolved in 4.8.0. Any help is greatly appreciated!
```
$font-size-base: rems(18) !default; // Assumes the browser default, typically 16px 
$font-size-lg: $font-size-base * 1.25 !default
```
Node v: 6.12.3
Npm v: 5.8.0
Node-sass: 4.8.3

**Comment by xzyfer** [comment]
How is the remaining function defined?

**Comment by ryyy20** [comment]
I've fixed the error, it was a stupid mistake on my end where I wasn't importing functions. Thank you for your help!
