### ISSUE TITLE
Could not find an option named "sourcemap"

### ISSUE THREAD

**Issue by ahmedfarag2010** [dlmanning/gulp-sass#688]
Its was work very fine until i setup a new windows on my pc and setup npm again .. then it now work again
I've tried many solutions
npm install - npm update

![1](https://user-images.githubusercontent.com/17453891/39646841-a558bb3a-4f91-11e8-924d-c50634757cdd.png)

**Comment by xzyfer** [comment]
That output doesn't look right. Can you run npm ls node-sass?

**Comment by ahmedfarag2010** [comment]
I did it .. the same error :(

**Comment by bhartendush** [comment]
@ahmedfarag2010  Did you find any solution to this issue. I have the same issue when I reinstalled window10 on my laptop. Can anybody help??

**Comment by bhartendush** [comment]
I solved the error. We need to install Ruby first on our system (http://www.rubyinstaller.org). Then run -  gem install sass command. Then check the version of the sass insalled with this command - sass -v

These steps fixed my error. Hope this solution works for you. Cheers!!

**Comment by xzyfer** [comment]
The OP appears to be using dart-sass not gulp-node-sass. With dart-sass the flag is --source-map.

**Comment by ahmedfarag2010** [comment]
No i'm still have the error for more than two weeks almost :(

**Comment by xzyfer** [comment]
Run npm ls gulp-sass

**Comment by Ardakilic** [comment]
Old thread, but the solution for me on macOS was to install sass over `gem install sass` instead of `npm i -g sass`.

**Comment by zhanglyni** [comment]
Its was work very fine until i setup a new windows on my,,?
