### ISSUE TITLE
tunnel-agent dependency is security vulnerability

### ISSUE THREAD

**Issue by PrabhanshuAttri** [dlmanning/gulp-sass#691]
npm@6 reported tunnel-agent as a potential security vulnerability, along with hoek.
![gulp-sass-vulnerability](https://user-images.githubusercontent.com/4739486/39950548-7b849d1a-559f-11e8-8a80-b95cfb3f9f17.png)

An issue for hoek already exits #687

**Comment by georgemeehan** [comment]
Is there a way to update this manually?

**Comment by Skriglitz** [comment]
I was having this same issue, it looks like node-sass is unwilling to update `request` as [it'll break their node 6 compatibility] (https://github.com/sass/node-sass/issues/2355). Looks like the only option is to fork `node-sass` update `request` then fork `gulp-sass` and update `node-sass` to your fork for now

**Comment by xzyfer** [comment]
This is fixed in node-sass@4.9.1. Run `npm update node-sass@latest --save`
