### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by DaleMckeown** [dlmanning/gulp-sass#692]
Getting the below error when updating to 4.0.1, which required Node.js 6.0.0

```
Failed to run "Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
\node_modules\gulp-sass\index.js:66
    let sassMap;
    ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (gulpfile.js:12:16)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
```

I understand that you've dropped the `'use strict';` decleration, but is it really worth it considering this will force people to update Node.js for the sake of a few characters? (updating Node.js is a bit of a pita in some IDE's such as VIsual Studio). I've not come across any other package that has taken his approach.

**Comment by xzyfer** [comment]
It isn't about a few characters. We have dependencies that will not work
with older versions of Node. Node 6 is supported. Make sure your IDE is
configured to use the system Node and not its own embedded Node.

**Comment by xzyfer** [comment]
You should only need to tick a check box in your editor settings to use the
system Node JS installation.

**Comment by xzyfer** [comment]
As I said, node 6 should work. Your editor it probably configured to use
VS' embedded node version.

**Comment by kwootten** [comment]
Installed node 6, and set IDE to use the system install and all works now, so thanks for update
