### ISSUE TITLE
gulp-sass not importing my partials

### ISSUE THREAD

**Issue by thomasfaller** [dlmanning/gulp-sass#696]
I'm sure I'm missing something silly here but I made sure the '_' was there on all filenames and import statements.

### gulpfile.js

```javascript
gulp.task('styles', function () {
  return gulp
    .src('./src/sass/**/*.scss')
    .pipe(sass({includePaths: ['./src/sass/']}).on('error', sass.logError))
    .pipe(gulp.dest('dist/styles'));
});
```
### scssfiles

```javascript
-src
    - sass
        - _fonts.scss
        - _mixins.scss
        - _variables.scss
        - theme.scss
```

My imports are in `theme.scss`
```css
// imports
@import './_fonts.scss';
@import './_mixins.scss';
@import './_variables.scss';
```

When typing `gulp styles` it doesn't give any error
```
[06:40:33] Using gulpfile ~/Dropbox-personal/xxxxxxxxxxxx/gulp-pipe-test/gulpfile.js
[06:40:33] Starting 'styles'...
[06:40:33] Finished 'styles' after 69 ms
```
But only 1 file ends up being compiled into the `dist/css` directory:
```
- dist
    - styles
        - theme.css
```

The partials are left untouched. Any thoughts on what I could be doing wrong here?
Thanks guys!

**Comment by xzyfer** [comment]
Sass does not compile partials. As the name suggests these are partially
complete files. Only entry files (no leading underscore) are compiled. It's
expected that partials are imported by entry files.
