### ISSUE TITLE
Error: Undefined variable but it works on browser acctually

### ISSUE THREAD

**Issue by Junior2Ran** [dlmanning/gulp-sass#698]
I got the exact same problem [#654](https://github.com/dlmanning/gulp-sass/issues/654)！
```
// index.scss
@import "./themes/huiyan";
@import "./core/index";
```

```
// huiyan.scss
$font-family: "PingFangSC-Regular", "PingFang SC", "Microsoft YaHei" !default;
```

```
//  core/index.scss
@import "./base";
@import "mixins";
```

```
//  core/base.scss
body {
    padding: 0;
    margin: 0;
    font-family: $font-family;
}
```

When I compile style.scss with gulp-sass I get this error:
> Error in plugin "sass"
> Message:
>     src/components/style/core/base.scss
> Error: Undefined variable: "$font-family".
>         on line 10 of src/components/style/core/base.scss
> >>     font-family: $font-family;
>
>    ---------------^

and it works on browser!
What should i do??

ps. my gulpfile.js
```
function compile(modules) {
    const scssStream = gulp.src(['src/components/**/*.scss'])
        .pipe(sass().on('error', sass.logError))
        .pipe(gulp.dest(modules === false ? esDir : libDir));
}
gulp.task('style', () => {
    compile();
});
```

**Comment by lpaduchuri** [comment]
I am facing the same issue.

**Comment by Junior2Ran** [comment]
@lpaduchuri 
I found the solution! sass compiling needs ONLY ONE entrance `.scss` file. So the `gulpfile.js` config above is incorrect~
The correct solution is to change the `gulpfile.js` file like below:
 ```
function compile(modules) {
    const scssStream = gulp.src(['src/components/index.scss'])  // the only one entrance sass file
        .pipe(sass().on('error', sass.logError))
        .pipe(gulp.dest(modules === false ? esDir : libDir));
}
gulp.task('style', () => {
    compile();
});
```
