### ISSUE TITLE
node v4.x broken

### ISSUE THREAD

**Issue by jguiban** [dlmanning/gulp-sass#699]
/data/buildroot/output.smarcfimx6/host/usr/lib/node_modules/gulp-sass/index.js:66
    let sassMap;
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

It can be fixed by adding 'use strict' on top of  inex.js

**Comment by xzyfer** [comment]
The latest gulp-sass requires Node 6 due to some dependencies.

**Comment by jguiban** [comment]
On m'y sise, adding 'use strict' on top of index.js IS enough to fix this issue.

**Comment by nheath99** [comment]
For people coming here using Visual Studio 2017, [this link](https://stackoverflow.com/questions/43849585/update-node-version-in-visual-studio-2017) tells you how to ensure VS is using the correct node version

**Comment by jguiban** [comment]
I don't see the reason for non adding strict mode and then support nodejs 4.x.
My project requires nodejs4.2.1, it is an embeddeed environment with buildroot where you cannot update easily nodejs version as on desktop/server.

**Comment by xzyfer** [comment]
The issue isn't strict mode. Even if we added it gulp-sass would still fail due dependencies requiring Node 6.

**Comment by xzyfer** [comment]
If you need Node < 6 support use gulp-sas@2. It's exactly the same.
