### ISSUE TITLE
gulp-sass some time stop working on gulp.watch method 

### ISSUE THREAD

**Issue by AR50** [dlmanning/gulp-sass#700]
gulp-sass work well when i run (gulp sass) but when i use it in gulp.watch it some time work and some time not.  I make some change and save  it give me error message (File to import not found or unreadable: ./base.) in which file i change . but if i save it again it's work.

**Comment by Priyam-EP** [comment]
Is there any solution for this?

**Comment by AR50** [comment]
I find one. use gulp-wait;
