### ISSUE TITLE
`node-sass` is required even if using a different `compiler`

### ISSUE THREAD

**Issue by mrkishi** [dlmanning/gulp-sass#715]
`node-sass` is always required upon `require('gulp-sass')`. This means when `node-sass` isn't working (eg. it isn't on node 11 yet right now), one can't use `sass.compiler = require('dart-sass')` because `require('gulp-sass')` itself will fail.

```
> const sass = require('gulp-sass')
[20:46:36] Error: Node Sass does not yet support your current environment:
Windows 64-bit with Unsupported runtime (67)
```

Could `gulp-sass` conditionally require `node-sass` inside the main function? This would be a breaking change since `require('gulp-sass').compiler` would be `undefined` until the gulp stream's started — but since it's currently not possible to use a different compiler without requiring the default one, it may very well be worth it.

**Comment by xzyfer** [comment]
This has been discussed before. It isn't currently planned. It's always
been possible to change compiler.

If you specifically just want to use dart sass you can try gulp-dart-sass.
