### ISSUE TITLE
Cannot compile some of the new iPhone X safe area functions

### ISSUE THREAD

**Issue by ConduciveMammal** [dlmanning/gulp-sass#718]
When trying to compile SCSS that contains the new iPhone X safe functions, Gulp Sass fails on some of them.

The main on I've found is `padding-left: max(12px, env(safe-area-inset-left));`
Gulp Sass produced the error: `"env(safe-area-inset-left)" is not a number for 'max'`

But strangely, this one works fine: `padding-left: env(safe-area-inset-left);`

There may be more that I've not yet found.

I'm getting these from: https://webkit.org/blog/7929/designing-websites-for-iphone-x/

**Comment by Patta** [comment]
https://github.com/sass/sass/issues/2378

**Comment by xzyfer** [comment]
This is being tracked in https://github.com/sass/libsass/issues/2701
