### ISSUE TITLE
Typescript problem

### ISSUE THREAD

**Issue by peterremote1980** [dlmanning/gulp-sass#727]
Hi All
   After i use the follow code to transpile all scss files to css files. My typescript code failed because it still try to include the scss file. I checked with other open source projects, they transpile scss into scss.js file. Any hints?

```
import styles from './QuantrCalendar.module.scss';
```

```
gulp.task('sass', function () {
	return gulp.src('./src/**/*.scss')
		.pipe(sass().on('error', sass.logError))
		.pipe(gulp.dest('./lib'));
});
```

thanks
From Peter

**Comment by xzyfer** [comment]
We don't know anything about typescript.
