### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by WuglyakBolgoink** [dlmanning/gulp-sass#729]
Hallo!

Can you update all dependencies?

Related #719

**Comment by chryton** [comment]
Installation is currently breaking in Node 12 due to the `node-sass` version being out of date and incompatible with newer versions of Node. #720 is a step towards that fix. @xzyfer Do we have an estimated timeline for when Node 12 will be supported and dependencies bumped to do so?

**Comment by simonua** [comment]
I updated #720 earlier todau to now also reference NodeJS 12.

**Comment by xzyfer** [comment]
This is not needed because of how SemVer works. You can always update the transient node-sass with `npm update node-sass` if you wish.

https://nodesource.com/blog/semver-tilde-and-caret
