### ISSUE TITLE
Crash on scss error when using source maps

### ISSUE THREAD

**Issue by artish** [dlmanning/gulp-sass#73]
When I use gulp-sass with sourcemaps the errors don't get logged to the console anymore and gulp just crashes.

My config:

```javascript
var options = {};

options.sass = {
    errLogToConsole: true,
    sourceComments: 'map',
    sourceMap: 'scss'
}

// Styles for development
// libSASS & Autoprefixer
// [gulp-sass](https://www.npmjs.org/package/gulp-sass)
// [gulp-autoprefixer](https://www.npmjs.org/package/gulp-autoprefixer)
gulp.task('styles-dev', function() {
  return gulp.src(scss_src_dir + '/style.scss')
    .pipe(plugins.sass(options.sass))
    .pipe(plugins.autoprefixer('last 2 versions', 'ie 9', 'ios 6', 'android 4'))
    .pipe(gulp.dest(scss_dst_dir))
    .pipe(browserSync.reload({stream:true}));
});
```

The error returned:
60543 segmentation fault  gulp

**Comment by Snugug** [comment]
This has been [resolved in 2.x](https://github.com/dlmanning/gulp-sass/blob/2.x). We have moved to using [`gulp-sourcemaps`](https://github.com/dlmanning/gulp-sass/tree/2.x#source-maps) like suggested earlier in this thread. Please try it and report back. If we don't hear back, we'll assume it's been resolved and close this issue.

```
npm install dlmanning/gulp-sass#2.x
```

**Comment by Snugug** [comment]
As it's been a month, I'm closing this.
