### ISSUE TITLE
Using dart sass still requires installing node-sass and its native addon

### ISSUE THREAD

**Issue by stof** [dlmanning/gulp-sass#731]
#694 added support for dart-sass, but node-sass is still always installed, with its gyp build process.

It would be great to make a new major version of gulp-sass which would make it required to always choose the compiler explicitly, avoiding that dependency (or to change the default compiler to dart-sass as always installing that one would not involve a special build process).

**Comment by xzyfer** [comment]
We have no plans to do this. You can use gulp-dart-sass to achieve this.
