### ISSUE TITLE
 Cannot run sass task: missing in gulpfile.js

### ISSUE THREAD

**Issue by silu44** [dlmanning/gulp-sass#733]
I got this error  :  Cannot run sass task: missing in gulpfile.js

here is my gulpfile.js
 
 
var gulp = require('gulp');
var sass = require('gulp-sass');
var cleanCss = require('gulp-clean-css');
var rename = require('gulp-rename');

var paths = {
  sass: ['./scss/**/*.scss']
};

gulp.task('default', ['sass']);

gulp.task('sass', function(done) {
  gulp.src('./scss/ionic.app.scss')
    .pipe(sass())
    .on('error', sass.logError)
    .pipe(gulp.dest('./www/css/'))
    .pipe(cleanCss({
      keepSpecialComments: 0
    }))
    .pipe(rename({ extname: '.min.css' }))
    .pipe(gulp.dest('./www/css/'))
    .on('end', done);
});

gulp.task('watch', ['sass'], function() {
  gulp.watch(paths.sass, ['sass']);
})

**Comment by kobrix** [comment]
Without seeing your package.json, my guess is you installed Gulp v4 but the gulpfile is written for Gulp v3.
