### ISSUE TITLE
How build @import '~normalize-css/normalize.css' in the node_modules dependencies

### ISSUE THREAD

**Issue by PolanZ** [dlmanning/gulp-sass#743]
main.scss
```
@import '~normalize-css/normalize.css'

// ..
```

Build:
main.css
```
// not normalize.css content.
...
```

How to do!

like webpack it can build, [see](https://github.com/webpack-contrib/css-loader/issues/12#issuecomment-41940311)

**Comment by matthewmcvickar** [comment]
@PolanZ Try this instead:

```
@import "normalize.css/normalize";
```

**Comment by PolanZ** [comment]
@matthewmcvickar thx!

I know the this way, But at the same time use webpack. So
I use the [node-sass-package-importer](https://github.com/maoberlehner/node-sass-magic-importer/tree/master/packages/node-sass-package-importer)  plugin solved it.
