### ISSUE TITLE
npm install fails installing node-sass

### ISSUE THREAD

**Issue by AreYouSureYouKen** [dlmanning/gulp-sass#752]
When running `npm install gulp-sass` it tries to download a binary from https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-72_binding.node but this returns a 404, where afterwards the postinstall fails to complete.

I noticed that the node-sass dependency is ^4.8.3, the most recent version of node-sass is currently 4.13.0. This might cause some issues.

**Comment by JoshLefebvre** [comment]
Getting the same error. Have you found a workaround for this?

**Comment by gimmixAT** [comment]
adding the latest node-sass to my package.json fixed it for me
