### ISSUE TITLE
wont compile and include all imported files

### ISSUE THREAD

**Issue by kumaresan-subramani** [dlmanning/gulp-sass#757]
Below is my import statment

```
@import '../../node_modules/@syncfusion/ej2-angular-grids/styles/material.scss';

.checking {
    @import '../../node_modules/@syncfusion/ej2-angular-grids/styles/material-dark.scss';
}
```
my gulp task is like below:

```
gulp.task('styles', function () {
    sass.compiler = require('node-sass');
    return gulp.src("./check/*.scss")
        .pipe(sass({
            outputStyle: 'expanded',
            includePaths: ["./node_modules/@syncfusion/"]
        }))
        .pipe(sass.sync().on('error', sass.logError))
        .pipe(gulp.dest('./src/'));
});

```

when i compile, it wont generate all required class for 2nd import inside `checking` class

Sample - https://github.com/kumaresan-subramani/anguular-scss

To Run Sample - 

1. npm i
2. gulp styles
3. ng serve

**Comment by nitro404** [comment]
This sounds like an issue with https://github.com/sass/node-sass.

**Comment by kumaresan-subramani** [comment]
Any reference ?

**Comment by XhmikosR** [comment]
@xzyfer this one too.

(Sorry for the numerous CCs, trying to clean up the repo issues)
