### ISSUE TITLE
Outdated node-sass is incompatible with node 12

### ISSUE THREAD

**Issue by mrgnou** [dlmanning/gulp-sass#759]
Hey,

The node-sass dependency needs to be updated as node-sass won't run with the current version of node (12+).

**Comment by mmunchandersen** [comment]
I'm getting this in Visual Studio 2019 16.5.0 when I do this in my Gulpfile.js (using "gulp": "4.0.2" and "gulp-sass": "4.0.2",:

`var sass = require("gulp-sass");`

> Failed to run "C:\project-x\Gulpfile.js"...
> cmd.exe /c gulp --tasks-simple
> C:\project-x\node_modules\node-sass\lib\binding.js:13
>       throw new Error(errors.unsupportedEnvironment());
>       ^
> Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (72)
> For more information on which environments are supported please see:
> https://github.com/sass/node-sass/releases/tag/v4.11.0
>     at module.exports (C:\project-x\node_modules\node-sass\lib\binding.js:13:13)
>     at Object.<anonymous> (C:\project-x\node_modules\node-sass\lib\index.js:14:35)
>     at Module._compile (internal/modules/cjs/loader.js:959:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
>     at Module.load (internal/modules/cjs/loader.js:815:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
>     at Module.require (internal/modules/cjs/loader.js:852:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (C:\project-x\node_modules\gulp-sass\index.js:162:21)
>     at Module._compile (internal/modules/cjs/loader.js:959:30)

**Comment by harski** [comment]
In my brief test, bumping the node-sass dependency to 4.13.1 did not break anything.

**Comment by mmunchandersen** [comment]
@harski I have never touched package-lock.json. Is this where you have bumped node-sass to 4.13.1?
![2020-03-21_18-59-02](https://user-images.githubusercontent.com/3047487/77233832-82b90f80-6baa-11ea-98cf-7198be86431e.png)

**Comment by harski** [comment]
@mmunchandersen I put `"devDependencies": { "node-sass": "^4.13.1" }` to my own project's `package.json` and ran `npm install`. The dependency got resolved to a node 12 compatible version.

**Comment by mmunchandersen** [comment]
thanks @harski it appears to have solved my issue too

**Comment by nitro404** [comment]
This can also be fixed by both bumping the internal version or by allowing the compiler to be passed in as an argument via https://github.com/dlmanning/gulp-sass/pull/748.
