### ISSUE TITLE
Is gulp-sass dead?

### ISSUE THREAD

**Issue by flexjoly** [dlmanning/gulp-sass#761]
Hi,
Is gulp-sass still maintained? And getting the latest updates?
It is not even mentioned anymore on sass-lang :-(

Do we need to switch to another builder? Or is there a new fork?

I do hope gulp-sass will be updated soon!!

Greetz, flexjoly

**Comment by sscholle** [comment]
Well one year unmaintained is a lifetime in the dev world. I'd recommend make a fork, and then possibly a PR for your updates. I need to do the same soon, can't live like this. :-(

**Comment by xzyfer** [comment]
It's maintained. There haven't been any required updates.

**Comment by ryanaltvater** [comment]
@xzyfer Updating `node-sass` to be compatible with Node 15 seems like a required update right now. This is an issue I ran into yesterday that was filed as an issue by someone else in November that is still unresolved. No updates for 9 months feels like a flatlining repo to me. Should maybe re-open this issue for visibility, in hopes that others are able to contribute if it's recognized that things aren't being maintained anymore. People could also recommend alternatives.
