### ISSUE TITLE
Changes to imported SASS files not updated on dev server

### ISSUE THREAD

**Issue by ajayns** [dlmanning/gulp-sass#764]
When I make changes to any files other than my `main.scss` file (the root which imports all the other scss files), the change is not reflected in live server. I get a flash of updated style and then it goes back to the existing style. Any changes to the `main.scss` still makes live updates.

For example:
main.scss
```scss
@import '_headings.scss';
```
Any changes made to `_headings.scss` is not updated but a momentary flash can be noticed.

My config:
```js
import { src, dest} from 'gulp';
import sass from "gulp-sass";
import autoprefixer from "autoprefixer";
import rename from "gulp-rename";
import cssnano from "cssnano";
import postcss from "gulp-postcss";
import gulpif from "gulp-if";
import { server } from "./serve";

// the server
// const server = browserSync.create();

function styles() {
  const plugins = [
    autoprefixer({ cascade: false }),
    cssnano()
  ];

  return src("src/styles/**/*.scss")
    .pipe(sass().on("error", sass.logError))
    .pipe(postcss(plugins))
    .pipe(rename({ suffix: ".min" }))
    .pipe(dest("public/"))
    .pipe(gulpif(!build, server.stream()));
}
```

I watch all files in the directory as well:
```js
import { watch } from 'gulp';

function gulpwatch() {
  watch("src/styles/", styles);
}
```

**Comment by kuzivany** [comment]
Hopefully this is helpful:

https://github.com/dlmanning/gulp-sass/issues/739#issuecomment-642510620

**Comment by ajayns** [comment]
@kuzivany Thank you, I shall check out the solution and get back

**Comment by ajayns** [comment]
Actually, I had to update node and it's file watchers recently and that seemed to have fixed this issue. I believe it due to other dependencies rather than sass itself. Thank you for the help though. 

Closing this issue.
