### ISSUE TITLE
Why is node-sass a hard dependency when one could also choose dart-sass?

### ISSUE THREAD

**Issue by hoeni** [dlmanning/gulp-sass#765]
as we only use dart-sass with gulp-sass, this is especially hard when you hit one of the various build problems of node-sass.

Are there reasons not to remove it or make it a peer dependency?

**Comment by xzyfer** [comment]
Because the maintainer of gulp sass are the same maintainers of node-sass

**Comment by DanielRuf** [comment]
Well, the docs mention to install node-sass too. So isn't the node-sass dependency a bit duplicate?
