### ISSUE TITLE
Support for node-sass custom functions

### ISSUE THREAD

**Issue by colis** [dlmanning/gulp-sass#767]
Hi,

does gulp-sass support node-sass [custom functions](https://github.com/sass/node-sass#example)?

Thanks!

**Comment by cpiber** [comment]
In case you still need this info: gulp-sass is a wrapper around node-sass, you can transparently pass all options (https://github.com/dlmanning/gulp-sass#options)

**Comment by XhmikosR** [comment]
@xzyfer this can be closed too
