### ISSUE TITLE
Gulp sass doesn't compile when a use preffix extension

### ISSUE THREAD

**Issue by victor-osf** [dlmanning/gulp-sass#769]
I'm tryng to create a new gulp task to run into my application and look for all '*.fragment.sass' files.

I wrote:

```
gulp.task('sassFragments', () => {
  return gulp
    .src('./src/**/*.fragment.sass')
    .pipe(debug())
    .pipe(sassGlob())
    .pipe(sass({ outputStyle: 'expanded' })).on('error', sass.logError)
    .pipe(concat('fragments_style.css'))
    .pipe(gulp.dest('./build/assets/css'))
    .pipe(browserSync.reload({ stream: true }));
})
```

but no fragments_style.css is created in /build/assets/css folder.

I have another task which does similar using src('./src/**/*.sass') to generate a style.css file and works great!

I think there is a issue with pipe sass() method, that is not matching this '.fragment.sass' pattern.

Can anyone help me?

Gulp version: 3.9.1

**Comment by yifaneye** [comment]
I got the same issue!
