### ISSUE TITLE
Should gulp-sass recommend node-fibers package now that it's obsolete?

### ISSUE THREAD

**Issue by adamjohnson** [dlmanning/gulp-sass#771]
From the [node-fibers](https://github.com/laverdet/node-fibers/blob/master/README.md) `README.md`:

  > **NOTE OF OBSOLESCENCE** -- The author of this project recommends you avoid its use if possible. The original version of this module targeted nodejs v0.1.x in early 2011 when JavaScript on the server looked a lot different. Since then async/await, Promises, and Generators were standardized and the ecosystem as a whole has moved in that direction.

  > I'll continue to support newer versions of nodejs as long as possible but v8 and nodejs are extraordinarily complex and dynamic platforms. It is inevitable that one day this library will abruptly stop working and no one will be able to do anything about it.

`node-fibers` is referenced in the [gulp-sass README](https://github.com/dlmanning/gulp-sass#basic-usage) under "Basic Usage with Dart Sass.

I'm wondering if there is a different way to solve what the `node-fibers` package does via Gulp v4 / async/await, et all.

**Comment by xzyfer** [comment]
Fixed in v5.0.0
