### ISSUE TITLE
Importing files with "@use" breaks compilation

### ISSUE THREAD

**Issue by nickbarrow** [dlmanning/gulp-sass#772]
I am attempting to switch all my `@imports` to `@use`, [as per Sass's intentions to remove the @import rule](https://sass-lang.com/documentation/at-rules/import).

For example, using 
```
@use 'defaults/variables';
@use 'layout/theme';
```
in my main.scss compiles to:
```
@use 'defaults/variables';
@use 'layout/theme';
```

in my compiled css file, where I would expect it to compile down to my rules in theme.scss as it does with `@import`.

**Comment by xzyfer** [comment]
This is not currently supported with the node-sass engine. You can opt into the Dart sass engine to this feature. See the read me on how to do this.

**Comment by vggarg96** [comment]
Hello I am having the similar issue although I am using 
`@import "~@angular/material/theming";` 
I am getting following error when i run my gulp task
`Error: File to import not found or unreadable: ~@angular/material/theming.`

I don't know why it is not working
