### ISSUE TITLE
Best practice to remove special comments /*! comment */

### ISSUE THREAD

**Issue by yansusanto** [dlmanning/gulp-sass#773]
Hi all,

May I know what is the best way to remove special comments /*! comment */?

```
		.pipe(
			sass({
				includePaths: ["node_modules"], 
				outputStyle: 'compressed',
			}).on("error", sass.logError)
		)
```

How can I get it to have special comments removed?

**Comment by XhmikosR** [comment]
Yeah, don't use special comments in the first place :)

**Comment by xzyfer** [comment]
This isn't a Sass feature. We suggest looking at a css minifier plugin.
