### ISSUE TITLE
Internet explorer 11 and -ms-grid-rows / -ms-grid-columns

### ISSUE THREAD

**Issue by joehuggans** [dlmanning/gulp-sass#777]
I have found an issue when the following is compiled -

-ms-grid-columns: (20%) [5];

The complied css is

-ms-grid-columns: 20% [5];

Which fails in ie11, the curly brackets seem to be necessary otherwise the grid fails.

Maybe I am missing something here, in which case I apologise, but I could not find anything else online about this issue and from my testing in IE11 (god save us all) the only way I could correct this was to re-add back in the curly braces.

**Comment by cpiber** [comment]
This is not an issue with gulp-sass and the intended behaviour of sass.
To get sass to output non-standard properties like these, consider using `-ms-grid-columns: unquote("(20%) [5]");`

**Comment by XhmikosR** [comment]
@xzyfer this is unrelated to this repo too
