### ISSUE TITLE
Support Node 15

### ISSUE THREAD

**Issue by edwin-egalite** [dlmanning/gulp-sass#778]
Sass 4 does not support Node 15. Hence, can't install gulp-sass on Node 15.

**Comment by merlinschumacher** [comment]
It works to forcibly install node-sass@5.0.1

**Comment by edwin-egalite** [comment]
> It works to forcibly install node-sass@5.0.1

Could you please advise how to do this? Thanks.

**Comment by bonesoul** [comment]
also looking for it @merlinschumacher

**Comment by merlinschumacher** [comment]
Just do
```bash
npm install node-sass@5.0.1 --save-dev
```
in your project directory.

**Comment by bonesoul** [comment]
should be node-sass@5.0.0 i guess.

**Comment by merlinschumacher** [comment]
> should be node-sass@5.0.0 i guess.

right! fixed it.

**Comment by Trainmaster** [comment]
`gulp-sass@4.1.0` requires `"node-sass": "^4.8.3"` which does not allow `node-sass@5.0.0`.

**Comment by selfisekai** [comment]
I created a fork of gulp-sass that doesn't list node-sass as a dependency at all:
https://yarnpkg.com/package/@selfisekai/gulp-sass
https://www.npmjs.com/package/@selfisekai/gulp-sass
https://git.sakamoto.pl/selfisekai/gulp-sass

**Comment by NickSharf** [comment]
There is a package based on this project with dart-sass replacement https://www.npmjs.com/package/gulp-dart-sass. Try to use it instead of gulp-sass.

**Comment by zetareticoli** [comment]
> There is a package based on this project with dart-sass replacement https://www.npmjs.com/package/gulp-dart-sass. Try to use it instead of gulp-sass.

Does it work on Apple Silicon?

**Comment by NickSharf** [comment]
> 
> 
> > There is a package based on this project with dart-sass replacement https://www.npmjs.com/package/gulp-dart-sass. Try to use it instead of gulp-sass.
> 
> Does it work on Apple Silicon?

I use my terminal app with Rosetta 2 because Node and some apps still have some issues with M1 processor. In this mode everything works fine on Node 15 .

**Comment by zetareticoli** [comment]
Ok! So I should replace gulp-sass with gulp-dart-sass to get things working

**Comment by NickSharf** [comment]
> 
> 
> Ok! So I should replace gulp-sass with gulp-dart-sass to get things working

Yep. That was the only thing I had to do. I have replaced it in package.json and gulpfile.js. And reinstall all packages (npm i)

**Comment by xzyfer** [comment]
Fixed in v5.0.0
