### ISSUE TITLE
Will gulp-sass be replacing deprecated node-sass with its replacement, dart sass?

### ISSUE THREAD

**Issue by ajssd** [dlmanning/gulp-sass#779]
See https://sass-lang.com/blog/libsass-is-deprecated

Just wondering what the future is for gulp-sass given the security issues with node-sass, and now the fact that it is deprecated?

**Comment by shlomiassaf** [comment]
I can only assume that replacement is an issue, due to backward compatibility of this package.

Of course, a new major version can issue a breaking change...

I think, as a first step, that hard require for `node-sass` but be remove as well as the direct dependency.
In angular, this is an issue...

**Comment by vincentwinkel** [comment]
I face the same issue. I cannot find an alternative.

**Comment by NickSharf** [comment]
There is a package based on this project with dart-sass replacement https://www.npmjs.com/package/gulp-dart-sass. Try to use it instead of gulp-sass.

**Comment by xzyfer** [comment]
Fixed in v5.0.0
