### ISSUE TITLE
Gulp-sass depends on Node-Sass

### ISSUE THREAD

**Issue by arontsang** [dlmanning/gulp-sass#782]
There should not be a dependency on Node-Sass given that users should be able to choose to use Dart-Sass as a dependency instead of Node-Sass.

**Comment by SteveMelons** [comment]
This is an issue. I can't npm install gulp-sass because it is trying to install node-sass and throwing errors.

**Comment by Synj24** [comment]
I'm also having troubles trying to install because of node-sass

**Comment by duolaam** [comment]
node-sass depends on the python2 environment. makes npm install difficult

**Comment by NickSharf** [comment]
There is a package based on this project with dart-sass replacement https://www.npmjs.com/package/gulp-dart-sass. Try to use it instead of gulp-sass.

**Comment by GregOriol** [comment]
I'd also like to add that node-sass seems to take up ~160MB when installed, which is huge for a module, and even mode huge when it is not used because using the dart compiler...
