### ISSUE TITLE
Depends on node-sass

### ISSUE THREAD

**Issue by jumodada** [dlmanning/gulp-sass#785]
it is recommended to replace node-sass with dart-sass

**Comment by NickSharf** [comment]
There is a package based on this project with dart-sass replacement https://www.npmjs.com/package/gulp-dart-sass. Try to use it instead of gulp-sass.

**Comment by Mister-Hope** [comment]
> There is a package based on this project with dart-sass replacement https://www.npmjs.com/package/gulp-dart-sass. Try to use it instead of gulp-sass.

That repo is closing its issue panel. I am fully negative to a 1 contributer forked project without a issue panel.

That means if I meet a bug, I must must read though the code and open a PR. And if no responese, I must fork, fix and publish a package of my own, I would rather fork this repo and implement a package by myself.

**Comment by Mister-Hope** [comment]
Unless the contributer wants to leave this project deperate in the future, I think it's necessary to switch to `sass` package.

**Comment by waltercruz** [comment]
I agree with @Mister-Hope. Please remove the node-sass dependency!

**Comment by Mister-Hope** [comment]
For anyone wants to use `sass` and prevent downloading `node-sass`, here is a plugin:

- [@mr-hope/gulp-sass](https://github.com/Mister-Hope/gulp-sass)

It's a totlly rewritten version of this repo, inlucding:

- all the files rewriten with typescript (This will provide better hint in options with IDE support)
- use `jest` instead of mocha to provide coverage support

**Comment by jerrylow** [comment]
Thanks @Mister-Hope I think `sass` is the way to go and should push for testing and getting #786 in.

**Comment by Mister-Hope** [comment]
> Thanks @Mister-Hope I think `sass` is the way to go and should push for testing and getting #786 in.

@jerrylow You PR do works, but I still recomand you to use my plugin.

This repo is lack of maintainence for quite a long while. I am using typescript for better option hints, and rewrite the test in typescript using jest to provide coverage support, also all the deps are in it's latest version.

**Comment by jerrylow** [comment]
@Mister-Hope actually good call.

**Comment by daedam** [comment]
I think it is useful that this plugin allows for the choice of node-sass or dart-sass, but it is unfortunate that node-sass is used by default and therefore a dependency. Wouldn't an easy fix be to remove the node-sass dependency, remove the [assignment to the `compiler` property](https://github.com/dlmanning/gulp-sass/blob/master/index.js#L166), and update the documentation to instruct users to install their preferred package and set the `compiler` property manually? Granted, it would be a breaking change, but it would allow this plugin to remain useful for either compiler without requiring node-sass to be installed even when dart-sass is being used.

**Comment by kitsunekyo** [comment]
please dont forget that node-sass isnt just "cosmetically" deprecated.
by using node-sass you miss out on all new sass features like namespaced imports (@use).

[https://sass-lang.com/blog/libsass-is-deprecated](https://sass-lang.com/blog/libsass-is-deprecated)

so node-sass CANNOT stay in this project unless we want to move this repo to the npm graveyard.

**Comment by Mister-Hope** [comment]
> please dont forget that node-sass isnt just "cosmetically" deprecated.
> by using node-sass you miss out on all new sass features like namespaced imports (@use).
> 
> [https://sass-lang.com/blog/libsass-is-deprecated](https://sass-lang.com/blog/libsass-is-deprecated)
> 
> so node-sass CANNOT stay in this project unless we want to move this repo to the npm graveyard.

Try my plugin🧐

**Comment by kitsunekyo** [comment]
> > please dont forget that node-sass isnt just "cosmetically" deprecated.
> > by using node-sass you miss out on all new sass features like namespaced imports (@use).
> > https://sass-lang.com/blog/libsass-is-deprecated
> > so node-sass CANNOT stay in this project unless we want to move this repo to the npm graveyard.
> 
> Try my plugin🧐

i prefer open source where we keep the quality of a few packages high, over a million duplicated projects, where most of them are broken and you have to be lucky to pick the "right" one.

**Comment by noppa** [comment]
@kitsunekyo Simple documentation change isn't quite enough - the dependency to node-sass should also be dropped from package.json (which is a breaking change) for this project to remain a viable alternative. The C++ libsass is a horrible transitive dependency to have, even if you don't actually use it at runtime. npm will still try to build it on install and then bursts into flames when some little thing isn't exactly right in the build environment. Just google "node-sass error" and witness the pain.

**Comment by duzun** [comment]
Besides the pain to build `node-sass`, there is a pain in trying to avoid loading it.
I was trying to use `gulp-sass` with `sass` (`dart-sass`) on node@15:

```js
const sass = require('gulp-sass');
sass.compiler = require('sass');
```

But `gulp-sass` is loading `node-sass` when `require`d, thus throwing an error.

I've made the PR [#791](https://github.com/dlmanning/gulp-sass/pull/791) to fix this pain, but now I'm thinking of switching to something else :(

**Comment by alpwe** [comment]
> Besides the pain to build `node-sass`, there is a pain in trying to avoid loading it.
> I was trying to use `gulp-sass` with `sass` (`dart-sass`) on node@15:
> 
> ```js
> const sass = require('gulp-sass');
> sass.compiler = require('sass');
> ```
> 
> But `gulp-sass` is loading `node-sass` when `require`d, thus throwing an error.
> 
> I've made the PR [#791](https://github.com/dlmanning/gulp-sass/pull/791) to fix this pain, but now I'm thinking of switching to something else :(


Hello
In my gulpfile.js I removed this line
sass.compiler = require ('sass');

And remove these "node-sass gulp-sass" packages
npm rm node-sass gulp-sass
npm cache clear --force
npm i gulp-sass
And start Gulp, the error was gone.

Perhaps the information in the manual for the "gulp-sass" package is not up to date?

**Comment by duzun** [comment]
@alpwe I guess I wasn't clear enough on what my intention is :)
I can not run `node-sass` on node@15, thus I wanted to replace `node-sass` with `dart-sass` (package name `sass`). That is my intention.

Before node@15 your suggestions would help.

**Comment by alpwe** [comment]
@duzun Ohh, sory )))
When I tried to install node-sass with node 15.14.0 I got a message in the terminal "node-sass is not supported yet"
And I just installed NodeJs LTS (14.6.1)
Maybe npm up node-sass will help?

**Comment by duzun** [comment]
@alpwe unfortunately `node-sass` states clearly that it is deprecated and there will be no support for new versions of NodeJs.
Also, I don't like the idea to keep using node@14 just because some deprecated libraries. Sooner or later it would bite.

**Comment by alpwe** [comment]
@duzun sorry in advance, but what if ...

in gulp-sass/**ipackage.json** remove line
```
"dependencies": {
    "node-sass": "^4.8.3",
}
```
and add
```
"optionalDependencies": {
    "node-sass": "^4.8.3",
    "sass": "^1.26.3"
}
```

in gulp-sass/**index.js** replace the line
```
gulpSass.compiler = require('node-sass');
```
on the
```
try {
  gulpSass.compiler = require('node-sass');
} catch (er) {
  gulpSass.compiler = require('sass');
}
```

**Comment by ghostdevv** [comment]
Please do this! Needing the newer sass features and unable to have them via `node-sass`
