### ISSUE TITLE
gulp-sass ignoring new changes

### ISSUE THREAD

**Issue by erik-valtechsd** [dlmanning/gulp-sass#787]
after making small changes in my scss files sometimes they are not included in the compiled version. I would guess that means there is an issue with cache not clearing? Not sure whats going wrong here but its been driving me mad. any tips on how to solve appreciated.

```
gulp.task("sass", async function () {
  gulp
    // Load styles.sass into the stream
    .src("scss/bootstrap.scss")
    // Compile the styles.scss using the gulp-sass package
    .pipe(sass({ noCache: true, outputStyle: "compressed" }))
    // Save the compiled file as styles.css to our distribution location
    .pipe(rename("style.min.css"))
    .pipe(gulp.dest("assets/css"));
});
```

**Comment by cpiber** [comment]
How is this task run? you did not include the watch portion.
Also this function does not need to be async and should return the stream (`return gulp.src...`).

**Comment by XhmikosR** [comment]
@xzyfer this can be closed too; it's a usage question.
