### ISSUE TITLE
Can´t install gulp-sass latest version in Windows 10

### ISSUE THREAD

**Issue by angelmgl** [dlmanning/gulp-sass#793]
I want to install gulp-sass in my new project, and I can't
I tried with npm and yarn, but anyone works
This is the data:

NPM version (npm -v): 7.0.15
Node version (node -v): 15.4.0
Node Process (node -p process.versions):
{
node: '15.4.0',
v8: '8.6.395.17-node.22',
uv: '1.40.0',
zlib: '1.2.11',
brotli: '1.0.9',
ares: '1.16.1',
modules: '88',
nghttp2: '1.41.0',
napi: '7',
llhttp: '2.1.3',
openssl: '1.1.1g',
cldr: '38.0',
icu: '68.1',
tz: '2020b',
unicode: '13.0'
}
Node Platform (node -p process.platform): win32
Node architecture (node -p process.arch): x64

Error log : 
[2021-04-21T23_29_30_828Z-debug.log](https://github.com/dlmanning/gulp-sass/files/6354481/2021-04-21T23_29_30_828Z-debug.log)

npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path C:\Users\acer\Desktop\Web Dev\Curso PHP\music-festival\node_modules\gulp-sass\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\acer\Desktop\Web Dev\Curso PHP\music-festival\node_modules\gulp-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\acer\\Desktop\\Web Dev\\Curso PHP\\music-festival\\node_modules\\gulp-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@15.4.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\acer\Desktop\Web Dev\Curso PHP\music-festival\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\acer\Desktop\Web Dev\Curso PHP\music-festival\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\acer\Desktop\Web Dev\Curso PHP\music-festival\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\acer\Desktop\Web Dev\Curso PHP\music-festival\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\acer\Desktop\Web Dev\Curso PHP\music-festival\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\acer\Desktop\Web Dev\Curso PHP\music-festival\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\acer\Desktop\Web Dev\Curso PHP\music-festival\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\acer\Desktop\Web Dev\Curso PHP\music-festival\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\acer\Desktop\Web Dev\Curso PHP\music-festival\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\acer\Desktop\Web Dev\Curso PHP\music-festival\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\acer\Desktop\Web Dev\Curso PHP\music-festival\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\acer\Desktop\Web Dev\Curso PHP\music-festival\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python39\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1063:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\acer\\Desktop\\Web Dev\\Curso PHP\\music-festival\\node_modules\\gulp-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\acer\Desktop\Web Dev\Curso PHP\music-festival\node_modules\gulp-sass\node_modules\node-sass
npm ERR! gyp ERR! node -v v15.4.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\acer\AppData\Local\npm-cache\_logs\2021-04-21T23_29_30_828Z-debug.log
`

**Comment by toitzi** [comment]
Got a similar error on latest ubuntu, digging a bit deeper the dependencies i think:

`npm ERR! gyp verb check python checking for Python executable "python2" in the PATH`
`npm ERR! gyp verb which failed Error: not found: python2`

is key here. Latest gulp-sass still uses ` "node-sass": "^4.8.3",` which depends on ` "node-gyp": "^3.8.0"`.
Hover `node-gyp` in v3.x still requires you to have `python2` installed (which as the error above indicates you do not have installed)

Upgrading the dependencies of `gulp-sass` to use the latest `node-sass` version which then has the latest `node-gyp` version which runs on `python3` would fix the issue i guess.

Otherwise you could also try to install `python2` on you machine.

**Comment by toitzi** [comment]
PR #792 would fix this

**Comment by btantlinger** [comment]
Would be great if someone would have a look at PR #792.  This issue is breaking things all over the place...

**Comment by felixhtoo30** [comment]
Try installing `@mr-hope/gulp-sass` instead of `gulp-sass`

`npm i @mr-hope/gulp-sass`

**Comment by khanchenkov** [comment]
Hi!
I had the same issue
**downgrading node.js to LTS** version which is recommended for most users helped me

**Comment by ZhangChengLin** [comment]
https://github.com/dlmanning/gulp-sass/pull/795

**Comment by XhmikosR** [comment]
This can be closed @xzyfer too
