### ISSUE TITLE
Doesn't install under nodejs 16

### ISSUE THREAD

**Issue by SagePtr** [dlmanning/gulp-sass#797]
gulp-sass requires node-sass@4, but node-sass@4 doesn't support nodejs 16 (different compilation errors).
gulp-sass should move to Dart Sass, as the Warning message on https://www.npmjs.com/package/node-sass advices to, or update node-sass dependency to version 6.0.0 if switching is not possible.

**Comment by vmaurin** [comment]
I think it is not so much about switching the default, but about having the node-sass as mandatory dependency. The project claim to give the option between dart and node-sass, but if you are using dart, you have to download and compile node-sass (exactly what it is failing with node 16).

Personally I would prefer to have neither node-sass nor dart part of the project dependency, even if it is complexifying the installation (the readme will have to state that you must install gulp-sass + one of the sass engine).

**Comment by new-era-technologies** [comment]
If you would like to use gulp-sass, you need to install node stable and node-sass 5.0.0

**Comment by Anoesj** [comment]
I'm working on a pull request where all compilers are optional dependencies and node-sass is not installed by default. Will report back when it's finished 🙂
