### ISSUE TITLE
Compiling time

### ISSUE THREAD

**Issue by santosh0954** [dlmanning/gulp-sass#804]
gulp-sass@4 is 5-8 times faster than gulp-sass@5, I don't know but this is the real issue, I think

**Comment by vr1e** [comment]
It seems that `dart-sass` is just slow out of the box. For my cases, it is around 5 times slower than node-sass was. And I'm talking about the `sync()` version. The async is even slower.

**Comment by stof** [comment]
this should rather be reported to the Sass project (which details about the kind of Sass codebase being slow).

**Comment by rmaenk** [comment]
FYI: https://github.com/sass/dart-sass/issues/113

**Comment by XhmikosR** [comment]
This issue is unrelated to gulp-sass IMHO @xzyfer.
