### ISSUE TITLE
Can't compile .sass file without sourcemap

### ISSUE THREAD

**Issue by pdufour** [dlmanning/gulp-sass#81]
Hi, I'm using indented sass syntax, so the only way for libsass to recognize this is the `.sass` extension. Therefore opts.file needs to get sent and not opts.data. But the only way do that is generate a sourcemap as well: https://github.com/dlmanning/gulp-sass/blob/master/index.js#L23. So there is no way to have indented syntax and **no** sourcemap.

I am proposing an extra option called forceFile which would force gulp-sass to use opts.file. What do you think?

**Comment by greypants** [comment]
This is no longer an issue and can be closed. Node-sass added an [indentedSyntax](https://github.com/sass/node-sass#indentedsyntax) option . 

Just pass `{ indentedSyntax: true }`. 

The source map hack is no longer needed (and doesn't work).

**Comment by dlmanning** [comment]
@greypants : Thanks for point that out!

**Comment by greypants** [comment]
:+1:

**Comment by pdufour** [comment]
Thanks!
