### ISSUE TITLE
Dart SASS Options not Working

### ISSUE THREAD

**Issue by alialaa** [dlmanning/gulp-sass#811]
I am trying to pass[ options provided by dart-sass](https://sass-lang.com/documentation/cli/dart-sass#options) to the sync function but apparently they are not working.

For example I am trying to quiet warnings and it's working using the SASS CLI but not with gulp-sass:
```js
import dartSass from 'sass';
import gulpSass from 'gulp-sass';
import gulp from 'gulp';

const sass = gulpSass(dartSass);


export const styles = () => {
  return (
    gulp
      .src(paths.styles.src)
      .pipe(sass.sync({ quiet: true }).on('error', sass.logError))
      .pipe(gulp.dest(paths.styles.dest))
      .pipe(server.stream())
  );
};
```

**Comment by joonassandell** [comment]
+1

**Comment by stof** [comment]
@alialaa the JS API of dart-sass does not support a `quiet` option: https://sass-lang.com/documentation/js-api#options

**Comment by xzyfer** [comment]
This package is in maintenance mode. We aim to resolved security issues and general high priority maintenance. 

A PR for this functionality would be welcomed.
