### ISSUE TITLE
Quiet option

### ISSUE THREAD

**Issue by coalacode-com** [dlmanning/gulp-sass#838]
How can I use "quiet" in the gulp module?

This solution does not work 

`return gulpif('*.scss', sass.sync({
					outputStyle: 'compressed',
					quietDeps: true,
					quiet: true,
				}).on('error', sass.logError));`

**Comment by XhmikosR** [comment]
See #811

**Comment by XhmikosR** [comment]
@xzyfer I'd merge this with #811 and perhaps close that too.
